fedspendingtransparency/usaspending-api

usaspending_api/common/threaded_data_loader.py

Fixing a case where collision fields weren’t looked up in the field map

Hotfix for threaded loader

---

usaspending_api/awards/urls.py
usaspending_api/awards/views.py
usaspending_api/common/api_request_utils.py
using_the_api.md

* Added 'range_intersect' operation and documentation
* Added 'value_format' filter parameter and documentation
* Added autocomplete handler code and documentation (although a bit sparse, mind you)
* Added autocomplete endpoint for award summary
* Fixed an issue where FY objects weren't having a timezone
* Updated using_the_api.md to be shiny and up to date - with a bonus table of contents 🎉

Ds 421 426 extra op search

---

usaspending_api/awards/serializers.py
usaspending_api/awards/views.py
usaspending_api/common/serializers.py
using_the_api.md

Allowing for the limiting of fields
* Added ‘fields’ option to post requests
* Added ‘exclude’ option to post requests
* Added docs for ‘fields’ and ‘exclude’
* Probably want to refactor the code from ‘views.py’ somewhere abstract for future use, but this can wait until next post method implementation

field limiting

---

requirements.txt
usaspending_api/settings.py
usaspending_api/urls.py

This commit enables the Django debug toolbar. Note that the toolbar
is only visible when the app is in DEBUG mode and when you're
coming from IP 127.0.0.1. One other thing worth noting is that
the changeset updates requirements.txt to install the debug
toolbar directly from git, because that version is compatible
with new-style Django MIDDLEWARE.

Enable Django debug toolbar

---

requirements.txt
usaspending_api/settings.py

This PR adds django-extensions to our code base. Specifically,
I'm adding it to make use of the show_urls command to debug
some urlpatterns. More generally, django extensions includes
a large collection of helpful things, which you can
read about in the docs.

Add django-extensions to the code base

---

usaspending_api/awards/management/commands/loadcontracts.py
usaspending_api/awards/test_contracts_load.py

@bsweger kindly asked that I write some unit tests in py.test style to demonstrate the value of both. This PR (which is best reviewed commit by commit) hopefully does that, by writing tests and refactoring (in sequence) a few chunks of the logic in the contract loading admin command. Several edge cases for each chunk are tested.
This doesn't make use of pytests' monkeypatch test fixture (which is great for code with lots of dependencies,) but I can probably find a use case if desired.

Write some unittests for functions related to contract loading

---

usaspending_api/awards/models.py
usaspending_api/awards/test_summary_awards.py
usaspending_api/awards/views.py

Adding managers to award object.
To get awards that aren’t “generated null awards”, use Award.nonempty
Award.objects = gets all awards, including the empty ones
Award.nonempty = gets all awards, but filters out the empty ones

Null awards pre-filtering

---

using_the_api.md

Because our story to create an API landing page got delayed in favor of data loads, this PR makes a few tweaks that will allow our current "using the api" file to server as a place to start when talking to folks about our API and doing user research.
The most notable change is hyperlinking the endpoint list at the top of the page. Note that a few of them (e.g., the references/locations endpoints) 404 because we haven't deployed them to prod yet. That should be ok, since those new endpoints will also be part of the next deploy.

Hotfix api doc

---

usaspending_api/common/mixins.py
usaspending_api/data/testing_data/endpoint_testing_data.json

There is a problem with Django filters when filtering on relational
fields that have multiple hits (i.e. a Summary Award has 7
transactions, filtering on a field from those transactions will return
7 duplicates)
Adding the distinct flag resolves this, and is the expected return
value in use.

Fix filter distinctness

---

usaspending_api/awards/management/commands/loadcontracts.py

When the field “unique_transaction_id” was renamed to
“usaspending_unique_transaction_id” this was not updated to match.
Does not need to be in for sprint review.

Fixing value map on contract loader

---

usaspending_api/accounts/serializers.py
usaspending_api/accounts/views.py
usaspending_api/awards/management/commands/loadcontracts.py
usaspending_api/awards/views.py
usaspending_api/common/api_request_utils.py
usaspending_api/common/serializers.py
usaspending_api/common/tests/test_threaded_data_loader.py
usaspending_api/common/threaded_data_loader.py
usaspending_api/financial_activities/serializers.py
usaspending_api/financial_activities/views.py
usaspending_api/references/management/commands/loadcfda.py
usaspending_api/references/views.py
usaspending_api/submissions/views.py

This PR fixes performance issues relating to the typical ORM N+1 issue.
Locally, this took a 3,600 query, 40s call to `/awards/` down to 5 queries, 1.2s 
* Changed a bunch of serializers to `LimitableSerializer` and moved
nested serializers into `Meta.nested_serializers`
* Added code to prefetch and select related nested serializer fields
based upon the `Meta` class
* Updated views to use the new eager loading method
* Updated autocomplete to use eager loaded when needed
* Codeclimate fixes

Fixing n+1 problem

---

usaspending_api/common/api_request_utils.py

Looks like I left an extra select_related (which is redundant) in this section of code; which ended up causing errors on autocompletes that wanted to return matching objects. this fixes the issue

Fixing overeager loading

---

usaspending_api/submissions/management/commands/load_submission.py
usaspending_api/submissions/tests/test_load_submission.py

Updating to the new txn model for broker loads
* Now make TxnAssistance and TxnContract objects instead of FinancialAssistanceAwards / Procurment
* Now make Transaction object to attach said objects to
* Updated tests for new models
Broker ETL in general needs a bit of work, which is coming later this sprint. Stay tuned.

Broker ETL updates for new TXN model

---

usaspending_api/submissions/management/commands/load_submission.py

*
After this has been merged into dev, I will re-load SBA, Treasury submissions and load Energy submission into dev to ensure all data is correct for broker submission loads.
* Adding support method to get_or_create object_class/program_activity
* Fixed location maps to use the new location field names
* Fixed a problem with loading D2 data with foreign province data
classed as state_code
* Fixed a missing treasury_account field

Update ETL to support missing OBJCLASS/PRGACTVT

---

usaspending_api/common/mixins.py
usaspending_api/settings.py

per @klrBAH request:
Ensure proper json format is followed for event output (double quotes instead of single quotes) (This also results in proper string-ifying of timestamps)
Ensure only the response object is captured in the data response,
instead of the entire HTML body for queries to the interactive api docs

Logging Tweaks (pt. 2)

---

usaspending_api/templates/index.html
usaspending_api/templates/rest_framework/api.html
usaspending_api/templates/warning.html

This adds a little "hat" to the top of the API docs pages to make clear it's not the official source of data and that users should still visit usaspending.gov for that.

Docs warning

---

usaspending_api/awards/tests/test_transactions.py
usaspending_api/common/api_request_utils.py
usaspending_api/common/mixins.py
usaspending_api/common/tests/test_filter_generator.py

* Add test for querying non-string field with string value
* Added test to see if field on a model is a string field (TextField, CharField) - this follows fk relationships 
* Changed the __iexact changes to default to regular operations unless the field being filtered on is a string

Fixing string checks

---

usaspending_api/common/api_request_utils.py
usaspending_api/common/mixins.py
usaspending_api/common/tests/test_filter_generator.py

While helping @ejgullo on her full text search story, I discovered that we were missing the code that performed vector annotation. It appears that during refactoring to the new mixins, the annotation of full-text search vectors was left out. This code rectifies this, cleans up the filter mixin, adds validation for full text search operation, and introduces a test case to catch this problem.
* Added extra validations for full text search queries to the filter
validator
* Added search vector annotation to the filtering mixin
* Removed deprecated code from the filtering mixin
* Added test case for full text search on multiple fields

Fixing Full Text Search

---

usaspending_api/api_docs/markdown/documentation_index.md
usaspending_api/api_docs/urls.py
usaspending_api/templates/plate.html
usaspending_api/urls.py

We should refactor the templates in the future to be more django-ific.
This is a PR into my documentation branch that will add the ERD diagrams @catherinedevlin added to the documentation pages, and style it according the the templates we use across the docs. 
Using a separate PR so we have the option of not merging this in, but I think we should as the diagram does provide some value (and we can polish it all up during next sprint!)

Adding ERD to docs

---

usaspending_api/common/mixins.py
usaspending_api/common/serializers.py
usaspending_api/common/views.py
usaspending_api/data/testing_data/endpoint_testing_data.json
usaspending_api/settings.py

This PR combines several performance improvement initiatives for the API. Shout out to @catherinedevlin and @afrasier for these ideas and work.
1. Remove `.distinct()`
2. Get all response metadata counts from paginator stored data
3. Use `prefetch_related` for all API queries
4. Log response only, not the HTML
5. Reduce the max db connection age from 10 min to 10 sec

API performance improvements (minus cache)

---

usaspending_api/accounts/migrations/0018_auto_20170322_2024.py
usaspending_api/accounts/models.py

New federal account model and data migration. Doing this in two parts to minimize blocking
some of the downstream stories that need this new table.
This is part one:
* add FederalAccount model
* add nullable foreign keys to FederalAccount on the TreasuryAppropriationAccount and AppropriationAccountBalances models
* add new data to test fixture .json
A follow-up PR will:
* update the submission loader to populate the FederalAccount FKs
* update the initial data load to populate FederalAccount FKs
* depending on how the above plays out, maybe make the FKs non-nullable

Add federal account model and data migrations

---

usaspending_api/common/management/commands/clear_usaspending_cache.py
usaspending_api/submissions/management/commands/rm_submission.py

Update `rm_submission` command to give more information back.
```
(usaspending-api) Armans-MBP:usaspending-api afrasier$ python manage.py
load_submission 1195
Acquired appropriation data for 1195, there are 1 rows.
Acquired program activity object class data for 1195, there are 39 rows.
Acquired award financial data for 1195, there are 3790 rows.
Acquired award financial assistance data for 1195, there are 3 rows.
Acquired award procurement data for 1195, there are 319 rows.
(usaspending-api) Armans-MBP:usaspending-api afrasier$ python manage.py
rm_submission 1195
Deleted submission 1195. Statistics:
Total objects Removed: 5057
awards.SubAward: 0
submissions.SubmissionAttributes: 1
awards.FinancialAccountsByAwards: 3790
awards.TransactionContract: 319 …
```

Rm submission updates

---

usaspending_api/awards/models.py
usaspending_api/etl/management/commands/load_submission.py
usaspending_api/etl/tests/test_load_submission.py

Fixes the duplicate load bug that Kaitlin found on Friday.

Cache parents of award objects where appropriate for bulk creation

---

usaspending_api/accounts/tests/test_tas_endpoints.py
usaspending_api/accounts/views/tas.py

Thanks @afrasier for noting that there were duplicative viewsets for the tas/oc/pa quarterly queryset. Not only were they duplicated, the one that `urls.py` pointed to was using the wrong `get_queryset`, so this was a great catch.
This PR fixes and updates the tests.

Fix up a copy and paste error on tas/oc/pa quarterly endpoint

---

data_reformatting.md

This is an update to our document about data reformatting (which is a better way to express what we're doing) to handles two things:
1. A correction on the foreign country/province information to reflect that we do those both on usaspending historic data and broker submissions
2. New information to reflect the quarterly balance calculations.
Am requesting @kaitlin's review on the quarterly numbers text and will also ping Kristine in the channel for her eyes.

Rename document and add information about quarterly data

---

README.md

I installed the project from scratch last night and got an error on installing the postgres python driver because it uses the bson stuff that's not available until version 9.4. Added in a note to clarify minimum of 9.4 is needed.

minor doc update to clarify that minimum postgres version is 9.4

---

usaspending_api/etl/management/commands/load_submission.py
usaspending_api/etl/tests/test_load_submission.py

After noticing that a bunch of program activities were being created but remaining nameless, I added an update to at least capture the name as we first see it in a submission. We won't necessarily track all variations that exist for a particular PA across submissions and if an agency needs to update the title of a PA, we can ask agency submitters to update their PA lists with OMB and provide the "official" name. 
Also include a quicky unit test.

updated submission loader to capture PA name

---

usaspending_api/references/models.py
usaspending_api/references/tests/test_agency.py

Go ahead and call .get_by_subtier with the `None` subtier code, just return `None` instead of the first agency that happens to have a null subtier code

DS-1139 - no agency when toptier and subtier are both None

---

usaspending_api/api_docs/markdown/api_tutorial.md
usaspending_api/api_docs/markdown/data_dictionary.md
usaspending_api/api_docs/markdown/endpoints.md
usaspending_api/api_docs/markdown/landing_page.md
usaspending_api/api_docs/markdown/request_recipes.md
usaspending_api/api_docs/markdown/using_the_api.md
usaspending_api/api_docs/urls.py
usaspending_api/static_doc_files/css/main.css
usaspending_api/static_doc_files/docs/usaspending_searchpage_postmancollection.json
usaspending_api/templates/warning.html

This PR includes some styling and formatting updates based on April's testing results from PUB-613. Most of the content is relatively unchanged, just reorganized.
I also included subnavs for the different pages, but commented them out until we have time to go back in and update the styling/js to work with it properly.

Rearrangement to API Docs for Hackathon

---

usaspending_api/etl/executive_compensation_etl.py
usaspending_api/etl/management/commands/load_submission.py
usaspending_api/etl/management/commands/load_usaspending_assistance.py
usaspending_api/etl/management/commands/load_usaspending_contracts.py
usaspending_api/etl/subaward_etl.py
usaspending_api/references/models.py
usaspending_api/references/tests/test_legal_entity.py
usaspending_api/references/tests/test_recipients_autocomplete.py
usaspending_api/references/views.py

* This duplicate PR fixes an issue with github not liking a rebase
This fixes the issue brought up in DS-1143 where null DUNS's were causing some serious linkage issues.
* Adds `get_or_create_by_duns(duns)` to the `LegalEntity` Objects
* This method returns `LegalEntity, Boolean` similar to other django get_or_create patterns.
* If the specified DUNS is null, it will always create a new LegalEntity
* If the specified DUNS exists, it will return that LegalEntity
* If the specified DUNS does not exist, it will create a LegalEntity with that DUNS
* Update all usages of `.get()`, `.filter().first()` and other accessor methods for `LegalEntity` throughout the codebase where DUNS were used to `get_or_create_by_duns`
* Update recipient autocomplete to exclude any null DUNS, per acceptance …

Recipient duns fixes

---

usaspending_api/etl/award_helpers.py
usaspending_api/etl/tests/test_award_helpers.py

This simplifies get_award_financial_transaction to try the
lookup by fain and then by uri (and not together as we were
previously doing). @catherinedevlin had suggested this approach
as a better way in a prior code review, and she was right!

Update transaction lookup to separate fain and uri

---

requirements/requirements.txt

We'll need this library to import the glossary import command

Add openpyxl to the requirements list

---

usaspending_api/api_docs/markdown/api_tutorial.md
usaspending_api/api_docs/markdown/data_dictionary.md
usaspending_api/api_docs/markdown/endpoints.md
usaspending_api/api_docs/markdown/landing_page.md
usaspending_api/api_docs/markdown/request_recipes.md
usaspending_api/api_docs/markdown/using_the_api.md
usaspending_api/templates/index.html
usaspending_api/templates/plate.html
usaspending_api/templates/rest_framework/api.html

The endpoint pages use a different template than the doc index, so we needed to remove the white background there as well.

Hotfix: additional logo update and API doc tweaks

---

usaspending_api/accounts/models.py
usaspending_api/accounts/serializers.py
usaspending_api/awards/models.py
usaspending_api/awards/serializers.py
usaspending_api/common/api_request_utils.py
usaspending_api/common/helpers.py
usaspending_api/common/serializers.py
usaspending_api/common/tests/test_limitable_serializer.py
usaspending_api/references/models.py
usaspending_api/references/serializers.py
usaspending_api/submissions/serializers.py

This resolves issue #342 which also affected @ebdabbs front-end work
* Move default fields from models to serializers
* Limitable serializer meta objects now support `default_fields` and
`default_exclude`, which take an array of strings and provide the
default exclude and include fields. (The `fields` variable should
remain '__all__' to allow access to all variables by API users)
* Nested serializers can now include `default_fields` and
`default_exclude` in their kwargs
* Limitable serializer now properly passes down include/exclude fields
to nested objects using Django double-underscore traversal
* If a child object's field is requested, but the child itself is not
requested, it will be automatically added (otherwise it would not
serialize)
* The verbose flag now _only_ applies to the …

Nested field limiting

---

usaspending_api/api_docs/markdown/using_the_api.md
usaspending_api/common/api_request_utils.py

Adding extra ArrayField specific operations to allowable operations to
make working with business categories easier.
Adds:
* `overlap` - Returns values where the specified array and the stored array intersect
* `contained_by` - Returns values where the specified array entirely contains the stored array
* `length_greater_than` and `length_less_than` - As less_than and greater_than, but on the length of the array
* Adds documentation for these

Adding extra ArrayField specific operations

---

usaspending_api/accounts/serializers.py
usaspending_api/accounts/tests/test_financial_balances.py
usaspending_api/accounts/urls_financial_balances.py
usaspending_api/accounts/views/financial_balances.py
usaspending_api/api_docs/markdown/endpoints.md
usaspending_api/urls.py

This PR is part of the work for [DS-1316](https://federal-spending-transparency.atlassian.net/browse/DS-1316). The acceptance criteria for the `financial_balances/agencies/` endpoint have changed as the sprint progressed--our latest thinking for how this endpoint should behave is here: https://gist.github.com/bsweger/91d85b7f4ef1fb9c4f0a54c541ef5da6

Add /v2/financial_balances/agencies endpoint

---

usaspending_api/etl/management/commands/load_submission.py

Because `get_or_create_location` updates `location_value_map`,
it was not safe to pass the actual dictionary - it could be
updated on one call, then inappropriately keep those updates
and use them the next time it's called, on a different record
entirely.

Pass a copy of `location_value_map` to `get_or_create_location`

---

usaspending_api/accounts/serializers.py
usaspending_api/accounts/tests/test_financial_balances.py

Because fiscal_year is required in the request parameters,
remove it from the response. This change makes the
/financial_balances/agencies/ endpoint behavior consistent
with the others that we're building out for the agency page.

Remove fiscal_year from AgenciesFinancialBalancesSerializer

---

usaspending_api/awards/tests/test_award_spending.py
usaspending_api/awards/views.py
usaspending_api/common/helpers.py

adding check to ensure awarding_agency_id actually corresponds to a toptier agency. if not, an appropriate error message is returned. Also removed unused imports.

Update to recipient and award_type v2 endpoints

---

usaspending_api/common/models.py
usaspending_api/etl/management/load_base.py
usaspending_api/references/models.py
usaspending_api/submissions/management/commands/rm_submission.py
usaspending_api/submissions/tests/test_rm_submission_command.py

An old bug in the submission loader left bogus Location instances
in the database.  This forces non-US Locations to specifically
seek or create locations without states, and removes Location
intances attached only to the old, deleted version of the submission.

Clean up old Location records when redoing a submission

---

usaspending_api/etl/management/commands/load_historical.py
usaspending_api/etl/management/commands/load_submission.py

It was mentioned during sprint planning that we would like the loading of submissions to be atomic (if it fails or is cancelled, all changes should be rolled back).  This simple change makes that happen.  I don't know if we created a ticket for it.
I've verified its working manually (temporarily embedding a `sys.exit()` and checking the state of the database), but I haven't thought of a great way to actually write a test for this.  I'm open to suggestions.

Load submissions atomically

---

usaspending_api/etl/management/commands/load_submission.py

Pandas throws a ValueError when trying to operate on a
zero-size data frame.
This is currently producing a crash when loading submission 4590.  
Our structure for testing submission loads is currently very awkward, and I'm not clear how I can write a test for this... suggestions welcome.

Avoid crashing when no File C records

---

usaspending_api/references/v2/views/toptier_agencies.py

Using coalesce to default to 0 when SUM returns with None since it can't find any values to SUM.

Hotfix: Updating /v2/references/toptier_agencies endpoint

---

usaspending_api/common/helpers.py
usaspending_api/common/tests/test_helpers.py
usaspending_api/search/tests/test_spending_by_award_type.py
usaspending_api/search/tests/test_spending_by_award_type_count.py
usaspending_api/search/v2/views/search.py

- Including `page_metadata` object to pagination requests
- Sorting `spending-by-category` results by descending `aggregated_amount`
Updated Gists:
- [Spending by Category](https://gist.github.com/dpb-bah/7f12df270210d7a830c98af71cfa580d)
- [Spending by Award Type](https://gist.github.com/dpb-bah/6cf34627ae6d221fafab20b05fca7d58)

Hotfix pagination metadata v2 search

---

usaspending_api/accounts/views/financial_balances.py
usaspending_api/accounts/views/financial_spending.py

Adding additional filter based on active fiscal quarter for /v2/financial_balances/agencies/, /v2/financial_spending/major_object_class/, and /v2/financial_spending/object_class/ endpoints

Hotfix: Updating additional endpoints for the correct dollar amounts on the agency page

---

usaspending_api/api_docs/markdown/using_the_api.md

This PR fixes some of the formatting on https://api.usaspending.gov/docs/using-the-api. There are some JSON responses that I was unable to fix (as I don't know the correct answer), namely the response on https://github.com/fedspendingtransparency/usaspending-api/blob/0def14cf989dd3756e557876d2eaba37657caa69/usaspending_api/api_docs/markdown/using_the_api.md#response-json
```javascript
{
// ...
"results": [
_agency": {   // FIXME: Note that the key here isn't inside quotes. This probably should've been "something_office"
"subtier_code": "7300",
"name": "SMALL BUSINESS ADMINISTRATION"
},
"office_agency": null
},
}
```

Fix some JSON formatting in the API docs

---

usaspending_api/broker/management/commands/update_awarding_agencies.py
usaspending_api/broker/tests/test_update_awarding_agencies.py

Update awarding agencies cleaning script to include all transactions in order to fix wrong mappings between agencies and transactions and awards. 
Fixed test to make sure test was correctly filtering transactions.

Hotfix update awarding agencies

---

usaspending_api/awards/v2/filters/award.py
usaspending_api/awards/v2/filters/transaction.py

😱 😱 😱 Using 
`if or_queryset:`, as we do in filter concats, actually evaluates the queryset!  
This changes these checks (across awards and transactions) to use a boolean flag.

change "if queryset" to a flag

---

usaspending_api/awards/serializers.py
usaspending_api/broker/management/commands/load_fsrs.py

Related JIRA Story: https://federal-spending-transparency.atlassian.net/browse/DS-1896
* Updating FSRS loader to account for updating related award metadata (subaward counts and totals).
* Updated subaward serializer to include associated award data to retrieve the metadata in the response.

Subaward loader and endpoint enhancements

---

usaspending_api/references/models.py

Updating fill_missing_state_data to check if the state code returned a valid state. if it's none, don't do anything.

Resolving state code to state name conversion in case there is no match found

---

usaspending_api/awards/v2/filters/location_filter_geocode.py
usaspending_api/awards/v2/filters/matview_transaction.py

Updated geocode filter since country_code was not correctly getting correctly mapped in the filter. 
Updated removed default model in call, since mat views are under awards

Hotfix Geocode Filter for Transaction endpoints on Award Search

---

usaspending_api/search/v2/views/search.py

Fixing matview mappings throwing 500 errors:
- State: no geolayer_filters throwing an error when no geo layer filters
- County District geolayer_filters were not mapping correctly because geocode location filter was not set to matview = True

Fixing matview for geofilters state/county/district

---

usaspending_api/search/v2/views/search.py

When processing awards filters using UniversalAwardMatview, we don't need to exclude categories because the mat view is made with a category IS NOT NULL clause

Bugfix: Removing extraneous IS NOT NULL check on category

---

usaspending_api/awards/v2/filters/matview_transaction.py

- Recipient type filter for awards was passing for DUNS that had that type in any of their instances, plus it was slower.
- Cleaned up transaction filter a little because it was doing extraneous work

Hotfix correct recipient type filter

---

usaspending_api/awards/v2/filters/matview_transaction.py

- Updating award_filter to use total_obl_bin for preset monetary ranges
- Updating non-preset ranges to include the lower and upper bounds instead of ignoring them

Bugfix: DS 1966 total obligation speed and logic fixes

---

usaspending_api/references/tests/test_agency_autocomplete_v2.py
usaspending_api/references/v2/views/autocomplete.py

Per bug DS-1708: 
> As identified in the PMO team's QA review: When searching in Funding Agency or Awarding Agency, "USDA" will not bring up Department of Agriculture, HHS does not bring up Health and Human Services, etc. If you put a space between each letter in the acronym it does work, but that is not intuitive to do.
https://federal-spending-transparency.atlassian.net/browse/DS-1708
```
url = 'http://localhost:8000/api/v2/autocomplete/awarding_agency'
payload = json.loads('''{"search_text":"usda","limit":20}''')
import requests
resp = requests.post(url, payload)
resp.json()
```
result 
```
{'results': [{'id': 112,
'office_agency': None,
'subtier_agency': {'abbreviation': 'USDA',
'name': 'Department of Agriculture',
'subtier_code': '1200'},
'toptier_agency': {'abbreviation': 'USDA', …
```

Autocomplete searches subtier abbrev

---

usaspending_api/database_scripts/matviews/universal_award_matview.sql

IDV contracts where not focused because their category would be null.  This change will surface IDV contracts the next time the mat view is run.

MatView now accounts for IDV Contracts

---

usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
usaspending_api/database_scripts/matviews/summary_transaction_month_view.sql
usaspending_api/database_scripts/matviews/summary_transaction_view.sql

small typo with large consequences. incorrectly mapped `county_name` instead of desired `country_name`

Fixed typo (county vs country col name)

---

usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
usaspending_api/database_scripts/matview_generator/universal_award_matview.json
usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json
usaspending_api/database_scripts/matviews/summary_transaction_month_view.sql
usaspending_api/database_scripts/matviews/summary_transaction_view.sql
usaspending_api/database_scripts/matviews/universal_award_matview.sql
usaspending_api/database_scripts/matviews/universal_transaction_matview.sql

The `business_categories` column wasn't properly indexed. It is used for "Recipient Type" searches
Endpoint: `/api/v2/search/spending_by_award_count/`
JSON: `{"filters":{"time_period":[{"start_date":"2012-10-01","end_date":"2013-09-30"},{"start_date":"2013-10-01","end_date":"2014-09-30"},{"start_date":"2014-10-01","end_date":"2015-09-30"},{"start_date":"2015-10-01","end_date":"2016-09-30"},{"start_date":"2016-10-01","end_date":"2017-09-30"},{"start_date":"2017-10-01","end_date":"2018-09-30"},{"start_date":"2007-10-01","end_date":"2008-09-30"},{"start_date":"2008-10-01","end_date":"2009-09-30"},{"start_date":"2009-10-01","end_date":"2010-09-30"},{"start_date":"2010-10-01","end_date":"2011-09-30"},{"start_date":"2011-10-01","end_date":"2012-09-30"}],"recipient_type_names":["nonprofit"]},"aud …

Added new GIN index on business categories

---

usaspending_api/awards/v2/filters/matview_award.py
usaspending_api/awards/v2/filters/matview_transaction.py

Recipient_name is already upper-case in the matviews
FY2018, FY2017, FY2016, FY2015, Recipient Lockheed Martin - Table Count
Original: (35.6s, 19.2s, 17.8s)
New: 1.6s

Removed Django's inefficient icontains from recipient_name

---

usaspending_api/awards/v2/filters/location_filter_geocode.py

For baby download, the matviews are not used and thus the `loc_dict` should use the `location_country_code` instead of the `country_code`

Hotfix: Fix for location country code between matview and normal filters

---

usaspending_api/references/v2/views/autocomplete.py

Removes duplicate subtier agencies (funding and awarding) on the Award Search page

Bugfix: Distinct Subagencies for Award Search

---

usaspending_api/bulk_download/v2/views.py

Previously it was blank, this sets it to 'All'. Tested with local dev frontend.

Bugfix: Display 'All' Agency Name monthly downloads

---

usaspending_api/awards/v2/filters/view_selector.py
usaspending_api/download/v2/views.py

Modified `/v2/download/count/` to utilize different materialized views depending on the provided filter. It follows the same logic as other endpoints used for the award search page.
No DB edits were required.
Jira Ticket: https://federal-spending-transparency.atlassian.net/browse/DEV-19

Modified download transaction count endpoint to use different views

---

usaspending_api/download/v2/views.py

Due to different django functions returning different values (None vs 0)

Fixed new bug in /v2/download/count/ when there are no rows

---

usaspending_api/broker/management/commands/update_agency_code_999_fpds.py

Created a script to update awarding and funding agency codes in `transaction_fpds` that are '999'. 
This is in coordination with the broker updates to 999 agency codes and a website script to fix rows with '999' based on subtier as part of verifying the monthly download files.
Bug Story: https://federal-spending-transparency.atlassian.net/browse/DEV-45

Create script to update agency code 999 in transaction_fpds

---

usaspending_api/broker/management/commands/update_agency_code_999_fpds.py

Fixing syntax error for running script

Removing string literal f with regards to Python 3.5 string formatting

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py

Fixing how we delete old FABS records. We now delete using the afa_generated_unique, which carries over, as opposed to the ID which would never point to the right one.

Hotfix dev 293 fabs records not deleting

---

usaspending_api/awards/v2/filters/award.py
usaspending_api/awards/v2/filters/matview_filters.py
usaspending_api/awards/v2/filters/transaction.py

Related Bug - DEV-300: https://federal-spending-transparency.atlassian.net/browse/DEV-300
1. Fixing matview agency filter to use `and` when filtering funding and awarding agencies
2. Fixing agency filter for download (awards.py & transactions.py) to use `or` when filtering between toptier and subtier agencies for awarding agency and funding agency and match matview filter
**URL** `/api/v2/search/spending_over_time/`
**Post Body**
```{"group":"fiscal_year","filters":{"time_period":[{"start_date":"2017-10-01","end_date":"2018-09-30"},{"start_date":"2016-10-01","end_date":"2017-09-30"},{"start_date":"2015-10-01","end_date":"2016-09-30"}],"agencies":[{"type":"funding","tier":"toptier","name":"Department` of Health and Human Services"},{"type":"awarding","tier":"toptier","name":"Department of …
```

Hotfix dev 300 agency filter

---

usaspending_api/download/filestreaming/csv_selection.py

Smart Open package was upgraded since the last deploy. It was causing the award search download to fail on Dev and Staging. Updated the zipfile writer to match the new library standards.  Additionally added logging to debug  future issues.

Hotfix download smart open issue

---

usaspending_api/broker/management/sql/load_constraints.sql

Removing index on award description due to overflow of max index size in postgres

Hotfix: Removing award description index creation from SQL bulk loaders

---

usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/management/commands/es_loader.py
usaspending_api/etl/management/commands/es_rapidloader.py

Original code works for Python 3.6. Unfortunately Jenkins runs Python 3.5.

Corrected method of adding timezone info to datetime in Python 3.5

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py
usaspending_api/broker/management/commands/fpds_nightly_loader.py
usaspending_api/etl/executive_compensation_etl.py
usaspending_api/etl/management/commands/load_executive_compensation.py

Fix dates we associate with last run date for the loader.
Using the date the script started running (in UTC) instead of the date it finished (not in utc) for the last run date.
Making sure transaction_normalized actually updates the `update_date` when we run the loaders
N/A

Fix nightly loader last update

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py

**High level description:** 
Fixing how FAIN and URI are set based on record type in the nightly loaders.
**Technical details:** 
Changing the logic to only set FAIN if record_type = "2" and only set URI if record_type = "1" so that award lookups/creations happen accurately.
**Link to JIRA Ticket:** 
N/A

Hotfix: unique award id generation

---

usaspending_api/awards/v2/filters/award.py

When testing baby download, we found that the award table counts weren't matching the row counts in the download awards file. We then found out the universal award filter used for downloads excludes awards where category is null. This then removes that restraint to include the IDV contracts missing beforehand.
See High level description.
[DEV-532](https://federal-spending-transparency.atlassian.net/projects/DEV/issues/DEV-532)
```
Award Search, Dev Database, All Fiscal Years, Contracts and Loans, 200k+
Before changes:
Award Count: 291
Download Count: 285
After changes:
Award Count: 291
Download Count: 291
```

Fix: Award Download IDV Contracts

---

usaspending_api/broker/management/sql/update_subsidy_cost_awards.sql
usaspending_api/broker/management/sql/update_subsidy_cost_tx_normalized.sql

**High level description:** 
Limiting SQL queries that propagate loans values to only operate on loan type transactions and awards.
**Technical details:** 
Added `WHERE` clauses to limit queries only to operate on loans. Updated queries have already been run on staging.
**Link to JIRA Ticket:** 
N/A

Fixing loans SQL queries

---

usaspending_api/search/v2/urls_search.py

The spending by category endpoint is being turned off for production.
Removed the url link to the viewset.  This disables the connection.
- NA Matview impact assessment completed
- NA Frontend impact assessment completed
- NA Data validation completed
- NA API Performance evaluation completed and present:

remove the spending by category endpoint

---

usaspending_api/awards/serializers.py

Added original loan subsidy cost field in the response
Adding original_loan_subsidy_cost to the top level award serializer
[DEV-552](https://federal-spending-transparency.atlassian.net/browse/DEV-552)

Adding original_loan_subsidy_cost to the top level award serializer

---

usaspending_api/spending_explorer/v2/filters/explorer.py
usaspending_api/spending_explorer/v2/filters/spending_filter.py
usaspending_api/spending_explorer/v2/views/spending_explorer.py

Updating spending explorer to group recipients by name and return any awards that match that recipient name when drilling down from recipients to awards.
Updating spending explorer logic to group by recipient name and to return awards based on the recipient name instead of ID. Also removing the "limit" since the grouping should handle the large amount of duplication previously present.
N/A
- No frontend impact as confirmed by @kevinli-work 
```
Timing changes (example of going from FY 18, Q1 Budget Function -> Social Security -> Recipient):
Before =  11.7 seconds & 5.3 mb response (500 error b/c of cache size limit)
After = ~7.8 seconds & 269.1 kb …
```

Hotfix: Update spending explorer to group recipients by name

---

usaspending_api/awards/serializers.py

Fixing API response to include necessary loans values
Replacing original_loan_subsidy_cost in award serializer with contract_data and assistance_data to provide necessary fields to display `face_value_loan_guarantee` for the spending by award table for loans on the federal account page
N/A
- `original_loan_subsidy_cost` will no longer be used by frontend. new fields have been communicated to @mab6bf for frontend updates.
- Value mappings discussed & confirmed with relevant stakeholders. Necessary fields are now part of the API response.

Hotfix: Federal account loan value field update

---

usaspending_api/spending_explorer/v2/filters/type_filter.py
usaspending_api/spending_explorer/v2/views/spending_explorer.py

Limiting award results in spending explorer to 500 records.
Changing global limit variable for spending explorer to 500 and only utilizing the limit if the type requested is "award".
N/A
- Frontend will include text to indicate result set is limited.
```
Timing changes (going down budget function path for SSA and selecting first option until you get to awards):
Before = Timeout
After = ~17.6 seconds
```

Hotfix spending explorer limiting for awards

---

usaspending_api/awards/serializers.py

Adding field to populate the Issue Date on the spending by award table, loans tab on the federal account profile page
Adding certified_date to the award serializer
N/A
- new field needed by frontend. Communicated to @mab6bf 
- Value mappings discussed & confirmed with relevant stakeholders. Necessary fields are now part of the API response.

Hotfix: Adding certified_date to response

---

usaspending_api/api_docs/markdown/endpoints.md

Was messing around with the lovely v2 API and noticed a small typo on the `federal_account` endpoint.
Congrats on flipping the site and thanks for all of the hard work on the V2 API! It's 🔥 🔥 🔥

Fix federal_accounts endpoint link

---

usaspending_api/download/v2/views.py

Ensures that a search filter which includes `keyword` will not drop the additional filters and route the queries to Elasticsearch. 
Adds additional check to ensure there is only one filter field before routing keyword download queries to Elasticsearch.
N/A

Allow bulk download logic to be used for Advanced Search w/ keyword

---

usaspending_api/download/filestreaming/csv_generation.py

The Keyword filter in Advanced Search has a slightly more complex query than other filters and was not properly accounted for in the python code when keyword was re-added to the UI.
A regex was tweaked. Unsure exactly how it fixed the issue.
(N/A)

Slight tweak to regex expression

---

usaspending_api/common/logging.py
usaspending_api/settings.py

Updating the `server.log` to display the error message when it is a 400-499 status code on Kibana.
- Added `error_msg` to the logger format so that it adds it to the log as a field that Kibana can pick up for filtering
- Additionally added the error `message` to the message field to make as requested by the Ops team, to make it easy to spot the error
- Common 400 error codes include:
1. 400 - Bad request (invalid parameter)
2. 404 -  Not Found ( endpoint is missing)
3. 405 -  Method is not allowed 
4. 422 - Unprocessable Entity ( For elasticsearch)
- Took out propagation so that the server.log would not logged in the console.
N/A - Requested by Ops …

Update logging error message for 400 errors

---

usaspending_api/database_scripts/matview_generator/matview_sql_generator.py

Fix has the script properly handle file paths with spaces. Currently our Jenkins workspace directories contain spaces. PR'ed as hotfix so it can reach `master` branch quicker
Split the argument string by spaces before adding the filepath to the command list. Also added a try-except 
(N/A)

Fixed issue of splitting up a filepath with spaces in Python SQL script 

---

usaspending_api/api_docs/api_documentation/download/custom_award_data_download.md
usaspending_api/awards/v2/filters/location_filter_geocode.py
usaspending_api/download/lookups.py
usaspending_api/download/v2/views.py

Allows Custom Award Data downloads to be filtered by recipient or place of performance locations.
* Simply allowing the `recipient_locations` and `place_of_performance_locations` universal filters to be sent to the Custom Award Data download endpoint and validating it before generating the files.
[DEV-653](https://federal-spending-transparency.atlassian.net/browse/DEV-653)
* [Custom Award Data Endpoint](https://github.com/fedspendingtransparency/usaspending-api/blob/feature-location-custom-award-download/usaspending_api/api_docs/api_documentation/download/custom_award_data_download.md)

Feature: Locations in Custom Award Search

---

usaspending_api/etl/management/commands/update_total_funding_amount_sql.py

total funding amount sql script was too slow.  Added a simple optimization.
total funding amount is only influenced by fabs data, so removing all contracts provides huge speedups. 60% speedup on dev, and the speedup should be exponential because of the group by.
NA
```
Timing changes:
Before = 800 ms
After = 290 ms

add speedup to update_total_funding_amount

---

usaspending_api/etl/management/commands/update_total_funding_amount_sql.py

Made improvements to queries used to update existing data to recalculate `total_funding_amount`
Limited SQL queries to operate only on Assistance data (aka FABS), thus cutting the data volume down to ~36 million rows from ~90 million.
N/A

Hotfix: updating total funding queries to improve performance

---

usaspending_api/search/v2/views/search.py

Fix bug in `spending_by_award_count` that Sums the amounts of the Sub-Awards instead of Counts the Sub-Awards themselves.

DEV-670: Advanced Sub-Award Search

---

usaspending_api/awards/models_matviews.py
usaspending_api/broker/management/commands/fabs_nightly_loader.py
usaspending_api/broker/management/commands/fpds_nightly_loader.py

By updating downloads to use matviews instead of tables, the nightly loads have gotten confused with Django. This substitutes Django's call to SQL.
(see above)
N/A
- * Matview impact assessment completed
- * Frontend impact assessment completed  (N/A)
- * API Performance evaluation completed (N/A)

Hotfix: Nightly Load Deletes Fix

---

usaspending_api/database_scripts/matview_generator/matview_sql_generator.py
usaspending_api/database_scripts/matview_generator/summary_award_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_geo_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
usaspending_api/database_scripts/matview_generator/summary_view.json
usaspending_api/database_scripts/matview_generator/summary_view_cfda_number.json
usaspending_api/database_scripts/matview_generator/summary_view_naics_codes.json
usaspending_api/database_scripts/matview_generator/summary_view_psc_codes.json
usaspending_api/database_scripts/matview_generator/universal_award_matview.json
usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json

Bulk download has moved to using matviews to support performance, as a result matviews need to be updated to go as far back as FY 2001 instead of the current limit of 2008.
Updated matview generator JSON to alter the action date condition to be `>= '2000-10-01'`
[DEV-882](https://federal-spending-transparency.atlassian.net/browse/DEV-882)
```
Timing changes (newman tests on staging):
Before = Ranged from 8-20 failures due to timeouts
After = Run after matview recreate resulted in 15 failures due to timeouts (no worse than before)
Data volume changes (comparison of prod `universal_transaction_matview` to that of staging):
Before = 75,163,632
After = …
```

Hotfix: Updating matviews to generate FY 2001 and newer

---

usaspending_api/common/helpers.py

`validate_date()` was only checking against `datetime.datetime`'s and not `datetime.date`'s
(see high level description)
(N/A)
- Matview impact assessment completed (N/A)
- Data validation completed (N/A)
- API Performance evaluation completed and present (N/A)

Bugfix: datetime.date's in validate_date()

---

usaspending_api/download/v2/views.py

Surface the Delta files with the Full files on the Award Data Archive page.
Update the `list_monthly_files` endpoint to search S3 and return both the Full and the Delta files. Delta files will automatically have a null `fiscal_year`.
[DEV-970](https://federal-spending-transparency.atlassian.net/browse/DEV-970)
- Matview impact assessment completed N/A
- Data validation completed N/A
- API Performance evaluation completed and present N/A

Feature: surface Delta files on the Award Data Archive page

---

usaspending_api/core/validator/award_filter.py

Fix bug when front-end provides a value of "no intersection" in `award_type_codes`
Added new value to enum
N/A

Added "no intersection" (award_type_code)

---

usaspending_api/download/v2/views.py

- Allowing both Keyword/Keywords for Yearly Download Endpoint
- Making sure Keyword Downloads still include `download_type` in request

Hotfix: Keywords Downloads

---

usaspending_api/download/management/commands/populate_monthly_files.py

Update `populate_monthly_files` script to match changes made to the download Viewsets

Hotfix: Monthly download files script

---

usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_geography.md
usaspending_api/search/tests/test_spending_by_geography.py
usaspending_api/search/v2/views/search.py

The frontend uses the `geo_layer_filters` parameter for the advanced search map, but does not want to use it for the map on the new state profile pages.
Updated TinyShield and how the JSONRequest retrieves the `geo_layer_filters` param. We already check if the `geo_layer_filters` exist before applying the filters, and set "not null" defaults. Updated tests to test when `geo_layer` is `"state"`, `"county"`, or `"district"`.
[DEV-1043](https://federal-spending-transparency.atlassian.net/browse/DEV-1043)
- Matview impact assessment completed N/A
- Data validation completed N/A
- API Performance evaluation completed and present N/A

Feature: Make the SpendingByGeography geo_layer_filters parameter optional

---

usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_category.md
usaspending_api/database_scripts/matview_generator/subaward_view.json
usaspending_api/search/v2/views/spending_by_category.py

The subward matview has inconsistent joins to obtain the funding and awarding agency columns.
Removed these categories from API docs: `funding_agency`, `funding_subagency`, and `recipient_parent_duns` as they are either not ready or undesired. The two funding_agency categories can possibly be completely removed from the code and API contract if it is decided there isn't much benefit.
Switched to use `funding_agency_id` from the awards_subaward table instead of from the awards table. Technically there should be no difference to the resulting view as the subaward table is populated with awards data.
[DEV-805](https://federal-spending-transparency.atlassian.net/browse/DEV-805)
**The following are ALL required for the …

Bugfix: altered subward_view Matview and edited API docs for Spending By Category

---

usaspending_api/search/tests/unit/test_spending_by_category.py
usaspending_api/search/v2/views/spending_by_category.py

Updating API response to display "XX-90" congressional districts as "XX-MULTIPLE DISTRICTS".
Updating API response to display "XX-90" congressional districts as "XX-MULTIPLE DISTRICTS". This update happens in the business logic only and does not affect any underlying data in the database.
[DEV-1053](https://federal-spending-transparency.atlassian.net/browse/DEV-1053)
- Data is returned "XX-MULTIPLE DISTRICTS". For example: 
```
{
"amount": 20611513026.06,
"code": "90",
"id": null,
"name": "AL-MULTIPLE DISTRICTS"
}
```

DEV-1053: Remapping "XX-90" to "XX-MULTIPLE DISTRICTS"

---

usaspending_api/awards/models_matviews.py

Missing a column in the Django ORM model definition which exists in the materialized view
N/A
[DEV-1111](https://federal-spending-transparency.atlassian.net/browse/DEV-1111)

Added missing field in django model for universal_award_matview

---

usaspending_api/search/tests/unit/test_spending_by_category.py
usaspending_api/search/v2/views/spending_by_category.py

Hotfixes some of the aggregate logic for the agency and recipient categories in Spending by Category.
* Agency categories are rolled up based on name and not their agency ids (led to duplicate results)
* The database IDS returned from the agency categories are the `agency` id and not the `toptier`/`subtier` ids in preparation for possible linking to agency pages. **Note: when grouping toptier agencies, the agency ID returned will be the single agency with `toptier_flag` is set to True. For subtier agencies, it may return a top or subtier agency depending on what agency listing the award links to**
* Recipient groups allows blank duns (allows `MULTIPLE RECIPIENTS`) …

Hotfix: Spending by Category (Agency and Recipient Rollup logic)

---

usaspending_api/database_scripts/etl/transaction_delta_view.sql

Removed `cfda_popular_name` from matviews, but failed to remove from Elasticsearch ETL
While `cfda_popular_name` is not used by any API endpoints it is included in the Elasticsearch ETL view. Instead of removing the column, or modifying the view to join to `references_cfda`, simply changed to inserting an empty string value. Elasticsearch isn't even indexing the values in the documents.
(N/A)

Hotfix: Remove cfda_popular_name from Elasticsearch ETL

---

usaspending_api/database_scripts/matview_generator/summary_state_view.json

`summary_state_view` materialized view description JSON file was surprisingly missing a necessary flag to trigger the sql generator script to create the necessary SQL file for matview refreshes.
(N/A)
[DEV-1135](https://federal-spending-transparency.atlassian.net/browse/DEV-1135)

Hotfix nightly pipeline: adding missing refresh flag to summary_state_view

---

usaspending_api/awards/models_matviews.py

* Removing the PK Django fields, keeping them in results in the failure of `generate_zip` to start which processes all the downloads

Bugfix: PK in models

---

usaspending_api/broker/management/sql/reload_duns.sql

Created a new script to reload the `duns` table with data from the Broker's `duns` table. The original `load_duns` script would cascade drop and recreate the table which is detrimental to the matviews as a number of them rely on that table and would be dropped.
New sql file is wrapped as a single transactions. It will truncate the table and reload from the broker using the same dblink SQL as the original load script.
(N/A)

Added reload_duns script for nightly updates

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py
usaspending_api/broker/management/commands/fpds_nightly_loader.py
usaspending_api/common/csv_helpers.py
usaspending_api/common/threaded_data_loader.py
usaspending_api/download/filestreaming/csv_generation.py
usaspending_api/download/filestreaming/s3_handler.py
usaspending_api/download/management/commands/generate_zip.py
usaspending_api/download/management/commands/populate_monthly_delta_files.py
usaspending_api/download/management/commands/populate_monthly_files.py
usaspending_api/download/v2/views.py
usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/management/commands/es_rapidloader.py
usaspending_api/etl/management/commands/fetch_transactions.py
usaspending_api/recipient/management/commands/load_state_data.py
usaspending_api/references/management/commands/generate_broker_agency_list.py
usaspending_api/references/management/commands/loadtas.py
usaspending_api/settings.py

Over the history of this API, many environment variable names have been used. Formerly, this repo used:
`CSV_AWS_REGION `
`BULK_DOWNLOAD_AWS_REGION`
and in many ETL scripts:
`AWS_REGION`
(There is also `CFDA_REGION`, which needs to exist separately as it comes from a different source).
This consolidates all of these into one environment variable, `USASPENDING_AWS_REGION`.
[link not provided]

USASPENDING_AWS_REGION env var consolidation

---

usaspending_api/download/filestreaming/csv_generation.py
usaspending_api/download/management/commands/populate_monthly_delta_files.py

- Reuse the `split_and_zip_csvs` from `csv_generation.py`.
- Add a timestamp to the `working_dir` to ensure that we don't delete files being accessed by another version of the script running on the same box.

Hotfix: delta file generations multiple scripts at the same time

---

usaspending_api/database_scripts/matviews/functions_and_enums.sql

Cannot restore dumped databases without qualifying where (what schema) pg_restore or psql should find the `total_obligation_bins` enum type. This adds that schema-qualification
See: See this postgres bug report for details: https://www.postgresql.org/message-id/flat/153184074037.1405.15097715315257989847%40wrigleys.postgresql.org
[OPS-257](https://federal-spending-transparency.atlassian.net/browse/OPS-257) discovered during working through this Operations Epic
**Links to Dependent/Related PRs**
N/A
**Special Deployment Steps**
1. Will need to explicitly run this sql script on each database. Note, if not run, it will run as part of the nightly pipeline where that jenkins job is run
**The following are ALL required …

OPS-257 qualifying the schema in which the enum type is declared for pg_dump restore

---

usaspending_api/accounts/tests/unit/test_account_download_filter.py
usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/api_docs/api_documentation/download/custom_account_data_download.md

Update the Custom Account download filter to filter by the `fr_entity_code` column instead of the `agency_id` column when a FREC agency is selected.
If the passed in `agency` filter is 4 digits, filter by the `fr_entity_code` column instead of the `agency_id`. Add unit tests for the `account_download_filter`. Update Custom Account download documentation.
[DEV-1291](https://federal-spending-transparency.atlassian.net/browse/DEV-1291)
- Matview impact assessment completed N/A
- Frontend impact assessment completed N/A
- Data validation completed
```
Successfully created a file filtered by FREC agency.
```
- API Performance evaluation completed and present …

DEV-1291: Custom Account download FREC agency filter

---

usaspending_api/database_scripts/matviews/functions_and_enums.sql

PR #1331 switched the DB relation used in a function to lookup the recipient name by DUNS (from the `duns` table to the `recipient_lookup_view` matview) . The original DUNS column name was "awardee_or_recipient_uniqu" the new relation column name is "duns"
See above.
(N/A)

Bugfix: Corrected column name in SQL function

---

usaspending_api/database_scripts/matviews/functions_and_enums.sql

Cannot restore dumped databases without qualifying where (what schema) pg_restore or psql should find the `duns` table, which is used as a lookup in this function. This adds that schema-qualification
See: See this postgres bug report for details: https://www.postgresql.org/message-id/flat/153184074037.1405.15097715315257989847%40wrigleys.postgresql.org
[OPS-257](https://federal-spending-transparency.atlassian.net/browse/OPS-257) discovered during working through this Operations Epic
**Links to Dependent/Related PRs**
- A continuation of: https://github.com/fedspendingtransparency/usaspending-api/pull/1336
**Special Deployment Steps**
1. Will need to explicitly run this sql script on each database. Note, if not …

Hotfix: OPS-257 missed qualifying schema on table used within function

---

usaspending_api/recipient/v2/views/list_recipients.py

Searching by keyword for a specific award-type wasn't returning expected results.
SQL predicate wasn't constructed properly do to typo with queryset filter construction. Changed it from an `or` and an `and` addition to the queryset filter.
[DEV-1231](https://federal-spending-transparency.atlassian.net/browse/DEV-1231)

Bugfix Award-type filter queryset

---

usaspending_api/conftest.py
usaspending_api/etl/management/commands/load_multiple_submissions.py
usaspending_api/etl/management/commands/load_submission.py
usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py

Reverts fedspendingtransparency/usaspending-api#1431

Revert "Hotfix: Moving c to d linkage call to end of the submission load"

---

usaspending_api/references/management/sql/restock_tas.sql

Resolving logic to check for nulls and empty strings

Hotfix: Fixing TAS restock SQL

---

usaspending_api/broker/management/sql/reload_duns.sql

After reloading SAM data in the Broker's `duns` table, the production nightly pipeline failed on the `reload_duns` stage due to default values now NULL instead of an empty text array. This changes the script to COALESCE NULLs to text arrays
(N/A)
[DEV-1449](https://federal-spending-transparency.atlassian.net/browse/DEV-1449)

Altering loader to handle NULL for `business_types_codes`

---

usaspending_api/recipient/management/sql/restock_recipient_profile.sql

There was unnecessary filters which reduced some recipient DUNS/type combinations for the Recipient Profile page.
Removed all of the predicates from the SQL insert command which creates all potential Recipient + type combinations before the data are populated for the last 12 months.
[DEV-1454](https://federal-spending-transparency.atlassian.net/browse/DEV-1454)
Rows before: 1,452,991
Rows after: 2,171,516
Diff: +718,525
No detectable performance changes. Responses still consistently under 2s for most requests, upper bounds of 5s max

Fixed the temporary_restock_recipient_profile row creation

---

usaspending_api/broker/helpers.py

Simply account for a legal entity column to be `None` instead of `True` and `False` when recreating the business categories.
(see above)
N/A
- Unit & integration tests updated with relevant test cases (N/A)
- Matview impact assessment completed (N/A)
- Data validation completed (N/A)
- API Performance evaluation completed (N/A)

Hotfix: Business Categories, allow Nones in Legal Entity

---

usaspending_api/accounts/models.py
usaspending_api/accounts/views/federal_accounts_v2.py
usaspending_api/references/management/commands/load_tas.py
usaspending_api/references/reference_helpers.py

In AppropriationAccountBalances, submissions which were marked as "final_of_fy" were not always correct. Some submission_id values were duplicated across different TAS. So if a submission was correctly listed as "latest" for one TAS might not be the latest for another TAS.
In AppropriationAccountBalances, there is a class method `populate_final_of_fy` which is run after each submission load. The SQL was modified to appropriately only update `final_of_fy` by linking submission ids to TASs using `treasury_account_identifier`.
Also, as a followup of the TAS reloader script, the federal_account rows were being deleted and recreated by `load_tas` management command every night. Minor edits were made with the command ordering and logging to …

[Hotfix] Fixed AppropriationAccountBalances to list the correct submissions as the latest for FY

---

.pyup.yml

For questionable reasons pyup.io does not allow users to edit global settings in the web app. To stop pyup.io from creating PRs this config file needs to be present 
https://pyup.io/docs/configuration/
(N/A)

Adding pyup file so pyup.io stops making PRs

---

usaspending_api/database_scripts/matview_generator/summary_award_recipient_view.json
usaspending_api/database_scripts/matview_generator/summary_state_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_geo_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_recipient_view.json
usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
usaspending_api/database_scripts/matview_generator/summary_view.json
usaspending_api/database_scripts/matview_generator/summary_view_cfda_number.json
usaspending_api/database_scripts/matview_generator/summary_view_naics_codes.json
usaspending_api/database_scripts/matview_generator/summary_view_psc_codes.json

A previous PR introduced bugs to a number of materialized views by breaking the unique column necessary for having a unique index which is used for concurrent refreshing of the matviews.
The column `duh` is only present to add a unique column to pre-aggregated materialized view. Incorrectly copy-pasted using awards.id instead of transaction_normalized.id
N/A

Bugfix: Referenced incorrect column for uniqueness

---

usaspending_api/accounts/tests/integration/test_budget_function.py
usaspending_api/accounts/v2/urls_budget_functions.py
usaspending_api/accounts/v2/views/budget_function.py
usaspending_api/urls.py

Create a `list_budget_functions` endpoint for the Budget Functions dropdown, and create a filterable `list_budget_subfunctions` endpoint for the Budget Subfunctions dropdown.
Budget functions are pulled from all unique budget function code/title combinations in the TAS table. Budget subfunctions are similarly pulled, and able to be filtered by a budget function code.
[DEV-1495](https://federal-spending-transparency.atlassian.net/browse/DEV-1495)
[DEV-1496](https://federal-spending-transparency.atlassian.net/browse/DEV-1496)
- Matview impact assessment completed N/A
```
Timing: 996 ms
Data volume: 20 rows
```
```
Timing: 1066 ms
Data volume: 69 rows
```

DEV-1495/1496: Create list_budget_functions and list_budget_subfunctions endpoints

---

usaspending_api/awards/v2/lookups/lookups.py

Changed mapping for the Prime Recipient in SpendingByAward for Subawards
Incorrectly mapped to `recipient_name` instead of  `prime_recipient_name`
[DEV-1473](https://federal-spending-transparency.atlassian.net/browse/DEV-1473)

Changed mapping for Prime-Recipient Names in SpendingByAward

---

loading_data.md
requirements/legacy_requirements.txt

I was incorrectly placing unused packages into `legacy_requirements.txt`, when the file is actually for python 2 packages.
I also make edits to the loading_data markdown file

Correcting legacy_requirements.txt

---

loading_data.md

Minor updates to the markdown docs to no longer reference the RDS snapshots of prod databases, but reference the new db downloads.

Removing refernece to the old rds snapshots of prod data

---

.gitignore
README.md
setup.cfg

Changing instructions in the `README.md` so that it embeds the project-local virtual environemnt directory into a 'hidden' dot directory (`.venv`).
Also adding an exclude in flake8 config in `setup.cfg` to not have `flake8` analyze python files in this dot directory. 
Without these, these extra subfolders under the project directory were interfering with local execution of `pytest` and `flake8`.

README.md instruct venv in dot dir

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py
usaspending_api/broker/management/commands/fix_deleted_fabs.py

DEV-679 reports of a deleted FABS record appearing on website. This updated script deletes all traces of it and any other FABS record marked as delete from the website.
* The issue was that the delete process from nightly FABS load didn't remove *all* traces of the FABS record from the website until mid-late April 2018 when it was fixed. However, we didn't run the same deletion process for all the previous records.
* Importing the same delete process as the FABS nightly loader
* Updating script to use db_link
[DEV-679](https://federal-spending-transparency.atlassian.net/browse/DEV-679)
- Unit & integration tests updated with relevant test cases
- Matview …

DEV-679: Removing all traces of fabs marked as deleted

---

pull_request_template.md

Adding a markdown file to auto-populate Github PR descriptions
https://tommcfarlin.com/github-pr-templates/
https://help.github.com/articles/about-issue-and-pull-request-templates/#pull-request-templates
```
Almost everything in N/A as this is a "mod" branch, only adding a single markdown file
```

Adding PR template for Github

---

usaspending_api/references/management/commands/load_naics.py
usaspending_api/references/tests/test_load_naics.py

Fix for the duplicate NAICS codes
Found when NAICS codes appeared multiple times in auto-complete. This was caused by NAICS codes with trailing spaces. Issue resolved by importing NAICS codes as integers.
2. [ ] Necessary PR reviewers:
3. [X] Data validation completed

NAICS duplicate code fix (branched from Staging)

---

usaspending_api/accounts/serializers.py
usaspending_api/accounts/tests/test_federal_obligations.py
usaspending_api/accounts/views/federal_obligations.py
usaspending_api/api_docs/api_documentation/federal_obligations.md

Adds the federal account code to the response from v2/federal_obligations
Adds the account code as an annotation to the queryset. 
2. [NA] API documentation updated 
8. [X] Jira Ticket [DEV-1552](https://federal-spending-transparency.atlassian.net/browse/DEV-1552):
```
Frontend will be updating the API Contract
```
Performance:
Before:
1248 ms
1337 ms
1283 ms
1278 ms
1316 ms
1298 ms
1249 ms
After
1275 ms
1293 ms
1260 ms
1296 ms
1286 ms
1281 ms
1279 ms
No Significant Change

DEV-1552: Adding federal account code to the v2/federal_obligations endpoint

---

usaspending_api/api_docs/api_documentation/spending_explorer.md
usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
usaspending_api/spending_explorer/v2/filters/explorer.py
usaspending_api/spending_explorer/v2/filters/type_filter.py

Adds account_number as a field to the v2/spending response when the type is a federal_account.
Annotates the response.  Also makes  'id's for all types for the v2/spending response into strings rather than ints.
8. [X] Jira Ticket [DEV-1549](https://federal-spending-transparency.atlassian.net/browse/DEV-1549):
```
```

DEV-1549: Adding account_number to v2/spending response for federal_account type

---

usaspending_api/download/filestreaming/csv_generation.py
usaspending_api/download/helpers.py

**Data Award Archive:** Archived files will lose its useful naming convention when unzipped, particularly the fiscal year, the download type (Full vs. Delta), creation date.
The contents of the archive files of Data Award Archive downloads are now inherited by the children `.csv` files.
Additional optional parameter named `file_name` has been added to `split_csv` function. When defined, the resulting archived `.csv` file inherits the archive name. 
1. [x] Necessary PR reviewers:
2. [x] Jira Ticket [DEV-1367](https://federal-spending-transparency.atlassian.net/browse/DEV-1367):

CSV names now inherit archive name on Award Data Archive

---

usaspending_api/accounts/v2/views/budget_function.py
usaspending_api/api_docs/api_documentation/budget_functions/list_budget_function.md
usaspending_api/api_docs/api_documentation/budget_functions/list_budget_subfunction.md

Testing showed that ordering by code is less useful than title, so we are fixing that.
Updated the `order_by` from `budget_function_code` to `budget_function_title`.
1. Unit & integration tests updated N/A
- Operations N/A
- Domain Expert N/A
4. Matview impact assessment completed N/A
6. Data validation completed N/A
7. Appropriate Operations ticket(s) created N/A
8. [x] Jira Ticket [DEV-1446](https://federal-spending-transparency.atlassian.net/browse/DEV-1446):
```
1. No changes were made to the core functionality of the endpoint.
3. This is a minor API endpoint …
```

Hotfix: DEV-1446: Update list_budget_function and list_budget_subfunction endpoints

---

usaspending_api/references/management/commands/load_rosetta.py
usaspending_api/references/v2/views/data_dictionary.py

Re-adding API Caching per @willkjackson's request. Also fixing issue with Python 3.5 dictionary ordering

Re-adding API caching to data_dictionary API and fixing ordering issue

---

usaspending_api/api_docs/api_documentation/recipient/recipient_profile.md
usaspending_api/recipient/management/sql/restock_recipient_profile.sql
usaspending_api/recipient/tests/integration/test_recipient.py
usaspending_api/recipient/v2/views/recipients.py

Modified the `restock_recipient_profile` script to include 100% of all parent DUNS listed for any given recipient DUNS instead of only listing the most recent parent DUNS.
Instead of finding the most-recent parent DUNS, the SQL script creates an array of all distinct parent DUNS for each DUNS in the transaction data. There were minimal SQL edits and slightly more Python edits to handle multiple parents instead of having 1 parent DUNS.
8. …

DEV-1402: Allow Multiple Parents for Recipient Profile page

---

usaspending_api/accounts/tests/unit/test_account_download_filter.py
usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/financial_activities/models.py

Remove duplicates (selecting the most recent of a fiscal year) from A and B account download files.
- Simply filtering account downloads A/B on `final_of_fy`
- Updating `financial_accounts_by_program_activity_object_class` final_of_fy SQL to be more accurate
Uniqueness for A: TAS
Uniqueness for B: TAS/PA/OC/DR
7. [x] Appropriate Operations ticket(s) created [OPS-407](https://federal-spending-transparency.atlassian.net/browse/OPS-407) …

DEV-1721: Dedupe Account Downloads A and B

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py

A change to the column name (total_funding_amount -> funding_amount ) in Transaction_Normalized cause the fabs nightly loader to stop populating the new column (funding_amount is blank for transactions populated after this change). This discrepancy is what causes the disconnect between federal_action_obligation and total_funding_amount in award, as the federal_action_obligation is summed from the properly populated transaction fields, while total_funding_amount is summed from the inconsistently populated funding_amount field. This change maps the data to the new column name in the fabs nightly loader. There will also be a data change to backfill the empty values.
The fabs_nightly_loader assumes incoming data from the broker maps 1:1 to column names …

DEV-1689: Mapping from broker to usaspending for funding_amount in fabs_nightly_loader

---

usaspending_api/accounts/tests/unit/test_account_download_filter.py
usaspending_api/accounts/v2/filters/account_download.py

Extension of [PR-1602](https://github.com/fedspendingtransparency/usaspending-api/pull/1602) to handle FYQs prior to the latest
**Technical Details**
* Moving the `final_of_fy` logic to the account downloads endpoint
* Including Account Download duplication logic
8. [x] Jira Ticket [DEV-1721](https://federal-spending-transparency.atlassian.net/browse/DEV-1721):
```
Matview impact assessment completed …
```

DEV-1721: Dedupe Account Downloads (older FYQs)

---

usaspending_api/etl/management/commands/load_submission.py
usaspending_api/financial_activities/models.py

Reverting new Final of FY logic for `FinancialAccountsByProgramActivityObjectClass` considering it's taxing for load_submission
8. [x] Jira Ticket [DEV-1819](https://federal-spending-transparency.atlassian.net/browse/DEV-1819):
```
Unit & integration tests updated - No unit tests affected
API documentation updated - No documentation affected
Matview impact assessment completed - No matviews …
```

Hotfix: Updating Final of FY for load B file submissions

---

usaspending_api/broker/management/commands/fpds_nightly_loader.py

Original code did not have an acceptable process for handling exceptions during the section to parse datetime objects from FPDS value strings. NULLs no longer cause the script to fail.
Moved the datetime string formatting from outside of the exception catch logic. Have the exception handling to provide `None` to be stored in the record.
8. [x] Jira Ticket [DEV-1824](https://federal-spending-transparency.atlassian.net/browse/DEV-1 …

[Hotfix] Handle NULLs and off-format values in FPDS last_modified

---

usaspending_api/etl/management/commands/update_total_funding_amount_sql.py

Fixing the backfilling script to properly normalize "funding_amount" so that the summed amount in awards/total_funding_amount is correct. 
In the backfilling script, the equation of non_federal_funding_amount and federal_action_obligation does not sum if one or both of the values are nulls. So we need to coalesce those nulls to zeros so they can always be summed.
1. [NA] Unit & integration tests updated
7. [X] Appropriate Operations ticket(s) created (OPS-409) …

DEV-1689: Coalescing null values so the script will function properly

---

usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award.md
usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award_count.md
usaspending_api/awards/v2/filters/matview_filters.py
usaspending_api/awards/v2/lookups/lookups.py
usaspending_api/core/validator/award_filter.py
usaspending_api/search/tests/test_spending_by_award_type.py
usaspending_api/search/tests/test_spending_by_award_type_count.py
usaspending_api/search/v2/views/search.py

Separates out IDV counts and awards from Contracts counts and awards for the responses on the Advanced Search page.
Add `idv_type_mapping`s to the `award_type_filter`. Update the filter to accept all or none of the IDV mappings, which will toggle whether or not we include IDVs in the results.
- Operations N/A
- Domain Expert N/A
```
Counts match up with DB counts when filters are applied.
```
7. Appropriate Operations ticket(s) created N/A
8. [ ] Jira Tickets: …

DEV-1799: Add IDV tab to Advanced Search, include IDV toggle in filters

---

usaspending_api/common/helpers/generic_helper.py
usaspending_api/search/tests/unit/test_new_awards_over_time.py
usaspending_api/search/tests/unit/test_spending_over_time_details.py
usaspending_api/search/v2/views/new_awards_over_time.py
usaspending_api/search/v2/views/spending_over_time.py

The code for adding missing time periods into the response utilized a Python dictionary which isn't an ordered structure in Python 3.5. These edits utilize lists to maintain order
Decided to refactor the code a little
8. [x] Jira Ticket [DEV-1820](https://federal-spending-transparency.atlassian.net/browse/DEV-1820):
```
API request unchanged. Response is same structure.
Matviews untouched …
```

DEV-1820 Fixing time period ordering

---

usaspending_api/awards/v2/lookups/lookups.py
usaspending_api/broker/management/commands/load_fsrs.py

Fixes two bugs related to the discrepancies between similar API endpoints/downloads.
- Bug 1: When not filtering by any award type versus filtering by all the award types we know, there are a couple award types that have been included that the project owners declared shouldn't be used. Code changes simply remove them (could comment them out though it's skeptical if they would return).
- Bug 2: When finding parent awards for subawards, the equivalent ids included dashes in their `NONE`s causing a mismatch and unlinked subawards. This resolves that and allows more subawards to be linked.
- Clarifying subaward log
3. [x] Necessary PR …

DEV-1829: Subaward Counts Initial Bugfixes

---

usaspending_api/accounts/tests/test_federal_account_v2.py
usaspending_api/accounts/views/federal_accounts_v2.py

In Custom Account Data, under Agency dropdown item Department of Defense (CGAC code `097`) does not contain all of DOD Armed Forces CGAC codes (`097`, `021`, `057`, `017`, `096`), as the DOD Armed Forces CGAC code logic exists only in v2. This change migrates and integrates the current functionality of v1 into v2. Allowing for `federal_accounts` to be queried from Custom Account Data page
The front-end will also need changes in processing the updated v2 POST request response structure. 
The Custom Account Data page, using Department of Defense agency dropdown, sends a POST request to `/v1/federal_accounts` to retrieve the list of all federal accounts under DOD Armed Forces.
The DOD Armed Forces hierarchy under the Department of Defense is …

Federal Accounts v2 migration for DOD CGAC list hierarchy

---

usaspending_api/api_docs/api_documentation/advanced_award_search/new_awards_over_time.md
usaspending_api/api_docs/api_documentation/awards/awards.md
usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/urls_awards.py
usaspending_api/awards/v2/views/awards.py
usaspending_api/common/exceptions.py

The distant goal is to only use the `generated_unique_award_id` for API responses and requests. Original /v2/awards/ only supported `generated_unique_award_id`, for backward-compatibility and testing, the endpoint can now utilize the awards.id PK ID in the request with no extra effort to API users.
If the value can be converted to an integer, search awards.id column. Otherwise, filter by `generated_unique_award_id` …

Improve v2/awards to support different ID types

---

usaspending_api/search/v2/views/spending_by_geography.py

Simple fix to broken link in rendered page https://api.usaspending.gov/api/v2/search/spending_by_geography/ .  Doc link shows as "https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/advanced" but should show as 
"https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_geography.md"
Root cause is missing underscores in spending_by_geography.py doc string
See above
6. [ ] Data validation …

fix broken link to docs in spending_by_geography

---

usaspending_api/broker/management/sql/update_idv_additions_awards.sql
usaspending_api/etl/award_helpers.py
usaspending_api/etl/tests/test_award_helpers.py

Includes both a SQL script to populate and modifications to the FPDS nightly loader to update the following columns in the Awards table:
- `fpds_agency_id`
- `fpds_parent_agency_id`
- `base_exercised_options_val`
7. [x] Appropriate Operations ticket(s) created - [OPS-494](https://federal-spending-transparency.atlassian.net/browse/OPS-494)
8. [x] …

DEV-1988, DEV-2000: Populate/Update Additional IDV Award Fields

---

usaspending_api/broker/management/commands/derive_office_names.py

Broker could not make OfficeName derivations for FY2019Q1 FABS records due to the lack of a reliable Office table. After Federal Hierarchy is merged into the Broker, we want to use its Office table to make these derivations.
New Django script that creates a temporary table with the Broker office data, derives the TransactionFABS AwardingOfficeName and FundingOfficeName using their corresponding OfficeCodes. Deletes the temporary Office table.
1. Unit & integration tests updated N/A
2. API documentation updated N/A
6. [x] Data …

DEV-1880: Backfill FABS OfficeNames using Federal Hierarchy Office data

---

usaspending_api/awards/serializers_v2/serializers.py
usaspending_api/awards/tests/test_awards_idv_v2.py
usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/views/awards.py

Additional data pertinent to IDV awards are being added to responses for IDVs returned by the `api/v2/awards/` endpoint
New ORM logic/serializers to fetch the desired data described in the [API contract](https://github.com/fedspendingtransparency/usaspending-website/blob/dev/api_contracts/contracts/award/AwardProfile.md#idvresponse-object)
8. [ ] Jira Ticket [DEV-1801](https://federal-spending-transparency.atlassian.net/browse/DEV-1801): …

[DEV-1801] IDV-specific data in v2/award/ responses

---

README.md
data_reformatting.md

While reviewing this codebase and getting my local installation ready, I noticed a couple of grammatical errors in the documentation.

Fix typos and grammatical errors

---

usaspending_api/broker/management/sql/restock_subawards.sql

Users found duplicated subawards in the USAspending database.  This addresses one of the underlying causes by uppercasing a couple of columns that were not being appropriately uppercased.
The `load_fsrs.py` delta loader was uppercasing the `internal_id` whereas `restock_subawards.py` was not.  This caused `load_fsrs.py` to reload some subawards since it was unable to find existing subawards due to the casing discrepancy. …

DEV-1873/OPS-519: Uppercase additional fields in subaward restock script

---

usaspending_api/awards/v2/views/idvs/awards.py

New endpoint was failing on Dev server.
We cannot use default connection in `dev`, `stg`, or `prod` since we use multiple read databases.
8. [X] Jira Ticket [DEV-2049](https://federal-spending-transparency.atlassian.net/browse/DEV-2049):

DEV-1935/DEV-2049: Fix new endpoint for IDV children

---

usaspending_api/awards/tests/test_awards_idv_v2.py
usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/data_layer/orm.py
usaspending_api/common/recipient_lookups.py

Recipient Profile pages are contingent on the "level" of the recipient (Parent, Child, or Recipient). Since the API response value was not including the level in the string, the links were broker.
A little more complicated than desired since there isn't an easy way to lookup the recipient level from a transaction
8. [x] Jira Ticket [DEV-2034](https://federal-spending-transparency.atlassian.net/browse/DEV-2034):
**Area for …

Fixing "Recipient Hash" value returned for /v2/awards/

---

usaspending_api/awards/v2/views/idvs/amounts.py
usaspending_api/awards/v2/views/idvs/awards.py
usaspending_api/awards/v2/views/transactions.py
usaspending_api/core/validator/award.py
usaspending_api/core/validator/tests/unit/test_award.py

Resolves bug introduced by TinyShield usage misunderstanding.
In several locations in code, TinyShield objects were being reused.  In its current incarnation, this does not work.  A new TinyShield must be instantiated per use.

Fix for inappropriate TinyShield usage

---

usaspending_api/common/management/commands/dump_urls.py

Simple management command to dump out all of the urls supported by/known to Django.
`python manage.py dump_urls`
1. [X] No unit or integration tests to update
2. [X] No API documentation needed
5. [X] Front end not impacted
6. [X] No data was affected
7. [X] No Operations ticket required
8. [X] No Jira ticket

Added ability to dump urls supported by Django

---

usaspending_api/api_contracts/contracts/award/idv/Funding.md
usaspending_api/awards/tests/test_awards_idvs_funding_v2.py
usaspending_api/awards/v2/views/idvs/funding.py

By request, added `funding_agency_id` to IDV Funding API endpoint.
4. [x] No materialized views were affected
6. [X] No data was affected
7. [X] No operations ticket required
8. [X] Jira Ticket [DEV-2184](https://federal-spending-transparency.atlassian.net/browse/DEV-2184):

DEV-2184: Added funding_agency_id to IDV Funding API endpoint

---

usaspending_api/awards/models_matviews.py

A recent change seemed to have upset Django.
```SystemCheckError: System check identified some issues:
ERRORS:
awards.SubawardView.award: (fields.E007) Primary keys must not have null=True.
HINT: Set null=False on the field, or remove primary_key=True argument.
```
```
Minor edit to an unmanaged ORM model which shouldn't affect anything
```

Odd issue with ORM

---

usaspending_api/awards/tests/test_awards_idvs_funding_v2.py
usaspending_api/awards/v2/views/idvs/funding.py

Bug was found with `transaction_obligated_amount` in IDV Funding endpoint that was causing peculiar front end sorting issues.
Database contains NaN values which do not translate to JSON.  Fix was to convert to NULL which is functionally equivalent in this context.
8. [X] Jira Ticket [DEV-2037](https://federal-spending-transparency.atlassian.net/browse/DEV-2037):

DEV-2307: Minor bug fix for IDV funding endpoint

---

usaspending_api/common/operations_reporter.py

Reviewing work that was piggybacked onto DEV-2245. This set comparison will only work if `set(self._internal_dict.keys())` is an empty set
Uses a set diff instead.

DEV-2245 new "ops reporter" function "required field" fix

---

usaspending_api/awards/v2/filters/sub_award.py

Currently, NAICS is not in FSRS data. It will be added in DAIMS 1.3.1. This is a temporary fix until USAspending contains DAIMS 1.3.1 fields.
Commented out section to search NAICS (only when keyword text is numeric)
8. [x] Jira Ticket [DEV-1909](https://federal-spending-transparency.atlassian.net/browse/DEV-1909):
```
Minor change for bugfix to not filter on non-existent …
```

DEV-1909: Keyword filter exception for Subawards

---

usaspending_api/download/management/commands/populate_monthly_delta_files.py
usaspending_api/download/management/commands/populate_monthly_files.py

Adding IDV award type codes to the `contracts` award types used by the management commands for generating the monthly files.
Added the pre-defined IDV type codes to the mapping objects.
8. [x] Jira Ticket [DEV-2353](https://federal-spending-transparency.atlassian.net/browse/DEV-2353):
```
This does not touch the database or API endpoints
No existing tests to update for monthly …
```

[DEV-2353] _Hotfix_ Adding IDV types to monthly download commands

---

usaspending_api/awards/v2/filters/sub_award.py

Added an explicit reference to the subaward materialized view to resolve a bug when trying to use the endpoint to generate downloads.
A line to add a SQL fragment caused ambiguity in the column reference.
8. [x] Jira Ticket [DEV-2023](https://federal-spending-transparency.atlassian.net/browse/DEV-2023):
```
No API behavior changes except correcting an error causing …
```

DEV-2023: Fixed Bulk Download API bug for sub-awards

---

usaspending_api/broker/management/commands/fpds_nightly_loader.py

Fixes a regression introduced during DEV-1904 where a date was incorrectly cast to a string.
1. [X] No unit tests for this code (although wouldn't it have been awesome if there were)
2. [X] API documentation unaffected
5. [X] Front end unaffected
7. [X] No Operations ticket required
8. [X] Jira Ticket [DEV-1904](https://federal-spending-transparency.atlassian.net/browse/DEV-1904):

Hotfix for regression added during DEV-1904

---

usaspending_api/awards/tests/data/idv_funding_data.py
usaspending_api/awards/tests/test_awards_idvs_funding_v2.py
usaspending_api/awards/v2/views/idvs/funding.py

The `Total Count of Federal Accounts` value appears incorrect when compared to the count of `Federal Account Name` values listed on the `Federal Account Funding` tab.  This pull request fixes that by pulling the preferred named instead of an alternate name.
The `api/v2/awards/idvs/funding/` endpoint should now pull `account_title` from `federal_account` instead of `treasury_appropriation_account`.
2. [X] No API documentation updates required
5. [X] Front end not affected
7. [X] No Operations tickets required …

DEV-2419: Pull funding account title from correct table

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py

Enhanced `fabs_nightly_loader` to accept FABS transaction ids.
1. [X] No tests to be updated
2. [X] API documentation affected
5. [X] Front end is unaffected
7. [X] Operations ticket [OPS-624](https://federal-spending-transparency.atlassian.net/browse/OPS-624)
8. [X] Jira Ticket [DEV-1904](https://federal-spending-transparency.atlassian.net/browse/DEV-1904):

DEV-1904: Enhance fabs_nightly_loader to accept FABS transaction ids

---

usaspending_api/broker/management/commands/derive_office_names.py

It was discovered that the office backfilling derivations script didn't account for funding agencies. This remediates that.
Should nearly match the equivalent broker SQL found in the [Broker PR](https://github.com/fedspendingtransparency/data-act-broker-backend/pull/1560)
7. [x] Appropriate Operations ticket(s) created [OPS-645](https://federal-spending-transparency.atlassian.net/browse/OPS-645)
8. [x] Jira Ticket [DEV-2308](https://federal-spending-transparency.atlassian.net/ …

DEV-2308: Office Backfill Funding Derivations

---

usaspending_api/awards/v2/filters/idv_filters.py
usaspending_api/download/filestreaming/csv_generation.py

Fixes bug where download jobs were not being marked as failed if they failed before being queued.
1. [X] No tests for this issue
2. [X] No API documentation needs to be updated
4. [X] No materialized views were affected
5. [X] Front end should not be affected as this is a new feature
7. [X] No Operations ticket required
8. [X] Jira Ticket [DEV-DEV-2336](https://federal-spending-transparency.atlassian.net/browse/DEV-2336):

DEV-2336: Mark download jobs as failed if they fail before being queued

---

usaspending_api/api_docs/markdown/api_tutorial.md
usaspending_api/api_docs/unused_markdown/request_recipes.md
usaspending_api/api_docs/unused_markdown/using_the_api.md
usaspending_api/references/management/commands/load_rosetta.py
usaspending_api/templates/index.html

Running site scans flagged a number of minor links which either:
- Needed to be https
- Changed from beta.usaspending.gov to www.usaspending.gov
Instead of waiting for the code changes to propagate and reload the data dictionary, I manually added the "s" to the URL stored in the JSON doc in the DBs on staging and production
8. [x] Jira Ticket [DEV-2561](https://federal-spending-transparency.atlassian.net/browse/DEV-2561):
**Area …

DEV-2561: Corrected a number of hardcoded URLs

---

requirements/legacy_requirements.txt
requirements/requirements.txt
requirements/server_requirements.txt

During the deploy process (see fedspendingtransparency/data-act-build-tools#198) we use Python 2 to support an old version of supervisor. This upgrades that by moving it into the reqs file used w/Python 3, server_requirements.txt.
The conditional check will happen with the next deployment. Supervisord 4.0.2 is currently running in sandbox.

add supervisor to server reqs, remove legacy file

---

usaspending_api/download/filestreaming/file_description.py
usaspending_api/download/tests/unit/test_file_description.py

Fixed an issue that was causing Windows to jam all of the readme paragraphs together in one great big giant long string.
As everyone is well aware (but at least one of us forgot), Windows likes CARRIAGE RETURN/LINE FEED for line endings.  These are now standard issue in the IDV download readme file.
2. [x] No API documentation affected
4. [x] No materialized views affected
6. [x] Data unaffected
7. [x] No operations ticket required
8. [x] Jira Ticket [DEV-2336](https://federal-spending-transparency.atlassian.net/browse/DEV-2336):

DEV-2336: HOTFIX: Added carriage returns to readme file for Windows

---

usaspending_api/common/helpers/sql_helpers.py
usaspending_api/etl/es_etl_helpers.py

The elasticsearch loader script was failing at the final step of updating the last load date in the postgres DB. This was new functionality and not fully tested outside of a local env.
Switched from using the Django connection to psycopg2's connect object for the child process spawned by the script.
```
PR is only correcting a DB connection during an …
```

Hotfix connection issues during Elasticsearch ETL

---

usaspending_api/awards/tests/test_awards_idvs_awards_v2.py
usaspending_api/awards/v2/views/idvs/awards.py

IDV child awards for which there was no funding agency information were not appearing the IDV child awards table on the IDV summary page.
This was due to the improper use of an inner join against the agency table.
2. [x] No API documentation updates required
8. [x] Jira Ticket [DEV-2108](https://federal-spending-transparency.atlassian.net/browse/DEV-2108):

Hotfix for awards not appearing in IDV results

---

requirements/requirements.txt
usaspending_api/common/elasticsearch/client.py

Thank you @willkjackson for figuring this out!
Changes should only be in effect during local development!
Requires `pip install -U requirements/requirement.txt` to upgrade external packages

Upgraded Elasticsearch lib version and disable ssl cert checks when local

---

usaspending_api/references/v2/views/autocomplete.py

`api/v2/autocomplete/glossary/` behavior was unexpectedly different than
`api/v1/references/glossary/autocomplete/`.
Changed the search field from `slug` to `term`
Found after [DEV-2430](https://federal-spending-transparency.atlassian.net/browse/DEV-2430) was tested in staging
```
Minor view logic change, no impact to API or database.
It would have …
```

[Hotfix] Change to search field used by v2/autocomplete/glossary

---

usaspending_api/awards/tests/test_awards_idv_v2.py
usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/data_layer/orm.py
usaspending_api/awards/v2/data_layer/orm_mappers.py

Fixes the mapping for the office agencies on the v2 endpoints 
The current version of the `/v2/awards` endpoint pulls the awarding/funding office from the empty `office_agency table`. This updates the endpoint to pull from the latest transaction in the `transaction_fabs` or `transaction_fpds` tables instead.
8. [X] Jira Ticket [DEV-2741](https://federal-spending-transparency.atlassian.net/browse/DEV-2741): …

DEV-2741 Change office_agency mapping 

---

usaspending_api/references/tests/test_toptier_agency_v2.py
usaspending_api/references/v2/views/toptier_agencies.py

Adds the Congressional Justification URL to the toptier_agency endpoint response
Builds on Brian's work here https://github.com/fedspendingtransparency/usaspending-api/pull/1845 to add the Congressional Justification from the model to the endpoint response
8. [X] Jira Ticket [DEV-2764](https://federal-spending-transparency.atlassian.net/browse/DEV-2764):
- [NA] Performance evaluation of affected (API | Script | Download)
- [NA] Before / After data …

DEV-2764: Update Top Tier Agency Reference Endpoint with Congressional Justification

---

usaspending_api/awards/tests/unit/test_location_filter_geocode.py
usaspending_api/awards/v2/filters/location_filter_geocode.py
usaspending_api/awards/v2/filters/matview_filters.py
usaspending_api/awards/v2/filters/sub_award.py
usaspending_api/search/tests/test_spending_by_geography_city.py
usaspending_api/search/v2/views/spending_by_geography.py

Originally overlooked the ES mapping changes made for Autocomplete work. We didn't revisit the filtering changes to use a better sub type.
Elasticsearch keyword type is an exact match and performant.
8. [x] Jira Ticket [DEV-2616](https://federal-spending-transparency.atlassian.net/browse/DEV-2616):
```
No changes to the API or materialized view.
No Operations impact
```

[Hot] Update for DEV-2616 to exact match city name

---

usaspending_api/awards/tests/unit/test_subawards.py
usaspending_api/awards/v2/views/subawards.py

Fixed bug that caused 500 error when attempting to sort subawards by id
subawards.py was not using the dictionary lookup to translate 'id' to 'subaward_id' in order to match with ORM object.
4. [N/A ] Matview impact assessment completed
5. [N/A ] Frontend impact assessment completed
6. [N/A ] Data validation completed
7. [N/A ] Appropriate Operations ticket(s) created
8. [x] Jira Ticket [DEV-2798](https://federal-spending-transparency.atlassian.net/browse/DEV-2798):
```
```

added id for sorting

---

usaspending_api/search/v2/elasticsearch_helper.py

In a previous PR, the behavior of Keyword Search was negatively impacted. 
The original input string sanitizing was restored.
```
Restoration of previous behavior
```

Restoring previous behavior to Keyword Search

---

usaspending_api/awards/v2/filters/location_filter_geocode.py

There were not enough results being provided from the ES query with the recent switch to obtaining transaction ids from the search.
Increasing the aggregation limit from 50k to 500k
```
```

Increasing the max number of results from ES for City Search

---

usaspending_api/database_scripts/job_archive/backfill_fabs_unique_transaction_key.py

Creating one-off script to update FABS transaction keys
Creating a script to re-derive all FABS transaction keys (in both transaction_fabs and transaction_normalized) in the new format
1. [x] No unit tests required for this
2. [x] No API documentation updates required
4. [x] No materialized views affected
5. [x] Front end is unaffacted
7. [x] Operations ticket [OPS-735](https://federal-spending-transparency.atlassian.net/browse/OPS-735)
8. [x] Jira ticket [DEV-2376](https://federal-spending-transparency.atlassian.net/browse/DEV-2376):

DEV-2376: Update unique transaction key fabs

---

usaspending_api/api_contracts/contracts/references/ToptierAgencies.md

Update to usaspending-api/usaspending_api/api_contracts/contracts/references/ToptierAgencies.md. It was missing the new `congressional_justification_url`. Additional edits were made to clean up the doc

[Hotfix] Update ToptierAgencies API Contract

---

usaspending_api/broker/management/commands/fpds_nightly_loader.py

A late addition to DEV-2504.  This modification to the FPDS nightly loader allows for reloading of specific transactions/awards.  When the `unique_award_key` promotion was further tested, it was discovered that a duplicate award exists.  This enhancement can be used to repair/collapse such awards.
**I LIED - THIS WILL NEED TO BE HOTFIXED INTO SPRINT 84**
Allows for the inclusion of `detached_award_procurement_id`s on the command line.  Those transactions will then be reloaded, repairing any awards in the process.  This uses entirely existing and tested processes.
2. [x] API documentation should be unaffected
4. [x] Materalized views were unaffected …

DEV-2590: Hotfix: Allow reloading of specific FPDS transactions/awards

---

usaspending_api/api_contracts/contracts/awards/AwardProfile.md
usaspending_api/awards/tests/test_awards_idv_v2.py
usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/data_layer/orm.py
usaspending_api/common/recipient_lookups.py

Added the parent_recipient_hash to the GET /api/v2/awards/<award_id> endpoint.
Adding a hash for the parent recipient to the recipient object that is returned on the above endpoint. Added a little logic to determine if a "-P" needs to be at the end of the hash.
8. [x] Jira Ticket [DEV-2740](https://federal-spending-transparency.atlassian.net/browse/DEV-2740):
This PR particularly targets the subtasks on …

Mod/dev 2740 add parent recipient hash to /api/v2/awards/<award_id>

---

usaspending_api/etl/es_transaction_mapping.json
usaspending_api/etl/es_transaction_template.json
usaspending_api/references/v2/views/city.py

Change to keyword type, fixed `pop_county_code` to `pop_country_code`
7. [X] Appropriate Operations ticket(s) created - https://federal-spending-transparency.atlassian.net/browse/DEV-2870#icft=DEV-2870
8. [X] Jira Ticket [DEV-2806](https://federal-spending-transparency.atlassian.net/browse/DEV-2806):
```
no change to matviews, no change to frontend, all tests already updated
```
**Data Validation / Performance
Before - Time: 33 ms
```
{
"count": …
```

change to plain keyword, country not county

---

usaspending_api/awards/v2/data_layer/orm.py
usaspending_api/common/recipient_lookups.py

Missed some cases when originally implementing this API change for DEV-2740. This PR should handle when a parent recipient does not exist for a provided recipient.
Use a boolean to determine when a recipient is a parent and also check if the recipient has a name and unique id before creating a hash when the recipient does not exist. If the parent recipient does not exist return None.
8. [ ] Jira Ticket …

Fix/Dev-2740: Handle parent recipients differently and cover missed cases

---

usaspending_api/api_contracts/contracts/awards/idvs/Activity.md
usaspending_api/awards/tests/test_awards_idvs_activity_v2.py
usaspending_api/awards/v2/views/idvs/activity.py

Rename field from `period_of_performance_ultimate_end_date` to `period_of_performance_potential_end_date`.  Also fixed minor bug in contract for `parent_generated_unique_award_id`.

DEV-2970: Minor last minute updates to the IDV activity endpoint

---

usaspending_api/awards/management/commands/load_subawards_sql/150_reset_unlinked_award_subaward_fields.sql

This hotfix is designed to resolve an issue with a sub-optimal query that was taking entirely too long to complete.  Has been tested on both DEV and STAGING and runs significantly faster than the previous version.

DEV-2116 HOTFIX: Update to long running SQL query

---

usaspending_api/common/helpers/orm_helpers.py

Quick fix for connection alias issue.  This is a known landmine whereby the default connection string works in some environments but not in any of our "live" environments.  See [DEV-2852](https://federal-spending-transparency.atlassian.net/browse/DEV-2852) for more details.

DEV-2068: Quick fix for connection alias issue

---

usaspending_api/common/helpers/unit_test_helper.py
usaspending_api/download/filestreaming/csv_generation.py
usaspending_api/download/filestreaming/csv_source.py
usaspending_api/download/helpers/download_annotations_helper.py
usaspending_api/download/lookups.py
usaspending_api/download/v2/download_column_historical_lookups.py

Add the Federal Account to the award and transaction download. Added so that the column will display similar to "075-0512; 075-0580; 075-8004" where "<agency_identifier>-<main_account_code>".
Screenshot showing the new column and an entry:
Representing annotations for downloads as an entry into the ordered dictionary with (<alias_name>, None). The None allows for easy removal when gathering all of the query paths, but allows for the correct location to be used with respect to order. The annotations are created as part of a function that is unique to each table. 
The hope is that any future annotations can be added to the annotations function per table and an entry with a matching alias can be added to the ordered dictionary to achieve what is …

Mod/Dev-2973: Add federal accounts for award to download

---

usaspending_api/database_scripts/matview_generator/tas_autocomplete_matview.json
usaspending_api/database_scripts/matview_generator/tas_search_matview.json

One more minor tweak to remove an unnecessary `distinct` and change sort order.  Very minor.  Nothing should be noticeably affected.

DEV-3212: Minor tweak to TAS autocomplete ticket

---

usaspending_api/download/filestreaming/csv_generation.py
usaspending_api/download/helpers/download_annotation_functions.py
usaspending_api/download/lookups.py
usaspending_api/download/v2/download_column_historical_lookups.py

Similar to Federal Account, TAS was added to the download. I also noticed an issue with Federal Account returning a "-" when should be null so I fixed that one liner as part of this PR. 
Following the approach that Brian and I put together to handle annotations on downloads, the tas_rendering_label was added. Some of the files that Brian and I have touched were updated as part of this PR after running Black. …

Mod/Dev-3222: Add TAS to download

---

usaspending_api/etl/management/commands/load_multiple_submissions.py
usaspending_api/etl/management/commands/submission_loader.py

Code to catch and log failed submissions without preventing other submissions from loading actually hid the submission exception and threw an error.
Swapped Java for Python
```
Minor changes to a operations script.
Code doesn't impact API or materialized views
```

Hot-Hot Fix to Master for load_multiple_submissions.py

---

usaspending_api/common/helpers/endpoint_documentation.py
usaspending_api/common/renderers.py
usaspending_api/references/v2/urls_autocomplete.py
usaspending_api/references/v2/views/tas_autocomplete.py

Originally all TAS autocomplete endpoints were serviced by the same view.   This caused documentation issues.  This pull requests separates them out into their own views.
8. [x] Jira Ticket [DEV-2963](https://federal-spending-transparency.atlassian.net/browse/DEV-2963)/[DEV-2853](https://federal-spending-transparency.atlassian.net/browse/DEV-2853):

DEV-2963/DEV-2853 HOTFIX: Separate TAS views for documentation purposes

---

usaspending_api/etl/management/commands/load_submission.py

Submissions loaded out of order were causing duplicates with multiple submissions pointing to the same submission as their "previous submission" record. The fix was to temporary reset the id to `null` and once the new submission was entered into SubmissionAttributtes to recalculate the previous submission for the pre-existing submissions.
None
8. [x] Jira Ticket [DEV-3291](https://federal-spending-transparency.atlassian.net …

[Hotfix] Update to load_submission to resolve submission load issue

---

usaspending_api/api_contracts/contracts/v2/awards/funding.md
usaspending_api/awards/v2/views/funding.py
usaspending_api/settings.py

Used the wrong method to get the metadata for the endpoint response was causing problems with the frontend infinite scroll feature
Used the get_pagination method instead of get_simple_pagination_data which was paginating the results for me even though I was already doing that in the sql. Issue wasn't discovered until the testing for awards with larger numbers of federal accounts that had more pagination needed.
5. [X] Frontend impact assessment completed  …

HOTFIX - scrolling for funding table

---

usaspending_api/awards/management/commands/load_subawards.py
usaspending_api/awards/management/commands/load_subawards_sql/030_frame_out_subawards.sql
usaspending_api/awards/management/commands/load_subawards_sql/090_create_temp_address_table.sql
usaspending_api/awards/management/commands/load_subawards_sql/900_cleanup.sql
usaspending_api/awards/tests/integration/test_load_subawards.py

In its current incarnation, the `load_subawards` management command does not perform deletes.  This is a problem when Broker reloads their subawards without a matching reload on the USAS side of the fence as we can end up with duplicate subawards.  This enhancement attempts to remedy that situation by looking for changes in the minimum Broker subaward serial autonumber id.
7. [x] No Operations tickets required
8. [x] Jira Ticket [DEV-3460](https://federal-spending-transparency.atlassian.net/browse/DEV-3460):

DEV-3460: Auto detect Broker subaward reloads

---

usaspending_api/broker/management/commands/fpds_nightly_loader.py

New FK column from awards to transaction_normalized (`earliest_transaction_id`) needs to be set to null along with `latest_transaction_id` when records are being purged. Value will be re-populated in a later stage of the script.
Thanks to @BrianZito for catching this in his open PR

[DEV-3442] adding overlooked update to FK field

---

usaspending_api/references/constants.py

Turned out to be completely trivial.  Removed 096 from the list of DoD rollup agencies.
8. [x] Jira Ticket [DEV-3597](https://federal-spending-transparency.atlassian.net/browse/DEV-3597):

DEV-3597: Removed Corps of Engineers (096) from DoD rollup

---

usaspending_api/references/migrations/0033_move_cgacs_back.py

Strike 1.  Last minute tweak to a migration was incorrect.  The FREC table was introduced in a previous pull request.  I moved the migration into the wrong file which caused Django to attempt to recreate an existing table.  This will safely work around the issue.

DEV-2752: Fix migration

---

usaspending_api/common/helpers/etl_helpers.py
usaspending_api/etl/transaction_loaders/tests/integration/test_fpds_loader.py

Better logic to determine the path to the .sql file to execute
- Use `settings.py` to find the BASE_DIR and establish path to SQL file from there. 
- This was determined by running the test from pycharm, which runs it _not_ from the root dir
- [NA] Operations <OPTIONAL>
- [NA] Domain Expert <OPTIONAL>
6. [NA] Data validation completed
8. [ ] Jira Ticket [DEV-3634](https://federal-spending-transparency.atlassian.net/browse/DEV-3634):
**Area for explaining …

[DEV-3634] Path resilience to execute c to d linkage .sql file

---

usaspending_api/conftest.py

Basically doing `docker --rm`
If not done, it leaves around a stopped container after the `pytest` session is run, which can be seen with `docker ps --no-trunc -a`
6. [NA] Data validation completed
8. [ ] Jira Ticket [DEV-1526](https://federal-spending-transparency.atlassian.net/browse/DEV-1526):
```
Automated test frameworking work
```

[DEV-1526] Adding removal of the container once done migrating broker

---

usaspending_api/broker/management/commands/load_fpds_transactions.py

Investigation has found that any angle of trying to find orphaned values takes prohibitively long, and that the amount of orphans has little impact on runtime. Given that work is under way to remove both of these tables altogether, I think it's a better choice to let this clutter accumulate for the time being, and invest time in either removing these tables, or developing a more complete way to deal with this problem if the tables can't go for some reason.

dev-3634 removed cleanup

---

usaspending_api/settings.py

Recent fancy string formatting changes cause local download files to save to the wrong folder, due to all slashes being deleted. This remedies the issue.

added slash back to local download path

---

requirements/requirements-app.txt

Setting the requirements to work around incompatibilities of `py-gfm` with `Markdown>=3.0`
So the `GithubFlavoredMarkdownExtension` we use is not up-to-date/compatible with newer versions of the Markdown lib.
https://github.com/fedspendingtransparency/usaspending-api/blob/dev/usaspending_api/api_docs/templatetags/docs.py#L5
So the maintainer of that library (`py-gfm`) just pinned their requirement to `Markdown<3.0`.
https://github.com/Zopieux/py-gfm/compare/0.1.3...0.1.4#diff-2eeaed663bd0d25b7e608891384b7298R13
The “fix” then for us, given our dependencies, would be to likewise Pin our Markdown, and upgrade to py-gfm 0.1.4.
I did this and the app comes up without the error.
Given we’re still waiting on final approval of the changes before staging …

COLDFIX: Using the py-gfm that attempts to enforce its compatibility with Markdown<3.0

---

.pre-commit-config.yaml
pyproject.toml
requirements/requirements-contrib.txt
usaspending_api/common/management/commands/reset_migrations.py

As a means by which to cut down on the number of bogus commits to GitHub (which should help with our Travis queues), this will implement pre-commit hooks that Black, flake8, and check for debug statements in code locally before allowing a git commit to finish.
If you want to try it out, pull this branch and run:
```
pip install pre-commit
pre-commit install
```
Then make some bogus changes and try to commit them.
If you do not wish to participate in pre-commits, you can either uninstall `pre-commit` or commit your code with the `--no-verify` switch.  Code checks will continue to occur in Travis, this is just a way to short circuit certain common errors that can be quickly and easily caught before wasting precious Travis time/energy/resources.
**IMPORTANT**
If Black …

Added pre-commit hooks for Black, flake8, and debug statements

---

usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/management/commands/es_rapidloader.py

Problem caused by using a persistent Django DB connection in a child process. A check to ensure a DB view is present leveraged pre-existing functions which used the Django connection.
The database connection needs to be new for each separate process. If the connection is accidentally used in another process, it _may_ appear to work for non-SSL connections. This issue was encountered before and the solution was to use psycopg2 to create a new short-lived connection for child process calls. This protects the parent process's DB connection.
Other solutions would be to manage the connections better. Two viable options (among others) are:
- close DB connections before executing leaves the parent process
- disabling persistent connections 
**Requirements …

[DEV-3864] Elasticsearch ETL DB connections fix 

---

usaspending_api/etl/transaction_loaders/fpds_loader.py

SQL was missing check for awards with an earliest_transaction_id FK in the transactions to delete.
This is a quick edit, there might be a better approach to determine which awards should be altered during this step.
```
Fix for a lacking SQL statement in ETL script.
A new test should have been written to correct this, but I couldn't find any tests …
```

[HOTFIX] Added check for earliest transaction FKs

---

usaspending_api/download/filestreaming/download_generation.py

Minor tweak to agency prefix from CSV files accidentally added an extra underscore to the custom account downloads.
N/A
8. [x] Jira Ticket [DEV-1566](https://federal-spending-transparency.atlassian.net/browse/DEV-1566):
```
No changes to matviews, data, API, or docs
```

[DEV-1566] Remove extra underscore from Custom Account Download files

---

usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
usaspending_api/search/tests/test_spending_by_transaction.py

While the ES query field mapper was altered to match the ES index mapping, the values were not being returned by the API. This reverts the `.keyword` change from #2164 to the API business logic
N/A
8. [x] Jira Ticket [DEV-4032](https://federal-spending-transparency.atlassian.net/browse/DEV-4032):
```
Fixing issue, no changes to database
```

[DEV-4032] Fixing SpendingByTransaction response fields

---

usaspending_api/download/tests/integration/test_download_status.py
usaspending_api/download/v2/download_column_historical_lookups.py

DEV-3993 specified that `prime_award_project_title` was supposed to only be in subcontracts. This removed the header from subgrants.
8. [x] Jira Ticket [DEV-3993](https://federal-spending-transparency.atlassian.net/browse/DEV-3993):
```
```

Warmfix: Remove unwanted header

---

usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
usaspending_api/search/tests/test_spending_by_transaction.py
usaspending_api/search/v2/elasticsearch_helper.py

Fix sorting on the keyword search page for:
* Recipient Name
* Awarding Agency
* Awarding Sub Agency
* Award Type
Changing the fields for the Elasticsearch transaction index meant that some changes needed to be made to keyword search to ensure that functionality was consistent with expected behavior. Adding `.keyword` to the `_source` fields in the ES query resulted in empty columns on the keyword page because it was trying to match `abc.keyword` to `abc`. Removing `.keyword` fixed empty columns, but broke sorting on those fields where it was removed. This solution is to put the `.keyword` usage back in place, but make sure to strip it out when passing fields to `_source`. 
Tests were added to verify that the sorting functionality is working for all …

[Warmfix][DEV-4032] Fix sorting on keyword search

---

config/supervisord.conf
usaspending_api/bulk_download/config/supervisord.conf

Reduce verbosity of supervisord.log by not duplicating app logs in it.
It turns out that having this set at debug will duplicate any console logging output from the running python processes to the supervisor logs
- see: debug puts process output into the normal log: http://supervisord.org/logging.html#activity-log-levels
- see: about how child process stderr and stdout gets logged when defaulted to AUTO: http://supervisord.org/logging.html#child-process-logs
- see that the defaults when not set puts it in the /tmp dir with 50MB rotated files up to a max of 10 files: http://supervisord.org/configuration.html
[OPS-1036](https://federal-spending-transparency.atlassian.net/browse/DEV-1036)
**Requirements for PR …

OPS-1036 remove debug log level for supervisor

---

usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/filestreaming/zip_file.py

Revert to using "append" mode when creating the download zip to fix the problem of each additional file added re-starting the zip from scratch. 
- Write mode `'w'` was introduced when creating the download zip as a precaution against re-using a stale, half-built zip file on a retry attempt of the bulk downloader (queue retry)
- Turns out our code does not create the zip in one-go, but in several calls to add files. 
- So put append mode `'a'` back into place instead
- And added a precautionary removal of a pre-established zip with the same file name on new download generations
- [NA] …

FIX: [DEV-2896] Fixing download zip file overwriting

---

usaspending_api/conftest.py
usaspending_api/download/tests/integration/test_download_accounts.py
usaspending_api/download/tests/integration/test_download_accounts_dev_3997.py
usaspending_api/download/tests/integration/test_download_assistance.py
usaspending_api/download/tests/integration/test_download_awards.py
usaspending_api/download/tests/integration/test_download_contract.py
usaspending_api/download/tests/integration/test_download_count.py
usaspending_api/download/tests/integration/test_download_idv.py
usaspending_api/download/tests/integration/test_download_status.py
usaspending_api/download/tests/integration/test_download_transactions.py
usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py
usaspending_api/references/tests/integration/test_city.py
usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
usaspending_api/references/tests/test_load_agencies.py
usaspending_api/references/tests/test_load_object_classes.py
usaspending_api/references/tests/test_toptier_agency_v2.py
usaspending_api/search/tests/integration/test_spending_by_award_type_count.py
usaspending_api/search/tests/integration/test_spending_by_transaction.py
usaspending_api/search/tests/integration/test_spending_over_time.py
usaspending_api/search/tests/unit/test_spending_by_award_count.py
usaspending_api/search/tests/unit/test_spending_over_time_details.py
usaspending_api/search/tests/unit/test_tas_search.py
usaspending_api/tests/test_award_index_elasticsearch.py
usaspending_api/tests/test_demo_elasticsearch_tests.py

As part of a larger effort to clean up our pytests, removed a problematic fixture that would occasionally cause subsequent tests to fail depending up the order in which the tests were executed along with some other issues.
There were three primary issues.
Issue #0:  A fixture was attempting to monkeypatch Django connections directly rather than the file-being-tested’s reference to the connections object. This meant that if the file was loaded before the test, the connections object would not be overridden which lead to inconsistent test failures.  This was a confusing piece of code anyway and was only used in one place so I just removed it and applied the specific monkeypatch required for the test within the test itself.
Issue #1:  One of the newer …

[DEV-4096] Remove problematic fixture

---

usaspending_api/references/tests/test_naics.py
usaspending_api/references/v2/views/naics.py

If a NAICS has no child, its count is 0, not 1
I'd like to refactor this whole file, but it's not nessicary so I'll wait on another PR based on my whims tonight/tomorrow.
1. [x] Unit & integration tests updated 
8. [x] Jira Ticket [DEV-4202](https://federal-spending-transparency.atlassian.net/browse/DEV-4202):
```
```

Minimalist fix to update grandchild count to 0

---

usaspending_api/etl/award_helpers.py

After edits to SQL, the psycopg2 values were not appropriately updated
Thanks @kbard 
N/A
8. [x] Jira Ticket [DEV-4109](https://federal-spending-transparency.atlassian.net/browse/DEV-4109):
```
Minor change to fix broken functionality after refactor
```

[DEV-4109] Part 2.1: Fixing FABS award updates

---

usaspending_api/common/elasticsearch/client.py
usaspending_api/search/tests/unit/test_spending_by_award_count.py
usaspending_api/search/v2/views/spending_by_award.py
usaspending_api/search/v2/views/spending_by_award_count.py

Adds elasticsearch capability to the `/api/v2/search/spending_by_award_count` endpoint.
Switch between the postgres implementation and the elasticsearch implementation by sending `X-Experimental-API/elasticsearch` header with the API request. Elasticsearch results are obtained by querying the different award type aliases with the same filters.
8. [x] Jira Ticket [DEV-4205](https://federal-spending-transparency.atlassian.net/browse/DEV-4205):
**Area for …

[DEV-4205] Elasticsearch spending_by_award_count endpoint

---

usaspending_api/database_scripts/etl/transaction_delta_view.sql
usaspending_api/database_scripts/matviews/vw_award_search.sql

Small change to how the views are created. Merging into Staging first to avoid issues with the Prod deploy.
For Sprint 98 Staging Deploy ran into an issue with removing columns from `vw_award_search`. The problem is rooted in the `CREATE OR REPLACE VIEW` statement since according to Postgres ["the new query must generate the same columns that were generated by the existing view query..."](https://www.postgresql.org/docs/9.3/sql-createview.html) The solution is to first remove the view and then create the view.  
5. [X] Frontend impact assessment completed (N/A)
6. [X] …

Less fragile delete statements for views

---

usaspending_api/database_scripts/job_archive/recompute_all_awards.py
usaspending_api/etl/award_helpers.py

Using `unique_award_key` for the award update SQL caused two issues:
1. Degraded performance (known)
1. Need to properly handle `unique_award_key` values with quotes
Also there was an issue with the fix script which didn't appropriately return a non-0 exit code for Jenkins to handle.
Since one script will check and correct bad FK values in `transaction_normalized`, using the FKs will not introduce data quality issues. The script will be run on a daily basis with a flag to test the FKs and ensure any drift is caught immediately and flagged.
5. [x] Frontend …

[DEV-4109] Part 3.1: Follow-up tweaks to script after test runs

---

usaspending_api/common/etl/etl_dblink_table.py

During work for new transaction import code, a bug was discovered that the DBLink object was attempting to map data types that did not exist to columns in the source data.  New code filters out columns that are not represented by provided data types.
1. [x] Unit & integration tests unaffeced
7. [x] Operations ticket not required
8. [x] Jira Ticket [DEV-1666](https://federal-spending-transparency.atlassian.net/browse/DEV-1666):

[DEV-1666] Minor fix for ETL importer

---

usaspending_api/references/v1/urls.py
usaspending_api/references/v2/urls.py
usaspending_api/references/v2/views/toptier_agencies.py

Very minor tweak to how the agency list is generated as it was inappropriately using the `is_toptier` flag.
Also removed a couple pieces of dead code.
1. [x] Tests unaffected
8. [x] Jira Ticket [DEV-3930](https://federal-spending-transparency.atlassian.net/browse/DEV-3930):

[DEV-3930] Remove is_toptier from agency list filter

---

usaspending_api/download/v2/base_download_viewset.py
usaspending_api/download/v2/download_status.py

Django was incorrectly treating https://api.usaspending.gov/api/v2/download/status/ as an endpoint which supported POST. This was caused from class inheritance.
Minor reorganizing
8. [x] Jira Ticket [DEV-4122](https://federal-spending-transparency.atlassian.net/browse/DEV-4122):
```
Minor changes for API documentation site
```

[DEV-4122] Removed download base class from status view

---

requirements/requirements-dev.txt
usaspending_api/awards/models/award.py
usaspending_api/awards/models/parent_award.py
usaspending_api/awards/models/transaction_normalized.py
usaspending_api/awards/tests/integration/test_subaward_endpoint.py
usaspending_api/awards/tests/test_awards_accounts_v2.py
usaspending_api/awards/tests/test_awards_funding_rollup_v2.py
usaspending_api/awards/tests/test_funding_v2.py
usaspending_api/awards/tests/unit/test_subawards.py
usaspending_api/common/api_request_utils.py
usaspending_api/common/tests/unit/test_helpers.py
usaspending_api/conftest.py
usaspending_api/idvs/tests/test_awards_idvs_accounts_v2.py
usaspending_api/idvs/tests/test_awards_idvs_activity_v2.py
usaspending_api/idvs/tests/test_awards_idvs_awards_v2.py
usaspending_api/idvs/tests/test_awards_idvs_funding_rollup_v2.py
usaspending_api/idvs/tests/test_awards_idvs_funding_v2.py
usaspending_api/recipient/tests/integration/test_recipient.py
usaspending_api/search/models/base_award_search.py
usaspending_api/search/models/subaward_view.py
usaspending_api/search/models/universal_transaction_matview.py
usaspending_api/search/tests/integration/test_spending_by_award_type_count.py
usaspending_api/search/tests/unit/test_new_awards_over_time.py
usaspending_api/search/tests/unit/test_spending_by_category.py
usaspending_api/search/tests/unit/test_spending_over_time_details.py

Made the necessary changes to upgrade Django to 2.2.X.
Not many code changes were needed for the upgrade. The most notable change is that `on_delete` is now required for ForeignKey, OneToOne, and ManyToMany. Older versions of Django [defaulted to CASCADE](https://docs.djangoproject.com/en/1.11/ref/models/fields/#arguments). This is why a lot of the models have been updated to explicitly say `on_delete=models.CASCADE`. The only exceptions are the matviews which are set to `on_delete=models.DO_NOTHING`. 
The majority of this PR is removing the use of MockModel and MockSet from `django-mock-queries` in favor of Model Mommy. Without getting into the weeds of re-writing every single test, an attempt was made to rewrite only the parts necessary for Model …

[DEV-3074] Remove MockSet, MockModel, and deprecated Django code

---

usaspending_api/api_contracts/contracts/v2/download/accounts.md
usaspending_api/download/download_utils.py
usaspending_api/download/lookups.py
usaspending_api/download/tests/integration/test_download_accounts.py
usaspending_api/download/tests/integration/test_download_accounts_dev_3997.py
usaspending_api/download/v2/request_validations.py

To facilitate multiple Submission types in a single Account Download request, `submission_type` is being replaced by `submission_types`. While `submission_type` is legacy and removed from the API Contract, it remains in place for backward compatibility. …

[DEV-4329] Implement new filter for array of submission types

---

usaspending_api/transactions/agnostic_transaction_deletes.py
usaspending_api/transactions/agnostic_transaction_loader.py
usaspending_api/transactions/loader_functions.py
usaspending_api/transactions/management/commands/transfer_assistance_records.py
usaspending_api/transactions/management/commands/transfer_procurement_records.py
usaspending_api/transactions/migrations/0001_initial.py
usaspending_api/transactions/models/source_assistance_transaction.py

Changing the unique field used for higher robustness and better data quality when loading data from Broker source system.
- Switching `published_award_financial_assistance_id` -> `afa_generated_unique` and `detached_award_procurement_id ` -> `detached_award_proc_unique `
- This will incur a performance hit, but still much much higher than anything we currently have
- Added unique flag to migration so `afa_generated_unique` will be indexed
- Manually added to staging
7. [x] …

[DEV-4408] Changing unique field for new transaction loaders

---

usaspending_api/common/query_with_filters.py
usaspending_api/conftest_helpers.py
usaspending_api/database_scripts/etl/award_delta_view.sql
usaspending_api/database_scripts/etl/transaction_delta_view.sql
usaspending_api/etl/es_award_template.json
usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/es_transaction_template.json
usaspending_api/tests/test_award_index_elasticsearch.py

Removed Nested Types from Transaction and Award ES indexes.
Did not change the View SQL that makes the JSON Array in Postgres, but instead added to the ETL so that it will parse the JSON Array and create a list of formatted strings. Made updates to the TAS filter to use `regexp` query since TAS and Federal Account records will be stored as a list of formatted strings in Elasticsearch.
Here is a sample query run on Kibana against Elasticsearch: 
```
{
"query": {
"regexp": {
"treasury_accounts": {
"value": """{\"a\": \".*\", \"aid\": \"097\", \"ata\": \".*\", \"sub\": \".*\", \"bpoa\": \".*\", \"epoa\": \".*\", \"main\": \"4930\"}"""
}
}
}
}
``` …

[DEV-4155] Removed all references to nested type with ES

---

usaspending_api/download/management/commands/populate_monthly_delta_files.py

Headers were updated for regular downloads in a previous PR. Delta file code failed because it was expecting the previous name for the uniqueness fields (`parent_award_id` -> `parent_award_id_piid `)
N/A
```
Minor edit to Delta download script which isn't run by the API.
There need to be tests around the deltas, save that for a future exercise.
```

[FIX] Updated Delta Download script fieldname 

---

usaspending_api/download/lookups.py
usaspending_api/download/tests/integration/test_download_accounts_dev_3997.py

HOTFIX to temporarily remove account rollups until such time as we can make them not require a temporary table.

[DEV-3997 HOTFIX]: Temporarily remove account rollups

---

usaspending_api/settings.py

Add info logging for USAspending-API modules to be able to track them in Kibana.
A "root" logger for the USAspending-API modules so that we can track Info logs in Kibana.
5. [X] Frontend impact assessment completed (N/A)
6. [X] Data validation completed (N/A)
8. [X] Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123):
```
```

Add info logging for USAspending-API modules

---

usaspending_api/references/management/commands/load_city_county_state_code.py

Minor tweak to make logging consistent in the `ref_city_county_state_code` loader.
1. [x] Unit tests unaffected
8. [x] Jira Ticket [DEV-4404](https://federal-spending-transparency.atlassian.net/browse/DEV-4404):

[DEV-4404] Change to logging

---

usaspending_api/broker/management/sql/restock_duns.sql
usaspending_api/recipient/management/sql/restock_recipient_lookup.sql
usaspending_api/recipient/management/sql/restock_recipient_profile.sql
usaspending_api/recipient/management/sql/restock_summary_award_recipient.sql

Truncate has a few nice benefits. Unfortunately, when run within a lengthly transaction block it completely locks the table to reads.
[TRUNCATE](https://www.postgresql.org/docs/10/sql-truncate.html) vs [DELETE FROM](https://www.postgresql.org/docs/10/sql-delete.html)
```
Minor SQL tweaks for ETL scripts
```

[OPS] Removing truncate from SQL scripts

---

usaspending_api/database_scripts/etl/award_delta_view.sql

Adds `DISTINCT` to the json aggregation in award delta view to prevent overrunning the csv field limit.

Fix JSON aggregation in award_delta_view 

---

usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/tests/test_es_rapidloader.py

Change method of running sql to the execute_sql_statement function in es_etl_helpers to prevent django db connection from breaking.

Check awards for deletes sql fix

---

usaspending_api/search/tests/conftest.py
usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_agency.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_subagency.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_agency.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_subagency.py

Since we all have to add different aspects to these transactions and awards, splitting that off from the ref data will avoid a lot of conflicts

seperated awards from ref data

---

usaspending_api/api_contracts/contracts/v2/bulk_download/list_agencies.md
usaspending_api/download/v2/download_list_agencies.py

**NOTE:**  Merge this at the same time as [FRONTEND 1524](https://github.com/fedspendingtransparency/usaspending-website/pull/1524)
How we return agencies for account downloads vs award downloads have diverged.  This code supports that divergence.  Also removed an unused response array/list.
8. [x] Jira Ticket [DEV-3932](https://federal-spending-transparency.atlassian.net/browse/DEV-3932):

[DEV-3932] Adjust download agency list

---

usaspending_api/search/v2/views/spending_by_award.py

The business logic to calculate if there was a next page was making a DB call instead of using a pre-run list of results
Django Querysets are lazily loaded, but they will run SQL everytime an operator is determining state. In this case, `len(queryset)` needed to run SQL to determine how many results were being returned. This is unnecessary since the DB rows were already returned to create the response JSON.
8. [x] …

[FIX] SpendingByAward was unintentionally running an extra SQL

---

usaspending_api/database_scripts/job_archive/dev-4531-fix-hashes.sql
usaspending_api/references/v1/views.py

Fixes the issue with the filter hashes on Advanced Search not functioning properly.
Trims the hash being stored in postgres to remove the python byte literal `b''` from the string.
7. [X] Appropriate Operations ticket(s) created [DEV-4624](https://federal-spending-transparency.atlassian.net/browse/DEV-4624)
8. [X] Jira Ticket [DEV-4531](https://federal-spending-transparency.atlassian.net/browse/DEV-4531):
```
No changes to matviews.
```

[DEV-4531] Trim hashes to remove byte literal

---

usaspending_api/common/query_with_filters.py
usaspending_api/etl/es_award_template.json
usaspending_api/etl/es_transaction_template.json

Two fields on the ES Index were changed a few sprints ago from Text to Keyword. Since Text type allows partial matches and Keyword does not it no longer allowed a user to supply a series of search terms (such as a DUNS seperated by commas). This PR reverts that change and makes small additional changes to keep expected functionality.
A problem was found where previously a user could pass in a list of DUNS using Keyword Search and it would return all Awards that have match any of those DUNS. A little while back this was removed when `recipient_unique_id` and `parent_recipient_unique_id` were changed from Text to Keyword type in the Elasticsearch Index. 
Below is an example from my Local that shows current functionality. When searching for a series of …

Updated ES Mappings for Recipient Unique ID

---

usaspending_api/bulk_download/tests/test_download.py
usaspending_api/database_scripts/tests/test_custom_sql_functions.py

**DO NOT MERGE:** Until downmerge #2316 has been completed.
This pull request fixes and enables the `test_list_agencies` test and fixes the `test_urlencoding_no_change` test which was adversely affected by the repairs to the `test_list_agencies` test.
`test_urlencoding_no_change` was assuming the insertion order would be the same as the return order which you cannot reliably do in a SQL database without an `order by` clause. …

[DEV-3932] Enable and fix tests

---

usaspending_api/awards/management/commands/load_subawards.py
usaspending_api/common/etl/mixins.py
usaspending_api/common/helpers/timing_helpers.py
usaspending_api/common/management/commands/matview_runner.py
usaspending_api/database_scripts/job_archive/management/commands/dev_4109_repair_awards.py
usaspending_api/etl/management/commands/submission_loader.py
usaspending_api/etl/transaction_loaders/fpds_loader.py
usaspending_api/references/management/commands/load_agencies.py
usaspending_api/references/management/commands/load_city_county_state_code.py
usaspending_api/references/management/commands/load_object_classes.py
usaspending_api/references/management/commands/load_tas.py
usaspending_api/transactions/agnostic_transaction_loader.py

Our Timer class allows us to log detailed timing information to Python logs (for example, how long unzipping a file takes).  When we added a new log level, it complicated the usage of the `Timer` class.  This pull request adds two new convenience classes that should re-simplify its usage.
The default behavior is now to just `print`.  Added a convenience class to log to the "console" logs (`ConsoleTimer`) and another to log to the "script" logs (`ScriptTimer`).  Of course, you can continue to override the default `Timer` if you wish something different.
5. [x] Frontend …

[UNTICKETED] Add Timer convenience classes

---

usaspending_api/api_contracts/contracts/v2/awards/award_id.md
usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/data_layer/orm.py
usaspending_api/idvs/tests/test_awards_idv_v2.py

Today, when an award is viewed that was awarded by an agency that has no agency page in USAspending, users are taken to a 404 page when they click on the agency link.  This pull request is the backend bit that provides the frontend with the information needed to determine whether or not an agency has an agency page.
Paired with [FRONTEND #1532](https://github.com/fedspendingtransparency/usaspending-website/pull/1532) although, **TECHNICALLY**, this change can be pushed without impacting the front end since it is additive.
7. …

[DEV-3935] Prevent linking to agencies without agency pages

---

usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/v2/base_download_viewset.py
usaspending_api/download/v2/request_validations.py

Forgot that we use an SQS Handler for download jobs that are not local. As a result, part of the logic that allows the new custom award download changes is not being hit when a non-local environment performs a download.
Checking for when the new `prime_and_sub_award_types` filter is present instead of the `origination` since the latter is not being provided by the SQS Handler. …

[DEV-4430] Change some logic to work with Download SQS Handler

---

usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
usaspending_api/bulk_download/tests/test_download.py
usaspending_api/download/v2/year_limited_downloads.py

User has the ability to select `Insurance` from the `Other` grouping by itself.
To accommodate the ability to select only `Insurance` the actual Award Type Codes are expected instead of the category that they fall in to on other pages. This allows for the `Other` category to be split into `Insurance` and `Other Financial Assistance`.
8. [X] Jira Ticket [DEV-4430](https://federal-spending-transparency.atlassian.net/browse/DEV-4430):
**Area for …

[DEV-4430] Split up the "Other" Award Type category for bulk award download

---

usaspending_api/api_contracts/contracts/v2/transactions.md
usaspending_api/awards/tests/integration/test_transactions_v2.py
usaspending_api/awards/v2/views/transactions.py

Adds the CFDA number for the transaction to the api/v2/transactions endpoint for assistance transactions to support the addition of the CFDA to the  
Annotates the TransactionNormalized query with a subquery to TransactionFABS.
8. [x] Jira Ticket [DEV-3478](https://federal-spending-transparency.atlassian.net/browse/DEV-3478):
```
No change to matviews, no ops tickets needed
```

[DEV-3478] Add CFDA number to transactions endpoint

---

usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
usaspending_api/bulk_download/tests/test_download.py
usaspending_api/download/v2/request_validations.py

Fix bug where you cannot download Custom Award Bulk Download by `All Foreign Countries`. This was a pre-existing issue that came up while testing the addition of Place of Performance to the location selection.
The current implementation was having `FOREIGN` passed from the Website as the Country to specify that all foreign countries should be queried and not the USA. Since this is not an actual country code it did not work with how the location filter logic. The solution to allow all foreign countries is to allow the scope filters on the Custom Award Bulk Download endpoint.  …

[DEV-4430] Warmfix foreign country location selection on custom award download

---

usaspending_api/etl/es_etl_helpers.py

Fixes issue where elasticsearch rapidloader was not deleting records.
During the upgrade to ES 7.1, I missed updating the delete query used to remove the `type` field, which caused elasticsearch not to delete any records. This allows us to combine the `delete_awards_from_es` and `delete_transactions_from_es` into one function. Additionally, the upgrade to ES also causes the total results returned from hitting the `_search` endpoint to generalize the response to be 
```
"total": {
"value": 10000,
"relation": "gte"
}
```
which causes the number of deletes to be recorded as `0` no matter what as the code subtracts the count of the before the deletes occur to the count of deletes after, and when the value is `10000` both times, it stays at `0`.

[DEV-4705] Fix Elasticsearch deletions

---

usaspending_api/search/v2/views/search_elasticsearch.py
usaspending_api/search/v2/views/spending_by_award.py

Removes the "jumping" feature on spending_by_award when using Elasticsearch due to performance issues.
The "jumping" worked by determining the correct record based on the page number and the limit, then doing a postgres search to get the value of the records preceding the desired first record, then querying elasticsearch using the `search_after`. The performance for this was bad. 
Note: Removing this code will require using a different API request for spending_by_award, but only after query through 50,000 records. I.E. - for pages 1-833 of the advanced search page (using limit: 60), the API will return fine. After that, you will have to use the last_record_unique_id" and "last_record_sort_value" to get the correct results.
**Requirements for PR …

[DEV-4649] Remove ES page jumping

---

usaspending_api/etl/es_etl_helpers.py

Use a routing key technique to put all the same transaction documents in the transactions ES index on the same physical shard.
TL;DR - this makes our high-cardinality (2M unique recipients to sum data for) queries performant and accurate, where they were not before. Further, this redistribution of data does not seem to hurt performance of other queries.
- See detailed explanations and background and conclusions here. 
- https://federal-spending-transparency.atlassian.net/browse/DEV-4538
- https://federal-spending-transparency.atlassian.net/browse/DEV-4685
- https://discuss.elastic.co/t/high-cardinality-aggregation-alternate-approaches-2-million-buckets/222814
**NOTE: It will require a reindex after deploy to staging and production for each of those …

[DEV-4685] Route transaction documents to shards by recipient_hash

---

usaspending_api/common/cache_decorator.py

Prevents Elasticsearch requests from populating the cache. Same as https://github.com/fedspendingtransparency/usaspending-api/pull/2347.

[DEV-4693] Prevent ES caching

---

.travis.yml

Elasticsearch tests will occasionally fail due to memory issues.
The current settings for `Xmx` and `Xms` are causing Elasticsearch tests to occasionally fail due to issues with memory. This increases those values to avoid random test failures on Travis runs.
5. [X] Frontend impact assessment completed (N/A)
6. [X] Data validation completed (N/A)
8. [X] Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123): (N/A)
```
```

Increase memory allocated to Elasticsearch on Travis

---

usaspending_api/search/elasticsearch/filters/naics.py

After being pointed back to the docs, it turns out that order of operations is not guaranteed with ES booleans, so the nodes of the recursive NAICS query now guard themselves with parens to ensure they work independently.
2. [ ] API documentation updated (N/A)
4. [ ] Matview impact assessment completed (N/A)
5. [ ] Frontend impact assessment completed (N/A)
6. [ ] Data validation completed (N/A)
7. [ ] Appropriate Operations ticket(s) created (N/A)
```
```

WARMFIX: Minor update to NAICS logic

---

usaspending_api/awards/v2/filters/matview_filters.py
usaspending_api/search/elasticsearch/filters/naics.py
usaspending_api/search/tests/integration/test_spending_over_time.py
usaspending_api/search/tests/unit/filters/naics.py

Throws an error if a user attempts to filter on naics codes that are not 2, 4, or 6 digits long.
Extra set of parens added to ES query recursive logic, since sometimes a `NOT` could end up on the same level as an `AND` or `OR`
8. [x] Jira Ticket [DEV-4782](https://federal-spending-transparency.atlassian.net/browse/DEV-4782):
```
```

WARMFIX: dev-4782 reject odd length naics codes

---

.travis.yml

Travis is not running integration tests that live in a sub-folder and not immediately under a `*/tests/integration/` directory.
The command to run integration tests will run all integration tests under a `*/tests/integration` folder. Some stats to prove this out:
* Total Tests: 724
* Total Unit Tests (or non-Integration Tests): 489
* Total Integration Tests (before fix): 206
* Total Integration Tests (after fix): 235
(Will note that the stats above are from a feature branch where this was noticed so they are off by about six tests from current state of DEV. Also, the numbers do not count skipped tests.) …

Correct travis command that runs integration tests

---

usaspending_api/references/tests/integration/filter_tree/conftest.py
usaspending_api/references/tests/integration/filter_tree/tas/tas_data_fixtures.py
usaspending_api/references/tests/integration/filter_tree/tas/test_level_1_tas.py
usaspending_api/references/tests/integration/filter_tree/tas/test_toptier_tas.py
usaspending_api/references/v2/views/filter_tree/tas_filter_tree.py

Old implementation was returning counts of children in the provided tree, not the "true" tree. 
The need to always make an extra query slows down the searches slightly, but local testing stayed well within 15 second parameters
```
```

Fix Child Counts of TAS Filter Tree

---

usaspending_api/common/recipient_lookups.py

Original SQL only worked when both the award's latest transaction and the recipient lookup record contained a DUNS. Now, in the event of no DUNS in the transaction/award the lookup will be performed using the name and null DUNS
N/A
8. [x] Jira Ticket [DEV-4506](https://federal-spending-transparency.atlassian.net/browse/DEV-4506):
```
Changes simply increase the results which …
```

[DEV-4506] Obtain recipient_id when record doesn't contain DUNS

---

usaspending_api/references/management/commands/load_agencies.py
usaspending_api/references/management/commands/load_agencies_sql/toptier_agency_query.sql

Army, Navy, and Air Force are no longer required in the USAspending toptier agency table.  In order to prevent confusion and accidental linking, they have been removed.  If you need to look up official names or abbreviations, they do still exist in the CGAC table.
1. [x] Tests unaffected
8. [x] Jira Ticket [DEV-4795](https://federal-spending-transparency.atlassian.net/browse/DEV-4795):

[DEV-4795] Remove DOD subsumed agencies from agency/toptier tables

---

usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/download/v2/download_column_historical_lookups.py

We added an Owning Agency column to Account Download files and renamed a handful of other columns.
1. [x] Tests unaffected
7. [x] No Operations tickets required
8. [x] Jira Ticket [DEV-4790](https://federal-spending-transparency.atlassian.net/browse/DEV-4790):

[DEV-4790] Add Owning Agency to downloads

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py
usaspending_api/common/helpers/s3_helpers.py
usaspending_api/etl/es_etl_helpers.py
usaspending_api/transactions/transaction_delete_journal_helpers.py

Last sprint we introduced a hotfix to use S3 last modified date when filtering FPDS/FABS delete files.  This will work right up until we move the files somewhere else.  Thankfully, the original developers added the file creation time epoch to the file name so we are able to persistently determine when those files were created.
This pull request converts the S3 code to use that epoch instead of the last modified date.  It also cleans up some of the logging we added when trying to track down the problem.  Finally it attempts to simplify a couple of the lower level functions.
1. [x] Unit & integration tests unaffected
5. [x] Front end …

[DEV-4943] Use file epoch instead of S3 last modified for filtering delete files

---

usaspending_api/etl/transaction_loaders/generic_loaders.py

This is a very minor fix for a very fringe case problem.  Because the FPDS loader looks up differences by `detached_award_proc_unique` then later attempts to update them by `detached_award_procurement_id`, there's a slight chance that records won't get updated if the `detached_award_procurement_id` changes (which happens fairly frequently).  This is really only an issue when deletes are not picked up correctly, so it only expresses itself due to another bug, but it compounds the mess that is created by the other bug making it significantly harder to clean up afterwards.
1. [x] Unit & integration unaffected
6. …

[DEV-4872] Change FPDS loader to consistently use natural key for updates

---

usaspending_api/common/query_with_filters.py
usaspending_api/references/v2/views/city.py
usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
usaspending_api/search/tests/unit/test_es_sanitize.py
usaspending_api/search/v2/elasticsearch_helper.py
usaspending_api/search/v2/es_sanitization.py
usaspending_api/search/v2/views/search_elasticsearch.py

Adds sanitization for elasticsearch text input to advanced search filters.
Strips all lucene special characters from the text entered into the advanced search filters. This is slightly different from the keyword search method, which strips only specific characters as the keyword search functionality allows using certain characters.
Additionally, for whatever reason importing the sanitization function from elasticsearch_helpers.py would not work in query_with_filters.py so we had to redefine it there.
6. [X] Data validation …

WARMFIX [DEV-4963] Sanitize elasticsearch text input

---

usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
usaspending_api/etl/es_transaction_template.json
usaspending_api/search/tests/integration/test_spending_by_transaction.py

A minor change from `integer` to `text` type resulted in an inability to sort by the Mod column on Keyword Search.
Add a `keyword` type for sorting and also fix the test case that should verify this ability to sort. Did verify that the test case now fails when the value does not support the `keyword` type.
Note: The test does not need the `logging_statements` variable, but this is being cleared up as part of moving Postgres functionality to Elasticsearch on numerous endpoints. 
7. [X] …

[DEV-4818] Fix sorting by Mod column on Keyword Search

---

usaspending_api/search/v2/es_sanitization.py

Fixes minor bug in keyword search sanitization.
Adds `\` to the regex sanitizing keyword search input. Also removes the `%` character from the regex as the error seems to be on the frontend
8. [X] Jira Ticket [DEV-4819](https://federal-spending-transparency.atlassian.net/browse/DEV-3819):
```
No changes to matviews, no ops tickets needed
```

WARMFIX [DEV-4819] Fix sanitization regex

---

usaspending_api/database_scripts/etl/transaction_delta_view.sql

A previous edit to the SQL view overlooked the scenario when a transaction record is updated or added, but the modification doesn't impact the award record.
This should have been the solution in #2408
8. [x] Jira Ticket [DEV-4836](https://federal-spending-transparency.atlassian.net/browse/DEV-4836):
```
Only SQL edits for ETL; doesn't impact API, data, or db schema
```

[DEV-4836] Corrected update_date values in SQL view

---

usaspending_api/agency/tests/integration/test_agency_endpoint.py
usaspending_api/agency/tests/integration/test_agency_federal_account_count.py
usaspending_api/agency/v2/views/agency_base.py
usaspending_api/agency/v2/views/agency_overview.py
usaspending_api/agency/v2/views/budget_function_count.py
usaspending_api/agency/v2/views/federal_account_count.py
usaspending_api/agency/v2/views/object_class_count.py
usaspending_api/agency/v2/views/program_activity_count.py
usaspending_api/api_contracts/contracts/v2/agency/toptier_code.md
usaspending_api/api_contracts/contracts/v2/agency/toptier_code/budget_function/count.md
usaspending_api/api_contracts/contracts/v2/agency/toptier_code/federal_account/count.md
usaspending_api/api_contracts/contracts/v2/agency/toptier_code/object_class/count.md
usaspending_api/api_contracts/contracts/v2/agency/toptier_code/program_activity/count.md
usaspending_api/api_contracts/contracts/v2/references/toptier_agencies.md
usaspending_api/common/helpers/generic_helper.py
usaspending_api/references/tests/test_toptier_agency_v2.py
usaspending_api/references/v2/views/toptier_agencies.py

A little post-PTO cleanup and consistency.
Highlights:
- Added `messages` to responses for new agency endpoints so we can document data limitations for consumers (e.g. account data only goes back to 2017).
- Cached properties on the base class.  An unfortunate side effect of a last minute tweak added to the pull request was that it was pinging the database about a dozen times to fill in response objects.  This way the database is only called once.
- Added `toptier_code` to agency list endpoint so front end will be able to link to Agency 2.0 pages when the cutover happens.
- Tried to add a little consistency to method names.  I guess one of the downsides of splitting up endpoint development is that you end up with different styles depending on who's working on what.  Or …

[DEV-4340] Little bit of cleanup and consistency

---

Dockerfile

rpm downloaded from download.postgresql.org no longer is available. referencing latest to increase our chances it will be available in the future.
When building the docker container, I could not build it because the rpm file on postgres' website was no longer available. This PR will update the referenced rpm file to the latest for the desired architecture.
can't build the docker container if the publicly hosted rpm is not available.

Updating Dockerfile: Referenced public rpm no longer exists.

---

usaspending_api/broker/management/commands/fabs_nightly_loader.py
usaspending_api/broker/tests/integration/test_incremental_load_start_datetime.py
usaspending_api/transactions/agnostic_transaction_loader.py

Currently, transactions submitted between when we copy transactions from Broker and when we process those transactions are never picked up by the nightly loader.  It's pretty rare for people to submit at 1am, but it has happened at least once.
This code adjusts the FABS nightly loader to use the lesser of last run or most recent `updated_at` in order to eliminate this gap
Also added support for AFA ids on the command line for the `fabs_nightly_loader` so we can more easily fix the skipped submission attached to the ticket.
7. [x] Operations …

[DEV-4972] Prevent FABS nightly loader skips

---

usaspending_api/download/helpers/elasticsearch_download_functions.py
usaspending_api/search/v2/elasticsearch_helper.py

Manually set the shard size for downloads with Elasticsearch.
The shard_size is automatically calculated as part of Elasticsearch query unless it is manually set in a query. This poses a problem when the values reach above 10k since 10k is the maximum size for the cluster. To prevent this the shard_size is manually set to be equal to the size (which defaults to 10k). There are issues around setting shard_size for aggregations since it can omit documents on another shard when performing aggregations, but in the case of downloads, we are using aggregations purely for the pagination aspect. A unique value is used and thus the issue of not finding documents is not a concern.  …

Set Elasticsearch Downloads Shard Size

---

config/uwsgi.ini

Reducing the deployed API server node from 32GB of RAM to 8GB requires some changes to the uwsgi config
Comments in the file explain the details
**OPS link**
fedspendingtransparency/usaspending-config#686

Reconfigure uwsgi.ini for a smaller server node

---

usaspending_api/search/v2/views/spending_by_award.py

Fixes issue where agency ids were not returning.
Adjust method of formatting agency codes to account of Elasticsearch sometimes returning the agency code as a `float` instead of an `int`
8. [ ] Jira Ticket [DEV-3986](https://federal-spending-transparency.atlassian.net/browse/DEV-3986):
```
```

[WARMFIX] Fix agency codes

---

usaspending_api/broker/helpers/delete_fabs_transactions.py
usaspending_api/broker/helpers/delete_stale_fabs.py
usaspending_api/broker/management/commands/fabs_nightly_loader.py
usaspending_api/broker/tests/integration/test_delete_fabs.py
usaspending_api/broker/tests/integration/test_get_delete_pks_for_afa_keys.py
usaspending_api/transactions/agnostic_transaction_deletes.py
usaspending_api/transactions/management/commands/delete_assistance_records.py
usaspending_api/transactions/management/commands/transfer_assistance_records.py

Cleaned up some code in an effort to stamp out some more pesky FABS delete issues.  Should also rectify a minor FPDS delete issue.
Bug 1 was an issue where `afa_generated_unique` values were being stored in delete files in mixed case, which is what we want, but the FABS loader wasn't updated to match so it was attempting to find uppercased `afa_generated_uniques` using mixed case values which resulted in many missed deletes.
Bug 2 was an issue where we were attempting to delete FABS records based solely on `afa_generated_unique` which is not possible to do correctly.  Added some code to look up the `published_award_financial_assistance_ids` that need to be deleted for the `afa_generated_uniques` provided.
Bug 3 affected both FABS and FPDS.  We were filtering deletes on …

[DEV-5323/5324] FABS delete bugs warmfix

---

usaspending_api/transactions/agnostic_transaction_loader.py

_Someone_ changed the SQL to have lower-cased keywords but failed to change the conditional to look for the correct string. This PR fixed that and makes it case insensitive
N/A
```
Minor fix to ETL script
```

[FIX] Update Conditional in transaction load script

---

usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/etl/management/commands/load_multiple_submissions.py
usaspending_api/etl/tests/integration/test_load_multiple_submissions.py
usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py

This pull request addresses some tweaks @kwhickey requested for the submission loader, specifically:
1. Use only `published_date` for `last_modified_date` in account downloads.
2. Add an optimized branch for updating `certified_date` that doesn't require reloading the entire submission.
3. Rename a test.
8. [x] Jira Ticket [DEV-5041](https://federal-spending-transparency.atlassian.net/browse/DEV-5041):

[DEV-5041] Requested changes to submission loader

---

usaspending_api/etl/management/commands/load_multiple_submissions.py

This fixes a minor logging issue.  The logic should otherwise be fine.  The "incremental" log message was displaying when submission ids were supplied which shouldn't have been the case.

[DEV-5041] Fix minor logging issue

---

usaspending_api/disaster/tests/integration/test_disaster_agency_count.py
usaspending_api/disaster/v2/urls.py
usaspending_api/disaster/v2/views/agency/count.py

New endpoint to return the count of the unique Agencies that match a list of DEF Code filters.
Implement new `v2/disaster/agency/count` endpoint that returns the count of unique Funding Toptier Agencies associated with File B matching the DEF Code filters supplied to the endpoint.
8. [X] Jira Ticket [DEV-5428](https://federal-spending-transparency.atlassian.net/browse/DEV-5428):
```
```

[DEV-5428] Disaster Agency Count endpoint

---

usaspending_api/disaster/tests/fixtures/disaster_account_data.py
usaspending_api/disaster/tests/integration/test_disaster_object_class_count.py
usaspending_api/disaster/v2/urls.py
usaspending_api/disaster/v2/views/object_class/count.py

Implemented an endpoint that returns the count of Object Classes for a provided set of DEF Code filters.
Implemented `v2/disaster/object_class/count` to return the count of Object Classes for the passed DEF Code filters.
8. [X] Jira Ticket [DEV-5429](https://federal-spending-transparency.atlassian.net/browse/DEV-5429):
```
```

[DEV-5429] Implement Disaster Object Class count endpoint

---

usaspending_api/disaster/tests/integration/test_disaster_def_code_count.py
usaspending_api/disaster/v2/urls.py
usaspending_api/disaster/v2/views/def_code/count.py

Implement a new endpoint that returns the count of DEF Codes that matches the DEF Code filter. There is the possibility for the count to not match the DEF Code filter length because we are also checking for non-zero results to be considered as part of the count.
Implement `v2/disaster/def_code/count` to return the count of DEF Codes that match the DEF Code filter.
8. [X] Jira Ticket [DEV-5430](https://federal-spending-transparency.atlassian.net/browse/D …

[DEV-5430] Disaster DEF Code Count endpoint

---

usaspending_api/common/helpers/fiscal_year_helpers.py
usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
usaspending_api/spending_explorer/v2/filters/type_filter.py

Ensure Spending Explorer continues to function in a world with monthly submissions.  Cleaned up some other stuff in the process.
- Still operates on quarters.
- Validates requested FYQ against new submission window table.
- Better handling of missing required filters (no longer 500s).
- Fixed a bug that was looking only at the quarter requested when summing transaction obligated amount instead of across all quarters for the year.
- Fixed a couple of small issues with the GTAS query.
1. [x] Unit tests unaffected …

[DEV-5170] Ensure Spending Explorer doesn't explode with the introduction of monthly submissions

---

requirements/requirements-app.txt

Updating DataDog client libraries to fix a known bug in tracing forked processes
we are tracking [this](https://github.com/DataDog/dd-trace-py/issues/1184) issue with DataDog client: forked process traces are not being captured properly in our currently used version. A workaround noted in the ticket above is available in the LTS release of the client.
6. [N/A] Data validation completed
8. [X] Jira Ticket [OPS-1272](https://federal-spending-transparency.atlassian.net/browse/OPS- …

updating datadog trace client

---

usaspending_api/accounts/tests/unit/test_account_download_filter.py
usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/agency/v2/views/agency_base.py
usaspending_api/agency/v2/views/budgetary_resources.py
usaspending_api/api_contracts/contracts/v2/download/accounts.md
usaspending_api/common/helpers/fiscal_year_helpers.py
usaspending_api/common/helpers/orm_helpers.py
usaspending_api/common/helpers/s3_helpers.py
usaspending_api/common/retrieve_file_from_uri.py
usaspending_api/common/sqs/sqs_handler.py
usaspending_api/common/tests/unit/test_fiscal_year_helpers.py
usaspending_api/common/tests/unit/test_helpers.py
usaspending_api/download/v2/download_column_historical_lookups.py
usaspending_api/download/v2/request_validations.py
usaspending_api/etl/management/commands/es_configure.py
usaspending_api/etl/management/commands/es_rapidloader.py
usaspending_api/etl/rapidloader.py
usaspending_api/search/v2/views/spending_over_time.py
usaspending_api/submissions/helpers.py
usaspending_api/transactions/transaction_delete_journal_helpers.py

Before we were returning the final TAS rows for a fiscal year regardless of the quarter in which it falls.
Now, for Files A and B, we only return TAS rows in the quarter or period requested.  For File C we only return rows in the quarter or period requested OR previous periods if the `transaction_obligated_amount` is non-zero.
Also "fixed" a few typos and bad imports.
And updated the account download endpoint to accepts quarter OR periods.  Is backward compatible so front end should be unaffected until they are ready to support periods.
5. [x] Frontend unaffected (new contract stuff, but backward …

[DEV-4443] AC 1 - Don't carry forward TAS in account downloads

---

usaspending_api/disaster/tests/integration/test_disaster_agency_count.py
usaspending_api/disaster/tests/integration/test_disaster_def_code_count.py
usaspending_api/disaster/tests/integration/test_disaster_federal_account_count.py
usaspending_api/disaster/tests/integration/test_disaster_object_class_count.py
usaspending_api/disaster/v2/views/agency/count.py
usaspending_api/disaster/v2/views/def_code/count.py
usaspending_api/disaster/v2/views/federal_account/count.py
usaspending_api/disaster/v2/views/federal_account/spending.py
usaspending_api/disaster/v2/views/object_class/count.py

We need to support the possibility of not having the latest closed submission for monthly.
Since there are currently no monthly submissions that have closed we need to add at least temporary support. Any use of a monthly submission closed date checks to make sure that it exists before being used. We know that quarterly submissions exist so the same check is not necessary.
8. N/A Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/b …

Fix Disaster Endpoints to Accommodate Data

---

usaspending_api/disaster/tests/integration/test_disaster_recipient_count.py
usaspending_api/disaster/v2/views/count_base.py

Previous functionality would just crash if count endpoints didn't have award types. This checks that, and adds a test to make sure it works.
```
```

added guard clause to count base

---

usaspending_api/settings.py

Undark the CARES Act features in backend code for Sprint 110 release heading to production on Monday 7/13.
This would allow the usaspending submission loader in prod to be compliant with the broker CARES act changes. And also allow real prod loads of monthly submissions as early as the 17th of July.
BUT - are there things in backend guarded by that flag that we would not want getting into prod on Jul 13th.
One example is starting to put a DEFC column in the downloads I don't think it would be populated with any data, because the P7/8/9 in prod would not have closed yet.
1. [NA] Unit & integration tests updated
- [NA] Operations …

[DEV-4930] ENABLE_CARES_ACT_FEATURES = True

---

usaspending_api/disaster/management/commands/generate_covid19_download.py

Early in development of the new download, an exception was mistakenly attributed to an empty CSV file. The check is too stringent for envs which might not contain enough COVID-19 spending data.
N/A
8. [x] Jira Ticket [DEV-5302](https://federal-spending-transparency.atlassian.net/browse/DEV-5302):
```
Minor change from raising an exception to logging the message
```

[DEV-5302] Replacing exception with logging

---

usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
usaspending_api/disaster/tests/integration/test_cfda_count.py
usaspending_api/disaster/tests/integration/test_cfda_spending.py
usaspending_api/disaster/v2/views/cfda/count.py
usaspending_api/disaster/v2/views/cfda/spending.py
usaspending_api/disaster/v2/views/disaster_base.py

Realized during demos that the CFDA endpoints should only allow the Assistance Award Type Codes. Additionally, needed to cleanup API Contracts where the `award_type_codes` was added for loans endpoints.
The `enum_values` for the TinyShield model are now sorted to prevent random order being returned when non-valid award_type_codes are passed back. This helps to make sure that tests don't break because of values not being sorted the same way as expected.
7. [X] Appropriate Operations ticket(s) …

[DEV-5299] Only allow assistance filters and minor cleanup on API contract

---

usaspending_api/api_contracts/contracts/v2/disaster/spending_by_geography.md
usaspending_api/disaster/tests/fixtures/recipient_location_data.py
usaspending_api/disaster/tests/integration/test_recipient_loans.py
usaspending_api/disaster/tests/integration/test_recipient_spending.py
usaspending_api/disaster/tests/integration/test_spending_by_geography.py
usaspending_api/disaster/v2/views/spending_by_geography.py

Add `award_count` to the /v2/disaster/spending_by_geography endpoint.
Populate the `award_count` on the response using the `doc_count` attribute of each bucket. This value represents the number of documents that go into each aggregation bucket, which in this case is the number of awards since it uses the Awards Index with each document being a different Award.
8. [X] Jira Ticket [DEV-5666](https://federal-spending-transparency.atlassian.net/ …

[DEV-5666] Add 'award_count' to disaster/spending_by_geography

---

usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
usaspending_api/database_scripts/etl/award_delta_view.sql
usaspending_api/disaster/tests/fixtures/disaster_account_data.py
usaspending_api/disaster/tests/integration/test_cfda_loans.py
usaspending_api/disaster/tests/integration/test_cfda_spending.py
usaspending_api/disaster/tests/integration/test_disaster_agency_loans.py
usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
usaspending_api/disaster/tests/integration/test_recipient_loans.py
usaspending_api/disaster/tests/integration/test_recipient_spending.py
usaspending_api/disaster/v2/views/agency/loans.py
usaspending_api/disaster/v2/views/agency/spending.py
usaspending_api/disaster/v2/views/elasticsearch_base.py

Original implementation returned the values from `id` in `toptier_agency` instead of `agency`
Required ES re-index of awards index
8. [x] Jira Ticket [DEV-5635](https://federal-spending-transparency.atlassian.net/browse/DEV-5635):
```
No changes to matviews
```

[DEV-5635] Fix Agency ID response values

---

usaspending_api/bulk_download/tests/test_download.py
usaspending_api/download/helpers/download_annotation_functions.py
usaspending_api/download/lookups.py
usaspending_api/download/tests/unit/test_file_generation.py
usaspending_api/download/v2/download_column_historical_lookups.py

Adds disaster emergency fund codes and covid-related obligations and outlays to the subaward download files.
DEFC and covid spending are added, summed as usual, and have 
7. [n/a] Appropriate Operations ticket(s) created
8. [x] Jira Ticket [DEV-5548](https://federal-spending-transparency.atlassian.net/browse/DEV-5548):
```
```

[DEV-5548] DEFC subaward download

---

usaspending_api/disaster/v2/views/award/amount.py

As a part of my investigation on discrepancies between counts, I noticed that the elasticsearch index filters out FABA with zero spending, so we should do the same with the award/amount endpoint
```
```

add non-zero filter to award amount endpoint to better match search

---

usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
usaspending_api/api_contracts/contracts/v2/disaster/award/amount.md
usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
usaspending_api/api_contracts/contracts/v2/disaster/federal_account/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/federal_account/spending.md
usaspending_api/api_contracts/contracts/v2/disaster/object_class/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/object_class/spending.md
usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
usaspending_api/api_contracts/contracts/v2/disaster/recipient/spending.md
usaspending_api/common/data_classes.py
usaspending_api/disaster/tests/integration/test_cfda_loans.py
usaspending_api/disaster/tests/integration/test_cfda_spending.py
usaspending_api/disaster/tests/integration/test_disaster_award_amount.py
usaspending_api/disaster/tests/integration/test_recipient_loans.py
usaspending_api/disaster/tests/integration/test_recipient_spending.py
usaspending_api/disaster/v2/views/agency/loans.py
usaspending_api/disaster/v2/views/agency/spending.py
usaspending_api/disaster/v2/views/award/amount.py
usaspending_api/disaster/v2/views/cfda/loans.py
usaspending_api/disaster/v2/views/cfda/spending.py
usaspending_api/disaster/v2/views/disaster_base.py
usaspending_api/disaster/v2/views/elasticsearch_base.py
usaspending_api/disaster/v2/views/federal_account/federal_account_result.py
usaspending_api/disaster/v2/views/object_class/object_class_result.py
usaspending_api/disaster/v2/views/recipient/loans.py
usaspending_api/disaster/v2/views/recipient/spending.py

1. Added a secondary sort on `id` for all disaster endpoints which support pagination to provide deterministic result order when results are sorted on fields with the same value
1. Changed the sort field from `count` to `award_count` for endpoints modified by #2623
1. Changed Response and sort field for other endpoints from `count` -> `award_count` not addressed in #2623
- ` /api/v2/disaster/award/amount/` (response only)
- `/api/v2/disaster/cfda/loans/`
- `/api/v2/disaster/cfda/spending/`
- `/api/v2/disaster/recipient/loans/`
- `/api/v2/disaster/recipient/spending/`
- `/api/v2/disaster/agency/spending/` (previously inconsistent)
- `/api/v2/disaster/agency/loans/` (previously inconsistent)
N/A
1. [x] Unit & integration …

[DEV-5706] Improving Sorting and fixed items from DEV-5621

---

usaspending_api/disaster/v2/views/disaster_base.py
usaspending_api/disaster/v2/views/elasticsearch_base.py

Fix sorting issues around endpoints using Elasticsearch.
Syntax for ES sorting is that a single sort can use a dictionary, but multiple sorts require a list of dictionaries. Most likely the query fell back to some default ranking instead of our specified sort which caused issues.
Also, found a typo in the pagination mixin.
8. [x] Jira Ticket [DEV-5730](https://federal-spending-transparency.atlassian.net/browse/DEV-5730):
**Area for …

[DEV-5730] Fix Elasticsearch Based Sorting

---

usaspending_api/common/query_with_filters.py
usaspending_api/disaster/v2/views/elasticsearch_base.py

The query filter should be similar in functionality to the recipient page.
Changed the default_operator used when Elasticsearch performs the query and did a minor refactor to make it more re-usable.
8. [x] Jira Ticket [DEV-5602](https://federal-spending-transparency.atlassian.net/browse/DEV-5602):
```
```

[DEV-5602] Change query filter to be 'AND' instead of 'OR'

---

usaspending_api/common/query_with_filters.py
usaspending_api/search/tests/integration/test_spending_over_time.py

Changes the code for DEFC filter to no longer filter awards by action date, only transactions.
8. [x] Jira Ticket [DEV-5673](https://federal-spending-transparency.atlassian.net/browse/DEV-5673):
```
No changes to matviews, not ops tickets needed
```

[DEV-5673] DEFC Action date fix

---

usaspending_api/common/query_with_filters.py

Previous functionality would surface recipients such as `YORK STREET PROJECT A NEW JERSEY NONPROFIT CORPORATION` when searching for `NEW YORK`. New functionality should not surface that recipient and will follow similar to the functionality below taken from ES documentation:
When searching for `quick brown f` this is how the query would handle matches. This search would match a message value of `quick brown fox` or `two quick brown ferrets` but not `the fox is quick and brown`.
Changed the query type to be `multi_match` due to multiple fields and using the `match_phrase_prefix` query type.
1. [x] Unit & integration tests updated (n/a)
2. [x] API documentation updated (n/a)
4. [x] Matview …

[DEV-5602] Minor fix to the query text filter for ES (QAT)

---

usaspending_api/download/download_utils.py
usaspending_api/download/lookups.py
usaspending_api/download/tests/integration/test_download_disaster_recipient.py
usaspending_api/download/v2/base_download_viewset.py

COVID Page download is grabbing the wrong download file since both COVID Page and Disaster Recipient both name the file `COVID-19_Profile...`. Now the COVID Page download only looks at the generated COVID Page downloads.
Add a check for a property that is only added to our downloads if they go through our download generation process, which the COVID page download does not since it is pre-generated. This will need to be changed if we move away from pre-generated download.
1. [x] Unit & integration tests updated (n/a)
4. [x] Matview impact assessment completed (n/a)
7. [x] …

[DEV-5557] Point to the right download for COVID Page Download (QAT)

---

usaspending_api/common/query_with_filters.py
usaspending_api/disaster/v2/views/elasticsearch_base.py
usaspending_api/download/v2/request_validations.py

Forgot to handle the nonzero case for downloads and so the number of recipients were off between download and recipient table.
Created a new filter to handle adding nonzero fields. This could be used by elasticsearch_base.py, but to minimize code changes at this point I have left a todo and only added to downloads.
1. [x] Unit & integration tests updated (n/a)
4. [x] Matview impact assessment completed (n/a)
5. [x] Frontend impact assessment completed (n/a)
7. [x] Appropriate Operations ticket(s) created (n/a)
8. [x] Jira Ticket [DEV-5557](https://federal-spending-transparency.atlassian.net/browse/DEV-5557):
**Area for …

[DEV-5557] Handle nonzero case for downloads (QAT)

---

usaspending_api/disaster/v2/views/award/amount.py

Fixes part of descrepencies between results from award/amount and spending endpoints
For our group by needed to filter out awards with net 0 outlays or obligations, we were accidentally including the primary key, rendering the filter useless. This narrows down the values checked.
```
```

added values to award amounts

---

usaspending_api/etl/management/commands/load_multiple_submissions.py
usaspending_api/etl/management/commands/load_submission.py
usaspending_api/submissions/dabs_loader_queue_helpers.py

- Reduce the number of Slack false negatives.  Only the last process standing reports unstable status if necessary.
- Didn't like that the queue status was pinging the database 5 times.
- Mentions when the database commit is starting so that anyone monitoring the logs isn't left wondering why nothing appears to be happening.
- Logs queue status after every submission is processed.  I found myself querying the database a lot trying to get a feel for how much was left in the queue.

[DEV-5696] Reduce submission loader false negatives (QAT)

---

usaspending_api/disaster/v2/views/agency/spending.py

Oversight on my part.  Query was running twice, once to return results and a second time to perform count.  Bad @kbard.  This a very slow endpoint so this should help a little with performance issues.  More invasive changes incoming.
1. [x] Unit & integration tests unaffected
4. [x] Matviews unaffected
8. [x] Jira Ticket [DEV-5413](https://federal-spending-transparency.atlassian.net/browse/DEV-5413):

[DEV-5413] Minor tweak to one of the agency endpoints to prevent running query twice

---

usaspending_api/references/v2/views/def_codes.py

Why you ask? Well, the frontend isn't requesting DEFC values in alphabetical order. While that alone isn't a problem for non-OCD individuals, there _is_ a problem if the order isn't deterministic between deploys or reference data loads. The problem is attempting to create an API cache warmer if the website's requests unexpectedly change over time. This minor change is simply reducing one potential reason for the order observed
N/A
7. [x] Appropriate Operations ticket(s) …

Set DEFC reference data array order

---

usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql

Restricts the records being downloaded to records that have their submission published date >= the reveal date for the submission window they were submitted in.
8. [X] Jira Ticket [DEV-5812](https://federal-spending-transparency.atlassian.net/browse/DEV-5812):
```
No frontend changes, no matview changes
```

[DEV-5812] add publish date restriction

---

usaspending_api/disaster/v2/views/agency/loans.py
usaspending_api/disaster/v2/views/agency/spending.py
usaspending_api/disaster/v2/views/cfda/loans.py
usaspending_api/disaster/v2/views/cfda/spending.py
usaspending_api/disaster/v2/views/recipient/loans.py
usaspending_api/disaster/v2/views/recipient/spending.py
usaspending_api/disaster/v2/views/spending_by_geography.py
usaspending_api/recipient/v2/views/recipients.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_federal_account.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient_duns.py
usaspending_api/search/v2/views/spending_by_geography.py

Title says it all. Recipient name contains three leading backslash characters. After the issue appeared in the COVID-19 page I tracked it down in other places across the website.
Escaping the slashes with another slash each fixed the issue. API responses will contain `\\\\\\STRIPES/// PARKING LOT SERVICE, INC.` which is correctly parsed by JSON readers, such as the website. …

[DEV-5825] Malformed json strings from Elasticsearch causing HTTP500s

---

usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/rapidloader.py

Description:
The number of rows downloaded into a CSV during the ElasticSearch ETL should be logged whether or not the --skip-counts flag is enabled. This flag is used to determine whether an additional sql script should be run to provide a secondary count to compare against the download count.
Additionally, it logs the total count of records to update before the CSV download phase begins. 
This PR makes the change described above.
Technical details:
The only non-cosmetic change is that the download_db_records method now returns the number of rows in the downloaded csv. It previously returned None if --skip-counts was enabled and the count from the count_sql script if disabled.
Requirements for PR merge:
3. [x] …

[DEV-5814] Logs download_count when downloading csv regardless of --skip-counts flag

---

usaspending_api/common/elasticsearch/json_helpers.py
usaspending_api/disaster/v2/views/agency/loans.py
usaspending_api/disaster/v2/views/agency/spending.py
usaspending_api/disaster/v2/views/cfda/loans.py
usaspending_api/disaster/v2/views/cfda/spending.py
usaspending_api/disaster/v2/views/recipient/loans.py
usaspending_api/disaster/v2/views/recipient/spending.py
usaspending_api/disaster/v2/views/spending_by_geography.py
usaspending_api/recipient/v2/views/recipients.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_federal_account.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient_duns.py
usaspending_api/search/v2/views/spending_by_geography.py

Apparently, encoding a string of json with `unicode_escape` will break the json loader if there are unicode characters in the string. Who knew?
New ugly helper function to handle json loading from str
8. [x] Jira Ticket [DEV-5825](https://federal-spending-transparency.atlassian.net/browse/DEV-5825):
```
fixing code
```

[DEV-5825] Fixing issue introduced by first PR

---

usaspending_api/disaster/v2/views/recipient/count.py
usaspending_api/search/models/vw_award_search.py

Current implementation of the Disaster Recipient Count endpoint will occasionally timeout on Postgres at more than 5 minutes. This PR gets the timing down to 2 minutes which will still timeout for the API, but will allow the response to be cached for future calls. 
Made some minor adjustments and tested code that Kirk provided using a CTE to improve performance. While greater than 2 minutes is not ideal this will allow the endpoint to be cached and further improvements can be attempted later on.
7. …

[DEV-5821] Refactor Recipient Count

---

usaspending_api/settings.py

When running the Django app in debug mode: log more
All SQL Django is executing will be logged in debug mode too
```
Changing DEBUG logging
```

When in DEBUG mode, set logging level to debug and include all SQL

---

usaspending_api/etl/award_helpers.py

`fiscal_year` is a neglected field in the `awards` table. Unfortunately, this was realized and not only were people running queries using this field, but ETL scripts were based on the values (or lack of values). Simple change so moving forward awards will be correctly updated
For a complete fix:
- `usaspending_api/database_scripts/job_archive/recompute_all_awards.py` should be run.
- If the above script is run, the update_date will be set and will be pulled into Elasticsearch indexes
6. [x] Data validation …

Populate fiscal_year field when updating award records

---

usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/management/commands/es_rapidloader.py
usaspending_api/etl/tests/test_es_rapidloader.py

There are no benefits and plenty of disadvantages when truncating the timestamp from the start time of the Elasticsearch ETL script. It is common for a large volume of records to be re-processed the following day even if the data have not changed. Since the timestamp is already being stored in the database and automatically added from the CLI this is a minor lift.
Additionally fixing CLI param to be consistent with others
8. [x] …

[DEV-5855] Remove the timestamp truncation from ES ETL

---

usaspending_api/common/datadog.py
usaspending_api/settings.py

adding headers as tags to root span in datadog trace. This will allow us to see the headers as they relate to a traced request, as well as if the request originated from frontend or API consumer.
datadog's django auto-instrumentation does not automatically include http headers in traces. So, we need to get them from django.request and add them to the root span's tag set.
- [N/A] Frontend <OPTIONAL>
- [N/A] Domain Expert <OPTIONAL>
6. [N/A] Data validation completed
8. [X] …

adding headers as tags to root span in datadog trace

---

usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md

These changes went into DEV but not QAT due to a miscommunication it was not merged on time for code freeze. This PR is to correct that, and the original PR is https://github.com/fedspendingtransparency/usaspending-api/pull/2740
8. [x] Jira Ticket [DEV-5322](https://federal-spending-transparency.atlassian.net/browse/DEV-5322):

[DEV-5322] change documentation in QAT, not just DEV 

---

usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/disaster/v2/views/object_class/loans.py
usaspending_api/download/helpers/download_annotation_functions.py

When working on DEV-5943 I realized the inefficient Django `concat` function was used in some places when concatenating more than two fields/strings. This minor warmfix PR should help with performance for some downloads and `/object_class/loans/`
Django's concat function oddly creates nested concatenations when there are more than 2 fields/text. Replacing with a simple function helps with performance when operating on large numbers of rows.
7. [x] Appropriate Operations …

[DEV-5943] Leveraging proper concat usage in postgres requires non-django function

---

usaspending_api/common/elasticsearch/json_helpers.py

There are Recipient Names that are causing issues when trying to decode a JSON formatted string to a dictionary due to not being properly escaped. As a temporary fix, these cases are handled as edge cases so that the endpoint will return successfully.
The regex is a "last chance" for the JSON Decoder to create a dictionary from the JSON formatted string. The particular recipient that caused the issues (or at least the Aggregation Key that caused the issue) is shown here:
```'{"name":""E" SECURITY, LLC","unique_id":"079542464","hash":"8b87be1f-002e-83d3-f6f9-a0d6b05edf41","levels":"{C}"}'```
After this change the Recipient Spending endpoint now returns a result for this recipient as:
```
{
"id": [
"8b87be1f-002e-83d3-f6f9-a0d6b05edf41-C"
],
"code": …
```

[DEV-6033] Regex to handle quotes in a json formatted string

---

usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
usaspending_api/spending_explorer/v2/filters/explorer.py
usaspending_api/spending_explorer/v2/filters/type_filter.py

Fixes an issue in the spending explorer where it would appear that large amounts of spending would "vanish" when switching from a File B layer to a File C layer (recipients, awards)
The reason that money seemed to be disappearing was that there are large amounts of money in File B that's non-award spending, and when switching to any of the award level/ File C spending, we did not include the non-award spending. This PR essentially queries File B data with the same filters we are using for File C, then adds the difference to the results from the File C request as "Unreported Data". 
4. [N/A] Matview impact assessment …

[DEV-4785] Spending Explorer file C unreported

---

usaspending_api/disaster/tests/fixtures/cfda_data.py
usaspending_api/disaster/tests/integration/test_cfda_loans.py
usaspending_api/disaster/tests/integration/test_cfda_spending.py
usaspending_api/disaster/v2/views/cfda/loans.py
usaspending_api/disaster/v2/views/cfda/spending.py

Originally thought `cfda_website` was a duplicate of `resource_link`, but as it turns out the field just needed to reference `website_address` instead of `url`.
Put `cfda_website` back and reference `website_address` instead of `url`.
8. [x] Jira Ticket [DEV-5977](https://federal-spending-transparency.atlassian.net/browse/DEV-5977):
```
```

[DEV-5977] Add back cfda_website as website_address

---

usaspending_api/disaster/v2/views/agency/count.py

Agency count is currently off by one in some cases when specifying award type codes.
Django ORM code was producing SQL that did a LEFT JOIN to get the agency and it needed to be an INNER JOIN to ensure that NULL is not counted as an agency. 
8. [x] Jira Ticket [DEV-6035](https://federal-spending-transparency.atlassian.net/browse/DEV-6035):
```
```

[DEV-6035] Use inner join for agency count

---

usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
usaspending_api/api_contracts/contracts/v2/download/awards.md
usaspending_api/api_contracts/contracts/v2/download/transactions.md

Updates documentation:
* Don't mention the old `agency` param, as that's now legacy
* Do add toptier_name to instances of the agency object

dev-4817 updated documentation to not mention old functionality

---

usaspending_api/common/elasticsearch/elasticsearch_sql_helpers.py
usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/management/commands/es_rapidloader.py
usaspending_api/etl/rapidloader.py
usaspending_api/etl/tests/test_es_rapidloader.py

After two attempts to increase parallelism to the Elasticsearch ETL I decided to step back and incrementally refactor the script until they were in an agreeable state for cranking up parallel/async workers downloading and uploading data.
This PR mainly replaces the `printf()` function with the application logger.
Tech Debt:
1. Removed unused SQL
1. Fixed column mapping to str for award ETL …

[DEV-5856] Elasticsearch ETL refactor (part 1)

---

usaspending_api/database_scripts/job_archive/backfill_submission_window_id.py

This is a follow up to PR: https://github.com/fedspendingtransparency/usaspending-api/pull/2793
- Fixes comment for expected CLI to run backfill script
- Moves backfill script to correct directory
This PR adds a foreign key from the `submission_attributes` table to the `dabs_submission_window_schedule` table. Previously these two tables were joined using the following attributes:
- Fiscal Year
- Fiscal Month
- Is Quarter
This PR contains two migrations. A SQL script will need to be run between the two migrations to populate the new field:
`python3 usaspending_api/database_scripts/job_archive/backfill_faba_distinct_award_key.py`
3. [x] Necessary PR …

[DEV-5945] Moves backfill script to correct location and fixes expected cli comment

---

usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
usaspending_api/api_contracts/contracts/v2/download/awards.md
usaspending_api/api_contracts/contracts/v2/download/transactions.md
usaspending_api/download/v2/request_validations.py
usaspending_api/download/v2/year_limited_downloads.py

When selecting "all" agencies in Custom Award Downloads it is causing downloads to return an empty CSV. This is because it is searching for an agency with the name of "all".
Small re-write to convert legacy "agency" filter to "agencies" and then handle the "all" agency case.
8. [x] Jira Ticket [DEV-6179](https://federal-spending-transparency.atlassian.net/browse/DEV-6179):
```
```

[DEV-6179] Fix 'all' agency case breaking downloads

---

usaspending_api/etl/es_etl_helpers.py
usaspending_api/etl/management/commands/es_rapidloader.py
usaspending_api/etl/rapidloader.py

For incremental loads, we must "delete-before-index" due to the fact that on many of our indices, we have different values for `_id` and `routing` key.
Not doing this exposed a bug in our approach to expedite incremental UPSERTS aimed at allowing ES to overwrite documents when it encountered one already existing by a given _id. The problem is that the index operation uses the routing key to target only 1 shard for its index/overwrite. If the routing key value changes between two incremental loads of the same doc with the same _id, it may get routed to a different shard and won't overwrite the original doc, leaving duplicates across all shards in the index. 
fwiw - _NOT_ using a routing key would default it to the same values as the `_id` and this would not have been a …

HOTFIX: [DEV-6181] Delete ES docs before incrementally UPSERTing to avoid dupes

---

usaspending_api/etl/elasticsearch_loader_helpers/es_etl_helpers.py

Left duplicative lines in the merge conflict resolution. Cleans that up.

Fixing duplicate code left in after a bad merge conflict resolution

---

usaspending_api/download/helpers/download_annotation_functions.py

Switches date field being checked for allowing DEFC data in the subaward download files.
Change to use `broker_subaward__sub_action_date` rather than `broker_subaward__action_date`
8. [X] Jira Ticket [DEV-6162](https://federal-spending-transparency.atlassian.net/browse/DEV-6162):
```
```

[DEV-6162] fix subaward date field

---

usaspending_api/database_scripts/matview_generator/chunked_matview_sql_generator.py
usaspending_api/database_scripts/matview_generator/matview_sql_generator.py
usaspending_api/database_scripts/matview_generator/shared_sql_generator.py

This adds "refresh" and "drops" componentized files for matview chunks in the `chunked_matview_sql_generator.py`. 
Previously chunks didn't get their own componentized files, but they are needed for `matview_runner.groovy`
8. [x] Jira Ticket [DEV-5892](https://federal-spending-transparency.atlassian.net/browse/DEV-5892):
```
Fixes to an ETL script
```

[DEV-5892] Adds componentized files refresh and drops for chunked matview sql generator

---

usaspending_api/common/management/commands/matview_runner.py
usaspending_api/etl/management/commands/combine_universal_transaction_matview_chunks.py

This PR adds an --index-concurrency parameter to the `matview_runner` and `combine_universal_transaction_matview` commands. This parameter specifies the max concurrency to use when creating the indexes on the `universal_transaction_matview` table.
Uses asyncio Semaphore to control concurrency limit 
8. [x] Jira Ticket [DEV-5892](https://federal-spending-transparency.atlassian.net/browse/DEV-5892):
- [] Before / After data comparison

Ftr/dev 5892 chunk utm refresh - Index Concurrency 

---

usaspending_api/download/filestreaming/s3_handler.py
usaspending_api/download/v2/base_download_viewset.py
usaspending_api/references/management/commands/load_historical_appropriation_account_balances.py
usaspending_api/settings.py

In a few places in the API we currently have hard coded `usaspending.gov`. With the DTI migration there is a need to specify the server URL.
Update settings.py so that an ENV can be used to specify the server URL. All hardcoded usages of `usaspending.gov` were also updated to use the new ENV. A default of `usaspending.gov` was left in place to avoid breaking any current functionality. 
Tested in DAOI Sandbox to verify that current functionality is not affected by the change. 
7. [ …

[BRUS2DTI-384] Add ENV for server URL to support DTI migration

---

usaspending_api/disaster/tests/integration/test_federal_account_award.py
usaspending_api/disaster/tests/integration/test_federal_account_loans.py
usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
usaspending_api/disaster/tests/integration/test_object_class_spending_loans.py
usaspending_api/disaster/v2/views/agency/loans.py
usaspending_api/disaster/v2/views/agency/spending.py
usaspending_api/disaster/v2/views/elasticsearch_account_base.py
usaspending_api/disaster/v2/views/federal_account/loans.py
usaspending_api/disaster/v2/views/federal_account/spending.py
usaspending_api/disaster/v2/views/object_class/loans.py
usaspending_api/disaster/v2/views/object_class/spending.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_psc.py
usaspending_api/search/tests/integration/test_spending_over_time.py

Minor tweaks to new COVID-19 page endpoints that use the ES accounts index. Fixes minor bug that prevent the child arrays from being sorted. Also removes the top level filtering on `outlay_sum` and `obligated_sum`, which was causing errors in the sums.  …

[DEV-6457] Fix ES covid endpoint discrepancies

---

usaspending_api/common/helpers/s3_helpers.py

To support new structure for NonProd vs Prod in DTI the ACL is set to `bucket-owner-full-control` meaning that the bucket owner has full control of the new objects.
This should not cause any negative effects since it is an AWS defined ACL.
6. [x] Data validation completed 
8. [x] Jira Ticket [DEV-6471](https://federal-spending-transparency.atlassian.net/browse/DEV-6471):
```
```

[DEV-6471] Add ACL to boto3 upload args

---

usaspending_api/common/sqs/sqs_handler.py
usaspending_api/common/tests/unit/test_sqs_work_dispatcher.py

Need to update endpoint URL to support migration to DTI.
In order to support Python2 boto3 will use a legacy format for the URL when the endpoint_url is not specified or certain regions are detected. DTI requires that that a different endpoint format is used for SQS. 
Old format: `https://<REGION>.queue.amazonaws.com/`
New format: `https://sqs.<REGION>.amazonaws.com/`
This was tested by pushing updates to both DTI and DAOI Sandbox and testing that downloads were still functional since that is the primary use of SQS for USAspending.
5. [x] Frontend impact …

[DEV-6468] Update boto3 endpoint format for SQS

---

usaspending_api/api_contracts/contracts/v2/reporting/agencies/agency_code/overview.md
usaspending_api/api_contracts/contracts/v2/reporting/agencies/overview.md
usaspending_api/reporting/tests/integration/test_agencies_overview.py
usaspending_api/reporting/tests/integration/test_agency_code_overview.py
usaspending_api/reporting/v2/views/agencies/agency_code/overview.py
usaspending_api/reporting/v2/views/agencies/overview.py

Updating the contract and putting placeholder values for unlinked awards in the two overview endpoints so frontend can begin coding to them.
`/api/v2/reporting/agencies/overview` and `/api/v2/reporting/agencies/<agency_code>/overview` have two new keys to account for unlinked awards. Currently hardcoded to 0
4. Matview impact assessment completed (N/A)
6. Data validation completed (N/A)
7. Appropriate Operations ticket(s) created (N/A)
8. [x] Jira Ticket [DEV-6305](https://federal-spending-transparency.atlassian.net/browse/DEV-6305):
- Performance evaluation of affected …

DEV-6305: unlinked award counts endpoint placeholder

---

usaspending_api/reporting/tests/integration/test_agency_code_overview.py
usaspending_api/reporting/v2/views/agencies/agency_code/overview.py

Adding a secondary sort to the single agency overview by fiscal period when sorting by fiscal year
N/A
2. API documentation updated (N/A)
4. Matview impact assessment completed (N/A)
7. Appropriate Operations ticket(s) created (N/A)
8. [x] Jira Ticket [DEV-6480](https://federal-spending-transparency.atlassian.net/browse/DEV-6480):
- Link to this Pull-Request (N/A)
- Performance evaluation of affected (API | Script | Download) (N/A)
- Before / After data comparison (N/A)
```
```

DEV-6480: Secondary sort fy

---

usaspending_api/agency/v2/views/agency_overview.py

Changed the ORM code to avoid an `EXISTS () = True` in the WHERE clause. 
A similar issue has come up before where the use of `EXISTS` in this current version of Django (2.2.9) create SQL such that `EXISTS () = True`. For some reason that `= True` slows the performance greatly even though the same result is achieved without it. In Django 3.0 and later it is possible to simply have an EXISTS in the .filter() (https://docs.djangoproject.com/en/3.0/ref/models/expressions/#exists-subqueries). However, in versions before 3.0 it is required that the EXISTS is first annotated and then the annotated name can be used.
Should add that this is NOT a perfect solution since the use of `.extra()` is discouraged, however, as mentioned above it is a required …

[DEV-6563] Change ORM implementation to avoid '= True' in SQL exists

---

usaspending_api/agency/tests/integration/test_agency_budget_function.py
usaspending_api/agency/tests/integration/test_agency_federal_account_list.py
usaspending_api/agency/tests/integration/test_agency_object_class_list.py
usaspending_api/agency/tests/integration/test_agency_program_activity_list.py
usaspending_api/reporting/tests/integration/test_agencies_overview.py

Should fix the tests that are failing due to hardcoded values in the tests. Replaces most instances of `2020` with `current_fiscal_year` for tests using `agency_account_data`. 
8. [N/A] Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123):
- [N/A] Link to this Pull-Request
- [N/A] Performance evaluation of affected (API | Script | Download)
- [N/A] Before / After data comparison
``` …
```

Fix tests using hardcoded values instead of current_fiscal_year

---

usaspending_api/references/v2/views/filter_tree/naics.py
usaspending_api/references/v2/views/filter_tree/psc_filter_tree.py
usaspending_api/references/v2/views/filter_tree/tas_filter_tree.py

Most of the filter trees were not explicitly ordered and instead were implicitly using the order of records obtained from database tables
1. One misuse of `sorted()` (should have been `<list>.sort()`)
2. OrderedDict is unnecessary in Python 3.7 and was often used for dictionaries with single keys, so the library was remoed and replaced by dictionaries
3. Simplified / reduced a little code
4. Added `sorted()` to many places in the filter tree logic
1. [x] Unit & integration tests updated (No changes were desired from refactor)
6. [x] Data validation …

[DEV-6198] Fixing Advanced Search filter tree ordering

---

usaspending_api/agency/v2/views/agency_base.py
usaspending_api/api_contracts/contracts/v2/reporting/agencies/agency_code/overview.md
usaspending_api/api_contracts/contracts/v2/reporting/agencies/overview.md
usaspending_api/reporting/tests/integration/test_agencies_overview.py
usaspending_api/reporting/tests/integration/test_agency_code_overview.py
usaspending_api/reporting/v2/views/agencies/agency_code/overview.py
usaspending_api/reporting/v2/views/agencies/overview.py

This PR adds an `assurance_statement_url` reporting agency overview endpoints.
Example url: https://files.usaspending.gov/agency_submissions/Raw%20DATA%20Act%20Files/2020/P10/073%20-%20Small%20Business%20Administration%20(SBA)/2020-P10-073_Small%20Business%20Administration%20(SBA)-Assurance_Statement.txt
URL is built using the following fields:  
- agency_name
- abbreviation
- toptier_code
- fiscal_year
- fiscal_period
- submission_is_quarter
8. [x] …

[DEV-6490] Assurance Statement url

---

usaspending_api/agency/tests/integration/test_agency_budget_function.py
usaspending_api/agency/tests/integration/test_agency_federal_account_list.py
usaspending_api/agency/tests/integration/test_agency_object_class_list.py
usaspending_api/agency/tests/integration/test_agency_program_activity_list.py
usaspending_api/common/helpers/fiscal_year_helpers.py
usaspending_api/reporting/tests/integration/test_agencies_overview.py
usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
usaspending_api/settings.py

Travis is currently running into issues with tests that were fixed in DEV branch and additional tests as a result of recent migration efforts. While looking at broken tests it was also noticed that the `current_fiscal_year()` (and other similar methods) were not returning the fiscal date / year.
Updates to `settings.py` to set the default file server to DTI until lower environment DNS are switched over. Additionally, made changes to how we determine fiscal date and fiscal year.
7. …

Fix Broken Tests in Travis

---

usaspending_api/reporting/tests/integration/test_agencies_overview.py
usaspending_api/reporting/tests/integration/test_agency_code_overview.py

A temporary fix was put in to QAT for the Prod deploy (and merged down to Dev) to set the default for `FILES_SERVER_BASE_URL` to include the DTI URL until the DNS changeover for lower environments. That fix allowed for endpoints that need to access S3 to pass, but caused some of the new tests in Dev to fail. 
Use the `settings.py` value for `FILES_SERVER_BASE_URL` in test cases to insure that the correct value is being used and to prevent them breaking when we eventually change this value again after lower environment DNS cutover.
5. [x] Frontend impact …

fix for some failing tests

---

usaspending_api/disaster/tests/fixtures/disaster_account_data.py
usaspending_api/disaster/tests/fixtures/federal_account_data.py
usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
usaspending_api/disaster/tests/integration/test_federal_account_total.py
usaspending_api/disaster/v2/views/agency/spending.py
usaspending_api/disaster/v2/views/federal_account/spending.py

Currently the total budgetary resources on the COVID Page for Federal Account and Agency tables are not accounting for all COVID FY. This change takes into account all current and future FY that include COVID data.
After searching around it appears that at least other places using Postgres are currently taking into account multiple FY.
Make use of the pre-existing `latest_gtas_of_each_year_queryset()` method to capture all necessary GTAS and use the same calculation logic as currently used by the `/api/v2/disaster/overview` endpoint. 
Additionally, adjusted test cases to have examples of GTAS spread across multiple different FY.
Few screenshots to showcase the change with data from QAT. The `Total Budgetary Resources` is greater than the `Total …

[Hotfix][DEV-6413] Account for COVID FY with total budgetary resources

---

usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
usaspending_api/etl/elasticsearch_loader_helpers/index_config.py
usaspending_api/etl/management/commands/elasticsearch_indexer.py
usaspending_api/etl/tests/test_es_rapidloader.py

Fixes problem described in bug [DEV-6724](https://federal-spending-transparency.atlassian.net/browse/DEV-6724). 
Does so by fetching correcting the lookup of award keys from the transaction index to match related transactions by the **transaction key** (`generated_unique_transaction_id`).
- More details in the linked bug
- Also making it more clear which module functions are shared/used outside the module with underscore naming convention (weak protected)
- [NA] Operations <OPTIONAL>
- [NA] Domain Expert <OPTIONAL>
5. [NA] Frontend impact …

HOTFIX: [DEV-6724] Fixing ES awards delete to lookup delete keys in ES by transaction key

---

usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py

Fixing bug that would limit award deletes to only ever process the last 1000 seen, if there are more than 1000 to delete.
- Discovered as part of working on [DEV-6756](https://federal-spending-transparency.atlassian.net/browse/DEV-6756)
- Solution: Extend the list by continuously concatenating the next chunk of results
- Analyzed recent data since last awards reindex, and did not find any syncs that had award deletes at that large of a number, so current data is not affected. 
- However, this is a fault in the code that could lead to bad data if not fixed asap
- See [DEV-6756](https://federal-spending-transparency.atlassian.net/browse/DEV-6756) and its PR's unit tests
2. [NA] API …

HOTFIX: [DEV-6763] Extend list of award keys needing to be deleted

---

usaspending_api/reporting/v2/views/agencies/overview.py
usaspending_api/settings.py

- Annoyance 1) Django's SQL output in debug mode was duplicated
- Annoyance 2) The SQL to obtain the Agency.id value was run 100+ times to fetch the id for each result which added 40+ seconds for local runs connected to a deployed RDS. Changing to a single query shaved 40s.
N/A
```
Minor edits to debug mode and de-duplicated a SQL query
```

Fixed two annoying duplications

---

usaspending_api/broker/helpers/delete_stale_fabs.py
usaspending_api/conftest.py
usaspending_api/etl/transaction_loaders/fpds_loader.py

The test pipeline recently failed during the `Broker -> USAspending (FABS/FPDS) ETL` phase. The pipeline is attempting to delete stale FPDS/FABS records along with records from related tables. One of those tables, `transaction_normalized` has a foreign key constraint from the `transaction_search` table, so the deletion of `transaction_normalized` is failing. 
This PR adds an extra step to delete `transaction_search` records in the delete stale fabs/fpds methods before `transaction_normalized` is deleted
**Technical Notes**
Extra logic is added to `conftest.py`. When unit testing, transaction_search is created as a single view. Views can't be deleted from, so a custom rule is added to transaction_search to prevent sql errors when deletes are attempted. This is done in the …

[Warmfix] Follows pattern for deleting stale fabs/fpds to also delete transaction_search

---

requirements/requirements-app.txt

Apparently ddtrace is incredibly fragile and needs extensive testing before even very minor version updates
- Rollback version introduced in #2885
- Sorry Windows devs
```
Reverting version after 
```

DDtrace Agent back to 0.37.1

---

usaspending_api/common/retrieve_file_from_uri.py
usaspending_api/common/tests/integration/test_retrieve_from_file_uri.py

This PR creates a new class to give tempfile.SpooledTemporaryFile an uplift. The current implementation in the standard library isn't satisfying the expected API. Augmenting the class methods and importing io.IOBase should get the class close to where it needs to be. Until https://github.com/python/cpython/pull/3249 is merge, released, and used by this project we will need to keep this augmented class around.
While this issue has existed since Python 3.0, it was only recently felt in this project with the upgrade from pandas v0.45.x to pandas v1.0.2+ (pandas v1.0.0 and v1.0.1 introduced another bug which they fixed in v1.0.2, relying on API missing in the SpooledTemporaryFile implementation). See https://bugs.python.org/issue26175 and …

[FIX] Augment tempfile.SpooledTemporaryFile() for expected behavior

---

usaspending_api/reporting/tests/integration/test_agencies_overview.py
usaspending_api/settings.py

Few tests are broken for different reasons not related to code changes. To avoid conflicts with Hotfixes, Warmfixes, and deploys this PR is going in as a hotfix to correct test cases.
Agency overview tests are broken due to a component that relies on current fiscal year and period.
There are additional download tests that are failing due to a dependency on the S3 Files Server. These tests will continue to fail until the issue with the files server is corrected, but once that is complete the default URL needs to have `dti` removed to make sure it works.
5. [x] Frontend impact …

Fix broken test cases

---

usaspending_api/etl/management/commands/load_submission.py
usaspending_api/reporting/tests/integration/test_agencies_submission_history.py
usaspending_api/reporting/v2/views/submission_history.py

Original implementation was only providing the most recent submission publication and certification instead of the full history of a submission
Implemented a HTTP 204 if there is no submission history  for the provided request
8. [x] Jira Ticket [DEV-6534](https://federal-spending-transparency.atlassian.net/browse/DEV-6534):
```
No changes to Materialized Views or API Contracts
``` …

[DEV-6534] Add Missing Submission history to endpoint

---

usaspending_api/etl/elasticsearch_loader_helpers/index_config.py
usaspending_api/etl/management/commands/elasticsearch_indexer.py

Minor adjustment to how Exit Code is handled for when a snapshot is ongoing for too long.
Change handling of Exit Code to match that of loadcfda.py such that the actual exit code is used in the Jenkins scripts.
8. [x] Jira Ticket [DEV-6657](https://federal-spending-transparency.atlassian.net/browse/DEV-6657):
```
```

[DEV-6657] Change how exit code 3 is handled

---

usaspending_api/download/tests/integration/test_populate_monthly_files.py

The `test_fiscal_years` test in `test_populate_monthly_files` was taking an overly long time,  ~five minutes. This should reduce the time this test takes to run by restricting the number of fiscal years in the test.
8. [X] Jira Ticket [DEV-5209](https://federal-spending-transparency.atlassian.net/browse/DEV-5209):
```
```

[DEV-5209 ]Fix long fiscal_year test

---

usaspending_api/disaster/tests/conftest.py
usaspending_api/disaster/tests/fixtures/overview_data.py
usaspending_api/disaster/tests/integration/test_overview.py
usaspending_api/disaster/v2/views/overview.py

This PR addresses the changes to the `total_budgetary_resources`, `total_obligations`, and `total_outlays` fields in the **Disaster Overview Endpoint**. 
Updated formulas for these fields can be found in the ticket. 
Unit tests were corrected to reflect the changes to the formulas, but new test cases were not optimized for new logic. 
8. [x] Jira Ticket [DEV-6910](https://federal-spending-transparency.atlassian.net/browse/DEV-6910):
**Area for …

[DEV-6910] Updates to Disaster Overview Calculations

---

usaspending_api/disaster/tests/fixtures/overview_data.py
usaspending_api/disaster/tests/integration/test_overview.py
usaspending_api/disaster/v2/views/overview.py

This PR updates the formula for award outlays on the `disaster/overview` based on the requirements in the ticket. Tests have also been updated
8. [x] Jira Ticket [DEV-6920](https://federal-spending-transparency.atlassian.net/browse/DEV-6920):
```
```

[DEV-6920] Updates award outlay calculation on disaster overview endpoint

---

usaspending_api/reporting/tests/integration/test_agencies_overview.py
usaspending_api/reporting/tests/integration/test_agency_code_overview.py
usaspending_api/reporting/v2/views/agencies/overview.py
usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py

The logic to generate Assurance Statement (aka Agency Comment File) URLs was running regardless if the submission existed
N/A
2. [x] API documentation updated (N/A, code matches contracts better now)
8. [x] Jira Ticket [DEV-6948](https://federal-spending-transparency.atlassian.net/browse/DEV-6948):
```
No changes to materialized views, operations, or API schema
```

[DEV-6948] Stop generating assurance urls for non-existent submissions

---

usaspending_api/conftest_helpers.py
usaspending_api/etl/es_config_objects.json
usaspending_api/etl/management/commands/es_configure.py

Elaticsearch template changes were not appearing in the correlating indexes due conflicting template names.
Additionally, some removed settings are not available for AWS managed Elasticsearch: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html#es_version_7_1
Taken from Staging --->
`_cat/templates`
> awar_template        [*awards]       0 
> transaction_template [*transactions] 0 
> covid19-fab_template [*covid19-faba] 0 
> transactio_template  [*transactions] 0 
> award_template       [*awards]       0 
`_template/transaction_template`
> ...
> "generated_unique_transaction_id" : {
>    "type" : "text"
> },
> ...
`_template/transactio_template`
> ...
> "generated_unique_transaction_id" : {
> …

Small cleanup around ES ETL config

---

usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/data_layer/sql.py

Corrects the calculation of the COVID-19 outlayed amount on the award summary page.
Adds the `ussgl487200_down_adj_pri_ppaid_undel_orders_oblig_refund_cpe` and `ussgl497200_down_adj_pri_paid_deliv_orders_oblig_refund_cpe` to the `gross_outlay_amount_by_award_cpe` value.
3.  [ ] Necessary PR reviewers:
8. [X] Jira Ticket [DEV-6942](https://federal-spending-transparency.atlassian.net/browse/DEV-6942):
```
```

[DEV-6942] Award summary page covid outlay correction

---

usaspending_api/download/helpers/disaster_filter_functions.py
usaspending_api/download/helpers/download_annotation_functions.py

Many different downloads (excluding COVID Page Download and Custom Account Download) need to use the new COVID Outlay calculation.
Update the annotations to use the new calculation for COVID outlay. Also moved around the COVID Obligation and Outlay subqueries for Download Annotations for more re-use.
8. [x] Jira Ticket [DEV-6932](https://federal-spending-transparency.atlassian.net/browse/DEV-6932):
```
```

[DEV-6932] Update downloads to use new COVID outlay calculation

---

usaspending_api/etl/management/sql/dev3627_compare_dabs_row_counts.sql
usaspending_api/etl/submission_loader_helpers/file_c.py
usaspending_api/etl/tests/integration/test_load_multiple_submissions.py

Added  non-null/non-zero checks to the values of two additional columns in File C checks which excluded rows in the DABS ETL. 
- `ussgl487200_downward_adjus_cpe` (`ussgl487200_down_adj_pri_ppaid_undel_orders_oblig_refund_cpe` in USAspending)
- `ussgl497200_downward_adjus_cpe ` (`ussgl497200_down_adj_pri_paid_deliv_orders_oblig_refund_cpe` in USAspending)  
Originally only `transaction_obligated_amou ` and `gross_outlay_amount_by_awa_cpe ` were examined 
4. [x] Matview impact …

[DEV-6936] Updates to DABS ETL for loading additional File C records

---

usaspending_api/disaster/tests/fixtures/disaster_account_data.py
usaspending_api/disaster/tests/fixtures/federal_account_data.py
usaspending_api/disaster/tests/fixtures/object_class_data.py
usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
usaspending_api/disaster/tests/integration/test_federal_account_award.py
usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
usaspending_api/disaster/v2/views/elasticsearch_account_base.py
usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py

Changes the method used to calculate how the outlay amounts are calculated on the COVID-19 profile page for endpoints using the Accounts ES index
Instead of just summing the `gross_outlay_amount_by_award_cpe` field, we also add the `ussgl487200_down_adj_pri_ppaid_undel_orders_oblig_refund_cpe` and `ussgl497200_down_adj_pri_paid_deliv_orders_oblig_refund_cpe` fields
8. [X] Jira Ticket [DEV-6922](https://federal-spending-transparency.atlassian.net/browse/ …

[DEV-6922] Fix outlay calculations

---

usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/download/v2/download_column_historical_lookups.py

Add new columns to File B and File C downloads for Custom Account Download.
Broke out some common logic used for the gross outlay columns to allow similar handling of closed periods for the new columns added in this PR. The new columns are only added to File B and File C downloads.
8. [x] Jira Ticket [DEV-6923](https://federal-spending-transparency.atlassian.net/browse/DEV-6923):
```
```

[DEV-6923] Add new fields to Custom Account Download

---

usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/disaster/v2/views/disaster_base.py

Need to take into account the new columns that are used alongside gross outlay when filtering out nonzero rows. Additionally, cleaned up some methods when seeing where else we might need to make this change.
Adjust the filter used by custom account download to filter out nonzero outlay.
8. [x] Jira Ticket [DEV-6923](https://federal-spending-transparency.atlassian.net/browse/DEV-6923):
``` …
```

[DEV-6923] Adjust filtering to take into account new columns that affect outlay calculations

---

usaspending_api/download/management/commands/populate_monthly_delta_files.py

Something must have changed with the pandas API which causes a `Series` to be returned instead of a `DataFrame`
`.rename()` called on a Series object does not use the `columns` keyword argument unlike `.rename()` called on a DataFrame. Adding a `.reset_index()` here for testing which does return a DataFrame object and does not appear to create unintended consequences
**Area for explaining above N/A …

[FIX] issue with pandas API

---

usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
usaspending_api/disaster/v2/views/award/amount.py
usaspending_api/disaster/v2/views/disaster_base.py

Fixes the calculation of outlays for the `/api/v2/disaster/award/amount` endpoint, updating it to match the other work done elsewhere on the site.
`/api/v2/disaster/award/amount` has two logic paths - one for File C and one for File D. The file C change can be done by just changing the query, but the File D change required an update to the  `CovidFinancialAccountMatview` where the outlay was being calculated …

[DEV-7004] Outlay calculation fix

---

usaspending_api/references/management/commands/load_gtas.py
usaspending_api/references/tests/data/broker_gtas.json
usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py

See ticket for some background and link to Slack conversation
`treasury_appropriation_account` stores all valid TAS in USAspending and does not include Financing Accounts. The GTAS ETL already created a FK from the GTAS data in `gtas_sf133_balances` to `treasury_appropriation_account`. While the business logic and SQL could have been altered to ignore all GTAS records without a FK, it was easier and more complete to simply drop all GTAS records without a FK to `treasury_appropriation_account`.
The question of "Is there ever a valid reason of a TAS in GTAS to not be located in TAS reference data" was answered with "No."
3. [x] Necessary PR …

[DEV-7025] Remove Financing Accounts from GTAS data

---

usaspending_api/common/query_with_filters.py
usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
usaspending_api/disaster/v2/views/elasticsearch_account_base.py

Make sure that Awards with negated outlay (e.g. `100` and `-100`) are filtered out taking into account the addition of the new downward adjustment columns that are part of the calculation.
After going back and forth multiple times on how to implement I settled on this implementation for performance reasons. A search of Staging showed that the cases where the outlay is zero the negated File C records share the same DEFC (which make sense). I wanted to keep the functionality where a user is able to filter by a single DEFC on the endpoint. The shared DEFC between negated File C means that a user should not be able to filter by a single DEFC and be robbed of data they would otherwise be able to see if the implementation was granular to DEFC instead of …

[DEV-7012] Change how Awards with negated outlay are filtered out

---

usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql

Missed the exclusion of $0 outlays with the adjustments included
Everyone overlooked the COVID-19 Outlay values in the sub-award files
N/A
8. [x] Jira Ticket [DEV-6921](https://federal-spending-transparency.atlassian.net/browse/DEV-6921):
```
No impact to materialized views or API
```

[DEV-6921] Fixed oversights from including outlay adjustment fields

---

usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
usaspending_api/reporting/tests/integration/test_agency_code_overview.py
usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py

Three issues in this PR for expediency
- Sorting was broken for `v2/reporting/agencies/<toptier_code>/overview` when `null` was the value (since this endpoint sorts the results in Python instead of Postgres)
- Fragile test would fail due to result order from ORM queryset results
- Fragile test would fail due to PKs being hardcoded in model mommy
N/A
``` …
```

[FIX] corrected two issues in QAT

---

usaspending_api/etl/elasticsearch_loader_helpers/aggregate_key_functions.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py

Fixes bug described where the county name was set to `NULL` in the agg key used by the spending_by_category endpoint
8. [X] Jira Ticket [DEV-6872](https://federal-spending-transparency.atlassian.net/browse/DEV-6872):
```
```

[DEV-6872] Spending by geo nulls

---

usaspending_api/etl/operations/treasury_appropriation_account/update_agencies.py
usaspending_api/etl/tests/integration/test_account_update_agencies.py
usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
usaspending_api/reporting/v2/views/agencies/overview.py

Many many issues appeared from #3014 after switching from "Funding Agency" to "Awarding Agency" for About the Data [DEV-6958](https://federal-spending-transparency.atlassian.net/browse/DEV-6958).
Updated the TAS ETL so `awarding_toptier_agency_id` wasn't null (went from over 90% null to 0% null). Fix was for `update_agencies.py`
8. [x] Jira Ticket [DEV-7071](https://federal-spending-transparency.atlassian.net/browse/DEV-7071):
**Area …

[DEV-7071] Fixed dearth of FKs in treasury_appropriation_account

---

usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
usaspending_api/etl/elasticsearch_loader_helpers/load_data.py

Smaller batch deletes to reduce incidence of the ES operation timing out. 
We've seen a few Elasticsearch incremental indexes that ran into a handful of server-side ES operation timeouts. Typically when running very deep (5M+) incremental loads. They seem to pile up and may even cause the whole ETL job to fail.
Originally, before using `_delete_by_query`, the batch size used was 1000 records. They were queried for, then deleted in two steps. This problem wasn't seen at that batch size so reducing from the current value of 10000 back down to 1000.
1. [NA] Unit & integration tests updated
5. [NA] Frontend impact …

WARMFIX: [DEV-6756] Reducing batch size of the _delete_by_query on incremental index

---

usaspending_api/download/v2/request_validations.py

Keyword search currently fails due to an oversight in the validation.
The BaseDownloadViewset performs a data transformation on the request that was not previously effecting the `elasticsearch_keyword` filter. As a result a change needed to occur that takes that into account. In addition to this, the attempt to retrieve the filter should have been a `.get()` to avoid running issues of the "filter" not being present in the dictionary since the value is retrieved prior to validation.
7. [x] …

[DEV-6567] Fix an oversight with Keyword Search validation changes

---

usaspending_api/etl/operations/treasury_appropriation_account/update_agencies.py
usaspending_api/etl/tests/integration/test_account_update_agencies.py
usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
usaspending_api/reporting/management/sql/populate_reporting_agency_missing_tas.sql
usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
usaspending_api/reporting/tests/integration/test_populate_reporting_agency_missing_tas.py
usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py

This PR rolls back some changes from #3014 and #3057 and improving tests. Also fixing a minor issue of extra future submission periods being created in `reporting_agency_overview` which wasn't optimal.
While it may seem to make sense to use `treasury_appropriation_account.awarding_toptier_agency_id` when there is a desire to use "awarding agency" for grouping. However, `awarding_toptier_agency_id` isn't the same as "awarding" in File D data. Also `funding_toptier_agency_id` isn't "funding" like File D but closer to "owning." This has caused plenty of recent confusion. …

[Fix] Fixed agency grouping of TAS data for About the Data

---

usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
usaspending_api/agency/v2/views/budgetary_resources.py

Fixes bug with the `bugdetary_resources` endpoint - should have been filtering with `is_final_balances_for_fy` per fiscal year, but was not
8. [X] Jira Ticket [DEV-6612](https://federal-spending-transparency.atlassian.net/browse/DEV-6612):
```
```

[DEV-6612] fix budgetary resources fy

---

usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
usaspending_api/reporting/v2/views/agencies/publish_dates.py

Fixes an issue with the publish_dates endpoint on the about the data page where the total_budgetary_resources amount was being summed per fiscal year when it should have been taking the latest entry for that fiscal year
The actual percentages on the website page will also require a frontend fix, since the total federal amount is also being summed per fiscal year, which is incorrect
8. [ ] Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-1 …

[WARMFIX] Fix calculation of total_budgetary_resources for publish_dates

---

usaspending_api/submissions/management/commands/load_dabs_submission_window_schedule.py
usaspending_api/submissions/models/dabs_submission_window_schedule.py

This PR addresses an issue created by https://github.com/fedspendingtransparency/usaspending-api/pull/3089
That PR added a statement that parses dates read in from a CSV. This code should not be executed when schedules are read from the broker db instead of the CSV, so this PR moves that logic into the `dabs_submission_window_schedule` with a check to make sure a string is being parsed. 
It also fixes a warning about naive datetimes when writing to the database. 
8. [x] Jira …

[DEV-7116] Adds Date Parsing to dabs_submission_window_schedule Class

---

usaspending_api/reporting/v2/views/agencies/overview.py
usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py

The last PR for this ticket updated the `reporting_agency_overview` table to default values to NULL instead of zero. The API endpoints were also updated to set fields not coming from that table to NULL if no submission is present. Under these conditions it was still possible for values to come through on period without submissions because rows in the `reporting_agency_overview` table are sometimes still populated without a submission.
This PR updates the endpoints to set Null values to zero even if those fields are coming from the `reporting_agency_overview` table. 
5. [x] Frontend impact …

[DEV-7191] Nulls more fields in the response if no submission is found

---

usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
usaspending_api/reporting/v2/views/agencies/publish_dates.py

Have `current_total_budget_authority_amount` return `None` instead of `0.0` when the value is NULL.
None cannot be compared to None so an issue was run into when sorting. To work around it a tuple is used for the sort functionality such that whenever the value of a field is `None` it will always be sorted at the bottom.
8. [x] Jira Ticket [DEV-7191](https://federal-spending-transparency.atlassian.net/browse/DEV-7191):
**Area for explaining above N/A …

[DEV-7191] Return None instead of 0.0 when null

---

usaspending_api/reporting/tests/integration/test_agency_code_overview.py
usaspending_api/reporting/v2/views/agencies/overview.py
usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py

Better handling of NULLs in DEV-7191 caused a slight issue with how we were trying to sort results with the Django ORM but then manipulated some of the values to be NULL depending on the value of the publication date.
Removed the Django ORM Order By since it is no longer effective at sorting NULL values for our use case in the endpoint. Also adjust the sorting for both Overview endpoints to be consistent with NULLs sorted last. 
The approach to handle the NULLs sorted last is to create a tuple where the first value is True or False depending on the combination of selected sort order and if a field is NULL. The remaining fields of the tuple will sort the non-NULL results correctly.
1. [x] Unit & integration tests …

[DEV-7191] Sort with nulls at the bottom of results

---

usaspending_api/reporting/v2/views/agencies/publish_dates.py

Handling of the publication_date sort was assuming that we always showed all fiscal periods in results. Changes that limited this to only valid fiscal periods for the Fiscal Year caused this sorting to break.
Determine the valid fiscal periods so that we can correlate it to a dictionary in the array of periods for each agency.
8. [x] Jira Ticket [DEV-7191](https://federal-spending-transparency.atlassian.net/browse/DEV-7191):
**Area for explaining above …

[DEV-7191] Fix sorting for non FY 2021 table views when sorting Fiscal Period

---

usaspending_api/etl/transaction_loaders/fpds_loader.py

[DEV-6425: Replace `universal_transaction_matview` with a Django managed table](https://federal-spending-transparency.atlassian.net/browse/DEV-6425) introduced a change to the `fpds_loader.py` that deletes stale transactions from the `transaction_search` table to prevent Foreign Key constraint violations when deleting stale transactions from `transaction_normalized`. 
When this extra step to delete `transaction_search` records was added, a check was added to make sure the same number of records were deleted as were deleted from transaction_normalized to follow the same pattern used with deleting from `transaction_fpds`. 
This check, however, does not make sense because transaction_normalized contains more transactions than `transaction_search`, the ladder being restricted …

[DEV-7277] Removes check comparing deleted transaction_search and transaction_normalized counts

---

usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
usaspending_api/search/v2/views/spending_by_award.py

Adjusts the values returned by the `spending_by_award` endpoint to filter the Covid-19 related outlays and obligations by the provided DEFC filter.
If the COVID-19 Obligations or COVID-19 Outlays values are requested in a call to `spending_by_award`, the values returned will be filtered by the `def_codes` filter (if present). So if Award 1 has $100 in obligations under DEFC "L" and 
$20 in obligations under DEFC "P", if the def_codes filter contains only "L", the value returned for Award 1's obligations will be $100, not $20.
6. …

[DEV-7197] Spending by Award DEFC filter updates

---

usaspending_api/common/helpers/unit_test_helper.py
usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/filestreaming/download_source.py
usaspending_api/download/helpers/download_annotation_functions.py

Take the DEFC filter into consideration for the COVID Outlay and Obligation columns. 
Ended up being much more straight forward than had feared. Passed the filters down into the download annotations functions where it limits on the DEFC filter if it exists. Since the column is specifically COVID Outlay and Obligation the check for `covid_19` group name was left in place to ensure no mater what only COVID spending is represented.
8. [x] Jira …

[DEV-7239] Add DEFC filter to COVID Outlay and Obligation in downloads

---

usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py

A bug currently exists on the `/v2/reporting/agencies/toptier_code/overview` page. It is currently possible for the calculation of `percent_of_total_budgetary_resources` in the case that `total_budgetary_resources` is None. This PR corrects the calculation by setting the result to zero when `total_budgetary_resources` is None
8. [x] Jira Ticket [DEV-7281](https://federal-spending-transparency.atlassian.net/browse/DEV-7281):
``` …
```

[DEV-7281] Correct calculation of percent TBR on reporting/toptier/overview endpoint

---

usaspending_api/references/management/commands/load_agencies_sql/agency_query.sql

Agency Loader is not pulling over the exact values for `toptier_flag` and `user_selectable` for agencies without a subtier_agency listed. This fix makes sure that we pull over those values exactly as they appear in the CSV.
Update to the Agency Loader SQL to make sure that we grab the correct values and don't overwrite any.
8. [x] Jira Ticket [DEV-7362](https://federal-spending-transparency.atlassian.net/browse/DEV-7362):
**Area for explaining …

[DEV-7362] Pull over correct toptier_flag and user_selectable for all agencies

---

usaspending_api/api_contracts/contracts/v2/references/submission_periods.md
usaspending_api/references/v2/views/submission_periods.py

This PR is adding a `use_cache` parameter to the `api/v2/references/submission_periods` endpoint. This specifies whether the django cache should be use to return the response. 
This is accomplished using an extra APIView. This APIView, `CachedSubmissionPeriodsViewSet` is not directly accessible via an endpoint and is called in code by `SubmissionPeriodsViewSet`. These two APIViews both use `get_closed_submission_windows` to create a list of closed submission window schedules. 
7. [x] Appropriate …

[DEV-7156] Adds use-cache query param to submission_periods endpoint

---

usaspending_api/download/tests/unit/test_base_download_helpers.py
usaspending_api/download/v2/base_download_viewset.py

Download "cache" is actually a reference to the DownloadJob table and the download .zip folder in S3. Previously the download was using a cutoff date of midnight every night, meaning any download after midnight would be a new download. Anything prior to midnight would first look to see if it had been previously run.
Use a combination of FPDS, FABS, ES Transactions, and ES Awards external load dates paired with the latest submission's reveal date. The goal is to have data as fresh as possible while still keeping the cache functionality. The download cache could be more granular but that would require adding a lot more external load dates to map each stage of the pipeline with a download.
The approach taken will compare the `update_date` of a …

[DEV-7118] Use external load dates to determine cutoff for download cache

---

usaspending_api/common/helpers/generic_helper.py
usaspending_api/common/helpers/orm_helpers.py
usaspending_api/references/tests/test_agency_v2.py
usaspending_api/references/tests/test_toptier_agency_v2.py
usaspending_api/references/v2/views/agency.py
usaspending_api/references/v2/views/toptier_agencies.py

Currently the `% of the total U.S. federal budgetary resources ` on Agency Profile is incorrect. This is because the denominator (`current_total_budget_authority_amount`) is not the correct value; it is using an older value. Make sure to populate this with the right value so that the correct percent can be derived on the frontend. 
Additional sort by `reporting_fiscal_period` since a fiscal quarter can have multiple fiscal periods. Without this sort the wrong period is returned, which results in the wrong denominator.
Along with data corrections some changes were made to boost performance. Previously the toptier_agencies endpoint would take about 2 minutes 38 seconds and fire off about 700+ queries. The new changes reduce it to 3 seconds and 4 …

[DEV-7404] Use correct fiscal period for total budget

---

usaspending_api/etl/tests/integration/test_load_multiple_submissions.py
usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py

This should resolve the tests breaking due to the addition of two cols in Broker's `tas_lookup` table and one of them being not null.
N/A
2.  API documentation updated
4.  Matview impact assessment completed
5.  Frontend impact assessment completed
6.  Data validation completed
7.  Appropriate Operations ticket(s) created
8.  Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123):
-  Link to this Pull-Request
-  Performance evaluation of affected (API | Script | Download)
-  Before / After data comparison
```
This is just a PR to fix some tests breaking due to the …
```

Test Fix: Adding TAS/Display TAS cols to Test Broker DB generation 

---

usaspending_api/download/v2/base_download_viewset.py

Custom Account Downloads are not being cached due to an oversight in the conditional that checks download_types.
Logic around the `download_types` check was adjusted for other downloads that provide a value that are not Elasticsearch downloads. 
8. [x] Jira Ticket [DEV-7118](https://federal-spending-transparency.atlassian.net/browse/DEV-7118):
```
```

[DEV-7118] Correcting conditional that omitted custom account downloads

---

usaspending_api/etl/management/commands/combine_transaction_search_chunks.py

Need to ensure that the new download view for Transaction based downloads is up-to-date after matview recreate.
An oversight on my part resulted in the download view for transactions being dropped during a matview recreate since we swap in a new `transaction_search` table. This change will recreate the `vw_transaction_seach_download` View whenever the `transaction_search` table is swapped out to make sure it is up to date. …

[DEV-7480] Ensure transaction download view is updated with table

---

usaspending_api/data/daims_maps.py
usaspending_api/database_scripts/matview_generator/chunked_matview_sql_generator.py
usaspending_api/database_scripts/matview_generator/shared_sql_generator.py
usaspending_api/etl/management/commands/combine_transaction_search_chunks.py

This PR updates the SQL statements used to insert records from `transaction_search_*` matviews into the `transaction_search` table. It uses the column definition from the `TransactionSearch` model to specify a list of columns to insert.
This PR breaks the pattern of generating all SQL for chunked matviews in the `chunked_matview_sql_generator.py` script. This is because there isn't a great way to get a list of columns from that script. Here are the ideas that I had to do so along with why they won't work. 
- **Get the list of columns from `transaction_search.json`** - Contrary to what I originally remembered, the JSON doesn't have a good list of columns. The file contains a list of lines of the table DDL, but this would need complicated parsing …

[DEV-7579] Adds column definition to TS inserts

---

usaspending_api/submissions/management/commands/load_dabs_submission_window_schedule.py
usaspending_api/submissions/tests/test_load_dabs_submission_window_schedule.py

There is a bug with the DABS Submission Window loader that will break when attempting to INSERT new records from Broker instead of UPDATE. This PR adds a default of the `datetime.max()` (since we have another job that handles the reveal logic) and adds test cases to cover this. 
A default value of `datetime.max()` was added in for `submission_reveal_date` for the case where we INSERT a new record instead of performing an UPDATE. I had a thought of adding a default on the field, but Django will only apply default values in the ORM. This means that any new records created with the ORM will use the default field, but any non-ORM created values will not utilize the default; I figured this would cause more confusion than it is worth.
The added test case …

[DEV-7854] Fix dabs window loader to allow new records

---

usaspending_api/disaster/tests/integration/test_disaster_award_amount.py
usaspending_api/disaster/tests/integration/test_disaster_award_count.py
usaspending_api/disaster/v2/views/award/amount.py
usaspending_api/search/v2/elasticsearch_helper.py

The `/api/v2/disaster/award/amount/` consistently runs over 1 min and occasionally over 5 minutes. This means that it cannot cache and will stay in a failing state with each call. By switching to Elasticsearch this consistently takes under 1 minute.
Previously we have always tried to get a unique count with Elasticsearch `cardinality` aggregation. This does not work in many cases since it can only guarantee accuracy up to 10k. However, this new `scripted_metric` approach that has been used in a few different places has proven to be accurate (when testing against Staging and local) while completing in enough time to be cached.
The only test case that was updated is `def test_award_amount_success()`. This test case looked for results with Award Type …

[DEV-7831] Refactor /award/amount to use Elasticsearch

---

usaspending_api/disaster/v2/views/spending_by_geography.py

Fixes the aggregation used by the `/disaster/spending_by_geography/` endpoint to allow for filtering by individual DEFC
Changes the aggregation used to be a nested aggregation filtering by the DEFC and summing the outlay/obligation/loan value from using the "total" value, which allows breaking down the covid amount by the specific DEFC
8. [X] Jira Ticket [DEV-7321](https://federal-spending-transparency.atlassian.net/browse/DEV-7321):
**Area for …

[DEV-7321 Spending by geography filtering by individual defc

---

usaspending_api/broker/helpers/last_load_date.py
usaspending_api/broker/lookups.py
usaspending_api/broker/tests/integration/test_last_load_date.py
usaspending_api/etl/elasticsearch_loader_helpers/controller.py
usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
usaspending_api/etl/management/commands/elasticsearch_indexer.py

This PR updates the start and end date range for Elasticsearch deletes to prevent deletes from Postgres being missed in ES
A new `external_data_load_date` is being used to keep track of this: `es_deletes`
When deletes finish, the earlier of the `fabs` and `fpds` load dates is set as the `es_deletes` date. 
When deletes are starting, the following range is used to query S3 for deletes:
- `start_date` - `es_deletes`
- `end_date` - The latter of `fabs` and `fpds` load dates
7. [ ] Appropriate …

[DEV-7787] Adjusts es delete timeframe

---

usaspending_api/api_contracts/contracts/v2/references/toptier_agencies.md
usaspending_api/references/tests/test_toptier_agency_v2.py
usaspending_api/references/v2/views/toptier_agencies.py

Adds `agency_slug` field to the `/api/v2/references/toptier_agencies/` endpoint to be used by frontend to create links to new Agency v2 profile page.
`agency_slug` is based on the name of the toptier agency, all in lowercase and with the spaces replaced by `-`.
8. [X] Jira Ticket [DEV-7809](https://federal-spending-transparency.atlassian.net/browse/DEV-7809):
```
```

[DEV-7809] Agency slugs

---

usaspending_api/download/tests/integration/test_download_disaster.py
usaspending_api/download/v2/base_download_viewset.py
usaspending_api/download/v2/request_validations.py

Noticed while testing the COVID single DEFC download that after generating the single DEFC download the request to get all DEFC will look to the latest which is the download for only a single DEFC. This fixes that by paying attention to the download file name and the request.
Made updates to how the pre-generated download is looked up to make sure that the correct one is returned. The test case change fails without the adjustments to the base download viewset logic which means that it should be working as intended now.
6. [x] Data …

[DEV-7894] Fix handling for generated download lookup

---

usaspending_api/api_contracts/contracts/v2/recipient/duns/recipient_id.md
usaspending_api/recipient/management/sql/restock_recipient_profile.sql
usaspending_api/recipient/tests/integration/test_recipient.py
usaspending_api/recipient/v2/views/recipients.py

Fix for the `restock_recipient_profile.sql`  which was not working properly, as well as adding the `parent_uei` field because I forgot.
8. [X] Jira Ticket [DEV-7700](https://federal-spending-transparency.atlassian.net/browse/DEV-7700):
```
```

[DEV-7700] UEI + SQL Fix

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_agency.py
usaspending_api/search/tests/unit/test_spending_by_category.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py

Adds the `agency_slug` field to the API response for `spending_by_category/awarding_agency/` endpoint.
Only returns a non-null value if the agency has a profile page - meaning it is an agency that has at least one submission.
8. [X] Jira Ticket [DEV-5081](https://federal-spending-transparency.atlassian.net/browse/DEV-5081):
```
```

[DEV-5081] Add agency_slug to spending_by_category

---

usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/helpers/elasticsearch_download_functions.py
usaspending_api/download/management/commands/download_sqs_worker.py
usaspending_api/download/v2/request_validations.py
usaspending_api/settings.py

Lowers the maximum number of rows allowed for download to be 10,000 rather than 500,000 to mitigate the database issue coming from the downloads.
Tested locally to confirm that the limit worked for the elasticsearch downloads.
8. [ ] Jira Ticket [DEV-8103](https://federal-spending-transparency.atlassian.net/browse/DEV-8103):
```
```

[HOTFIX] Change download limit to 10,000 rows

---

usaspending_api/disaster/tests/integration/test_overview.py
usaspending_api/disaster/v2/views/overview.py

This updates the calculation of the `additional.total_budget_authority` value on the `/v2/disaster/overview` endpoint to align with Data Lab. 
Data Lab uses the same value as `additional. total_obligations` for this field, so we are updating to match. 
```
```

[WARMFIX] Updates Calculation for Additional TBR on ARP Page

---

usaspending_api/disaster/v2/views/overview.py

Removes unused aggregations and selections from the calculation for additional values on the Disaster Overview endpoint. Includes a comment about the changed calculation.
8. [x] Jira Ticket [DEV-8143](https://federal-spending-transparency.atlassian.net/browse/DEV-8143):
```
```

[DEV-8143] Removes unused TBR aggregations after warmfix

---

usaspending_api/agency/tests/fixtures/bureau_data.py
usaspending_api/agency/tests/integration/conftest.py
usaspending_api/agency/tests/integration/test_subcomponents.py
usaspending_api/agency/v2/urls.py
usaspending_api/agency/v2/views/subcomponents.py
usaspending_api/api_contracts/contracts/v2/agency/toptier_code/sub_components.md
usaspending_api/api_docs/markdown/endpoints.md

Adds `/api/v2/agency/{toptier_code}/subcomponents/` endpoint to return bureau titles and relevant spending.
Uses GTAS to generate the spending amounts, and joins from gtas->tas->fed account->bureau title lookup table to get the bureau names.
8. [X] Jira Ticket [DEV-8043](https://federal-spending-transparency.atlassian.net/browse/DEV-8043):
```
```

[DEV-8043] bureau agency endpoint

---

usaspending_api/settings.py

Small setting changes to allow downloads up to 250k rows.

Increase download limit to 250k

---

usaspending_api/agency/v2/views/bureau_federal_account.py
usaspending_api/agency/v2/views/subcomponents.py

Groups bureau codes by division of the military/defense-wide spending instead of having individual bureau codes all under the DOD toptier code.
We also had to add checks for the federal account endpoint so that clicking through one of the grouped bureaus will still return the federal accounts for that branch of the military
8. [X] Jira Ticket [DEV-8117](https://federal-spending-transparency.atlassian.net/browse/DEV-8117):
**Area for explaining …

[DEV-8117] add special DOD groupings

---

usaspending_api/references/v2/views/autocomplete.py

Adds sorting to the CFDA autocomplete endpoint. While the endpoint has never actually had sorting, the previous limit of 10 results on the frontend made it appear that there was sorting, likely just due to the way that the results return from the database.
Sorts by program number
8. [X] Jira Ticket [DEV-8147](https://federal-spending-transparency.atlassian.net/browse/DEV-8147):
```
```

[DEV-8147] CFDA Autocomplete sorting

---

usaspending_api/api_contracts/contracts/v2/awards/award_id.md
usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/data_layer/orm.py
usaspending_api/idvs/tests/test_awards_idv_v2.py

Need to add Agency slug to the Award summary endpoint to support linking from Award summary page to new Agency V2.
Add agency slug to both the Awarding and Funding agency sections for only the toptier agencies with a file C submission since those will be the agencies with an Agency profile page.
8. [x] Jira Ticket [DEV-8300](https://federal-spending-transparency.atlassian.net/browse/DEV-8300):
```
```

[DEV-8300] Add Agency slug to Award Summary endpoint

---

usaspending_api/agency/tests/integration/test_awards.py
usaspending_api/agency/v2/views/awards.py

Need to handle the possibility of no action date for a FY. Came up in QAT when querying FY 2022.
Check for NULL `latest_action_date` before attempting to divide. Without this check the endpoint fails with a 500 since you cannot divide None.
8. [x] Jira Ticket [DEV-8269](https://federal-spending-transparency.atlassian.net/browse/DEV-8269):
```
```

[DEV-8269] Handle no action_date for a FY

---

usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
usaspending_api/agency/v2/views/budgetary_resources.py

Limit `/api/v2/agency/<toptier_code>/budgetary_resources/` endpoint to only quarterly periods prior to FY 22.
It was noticed during testing that there are some cases (such as for DoD) where multiple agencies had submissions under the same funding agency. Prior to FY 22 monthly submissions were not required and you had some agencies submitting monthly and others quarterly. In some rare cases part of the agencies submitted under a funding agency might submit monthly while others have not made the switch yet. In those cases values such obligations drop drastically since they are a sum of `_cpe` values for that particular submission period. Ideally this logic will not be permanent, but will prevent odd looking data until we can get a more permanent fix …

[DEV-8317] Limit to quarterly periods prior to FY22

---

usaspending_api/agency/tests/fixtures/sub_agency_data.py
usaspending_api/agency/tests/integration/test_sub_agency.py
usaspending_api/agency/v2/views/sub_agency.py

Handle case of no offices for provided filters.
No office came up if the Agency does not have any transactions for a particular type. In that case a `"size": None` was passed to Elasticsearch and resulted in a parser error. A new default size of 10 is used as passing 0 could also force a parser error if there was a case where a subagency existed on a transaction without an office. …

[DEV-8330] Handle case of no offices for filters

---

usaspending_api/agency/v2/views/obligations_by_award_category.py

In the `obligations_by_award_category` endpoint, the "other" category both accounts for the defined award category "other" as well as anything that doesn't match one of the existing award categories. The endpoint was overriding the defined "other" category amount with the sum of non-matching categories, resulting in the "other" category to be 0 when it should not be.
Switched a `=` to a `+=` sign when formatting the "other" results. 
8. [N/A] Jira …

[WARMFIX] Fix "other" award category grouping

---

usaspending_api/recipient/management/sql/recipient_agency.sql

Adding the UEI CASE to the GROUP BY was overlooked and caused the pipeline to fail.
UEI is now part of the recipient_hash logic. That same logic needed to get added into the GROUP BY.
Additional changes were changing tabs for spaces.
8. [x] Jira Ticket N/A
```
```

Fix recipient sql GROUP BY

---

usaspending_api/agency/v2/views/bureau_federal_account.py
usaspending_api/agency/v2/views/subcomponents.py

Remove prior year values in TBR, Obligation, and Outlay calculations
During implementation we used prior year values to calculate TBR, Obligation, and Outlay. This was found to be incorrect for the purpose of Agency V2 as we are looking at a slice of a single FY instead of sums across many FY similar to what was done on the COVID profile page.
8. [x] Jira Ticket [DEV-8341](https://federal-spending-transparency.atlassian.net/browse/DEV-8341): …

[DEV-8341] Remove prior year values from calculations

---

.travis.yml

Travis recently came default with ES 7.16 instead of the previous version of 5.5. For some reason the process of downgrading from 7.16 causes the install of our currently used version (7.1) to fail when starting. The fix created in #3343 is to remove the previously installed version of Elasticsearch prior to installing 7.1.
The PR mentioned above was created for testing purposes and branched off QAT. As a result, this new branch was created from `master` in order to get the Travis fix to all environments.

[Prod] Fix travis by removing newer ES

---

.travis.yml

Travis recently came default with ES 7.16 instead of the previous version of 5.5. For some reason the process of downgrading from 7.16 causes the install of our currently used version (7.1) to fail when starting. The fix created in #3343 is to remove the previously installed version of Elasticsearch prior to installing 7.1.
The PR mentioned above was created for testing purposes and branched off QAT. As a result, this new branch was created from `master` in order to get the Travis fix to all environments.

[Staging] Fix travis by removing newer ES

---

usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/helpers/elasticsearch_download_functions.py
usaspending_api/settings.py

Help to resolve issues with downloads having incomplete data.
It appears that replication might be causing issues with our downloads in environments that utilize a Primary/Replica structure for the API/Downloads. Since the replica is readonly the lookup IDs for the Elasticsearch based downloads are inserted into the Primary and then it would appear that they are not being replicated over to the replica in time for the first CSV downloaded. 
This PR adds a wait following the step that inserts lookup IDs to make sure they are on the DB designated for downloads prior to proceeding with the download.
4. [x] Matview …

[DEV-8388] Fix ES download replication race condition

---

usaspending_api/awards/migrations/0090_add_back_faba_covid_index.py

Adds back a database index that was removed most likely by accident with a previous migration. Current thought is that the work to change the disaster_emergency_fund_code column from a `char` to `text` type removed this index.
The SQL queries for the COVID Profile Page on `financial_accounts_by_awards` rely on this database index to help performance. Most likely as an accident due to a previous migration this index was removed. To make sure the COVID Profile Page is performant this migration adds the index back, but leverages the `migrations.RunSQL` method to create the index manually via `CREATE INDEX IF NOT EXISTS`. This approach will help ensure that others who pull down the code base don't run into a potential conflict when running the …

[DEV-8486] Recreate the partial COVID index

---

usaspending_api/settings.py

Updating the download max limit back to 500k following a series of improvements in the past few sprints.

[DEV-8499] Increase download limit back to 500k

---

usaspending_api/broker/helpers/delete_stale_fabs.py
usaspending_api/broker/tests/integration/test_delete_fabs.py

https://github.com/fedspendingtransparency/usaspending-api/pull/3378/files Updated the fabs loader to stop deleting awards before transactions, so awards were not recreated, causing duplicates in ES. This caused deletes of transactions to fail because awards had FKs to them. (see [http://jenkins-master-8ca0e1e199b2c8fc.elb.us-gov-west-1.amazonaws.com:8080/blue/organizations/jenkins/NonProd[…]Prod-Nightly-Pipeline/77/pipeline/](http://jenkins-master-8ca0e1e199b2c8fc.elb.us-gov-west-1.amazonaws.com:8080/blue/organizations/jenkins/NonProd-Nightly-Pipeline/detail/NonProd-Nightly-Pipeline/77/pipeline/))
This PR adds a step to remove transactions from awards that are about to be deleted before the actual deletion takes place to prevent FK violations on awards. 
**Requirements …

[DEV-8442] Fix FABS Loader Transaction Deletes

---

requirements/requirements-app.txt

Newer version of `marshmallow` caused issues when deploying a new image. Need to set the version to avoid conflicts. 
`dataclasses-json` installs the latest version of `marshmallow`, but does not necessarily need the latest version. This issue came up with the newest version of `marshmallow==3.15.0` which is why the version is set to the previous latest version of `marshmallow==3.14.1`
8. [ ] Jira Ticket (N/A)
**Area …

Updating marshmallow version

---

usaspending_api/awards/v2/filters/sub_award.py
usaspending_api/search/tests/data/spending_by_award_test_data.py
usaspending_api/search/tests/integration/test_spending_by_award.py

Adds the `recipient_uei` field to the advanced search recipient filter
8. [X] Jira Ticket [DEV-8584](https://federal-spending-transparency.atlassian.net/browse/DEV-8584):
```
```

[DEV-8584] add UEI to subawards filter

---

usaspending_api/bulk_download/tests/test_download.py
usaspending_api/download/v2/download_column_historical_lookups.py

Simple update to the reusable `lookups.py` file to ensure it includes appropriate UEI fields.
8. [x] Jira Ticket [DEV-7948](https://federal-spending-transparency.atlassian.net/browse/DEV-7948):
```
```

[DEV-7948] Ensure UEI related fields are available in subaward downloads

---

usaspending_api/api_docs/markdown/endpoints.md

The `/api/v2/recipient/children/<DUNS\>/` endpoint was recently updated to `/api/v2/recipient/children/<DUNS_OR_UEI\>/`, but the `endpoints.md` file was not updated to match. This PR addresses this inconsistency. 
8. [x] Jira Ticket [DEV-8434](https://federal-spending-transparency.atlassian.net/browse/DEV-8434):
- N/A - Performance evaluation of affected (API | Script | Download)
- N/A - Before / After data comparison
```
```

[DEV-8434] Adds duns_or_uei to children endpoint in MD

---

usaspending_api/agency/v2/views/recipients.py
usaspending_api/api_contracts/contracts/v2/agency/toptier_code/recipients.md
usaspending_api/disaster/tests/fixtures/disaster_account_data.py

Adds a deprecation warning to the GET response for the `/api/v2/agency/{toptier_code}/recipients/` endpoint as it will be removed.
8. [X] Jira Ticket [PIPE-248](https://federal-spending-transparency.atlassian.net/browse/PIPE-248):
```
```

[PIPE-248] Add deprecator tag to /agency/recipients/

---

.travis.yml

Updating the default branch used by Travis to be `qat` instead of `development` since we have moved away from the dev branches.

Updating .travis.yml default broker branch

---

usaspending_api/common/helpers/spark_helpers.py
usaspending_api/config/__init__.py
usaspending_api/config/envs/__init__.py
usaspending_api/config/envs/default.py
usaspending_api/config/envs/local.py
usaspending_api/config/tests/unit/test_config.py
usaspending_api/config/utils.py

Remove the subtle error-prone weakness of using property() fields with late-binding (lazily evaluated by way of its closure nature) lambda functions. Using them _excludes_ those fields from the set of fields that pydantic is tracking, and makes it so they can't be overridden as expected.
Looking into using [`validators`](https://pydantic-docs.helpmanual.io/usage/validators/) as a workaround and better approach for this. `validators` are perhaps poorly named. Yes they "validate" entries/assignments/sourced-values, but they can also be used as a way to pre or post-process values, e.g. to _transform_ them, and return a altered or different value than what was provided/sourced.
2. [ …

[PIPE-10] Use pydantic validators for lazily composed config vars

---

Makefile
docker-compose.yml

Sets default minio ports in docker-compose file to 10001 and 10002 to match local config and template env. 
Adds ${profiles} to `docker-compose-run` make target to allow profiles to be passed in.
3. N/A Necessary PR reviewers:
8. [x] Jira Ticket [PIPE-284](https://federal-spending-transparency.atlassian.net/browse/PIPE-284):
```
```

[PIPE-284] Updates minio default ports and adds docker-compose-run profiles option

---

usaspending_api/download/filestreaming/download_generation.py

Fixes a bug with the download/awards endpoint where the `date_type` field was not being applied correctly. Also fixes bug that was causing subaward downloads to fail
The subaward bug was due to the fact that the subaward data does not contain any form of `date_signed` for subawards,  so the subaward download will ignore the `date_signed` type and default to using `action_date`. …

[DEV-8603] Download date fix

---

usaspending_api/common/helpers/spark_helpers.py
usaspending_api/etl/management/commands/create_delta_table.py
usaspending_api/etl/management/commands/load_table_to_delta.py
usaspending_api/etl/tests/integration/test_create_delta_table.py
usaspending_api/etl/tests/integration/test_load_table_to_delta.py

When running the create and load django mgmt commands for delta tables, use `--alt-db` or `--alt-name` to allow overriding the name of the db and table used.
- Still needs the `--destination-table`, as that is what is used to look up the default metadata from the `TABLE_SPEC` for the delta table
- If not provided, will use defaults
- Can use one or both
- Unit tests updated to exercise this functionality and existing create/load tests pass
8. [x] …

[PIPE-279,PIPE-280] Allow override of Delta db and table names

---

usaspending_api/etl/tests/integration/test_load_to_delta.py
usaspending_api/search/delta_models/award_search.py
usaspending_api/transactions/delta_models/transaction_search.py

Improvements to both Award and Transaction Search SQL in order to handle NULLs in Spark so that data matches that of Postgres.
Multiple changes around the use of COALESCE and COLLECT_SET to make sure that NULLs are handling correctly and data matches the Postgres table the Spark SQL is based off of. Additionally, combined several JOINs together to help reduce the complexity of the query optimizer. The data difference was only pointed out in transaction_search so far, but award_search would have suffered from similar problems.
6. …

Update transaction search sql

---

usaspending_api/bulk_download/tests/test_download.py
usaspending_api/download/tests/integration/test_populate_monthly_delta_files.py
usaspending_api/download/v2/download_column_historical_lookups.py

Changes the names of `award_description` in several download files to `prime_award_base_transaction_description` or `transaction_description` and updates Glossary/Data Dictionary.
8. [X] Jira Ticket [DEV-8905](https://federal-spending-transparency.atlassian.net/browse/DEV-8905):
```
```

[DEV-8905] Adjust award_description download field

---

usaspending_api/database_scripts/matview_generator/chunked_matview_sql_generator.py

The `make_read_indexes(table_name)` method in `chunked_sql_matview_generator.py` is expecting the schema to be included in the `table_name` parameter in the following format `<schema>.<table>`, otherwise the schema defaults to public. 
The `chunked_sql_matview_generator.py` script is already reading the schema from the source json file, but it wasn't being used in the `make_read_indexes(table_name)` call. This PR adds the schema to the `table_name` string.
7. [x] Appropriate Operations ticket(s) …

[PIPE-289] Adds schema to call to make_read_indexes()

---

usaspending_api/etl/management/commands/load_table_from_delta.py

Change the `autovacuum` setting for the new tables created via `load_tables_from_delta`.
In Postgres autovacuum on a table is used to help manage dead tuples that accumulate from UPDATE and DELETE statements. In the case of any table created via `load_tables_from_delta` there should never be any sort of UPDATE or DELETE since these are copied over from Databricks and put into place. That means that any resources spent on `autovacuum` is essentially a waste / going to block other queries for no reason.
6. [ ] Data validation …

Set autovacuum_enabled=FALSE for new tables

---

usaspending_api/search/migrations/0008_awardsearch_table.py

Simply drops the unique constraint on `award_id` in `rpt.award_search`
Note: this unique index is not managed by the model. 
8. [x] Jira Ticket [PIPE-289](https://federal-spending-transparency.atlassian.net/browse/PIPE-289):
```
```

[PIPE-289] Drop Unique Award ID Constraint in Award Search

---

.env.template
.gitignore
.travis.yml
Makefile
README.md
requirements/requirements-app.txt
requirements/requirements-dev.txt
requirements/requirements.txt
setup.cfg

Only pip install pyspark when in local dev or a CI build.
- The web app does not need pyspark
- The bulk download does not need pyspark
- `usaspending-backend` docker container doesn't need it
- And spark platforms we run on will already have pyspark
NOTE: Is based on `mod/pipe-191-include-all-static-files-on-install` from #3495 
Testing:
- It passes CI and all unit/integration tests, after Travis was changed to use `pip install .[dev]`
- Ran the `load_table_from_delta` in spark platform and it succeeded without error. i.e. it uses the baked-in Spark that's already there (we don't need to supply it via a pip installed `pyspark`).
3. [ ] Necessary …

[PIPE-10] pyspark as dev dependency only

---

config/uwsgi.ini

We are periodically seeing instances in prod get replaced by the load balancer due to failing health checks on random intervals that sometimes round to 29 hours.
Uwsgi workers are currently set to restart after a lifetime of 29 hours. This causes all of the workers to go down at the same time if their lifetime is the same. This addresses the issue by implementing a delta to spread the restart times out.
Also removing an unsupported value for the max-requests-delta.
4. [ ] Matview …

[OPS-2361] Implement delta for uwsgi max lifetime restart

---

usaspending_api/common/query_with_filters.py

Change to account for whitespace in CFDA filter.
With the move to Spark the JSON formatted values have a white space difference. After a look around the codebase this doesn't appear to be affecting anything else, but in this particular case is causing the regex to not find any / limited matches. 
Unit / integration tests were not updated for this case because they populated using the award and transaction search views. There are tech debt ticket(s) to determine the best path forward for tests.
This change will support old and new records in Elasticsearch without the need to re-index.
4. [x] Matview impact assessment …

[DEV-9043] Fixing the CFDA filter to account for whitespace in regex

---

usaspending_api/etl/management/commands/swap_in_new_table.py

The `swap_in_new_table.py` command is currently failing to swap the `recipient_profile` table with it's temporary counterpart. This is because a query used to determine whether the columns match between temp and live tables is returning an extra record, representing a column that was dropped on `recipient_profile`. This PR adds a filter to the query to prevent dropped columns from being returned 
From: https://www.postgresql.org/docs/current/catalog-pg-attribute.html
```
attisdropped bool
This column has been dropped and is no longer valid. 
A dropped column is still physically present in the table,
but is ignored by the parser and so cannot be accessed via SQL.
```
2. [ ] API …

[Bug Fix] Adds filter for attisdropped to Swap Commands column verification query

---

usaspending_api/broker/management/sql/restock_duns.sql

Recipients in broker that came from SAM after Apr 2021 that have a UEI and `NULL` for DUNS number are ignored by the broker -> usaspending `sam_recipient` data integration
Need to be grouping by `UEI` and not DUNS number (`awardee_or_recipient_uniqu`)
See Jira ticket for in depth discussion: [DEV-9073](https://federal-spending-transparency.atlassian.net/browse/DEV-9073)
8. [x] Jira Ticket [DEV-9073](https://federal-spending-transparency.atlassian.ne …

[HOTFIX] [DEV-9073] Fetch unique broker recipients by UEI

---

usaspending_api/download/v2/download_column_historical_lookups.py

Subaward download piid/fain columns should have piid/fain, not award_id
N/A
8. [x] Jira Ticket [DEV-9171](https://federal-spending-transparency.atlassian.net/browse/DEV-9171):
```
```

[DEV-9171] Subaward Download piid/fain, not award_id

---

usaspending_api/search/migrations/0016_award_search_index_rename.py

Renames an award_search index that is causing issues with the table swap due to the name being too long
```
```

Award Search index rename

---

usaspending_api/etl/tests/integration/test_load_to_from_delta.py

Several tests in `test_load_to_from_delta.py` cover scenarios that are not present in production. This PR removes those tests or sections of tests.
There are two main scenarios that are removed:
1. A test is loading a datasource for `*_test` tables, which are not being used in production. This configuration is only used for testing and comparing data
2. A test is loading a datasource from Delta to Postgres that is not being done in production. Many tables are only loaded from Postgres to Delta, but not the other way around. In these cases, there is no reason to test the load from Delta back to Postgres
3. [x] API documentation updated
4. [ ] Necessary PR reviewers:
5. [x] Matview …

Remove Unused Spark Tests

---

usaspending_api/search/v2/views/spending_over_time.py

The subaward spending over time query discreetly groups by `prime_fy` which skews the counts. This replaces it with `sub_fiscal_year` appropriately.
N/A
8. [x] Jira Ticket [DEV-9269](https://federal-spending-transparency.atlassian.net/browse/DEV-9269):
```
```

[DEV-9269] Subaward Spending Over Time Hotfix

---

usaspending_api/search/delta_models/award_search.py
usaspending_api/transactions/delta_models/transaction_search.py

Including pre-2000 data in awards and transactions to not lose data in the gold view transition and to work with the migrations.

Include pre-2000 data to award and transaction search

---

usaspending_api/agency/v2/views/sub_agency.py

Moved line that converts a `list` to a `set` to be outside of the `for` loop. This line was added in [PR #3646](https://github.com/fedspendingtransparency/usaspending-api/pull/3646)
List was being converted to a set within a loop that was then trying to call the `.extend()` method on the set. I moved the `set()` call to be outside of the loop.
1. [ ] Necessary PR reviewers:
2. Jira Ticket [DEV-9400](https://federal-spending-transparency.atlassian.net/browse/DEV-9400):

[HOTFIX] [DEV-9400] Fix over-indentation in for-loop

---

usaspending_api/disaster/tests/fixtures/disaster_account_data.py
usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
usaspending_api/disaster/tests/integration/test_disaster_def_code_count.py
usaspending_api/disaster/tests/integration/test_disaster_federal_account_count.py
usaspending_api/disaster/tests/integration/test_disaster_object_class_count.py

Should fix bug where tests from usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py were failing due to having hardcoded "future dates" that have now passed.
```
```

Date change test fix

---

usaspending_api/etl/management/commands/load_transactions_in_delta.py

Make sure that the `es_deletes` load date is also reset when the new delta load dates are _initially_ set
- Set at the `initial_run` of the transaction delta tables **only**
```
```

[PIPE-347] reset es deletes load date at delta transaction loader initial_run

---

usaspending_api/config/envs/default.py

Scaling up how many write connections are open when pushing CSV data from delta tables back down to Postgres
With our approach to scaling up the aurora writer instance, it looks like we can handle more concurrent writers. That and the transaction_search parallel write seems to lag fairly far behind award search, so less concurrency is happening among writing the two tables.
8. [ ] Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net …

[PIPE-353] More concurrent CSV writers for load_table_from_delta

---

usaspending_api/etl/management/commands/load_transactions_in_delta.py

This PR addresses the issue of "orphaned" transactions (records in the `transaction_fabs|fpds|normalized` tables that have no associated records in the source (`raw.detached_award_procurement` or `raw.published_fabs`) tables, and any awards that are impacted by orphaned transactions.
Due to timing of reviews, etc, this PR also fixes an issue with the `awards` ETL level.
During the `initial_run` ETL level of the `load_transactions_in_delta` command, this code first identifies any orphaned transactions in the `raw.transaction_normalized` table.  It then prevents those transactions from being added to the `int.transaction_id_lookup` or `id.award_id_lookup` tables, and prevents them from being copied from the `raw` to `int` versions of the …

[PIPE-474] Modify initial_run code in Delta loader to handle orphaned transactions & awards

---

usaspending_api/etl/management/commands/load_transactions_in_delta.py

Previous code was not correctly handling the `subaward_count` field in the `awards` table.  It is declared as `NOT NULL`, but was getting NULL values.
When updating or inserting awards in `int.awards` table, set `subaward_count` field to 0 to match previous behavior.
8. [ ] Jira Ticket [PIPE-474](https://federal-spending-transparency.atlassian.net/browse/PIPE-474):
```
```

[PIPE-474] Handle non-NULL subaward_count field

---

usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql

Subaward File F SQL for COVID Download has wrong PK reference
Find and replace left `award.id` when it should reference `award_id` of `award_search` on the join.
```
```

[PIPE-236] Fix covid sql award id ref in subaward files

---

usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py
usaspending_api/etl/management/commands/update_covid_awards_in_delta.py
usaspending_api/search/delta_models/award_search.py
usaspending_api/search/delta_models/subaward_search.py
usaspending_api/transactions/delta_models/transaction_search.py

**Descriptions**
Updates a few downstream jobs to use the `int` version of the `financial_accounts_by_awards` table:
- Subaward Search
- Transaction Search
- Award Search
- Touch Covid Awards

[PIPE-466] Usage of INT FABA 

---

usaspending_api/etl/management/commands/load_transactions_in_delta.py
usaspending_api/transactions/delta_models/transaction_fabs.py
usaspending_api/transactions/delta_models/transaction_fpds.py

Adding further date-parsing handling of the published_fabs to transaction_normalized mappings for action_date and the two period of performance columns, since raw fabs records see string dates in a variety of formats"
- the `raw.published_fabs.action_date` column was being used in its raw form to derive the fiscal year, and needed to be parsed into a date first
- the `raw.published_fabs.period_of_performance_curr|star` columns were being casted to date, but that will now work with strings in the format of `mm/dd/YYYY`, which this raw table has
5. [ ] Frontend impact …

[PIPE-474]  raw fabs to tx norm date parsing fixes

---

usaspending_api/etl/management/commands/load_transactions_in_delta.py
usaspending_api/etl/tests/integration/test_load_transactions_in_delta.py
usaspending_api/transactions/delta_models/transaction_fpds.py

Continuing to update delta transaction loader code to match any additional differences with the Postgres transaction loader behavior.
Changes:
1. In `initial_run`, change the way the `int.award_id_lookup` table is populated and how orphaned transactions are excluded from this table.
2. In last PR, mistakenly allowed several fields to pass unaltered from `raw.detached_award_procurement` to `int.transaction_fpds`.  Revert this change and the changes to the tests.
3. [ ] API documentation updated
4. [ ] Necessary PR reviewers:
5. [ ] Matview impact assessment completed
6. [ ] Frontend impact assessment completed
7. [ ] Data validation completed
8. [ ] Appropriate Operations …

[PIPE-474] Handle additional data discrepancies

---

usaspending_api/etl/elasticsearch_loader_helpers/controller.py

Fixes issue of `self.config['partitions']` not being set when 0 records need to be updated.
Fixes issue of null partition overwriting final partition 
8. [ ] Jira Ticket [PIPE-347](https://federal-spending-transparency.atlassian.net/browse/PIPE-347):
```
```

[PIPE-347] ES Bugfixes

---

usaspending_api/etl/management/commands/swap_in_new_table.py

During swap of a partitioned table, skip dropping partitions, and wait til parent table is dropped which will remove them
If a targeted table to swap-out is a partition of a parent partitioned table,  it will not be dropped after its swap takes palce. Swapped-out partitions are not deleted after the swap due to the risk of their live parent partitioned table still receiving traffic while having one of its partitions deleted. If the parent partitioned table is also being swapped, then the partition will be deleted when the parent is deleted. Otherwise delete swapped/old partitions need to be deleted manually.
4. [ ] …

[PIPE-380] Defer partition drop on swap

---

usaspending_api/etl/management/commands/load_table_from_delta.py
usaspending_api/etl/management/commands/swap_in_new_table.py
usaspending_api/search/migrations/0027_transaction_search_guaid_idx.py

1. Keeping inherited indexes named according to convention during migrations
2. Shrinking boundaries around table+view renames during swap to avoid deadlocks
1. `copy_table_metadata` does not work if child/inherited indexes are not named the same as parent indexes except for the partition suffix. So migrations (for now) need to rename the auto-named inherited indexes.
2. Deadlocks have occurred if a table rename is happening in the same transaction as the dependent view renames that direct queries to the view
- The suspicion is that queries can eek in by way of the view, which has not yet been locked for rename, that direct the query to the table, which is already locked for rename, and then the view cannot be locked due to this deadlock scenario
- …

[PIPE-408] Rename inherited partition indexes and shrink swap transaction boundaries

---

usaspending_api/search/migrations/0028_transaction_search_agency_indexes.py

Index name on the partitions got the wrong name due to copy-paste error. Fixing that. 
Should have contained `funding_ageny_id` in the name.
```
```

[PIPE-408] Fixing copy-paste error on funding_agency_id index rename

---

usaspending_api/download/helpers/elasticsearch_download_functions.py
usaspending_api/settings.py

Using Django `extra()` to 'join' using WHERE on download_job_lookup rather than the slower EXISTS queries
Comes up with a query like:
```
FROM "transaction_search"
LEFT OUTER JOIN "award_search" ON ("transaction_search"."award_id" = "award_search"."award_id"),
"download_job_lookup"
WHERE (("download_job_lookup"."download_job_id" = 7156455
AND "download_job_lookup"."lookup_id" = "transaction_search"."transaction_id")
AND "transaction_search"."is_fpds")
LIMIT 500000
```
Instead of
```
FROM "transaction_search"
LEFT OUTER JOIN "award_search" ON ("transaction_search"."award_id" = "award_search"."award_id")
WHERE (EXISTS (
SELECT
(1) AS "a"
FROM
"download_job_lookup" U0
WHERE (U0."download_job_id" = 7156454
AND U0."lookup_id" = "transaction_search"."transaction_id")
LIMIT 1) …
```

[HOTFIX] Use Django extra() to join ES downloads to download_job_lookup

---

usaspending_api/common/helpers/aws_helpers.py

Updates AWS function to indicate that the environment is not AWS if a socket timeout is caught.
Depending on a developer's host machine configurations, a `socket.timeout` exception could be raised when checking if the environment is AWS. The code base before this PR did not account for such a case.
8. [x] Jira Ticket [DEV-9609](https://federal-spending-transparency.atlassian.net/browse/DEV-9609):
**Area for …

[DEV-9609] `is_aws()` missing exception

---

Dockerfile

Updated Dockerfile to add liblzma headers package and to install a newer version of the PostgreSQL client.
Added the `xz-devel` package so that Python can build with LZMA compression supported and remove the following warning when launching Python inside a container:
> UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
Updated `postgresql10` to `postgresql13` since the version 10 client is no longer available through **pgdg-redhat-repo-latest.noarch.rpm**.
1. [ ] Necessary PR reviewers:

Update postgresql version and add liblzma headers

---

usaspending_api/settings.py

Download time limit (in hours) was increased to 6 temporarily to support a GAO audit. This PR restores the time limit to 4 hours.

[DEV-9705] Restores download limit of 4 hours

---

usaspending_api/accounts/v2/filters/account_download.py
usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/tests/unit/test_file_generation.py

Adds a third bucket to Custom Account File C downloads that includes unlinked File C records.  
Adds a third `download_source` to this download. It uses a new filter to check that `award_id` is `None` for this.
2. N/A- API documentation updated
8. [x] Jira Ticket [DEV-9729](https://federal-spending-transparency.atlassian.net/browse/DEV-9729):
```
```

[DEV-9729] Adds third bucket for unlinked awards

---

usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/management/commands/download_sqs_worker.py

Adds some logging around downloads that are being marked as failed. 
- Simply logs the same message being stored in the db in the `fail_download()` method of `download_generation`. 
- Adds exception handling to the SQS step attempting to fail the job
8. [x] Jira Ticket [DEV-9733](https://federal-spending-transparency.atlassian.net/browse/DEV-9733): …

[DEV-9733] Adds additional logging for downloads

---

requirements/requirements-app.txt

We have been experiencing the same issue described in this bug for the `drf-api-tracking` Python library. The suggested fix is to pin to version `1.8.0` instead of using the latest version `1.8.2`
https://github.com/lingster/drf-api-tracking/issues/92

[FIX] Pin previous version of `drf-api-tracking` to fix failing app installs

---

usaspending_api/agency/tests/integration/test_agency_tas_object_class.py
usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
usaspending_api/agency/v2/views/tas_object_class_list.py
usaspending_api/agency/v2/views/tas_program_activity_list.py

**Description & Technical details:**
When aggregating obligations and outlays for object class, we need to use major object class name. This was a miss when this work was originally developed. Additionally, there are multiple ids per major object class name so now we need to remove id from the aggregation otherwise we'll have multiple groups with the same name.

[DEV-9887] Use Major Object Class Name

---

usaspending_api/agency/v2/views/new_award_count.py
usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
usaspending_api/api_contracts/search_filters.md
usaspending_api/search/filters/time_period/decorators.py
usaspending_api/search/filters/time_period/query_types.py
usaspending_api/search/tests/integration/test_spending_by_award.py
usaspending_api/search/tests/unit/test_time_period.py
usaspending_api/search/v2/views/spending_by_award.py

Currently, requests to the `spending_by_award` endpoint can request new awards only by including a time period filter with `date_type = date_signed`. However, other endpoints (namely those that are transaction based) only return new awards only when a time period filter has `date_type = new_awards_only`. Even though new awards only is supported in both the transaction based endpoints and the `spending_by_award`, we’d like to make a consistent way to retrieve new awards only between all endpoints. Consistency is the purpose of this PR.
Additionally, this PR updates another award based endpoint that returns a count of new awards to leverage the new "new_awards_only" `date_type` member.
1. [x] Unit & integration tests …

[DEV-9941] Updates `spending_by_award` with "new_awards_only" `date_type`

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_award_count.md
usaspending_api/search/tests/unit/test_spending_by_award_count.py
usaspending_api/search/v2/views/spending_by_award_count.py

Currently, requests to the `spending_by_award` endpoint can use a `date_type` member called "new_awards_only". Our API exposes a similar endpoint `spending_by_award_count`. In order for this endpoint to return a correct count it also needs to support the `date_type` member.
8. [x] Jira Ticket [DEV-9941](https://federal-spending-transparency.atlassian.net/browse/DEV-9941):
4. The nature of this work does not …

[DEV-9941] Updates `spending_by_award_count` with "new_awards_only" `date_type`

---

usaspending_api/awards/tests/unit/test_subaward_filter.py
usaspending_api/awards/v2/filters/sub_award.py
usaspending_api/download/tests/integration/test_download_disaster.py
usaspending_api/search/filters/postgres/defc.py

Update the existing date filter that is used when searching for Subawards associated with a DEFC.
The current logic picks the earliest `earliest_public_law_enactment_date` of all DEF codes in the request and compares the Subaward's `sub_action_date` to that value. This is inaccurate because the same enactment date is applied to all Subaward results and extra Subawards can be returned for DEF codes with an enactment date later than the earliest enactment date.
The updated logic will only return Subawards, that are associated with a DEFC, where the `sub_action_date` is on/after the DEFC's `earliest_public_law_enactment_date`.
2. [ ] Necessary PR reviewers:
3. [x] Frontend impact …

[DEV-9929] Update Subaward DEFC date filter

---

usaspending_api/search/filters/postgres/defc.py

Remove duplicate Subaward IDs in the case where the same Subaward is associated with multiple disaster codes that are included in the API request. A Subaward ID should only be returned once, even if it's associated with multiple DEF codes in the request.
Use a set instead of a list to remove duplicate Subaward IDs from the subquery.
1. [ ] Necessary PR reviewers:
2. [x] Data validation completed
3. [x] Jira Ticket [DEV-9929](https://federal-spending-transparency.atlassian.net/browse/DEV-9929):

[DEV-9929] Use set comprehension instead of list comprehension

---

usaspending_api/awards/tests/test_awards_v2.py
usaspending_api/awards/v2/data_layer/orm.py

Updated the logic for calculating the `total_outlay` value, on the /v2/awards/{id} endpoint, to include all outlay amounts including COVID and IIJA outlays. Also removed any date filtering. The endpoint also returns `null` if there are no outlays, instead of `0`.
Updated the logic for calculating the `total_outlay` value, on the /v2/awards/{id} endpoint, to include all outlay amounts including COVID and IIJA outlays. Also removed any date filtering. The endpoint also returns `null` if there are no outlays, instead of `0`.
2. [ ] Necessary PR reviewers:
3. [x] Data validation completed
4. [x] Jira Ticket [DEV-9403](https://federal-spending-transparency.atlassian.net/browse/DEV-9403 …

[DEV-9403] Update total_outlays calculation for /v2/awards/{id} endpoint

---

usaspending_api/references/management/commands/load_population_data.py
usaspending_api/references/management/commands/load_reference_data.py
usaspending_api/references/tests/data/census_2021_population_congressional_district.csv
usaspending_api/references/tests/test_load_population_data.py

Updated the `load_population_data` command to support more generic CSV file column headers and generated a new CSV file with congressional district population data from 2021 and new post-census congressional districts. Added unit tests for the `load_population_data` command.
Previously, the `load_population_data` command expected some year-specific column names in the CSV file provided to it. I updated the expected CSV column names to be more generic and not tied to any specific year. I also created a new CSV file containing U.S. congressional district data for all states and territories based on data from 2021 and using the most recent congressional districts. I also updated the `load_reference_data` command so that when it's run and calls the …

[DEV-10017] Congressional districts update [hotfix][staging]

---

usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
usaspending_api/search/tests/integration/test_spending_by_geography.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py

Add support for congressional district values of `90`. Add a function for combining multiple dictionaries in a list that have the same `code` and `name` value and sum their `amount` field values together into one dictionary.
Since the congressional district value of `90` is not in the database for any U.S. state, the transactions associated with this congressional code had the congressional district value (`90`) replaced with `None`. There is now a check to see if the amount of congressional districts for the given state is greater than 1. If this is true, then `90` is added to the list of valid congressional districts for that state and will no longer be replaced with `None`.
Added a function that checks all of the dictionaries in the provided list …

[DEV-10017] Add support for CD code 90 [hotfix][staging]

---

usaspending_api/download/filestreaming/download_generation.py
usaspending_api/settings.py

Several Nightly Pipelines have failed during the Covid Download generation step. These failures were caused by timeouts when trying to download the latest version of the Data Dictionary to include in the Download Zip file. 
Example failed pipeline logs:
```
[2023-06-11T18:31:56.498Z]   File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
[2023-06-11T18:31:56.498Z]     raise HTTPError(req.full_url, code, msg, hdrs, fp)
[2023-06-11T18:31:56.498Z] urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
```
```
[2023-06-10T23:23:39.429Z]   File "/usr/local/lib/python3.7/http/client.py", line 265, in _read_status
[2023-06-10T23:23:39.429Z]     raise RemoteDisconnected("Remote end closed connection without"
[2023-06-10T23:23:39.429Z] …
```

[DEV-9974] Retry Data Dictionary Download 

---

usaspending_api/transactions/delta_models/transaction_current_cd_lookup.py

Resolving minor bug with the transaction current cd derivations: making the ppop scope checks case-insensitive. This should help us derive a bit more values.
N/A
```
```

Fix: Current CD FABS PPoP Scope, Case Insensitive

---

usaspending_api/accounts/v2/filters/account_download.py

This PR corrects the federal account behavior in account downloads. The endpoint impacted by this PR is `/api/v2/download/accounts/` with "account_level" = "federal_account". The records in this download will now be unique per pair of federal_account_symbol and submission_period values. The other columns are aggregated accordingly to get the result set down to this grain.
This work leverages the existing pattern of annotations in the `account_download.py` module.
7. [x] Appropriate …

[DEV-9958] Federal Account Balance not Collapsing Properly in Download

---

usaspending_api/common/query_with_filters.py
usaspending_api/search/tests/data/spending_by_award_test_data.py
usaspending_api/search/tests/integration/test_spending_by_award.py

Update the Award Search Elasticsearch query to allow for searching by recipient names that end in a period. Previously searching for ACME INC would match `ACME INC` and `ACME INC.`, but searching for ACME INC. would not returns results for `ACME INC.`
If the `recipient_search_text` value ends in a period then add a `regexp` query to return any recipient names that match the given text that end in a `.` or have a `.` after the `recipient_search_text` value followed by 0 or more characters. As an example, searching for `ACME INC.` will now return results for:
* `ACME INC.`  (ends with a period, exact match for the given search text)
* `ACME INC.Q`  (has a period followed by 1 character)
* `ACME INC.XYZ`  (has a period followed by multiple characters) …

[DEV-9901] Update spending_by_award endpoint to support recipient names ending in periods

---

usaspending_api/api_docs/markdown/landing_page.md
usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
usaspending_api/spending_explorer/v2/filters/type_filter.py

Spending explorer is currently adding an extra section to the breakdown of a Recipient by Awards called “Non-Award Spending”. This amount represents the difference between calculated File B spending and File C spending. Because this amount skews the results of the breakdown by award, causing totals not to roll up to the amount from the previous drill down (see screenshot), we have decided to remove this section from the breakdown by recipient. 
N/A
7. [x] Appropriate Operations ticket(s) …

[DEV-7066]; Removes 'Non-Award Spending' from `api/v2/spending` endpoint

---

usaspending_api/download/filestreaming/download_generation.py
usaspending_api/download/helpers/elasticsearch_download_functions.py

In DEV-9834 we implemented a decorator pattern for the Time Period filter object in requests. We’ve updated most places in our code to work with a concrete class of this decorator pattern. However, there are still some places in our code that do not use these classes and instead manipulate the time period dictionary directly. The purpose of this story is to implement this pattern for the remaining time periods.
A side effect of this PR is that it actually fixes a bug that wasn't known in the awards download. Turns out because this last time period filter wasn't update to the new pattern, the awards download didn't support `new_awards_only`. Now it does.
2. [x] API documentation …

[DEV-10089] Remaining endpoints implement time period filter decorator pattern

---

.travis.yml
usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain.sql
usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain_and_uri.sql
usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_piid.sql
usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_uri.sql
usaspending_api/submissions/management/commands/rm_submission.py

In order for an Award record to be updated in Elasticsearch in the nightly pipeline, it’s `update_date` must be later than the last time Elasticsearch indexer ran. Consequently several places in the codebase update the `update_date` field on the `award_search` table such as the DAB Submission Loader.
In the post-Phase-3 version of the pipeline, the Elasticsearch indexer runs using Delta data instead of Postgres data, so any changes to the Postgres copy of `award_search` don’t have any impact on the Elasticsearch Indexer. 
We still have a few steps related to loading submissions that update the Postgres `award_search` table’s `update_date` field. This can be a lengthy operation that can cause significant slowdowns in the nightly pipeline, especially when a large submission …

[DEV-10149] Removes Unnecessary Award Updates from Postgres C to D Linkage Code

---

usaspending_api/idvs/tests/test_awards_idvs_accounts_v2.py
usaspending_api/idvs/tests/test_awards_idvs_activity_v2.py
usaspending_api/idvs/tests/test_awards_idvs_amounts_v2.py
usaspending_api/idvs/tests/test_awards_idvs_awards_v2.py
usaspending_api/idvs/tests/test_awards_idvs_funding_v2.py
usaspending_api/idvs/tests/test_federal_account_count.py
usaspending_api/tests/conftest_spark.py
usaspending_api/urls.py

Fixes some minor local unit test errors that likely came in with django upgrade.
1. When DEBUG=True, seems the django debug toolbar urls throws issues unless we import our settings from the designated DJANGO_SETTINGS_MODULE (`usaspending_api.settings`)
2. Need to set this so that data for TestCase (and inheritors like SimpleTestCase) flush these DBs at tear-down
- See: https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.SimpleTestCase.databases
4. [ ] API documentation updated
5. [ ] Necessary PR reviewers:
6. [ ] Matview impact assessment completed
7. [ ] Frontend impact assessment completed
8. [ ] Data validation completed
9. [ ] Appropriate Operations …

[FIX] Fixes for local unit test issues with newer versions of django

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_geography.md
usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
usaspending_api/etl/es_transaction_template.json
usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_country.py
usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
usaspending_api/search/tests/integration/test_spending_by_geography.py
usaspending_api/search/v2/views/spending_by_geography.py

Add a new `geo_layer` filter value of `country` that returns award and subaward spending by country.
* Update the Transactions ES index to add a `recipient_location_country_agg_key` field.
* Updated the `search/spending_by_geography` endpoint to use the `recipient_location_country_agg_key` or `pop_country_agg_key` to group ES transactions by country and return that amount for any/all countries included in the request.
* Updated the `search/spending_by_geography` endpoint to query SubawardSearch for all subawards where `sub_place_of_perform_country_co` or `sub_legal_entity_country_code` contains the country code included in the API request.
3. [ ] …

[DEV-10128] Add countries to search/spending_by_geography endpoint

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_geography.md
usaspending_api/search/tests/integration/test_spending_by_geography.py
usaspending_api/search/v2/views/spending_by_geography.py

Update the `search/spending_by_geography` endpoint to allow for requests that include USA and non-USA country codes in the same request.
Previously, either `place_of_performance_scope` or `recipient_scope` (depending on the `scope` value) were being added to requests if it wasn't already present and defaulting to a value of `domestic`. This meant that only USA results would be returned, even if non-USA country codes were included in the `geo_layer_filters` filter. Previously there was no way to get both domestic and foreign country results in the same request because you could only do one of the following:
1. Add either `place_of_performance_scope` or `recipient_scope` and set it to `domestic`. This filters out any non-USA results.
2. Add either …

[DEV-10183] Update search/spending_by_geography endpoint to support domestic and foreign countries

---

usaspending_api/common/etl/spark.py

The PostgresSQL queries were converted to SparkSQL for the Covid-19 download job. There were a few differences between the download files from before and after the changes.
Small adjustments were made to the SparkSQL queries and the settings were adjusted for how to write null data to a csv file when using spark.
8. [x] Jira Tickets - [PIPE-493](https://federal-spending-transparency.atlassian.net/browse/PIPE-493), …

PIPE-493; Change nullValue arg to emptyValue in spark csv write options

---

usaspending_api/transactions/delta_models/transaction_fabs.py
usaspending_api/transactions/delta_models/transaction_fpds.py

The purpose of this PR is to fix a bug found during testing of DEV-9816. The bug was caused by coalescing country name to UNITED STATES anytime it was blank and the country code was USA. We only want to coalesce country name to UNITED STATES when the code is UNITED STATES. This transformation was also missing in the FPDS transaction load. This PR adds it there.

[DEV-9816] Don't COALESCE Country Name in One Case

---

usaspending_api/settings.py

Download ENV is not an accessible environment variable in Databricks when this command runs as a job. To workaround this issue we are changing the variable to one that represents the same knowledge and is accessible.

[PIPE-504]; Fixes bucket name in staging and prod lane

---

usaspending_api/common/helpers/api_helper.py
usaspending_api/search/tests/unit/test_spending_by_award.py
usaspending_api/search/v2/views/spending_by_award.py

An uncaught error was thrown when an API user would try to search for loan awards and sort them by `Start Date`. This is because loan awards have an `Issued Date`, and not a `Start Date`. More filtering was added when the API request is received to not allow this invalid sort value to be processed.
The request verification previously was allowing sort values that appeared in any of the award mappings, although some types of awards don't have the same mappings. This is what allowed the `Start Date` to not be rejected and then cause an error later on when the application was trying to sort the results on a column that doesn't exist. I changed the sort value verification to be more granular and only allow values that correspond with the award type …

[DEV-10278] Fix Error when Sorting by Start Date with Loans

---

usaspending_api/etl/management/commands/load_transactions_in_delta.py
usaspending_api/etl/tests/integration/test_load_transactions_in_delta.py
usaspending_api/etl/tests/unit/test_load_transactions_in_delta.py

The unit tests in the file `test_load_transactions_in_delta.py` were optimized to not make so many calls that use a Django command. These commands take the majority of the time, so by reducing even a few calls, it helped reduce the overall runtime by over 2 minutes.
Some tests were combined and other parts of the code were refactored so that certain functionality could be tested without needing to use the Django command. There is a new unit test file that can run independently from the integration tests.
6. N/A - Data …

[PIPE-509] Reduce Calls to load-transactions-in-delta Django Command

---

usaspending_api/bulk_download/tests/integration/test_download.py
usaspending_api/download/helpers/download_annotation_functions.py
usaspending_api/download/v2/download_column_historical_lookups.py

Loans use original loan subsidy cost to measure the value of an award. Non-loans use federal action obligation. This makes it tricky to sum up spending on download files that include both loans and non-loans. The database has a column `generated_pragmatic_obligation`s that can be summed in these cases. For these reasons, this PR adds `generated_pragmatic_obligations` to downloads so that users can aggregate on this column alone to get a total that accounts for these nuisances.
7. [x] Appropriate Operations …

[DEV-10072] Assistance obligations added to downloads

---

usaspending_api/search/v2/views/search_elasticsearch.py

A server error with 500 status code was encountered anytime an unknown sort value was included in a request to the `spending_by_transaction` endpoint. According to REST API standards a RESTful API should return a status code in the 400 range for malformed or bad data provided by the user to the API. This PR addresses that issue.
[JIRA: PR Description Template]
8. [x] Jira Ticket [DEV-9790](https://federal-spending-transparency.atlassian.net/browse/DEV-9790): …

[DEV-9790]: Implements Supported Sort Keys

---

usaspending_api/etl/management/commands/load_multiple_submissions.py
usaspending_api/etl/management/commands/load_submission.py
usaspending_api/etl/submission_loader_helpers/file_c.py
usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py

Adds `--skip-file-c-to-d-linkage` flag to `load_submission` and `load_multiple_submissions` commands. Skip file c to d linkage process when flag is present. 
7.  N/A - Appropriate Operations ticket(s) created
8. [x] Jira Ticket [DEV-10362](https://federal-spending-transparency.atlassian.net/browse/DEV-10362):
```
```

[DEV-10362] Adds --skip-file-c-to-d-linkage Flag to Submission Loaders

---

usaspending_api/etl/es_covid19_faba_template.json

Covid FABA index is currently failing because it has a single document with over 10k nested objects. Increasing the limit to allow this record to be successfully indexed. 
2. N/A -API documentation updated
6. N/A - Data validation completed
8. [x] Jira Ticket [DEV-10384](https://federal-spending-transparency.atlassian.net/browse/DEV-10384):
- N/A - Before / After data comparison
```
```

[DEV-10384] Increases max nested objects limit to 12k on Covid FABA Index

---

usaspending_api/data/AssistanceSummary_download_readme.txt
usaspending_api/data/COVID-19_download_readme.txt
usaspending_api/data/ContractSummary_download_readme.txt
usaspending_api/data/idv_download_readme.txt

Fix broken data dictionary links from "https://www.usaspending.gov/download_center/data_dictionary" to  "https://files.usaspending.gov/docs/Data_Dictionary_Crosswalk.xlsx" in data README files. 
Updated broken data dictionary links. No further technical details required. 
1. [x] Unit & integration tests updated N/A
2. [x] API documentation updated N/A
4. [x] Matview impact assessment completed N/A
5. [x] Frontend impact assessment completed N/A
6. [x] Data validation completed N/A
8. [x] Jira Ticket [DEV-8956](https://federal-spending-transparency.atlassian.net/browse/DEV-8956):
```
```

Dev-8956 Fixed broken data dictionary links in data README files.

---

usaspending_api/agency/tests/integration/test_award_count.py
usaspending_api/agency/v2/urls.py
usaspending_api/agency/v2/views/award_count.py
usaspending_api/api_contracts/contracts/v2/agency/awards/count.md
usaspending_api/api_contracts/contracts/v2/agency/toptier_code/awards/count.md
usaspending_api/api_docs/markdown/endpoints.md
usaspending_api/common/helpers/fiscal_year_helpers.py

GSA generates a yearly report with award counts for the previous FY by agency and award type. Their current method requires them to run dozens of separate searches and manually copy the award counts by type into a table. This allows them to count prime award summaries where the date range from the earliest to the latest transaction overlaps with the FY. This process takes them several hours per year. They need to continue pulling these same numbers once a year indefinitely. If we change how advance search counts prime award summaries (only count awards with a transaction in the selected FY) they would no longer be able to use that feature for their purposes. There are several possible solutions to support this use case. The ideal solution for GSA would be to create a …

[DEV-10148] New Endpoint for Award Counts by Agency

---

usaspending_api/references/management/commands/loadcfda.py

During testing, an issue was found with the `loadcfda` command after upgrading Pandas to version 1.3.*. The `pandas.read_csv()` command was failing to read [cfda.csv](https://files.usaspending.gov/reference_data/cfda.csv) file because it contains characters that cannot be decoded using the `utf-8` codec.
This was not an issue with 1.1.* because of [a bug](https://github.com/pandas-dev/pandas/issues/39450#issuecomment-769960851) with the version that resulted in these decoding issues not to be raised. When the bug was fixed a new optional parameter was added to the `read_csv()` command called `encoding_errors`, which defaults to `strict`. 
In order to reproduce the behavior that was occurring with the previous version, this PR sets the `encoding_errors` parameter to …

[DEV-10415] Fix Pandas 1.3.* Upgrade Encoding Issue

---

usaspending_api/search/delta_models/subaward_search.py
usaspending_api/transactions/delta_models/transaction_current_cd_lookup.py

The Broker table `cd_city_grouped` was updated to support city codes which affected its uniqueness. This adjusts the several loaders (subaward_search, transaction_current_cd_lookup) that use that table to group by its previous uniqueness.
N/A
8. [x] Jira Ticket N/A
```
```

Fix: cd_city_grouped Duplicates

---

usaspending_api/etl/es_covid19_faba_template.json

Increases nested objects limit to 25k on Covid Index to address the job failing due a record with a 17k nested objects, which is over the current limit of 12k. 
4. N/A -  Matview impact assessment completed
6. N/A - Data validation completed
8. [x] Jira Ticket [DEV-10555](https://federal-spending-transparency.atlassian.net/browse/DEV-10555):
```
```

[DEV-10555][Master] Increases nested objects limit to 25k on Covid Index

---

usaspending_api/etl/elasticsearch_loader_helpers/controller.py
usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py

Added an update to allow for the Spark controller to support a transform_func value of `None`. This same change was added to the non-Spark controller, but was the Spark controller was missed in the original PR for DEV-10427.
Added an update to allow for the Spark controller to support a transform_func value of `None`. This same change was added to the non-Spark controller, but was the Spark controller was missed in the original PR for DEV-10427.
8. [x] Jira Ticket [DEV-10427](https://federal-spending-transparency.atlassian.net/browse/DEV-10427):
```
There isn't currently a …
```

[DEV-10427] Recipient Profile Spark controller update

---

usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py

Add the schema to the `award_search` and `transaction_search` table names in the new SQL.
Add the schema to the `award_search` and `transaction_search` table names in the new SQL.
8. [x] Jira Ticket [DEV-10453](https://federal-spending-transparency.atlassian.net/browse/DEV-10453):
```
No tests need to be updated for this fix.
Matviews are not affected by this change.
The frontend is not impacted by this change.
7. …
```

[DEV-10453] Fix table names in new pre FY2008 SQL

---

usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py

Fix an issue in the recently added Transactions delete code where we weren't iterating over a dictionary correctly and adding it's values to a list.
Fix an issue in the recently added Transactions delete code where we weren't iterating over a dictionary correctly and adding it's values to a list.
8. [x] Jira Ticket [DEV-10453](https://federal-spending-transparency.atlassian.net/browse/DEV-10453):
```
No new tests are required for this fix.
No API endpoints were updated as part of this fix.
No matviews were …
```

[DEV-10453] Fix Spark dictionary error

---

usaspending_api/common/helpers/download_csv_strategies.py
usaspending_api/common/helpers/spark_helpers.py
usaspending_api/etl/management/commands/create_delta_table.py
usaspending_api/etl/management/commands/elasticsearch_indexer_for_spark.py
usaspending_api/etl/management/commands/load_table_to_delta.py
usaspending_api/etl/management/commands/load_zips_from_broker.py

Removed unused imports flagged by flake8. This ticket has not yet been moved to the current sprint. However, I implemented the changes so travis build could proceed to the unit tests where I can see the spark/unit tests that are failing.
Flake8 tests were not passing in Travis due to a list of unused imports across various files. Those unused imports were removed. 
5. [x] Jira Ticket …

[DEV-10804] Removed unused imports flagged by flake8

---

usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
usaspending_api/disaster/v2/views/elasticsearch_account_base.py
usaspending_api/reporting/tests/integration/test_agencies_overview.py
usaspending_api/reporting/v2/views/agencies/overview.py

Updates the `/api/v2/disaster/agency/spending` and `/api/v2/reporting/agencies/overview` endpoints to sort agency names in lowercase when sorting by agency names. This allows agencies like "Department of the Interior" and "Department of the Treasury" to be correctly sorted and not just added to the end of the agencies list.
Updates the `/api/v2/disaster/agency/spending` and `/api/v2/reporting/agencies/overview` endpoints to sort agency names in lowercase when sorting by agency names. This allows agencies like "Department of the Interior" and "Department of the Treasury" to be correctly sorted and not just added to the end of the agencies list.
6. …

[DEV-8150] Fix agency name sorting on agency disaster spending and agencies overview endpoints

---

usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
usaspending_api/disaster/v2/views/agency/spending.py

Updates the `/api/v2/disaster/agency/spending` endpoint to sort the sub-tier agency results by their top-tier agency names in lowercase when sorting by agency names. This allows agencies like "Department of the Interior" and "Department of the Treasury" to be correctly sorted and not just added to the end of the agencies list.
This does **not** sort the child (sub-tier) agency results alphabetically in the results, only the parent (top-tier) agency. We've discussed adding sorting the child results in the same way in the future.
8. [x] Jira Ticket [DEV-8150](https://federal-spending-transparency.atlassian.net/browse/DE …

[DEV-8150] Sort the award spending by sub-agency results alphabetically

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md

Previously the `/spending_by_transaction` endpoint only had `keywords` and `award_type_codes` listed as valid filters even though it supported other filters available in Advanced Search. This fixes this inconsistency by adding documentation about the available filters. 
6. N/A - Data validation completed
8. [x] Jira Ticket [DEV-10768](https://federal-spending-transparency.atlassian.net/browse/DEV-10768):
- N/A - Performance evaluation of affected (API | Script | Download)
- N/A - Before / After data …

[DEV-10768] Adds required filters to spending_by_transaction

---

usaspending_api/accounts/tests/integration/test_federal_account_v2.py
usaspending_api/accounts/views/federal_accounts_v2.py

Update the calculation for the total budgetary resource amount on the `/v2/federal_accounts/` endpoint to use the `is_final_balances_for_fy` column from the submission_attributes table instead of the `final_of_fy` column from the appropriation_account_balances table.
Update the calculation for the total budgetary resource amount on the `/v2/federal_accounts/` endpoint to use the `is_final_balances_for_fy` column from the submission_attributes table instead of the `final_of_fy` column from the appropriation_account_balances table.
8. [x] Jira Ticket [DEV-9234](https://federal-spending-transparency.atlassian.net/browse/ …

[DEV-9234] Use is_final_balances_for_fy instead of final_of_fy for total_budgetary_resources calculations

---

usaspending_api/spending_explorer/v2/filters/spending_filter.py

Use the `latest_transaction_search` field instead of the `latest_transaction` field in spending_filter to reduce the number of joins to the transaction_search table.
Use the `latest_transaction_search` field instead of the `latest_transaction` field in spending_filter to reduce the number of joins to the transaction_search table. Previously, this filter was joining to the `transaction_search` table multiples times through different views and this was causing poor performance. This change uses the `transaction_search` table directly to reduce those JOINs to just one. …

[DEV-9633] Use latest_transaction_search instead of latest_transaction

---

usaspending_api/broker/migrations/0009_add_all_swap_in_new_table_test_steps.py
usaspending_api/search/migrations/0024_partition_transaction_search_pt4_swap_in_partitioned_table.py

The purpose of this PR is to implement a solution that creates a dependency between migrations conditionally. In this solution, the migration 0024 will only depend on the load tracker migrations if neither the 0024 or load tracker migration has ran. This solves the problem of the dependency needing to exist when we run our test suite and the dependency not able to exist when deploying.

PIPE-514; Migration Fix

---

usaspending_api/common/etl/spark.py

Optimizes the covid-19 download generation job.
The job ran in 1h 12m 22s in QAT with these changes. Additionally, this code is shared with the `unlinked_awards` generation job. These changes showed no increase in runtime for that job.
Through my research I was able to determine that coalesce has an issue where if you're calling it using a number smaller than your current number of executors, the number of executors used to process that step will be limited by the number you passed in to the coalesce function.
The repartition function avoids this issue by shuffling the data. I discovered a good rule of thumb, that is, in any scenario where you're reducing the data down to a single partition (or really, less than half your number of executors), you …

[DEV-10806] Optimize Covid Download

---

requirements/requirements-app.txt

The testing suite for the usaspending backend failed to run because the very first test "test_trigger_test_db_setup" that sets up the dbs for testing failed to run. It seemed to be resulting from Django >= 5.*.
Reverted the Django dependency to an older version. 
2. [x] Necessary PR reviewers:
3. [x] Appropriate Operations ticket(s) created
4. [x] Jira Ticket [PIPE-528](https://federal-spending-transparency.atlassian.net/browse/PIPE-528):
```
```

[Pipe-528] Fix for test_trigger_test_db_setup error

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction_count.md
usaspending_api/search/tests/integration/test_elasticsearch_helpers.py
usaspending_api/search/tests/integration/test_spending_by_transaction_count.py
usaspending_api/search/v2/elasticsearch_helper.py
usaspending_api/search/v2/views/search_elasticsearch.py

The `/api/v2/search/spending_by_transaction_count/` only currently supports the keywords filter. It should be updated to support all the filters supported by `/api/v2/search/spending_by_transaction/`. That ask, is implemented by this PR> 
8. [x] Jira Ticket [DEV-10812](https://federal-spending-transparency.atlassian.net/browse/DEV-10812):
3b, 3c, 3d The nature of this work does not require PR reviews from these …

[DEV-10812] Filters in Txn Count Endpoint

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction_count.md
usaspending_api/search/tests/integration/test_spending_by_transaction_count.py
usaspending_api/search/v2/views/search_elasticsearch.py

Removes `award_type_codes` as a required filter on the Spending by Transaction Count endpoint
8. [x] Jira Ticket [DEV-11009](https://federal-spending-transparency.atlassian.net/browse/DEV-11009):
```
```

[DEV-11009] Spending by Transaction Count - Award Type Codes filter requirment

---

usaspending_api/download/tests/integration/test_download_status.py
usaspending_api/download/tests/integration/test_download_transactions.py

This ticket was created to fix some tests that were failing within the travis job `Non-Spark Integration Tests`. The error that was the culprit for many test failures was `Database queries to 'db_download' are not allowed`. 
N/A
5. [x] Jira Ticket [PIPE-529](https://federal-spending-transparency.atlassian.net/browse/PIPE-529):
```
```

[PIPE-529] Database queries to db_download fix

---

Dockerfile

switch to rocky linux

---

usaspending_api/common/query_with_filters.py
usaspending_api/conftest_helpers.py
usaspending_api/disaster/tests/integration/test_disaster_award_amount.py
usaspending_api/disaster/tests/integration/test_disaster_award_count.py
usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
usaspending_api/disaster/v2/views/agency/loans.py
usaspending_api/disaster/v2/views/agency/spending.py
usaspending_api/disaster/v2/views/award/amount.py
usaspending_api/disaster/v2/views/elasticsearch_account_base.py
usaspending_api/disaster/v2/views/elasticsearch_base.py
usaspending_api/disaster/v2/views/federal_account/loans.py
usaspending_api/disaster/v2/views/federal_account/spending.py
usaspending_api/disaster/v2/views/object_class/loans.py
usaspending_api/disaster/v2/views/object_class/spending.py
usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
usaspending_api/etl/elasticsearch_loader_helpers/index_config.py
usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
usaspending_api/etl/es_covid19_faba_template.json
usaspending_api/etl/management/commands/elasticsearch_indexer.py

Reverts fedspendingtransparency/usaspending-api#4094

Revert "[Hotfix] [DEV-10961][QAT] Update the COVID19-FABA Elasticsearch index to be un-nested"

---

.travis.yml
usaspending_api/references/v2/views/filter_tree/psc_filter_tree.py

Certain jobs within out testing suite in travis were having timeout issues where the tests would keep running in the background but Travis would think that the tests may have failed or stalled. This adds a fix for that. Furthermore, certain chunks of code were not passing the codeclimate check due to high complexity, so those were reformatted. 
N/A
5. [x] Jira Ticket [DEV-11022](https://federal-spending-transparency.atlassian.net/browse/DEV-11022):

[DEV-11022] Fix for Travis Timeout Issues

---

usaspending_api/database_scripts/etl/recipient_profile_delta_view.sql
usaspending_api/etl/es_recipient_profile_template.json
usaspending_api/references/tests/integration/test_recipients_autocomplete_v2.py

To support Advanced Search 2.0 we need to support searching for recipients by their DUNS value. Currently only Recipient Name, UEI, and Recipient Level are supported by Elasticsearch, so DUNS was also added. 
4. [x] Jira Ticket [DEV-11100](https://federal-spending-transparency.atlassian.net/browse/DEV-11100):
```
```

[DEV-11100] Add DUNS to recipient profile index in Elastic-search

---

usaspending_api/download/v2/base_download_viewset.py
usaspending_api/routers/replicas.py

Previously, we were randomly choosing between our DB writer instance and the read replicas when choosing a database to use for read operations. This sets the read replicas as the only options for read operations to reduce unnecessary load on the writer instance.
8. [x] Jira Ticket [DEV-11345](https://federal-spending-transparency.atlassian.net/browse/DEV-11345):
```
There are no tests for the application settings.
5. …
```

[DEV-11345] Don't use the DB writer instance for reading [hotfix] [qat]

---

usaspending_api/download/v2/base_download_viewset.py
usaspending_api/routers/replicas.py

Previously, we were randomly choosing between our DB writer instance and the read replicas when choosing a database to use for read operations. This sets the read replicas as the only options for read operations to reduce unnecessary load on the writer instance.
8. [x] Jira Ticket [DEV-11345](https://federal-spending-transparency.atlassian.net/browse/DEV-11345):
```
The …
```

 [DEV-11345] Don't use the DB writer instance for reading [hotfix] [qat]

---

usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
usaspending_api/search/v2/views/spending_by_category_views/spending_by_category.py

Continuing on DEV-11452, the Spending by DEFC endpoint needed additional changes that included logic to ensure that the defc are filtering properly whether or not if the user was searching by transactions or subawards.
A hardcoded filter was added under the `post` method in `spending_by_category.py` that passes the `def_codes` filter with all of the DEFCs.
1. [ ] Necessary PR reviewers:
2. [x] Jira Ticket [DEV-11452](https://federal-spending-transparency.atlassian.net/browse/DEV-11452):
```
No API documentations needed to be updated.
4. Matview impact assessment completed.
No matviews were affected by this change.
5. Frontend impact assessment …
```

[DEV-11452] Update DEFC logic to filter with existing defc filter

---

usaspending_api/transactions/delta_models/summary_state_view.py

A problem was found relating to how data was bound to a fiscal year when calculating total outlays. Instead of using the fiscal year from the File C records, the fiscal year was coming from transactions. This PR reorganizes the queries to calculate the totals and breakdown by year, state, and type and join back to Summary state view based on this rather than using the DUH from Transactions that occurred within a given Fiscal Year.  …

[DEV-11422] Fixes total outlay calculation relating to bound by year

---

usaspending_api/recipient/tests/integration/test_state.py
usaspending_api/recipient/v2/views/states.py

Return all states and set their award count and spending amounts to 0 if no results were found in the previous database query. This is a common case on the first day of a new fiscal year when we don't have any spending for that fiscal year yet.
8. [x] Jira Ticket [DEV-11525](https://federal-spending-transparency.atlassian.net/browse/DEV-11525):
```
7. Appropriate …
```

[DEV-11525] Update recipient states endpoint [hotfix][staging]

---

usaspending_api/api_contracts/contracts/v2/download/count.md
usaspending_api/common/helpers/generic_helper.py
usaspending_api/download/tests/integration/test_download_count.py
usaspending_api/download/v2/download_count.py
usaspending_api/download/v2/urls.py

The changes made in this ticket makes it so that calling the `/api/v2/download/count` endpoint will return the number of records that would be included in a download based on the current spending_level filter (Awards, Transactions, or Subawards), which has a default of transactions. This would allow users to download 3 Awards that have more than 500,000 Transactions, because the endpoint would return 3 in this example regardless of how many Transactions make up those 3 Awards.
7. [x] …

[DEV-11402] Update download count endpoint

---

usaspending_api/api_contracts/contracts/v2/download/awards.md

Adding `def_codes` property to the `Filters` object of the award download api contract.
I used the `DEFC` type.  The filter properties and filter objects seemed to be sorted in roughly alphabetical order, but there were some deviations from alpha ordering, so I put everything in alpha.  The only new lines are line 142 and lines 183-185.
8. [x] Jira Ticket [DEV-10988](https://federal-spending-transparency.atlassian.net/browse/DEV-10988):
```
This is a text change, so the following requirements are not necessary:
5. [ ] Frontend …
```

[DEV-10988] Add def_codes to filter of award download api contract

---

usaspending_api/accounts/tests/integration/test_federal_account_v2.py
usaspending_api/agency/tests/integration/conftest.py
usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
usaspending_api/agency/tests/integration/test_subcomponents.py
usaspending_api/awards/migrations/0108_stage_renamed_park_columns_faba.py
usaspending_api/awards/migrations/0109_delete_old_park_columns_faba.py
usaspending_api/awards/models/financial_accounts_by_awards.py
usaspending_api/common/calculations/file_b.py
usaspending_api/common/tests/integration/test_calculations_for_file_b.py
usaspending_api/database_scripts/job_archive/backfill_renamed_park_fields.py
usaspending_api/disaster/tests/fixtures/disaster_account_data.py
usaspending_api/disaster/tests/fixtures/federal_account_data.py
usaspending_api/disaster/tests/fixtures/object_class_data.py
usaspending_api/etl/submission_loader_helpers/file_b.py
usaspending_api/financial_activities/migrations/0012_stage_renamed_park_columns_fabpaoc.py
usaspending_api/financial_activities/migrations/0013_delete_old_park_columns_fabpaoc.py
usaspending_api/financial_activities/models.py
usaspending_api/references/tests/integration/test_financial_spending.py
usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py

Rename some USAspending fields to match new Broker names.
The changes are pretty straightforward, but the migrations are a little bit involved. The order of events is as follows:
- Run `stage` migrations for both File B and C tables to create the new columns
- Run `backfill` script to populate the new field while minimizing the time that a lock is held
- Run `delete` migrations for both File B and C tables to remove the old columns
Afterwards, an additional step to VACUUM the File B and C tables will be added to the deploy coordination to help reduce bloat.
5. [x] Frontend …

[DEV-11876] Update PARK field names

---

usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
usaspending_api/etl/management/commands/elasticsearch_indexer.py

Convert the `program_activities` JSON data into a dictionary so it can be inserted into the Elasticsearch indices.
8. [x] Jira Ticket [DEV-11489](https://federal-spending-transparency.atlassian.net/browse/DEV-11489):
```
No tests were affected by this change.
No API endpoints were affected by this change.
No matviews were affected by this change.
The frontend was not impacted by this change.
```

[DEV-11489] Convert program activities JSON to dictionary for Elasticsearch indexer

---

Makefile
usaspending_api/database_scripts/job_archive/backfill_renamed_park_fields.py

Fix some formatting of inputs in the Makefile and also removing project imports from Python script.
Some changes were made to the Makefile in an attempt to improve readability, however, this instead broke some aspects of the Makefile.
Additionally, the backfill Python script for PARK fields was updated to include an import from usaspending_api. With how the jobs are run in Jenkins this caused the job to fail even though it succeeds when run locally. The change is to move back to importing via a workaround.
6. [ ] Data validation …

Fix Makefile and remove project imports from python script

---

usaspending_api/database_scripts/etl/subaward_es_view.sql

Fix typo in the Subaward view for Elasticsearch where the `program_activities` column was being pulled from the `award_search` table instead of the `subaward_search` table.

[DEV-11489] Fix typo in Subaward ES view

---

usaspending_api/database_scripts/etl/subaward_es_view.sql

Fix typo in the Subaward view for Elasticsearch where the `program_activities` column was being pulled from the `award_search` table instead of the `subaward_search` table.

[Down merge] Fix typo in Subaward ES view

---

usaspending_api/etl/es_recipient_profile_template.json
usaspending_api/references/tests/integration/test_recipients_autocomplete_v2.py
usaspending_api/references/v2/views/recipients.py

Update the Elasticsearch query used in the recipient autocomplete endpoint.
QAT with old query: 178ms to return more than 10,000 results
QAT with new query: 55ms to return 43 results
8. [x] Jira Ticket [DEV-12006](https://federal-spending-transparency.atlassian.net/browse/DEV-12006):
```
The frontend is not impacted by this …
```

[DEV-12006] Update recipient ES query [hotfix][staging]

---

usaspending_api/common/etl/postgres/operations.py
usaspending_api/common/long_to_terse.py
usaspending_api/etl/es_subaward_template.json
usaspending_api/etl/tests/integration/test_model.py
usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
usaspending_api/search/tests/integration/test_spending_over_time.py
usaspending_api/search/v2/views/spending_over_time.py

Updates spending_over_time to use elasticsearch to query subawards. 
Added similar functionality that awards and transactions is using within spending_over_time. Decided not to consolidate the three methods (query_elasticsearch_for_awards, transactions, and subawards) due to the amount of varied methods names within each method
8. [X] Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123): …

[DEV-11467] subawards elasticsearch spending over time

---

usaspending_api/conftest_helpers.py
usaspending_api/etl/elasticsearch_loader_helpers/controller.py
usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
usaspending_api/etl/management/commands/elasticsearch_indexer.py
usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py

Updating the Elasticsearch loader to calculate the number of slices.
Updating the number of Shards on the Transaction Index caused the incremental load of the Transaction Index to fail due to passing the 500 scroll contexts threshold. This change calculates the number of slices that the Transaction Index should use with the assumption that it is running in parallel with the Award Index, and the maximum value is still set to 500. There are further improvements that could be made, but for now this will keep us from hard coding the value and allow us to build it out further as we look to either change the maximum scroll contexts or increase the Shards on Award index
2. [ ] API …

Calculating the number of slices that should be used for deleting

---

.travis.yml

Pinning the Python patch version used in Travis CI.
There were some build failures due to Travis trying to use Python 3.10.1 instead of a later version.

Pin the Python Patch Version for Travis

---

usaspending_api/common/query_with_filters.py
usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_basic_cases_subaward.py
usaspending_api/search/tests/integration/test_spending_by_award.py

Update the `spending_by_awards` endpoint to search `award_piid_fain` and `subaward_number` when searching by **Award ID** for Subawards.
8. [x] Jira Ticket [DEV-12248](https://federal-spending-transparency.atlassian.net/browse/DEV-12248):
```
The frontend is not impacted by this change.
No operations tickets are required for this …
```

[DEV-12248] Update Award ID query for Subawards [hotfix][staging]

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
usaspending_api/common/helpers/api_helper.py
usaspending_api/common/query_with_filters.py
usaspending_api/common/validator/award_filter.py
usaspending_api/search/tests/integration/test_spending_by_award.py

Adds a filter to `spending_by_award` to allow users to filter their `spending_by_award` query by the unique ID for a given prime award.
No particularly interesting technical details, although this does make a change to the `spending_by_award` API contract.
8. [X] Jira Ticket [DEV-12209](https://federal-spending-transparency.atlassian.net/browse/DEV-12209):
```
- Matview impact assessment completed
Does not impact any Matviews.
- Appropriate Operations ticket(s) created
No data changes are required for this ticket.
- …
```

[DEV-12209] Update spending_by_award to accept new unique_award_id filter

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_award_count.md
usaspending_api/search/tests/integration/test_spending_by_award_count.py
usaspending_api/search/tests/integration/test_spending_by_award_type_count.py
usaspending_api/search/v2/views/spending_by_award_count.py

Updates `spending_by_award_count` endpoint to use Elasticsearch for subawards. 
No particular special details for this ticket.
2. [X] API Documentation updated
8. [X] Jira Ticket [DEV-12208](https://federal-spending-transparency.atlassian.net/browse/DEV-12208):
```
- Matview impact assessment completed
Doesn't impact Matviews
- Frontend impact assessment completed
Doesn't impact frontend
- Appropriate Operations ticket(s) created
No data changes are required for this ticket.
```

[DEV-12208] Update spending_by_award_count to use Elasticsearch

---

usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py

Removing the schema from the dataframe to allow running when Pyspark is not available. 
Pyspark is only available in Databricks and local development. This thus runs into an error when the code is used by a job that doesn't install the dev dependencies. The workaround is to allow pyspark to infer the schema. …

Remove pyspark import and infer schema

---

usaspending_api/api_contracts/contracts/v2/download/count.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_subagency.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/cfda.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/country.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/county.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/defc.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/district.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/federal_account.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_agency.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_subagency.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/naics.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/psc.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient_duns.md
usaspending_api/api_contracts/contracts/v2/search/spending_by_category/state_territory.md

The `recipient_id` filter is currently called out on multiple API contracts. While this filter is available to Awards and Transactions, it is not available for Subawards. This PR updates the contracts where the `recipient_id` filter currently exists to clarify that it is not available for Subawards.
Instead of adding `recipient_id` filter to API contracts where it wasn't currently present, this looks to make sure that the API contracts that currently call it out are correctly specifying that the filter isn't available for Subawards.
5. N/A Frontend impact assessment …

[DEV-11927] Update recipient_id description on API contracts where present

---

usaspending_api/search/v2/views/spending_by_transaction_grouped.py

This is an update to https://github.com/fedspendingtransparency/usaspending-api/pull/4313 to ensure that results are returned with two decimals instead of float.

[DEV-12237] - Spending by transaction grouped decimal

---

usaspending_api/api_contracts/contracts/v2/search/spending_by_award_count.md
usaspending_api/search/tests/integration/test_spending_by_award_count.py
usaspending_api/search/v2/views/spending_by_award_count.py

This allows `/api/v2/search/spending_by_award_count` to accept the spending_level filter 
`spending_level` supports `awards` and `subawards` and is updated similarly to other endpoints that support `spending_level`
8. [x] Jira Ticket [DEV-12349](https://federal-spending-transparency.atlassian.net/browse/DEV-12349):
**Area for explaining above N/A …

[DEV-12349] add spending_level filter

---

usaspending_api/broker/helpers/last_load_date.py
usaspending_api/common/helpers/s3_helpers.py
usaspending_api/etl/elasticsearch_loader_helpers/controller.py
usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
usaspending_api/etl/tests/integration/test_es_deletes_pre_fy2008.py

Fix a bug in our pipeline around the use of the load dates for deleting records from Elasticsearch.
The changes fall into the following buckets:
* Test cases
* Support running these commands locally for test
* Add more verbose logging
* `--verbosity` or (`-v`) is built into the Django command argparse; we simply use it to set our own `verbose` config regardless of verbosity level provided (see [here](https://docs.djangoproject.com/en/5.2/ref/django-admin/#cmdoption-verbosity))
* Cleanup and move around where some items are logged
* Update the ES Deletes to use the new `transaction_fabs` and `transaction_fpds` external load dates since the pipeline is running in Delta now
* Future improvement would be to include the load date names as part of the …

[DEV-12376] Updated ES delete logging and corrected use of pipeline timestamp

---

.github/actions/init-test-environment/action.yaml
.github/actions/run-pytest/action.yaml
.github/workflows/pull-request-checks.yaml
.github/workflows/test-non-spark-integration-signal-handling.yaml
.github/workflows/test-non-spark-integration.yaml
.github/workflows/test-spark-integration-load-to-from-delta.yaml
.github/workflows/test-spark-integration-load-transactions-fabs-fpds.yaml
.github/workflows/test-spark-integration-load-transactions-lookup.yaml
.github/workflows/test-spark-integration-other.yaml
.github/workflows/test-unit-signal-handling.yaml
.github/workflows/test-unit.yaml
usaspending_api/common/logging.py

Update the GitHub workflows to add the `signal_handling` checks previous implemented in Travis. Additionally, change the number of processes depending on the test suite.
The `signal_handling` tests appear to be breaking randomly when run in multiple processes by pytest. While ideally I wanted to avoid having as many runners as the Travis Build, it appears we may need to break out the `signal_handling` tests in order to be consistent build to build, and also keep our performance gains.
Additionally, the value of `num_processes` has been updated to match more closely to what Travis was previously using.
4. N/A Matview …

Adjust num_processes for test suite and add back signal_handling branches

---

usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
usaspending_api/references/v2/views/location_autocomplete.py

The `/api/v2/autocomplete/location` endpoint now applies the `limit` value to each `location_type` instead of to the result as a whole.
8. [x] Jira Ticket [DEV-12478](https://federal-spending-transparency.atlassian.net/browse/DEV-12478):

[DEV-12478] Update location autocomplete to limit by location_type [hotfix][staging]

---

usaspending_api/etl/elasticsearch_loader_helpers/controller.py

This sets the slice count when performing delete_by_query on the Transaction Index to 1.
The Transaction Index currently has 15 shards which means any increase in the slice count will drastically increase the number of queries that it fires off. Previously there was logic that calculated what this slice count should be. The flaw in this logic is that it assumed minimal traffic and only viewed the scroll context as the limiting factor. To get around this the slice count is set to 1 for Transactions …

Set the slice count for deletes on the Transaction Index to 1

---

usaspending_api/database_scripts/etl/location_delta_view.sql

The location_delta_view SQL was checking if the state_code fields were NULL when creating the count_fips value, but then using the county_code fields to build the county FIPS. The SQL has been updated to correctly check if the county_code fields are NULL instead of the state_code fields.
8. [x] Jira Ticket [DEV-12503](https://federal-spending-transparency.atlassian.net/browse/DEV-12503):
```
```

[DEV-12503] Fix typo in county_fips SQL

---

usaspending_api/search/v2/views/spending_by_award.py

When searching on the subaward recipient ID you have the chance of getting a 500 error.
This handles the possible case of the recipient hash and/or level being NULL. 
8. [x] Jira Ticket [DEV-12286](https://federal-spending-transparency.atlassian.net/browse/DEV-12286):
```
```

[DEV-12286] Handle null recipient hash and level

---

usaspending_api/settings.py

Increases download db timeout limit from 4 to 6 hours using `DOWNLOAD_DB_TIMEOUT_IN_HOURS` setting.
8. [x] Jira Ticket [DEV-12578](https://federal-spending-transparency.atlassian.net/browse/DEV-12578):
```
```

[DEV-12578] Increases download db timeout limit from 4 to 6 hours

---

usaspending_api/settings.py

Staging PR for https://github.com/fedspendingtransparency/usaspending-api/pull/4385

[DEV-12578] [Staging] Increases download db timeout limit from 4 to 6 hours

---

usaspending_api/awards/management/commands/generate_unlinked_awards_download.py
usaspending_api/common/etl/spark.py
usaspending_api/disaster/management/commands/generate_covid19_download.py
usaspending_api/etl/management/commands/load_transactions_in_delta.py
usaspending_api/transactions/management/commands/delete_procurement_records.py

The built in python library logging has a logger object with a `warning` method.  There is also a `warn` method that has been deprecated.  The `warn` method is in use in a few places in our code base.
> **warning(msg, *args, **kwargs)**
> Logs a message with level WARNING on this logger. The arguments are interpreted as for debug().
> 
> Note There is an obsolete method warn which is functionally identical to warning. As warn is deprecated, please do not use it - use warning instead.
[logging — Logging facility for Python — Python 3.10.17 documentation](https://docs.python.org/3.10/library/logging.html#logging.Logger.warning)
This PR relates to https://github.com/fedspendingtransparency/usaspending-api/pull/4409, which was originally opened by …

[DEV-12757] - Migrate to modern logger interface

---

usaspending_api/download/tests/integration/test_download_accounts.py
usaspending_api/download/v2/base_download_viewset.py

Removes the experimental header logic that hid Spark downloads for File C.
2. [x] API documentation updated (examples listed below)
2. API UI
3. Comments
3. [ ] Data validation completed (examples listed below)
4. [ ] Appropriate Operations ticket(s) created
5. [x] Jira Ticket(s)
1. [DEV-13183](https://federal-spending-transparency.atlassian.net/browse/DEV-13183)
[DEV-13183]: https://federal-spending-transparency.atlassian.net/browse/DEV-13183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …

[DEV-13183] Enable Spark Download for File C by default

---

usaspending_api/search/tests/integration/test_spending_over_time.py
usaspending_api/search/v2/views/spending_over_time.py

The program activity type should not default to `"PAC/PAN"`.

Update spending_over_time.py to remove type default
