fedspendingtransparency/usaspending-api

- reflected_models.py
> Aj ds 330 first reflection

- fixtures.md
- usaspending_api/accounts/test_accounts.py
- usaspending_api/accounts/urls.py
- usaspending_api/awards/management/commands/loadcontracts.py
- usaspending_api/awards/models.py
- usaspending_api/awards/test_awards.py
Adding some missing test cases
> More tests

- requirements.txt
- usaspending_api/awards/views.py
- usaspending_api/common/api_request_utils.py
- usaspending_api/settings.py
- usaspending_api/submissions/management/commands/load_submission.py
- using_the_api.md
* Supports full text search on single fields
* Support full text search on multiple fields :tada: 
* Sneaking in some CORS fixes
> Full text search

- usaspending_api/common/api_request_utils.py
Changing comparison operators to ensure they work correctly all the time
> Fixing comparison problem

- .gitignore
- README.md
- config/supervisord.conf
- config/uwsgi.ini
- requirements.txt
- usaspending_api/settings.py
Adding /config/ directory for supervisord.conf and uwsgi.ini
Also updating some README, .gitignore, and settings module
> Production configuration

- usaspending_api/references/management/commands/loadtas.py
After inspection, this was the only data loader that was not setting
the data source field.
> Adding Data Source to TAS Model

- README.md
- fixtures.md
I made a few tweaks to the install docs while everything was fresh in my mind. Overall, the project was pretty straightforward to stand up--nice!
> Update install docs

- usaspending_api/awards/views.py
- usaspending_api/common/api_request_utils.py
- using_the_api.md
Adding unique value functionality
* Just throw in a list of fields into `unqiue_values`
* Added some docs
> Unique value functionality  + documentation

- usaspending_api/common/api_request_utils.py
- usaspending_api/references/serializers.py
- usaspending_api/references/urls.py
- usaspending_api/references/views.py
- usaspending_api/submissions/management/commands/load_submission.py
- usaspending_api/urls.py
- using_the_api.md
* Added /references/locations/ endpoint that accepts normal POST requests
* Added /references/locations/geocomplete endpoint that accepts new Geographical hierarchy autocomplete requests (see _using_the_api.md_ as usual for docs)
> Fancy location endpoint

- usaspending_api/common/api_request_utils.py
- using_the_api.md
* Adding new parameter `scope` to autocomplete
* Updated docs
> Adding Scope to GeoComplete

- usaspending_api/common/threaded_data_loader.py
- usaspending_api/references/management/commands/load_reference_csv.py
* Added generic CSV data loader
* Updated reference_fixture.json with RefCitycountyCode data
> Ref city county codes

- usaspending_api/awards/models.py
- usaspending_api/awards/serializers.py
- usaspending_api/common/serializers.py
- usaspending_api/data/testing_data/endpoint_testing_data.json
- usaspending_api/references/models.py
- usaspending_api/references/serializers.py
- using_the_api.md
Added default field limiting and nested_serializer meta
parameterization to Awards/Summary
> Default field limit

- usaspending_api/awards/management/commands/loadcontracts.py
- usaspending_api/settings.py
- usaspending_api/urls.py
Re-add the django debug toolbar now that the team's Windows devs are using an ubuntu VM.
> Re add debug toolbar

- usaspending_api/awards/views.py
- usaspending_api/common/api_request_utils.py
- usaspending_api/references/urls.py
- usaspending_api/references/views.py
- using_the_api.md
* Agency autocomplete endpoint
* Includes upgrades to the autocomplete endpoint to allow returning
matching objects, as well as introducing a “limit” function
> Agency autocomplete update

- README.md
- usaspending_api/awards/test_awards.py
- usaspending_api/awards/test_contracts_load.py
- usaspending_api/awards/test_summary_awards.py
- usaspending_api/common/tests/test_endpoints.py
- usaspending_api/common/tests/test_threaded_data_loader.py
- usaspending_api/common/threaded_data_loader.py
- usaspending_api/financial_activities/test_financial_activities.py
- usaspending_api/references/migrations/0046_update_location_usage_flags.py
- usaspending_api/references/test_agency_loader.py
- usaspending_api/references/test_cfda_loader.py
- usaspending_api/references/test_tas_loader.py
- usaspending_api/submissions/test_load_submission.py
- usaspending_api/submissions/test_submissions.py
This is a simpleminded direct conversion to using py.test; will be followed by more work to take advantage of pytest capabilities
> Initial pytest conversion of Django TestCases

- requirements.txt
- usaspending_api/accounts/views.py
- usaspending_api/awards/views.py
- usaspending_api/common/management/commands/generate_analytics_json_file.py
- usaspending_api/common/mixins.py
- usaspending_api/common/tests/test_drf_tracking.py
- usaspending_api/common/views.py
- usaspending_api/financial_activities/views.py
- usaspending_api/references/views.py
- usaspending_api/settings.py
- usaspending_api/submissions/views.py
* Added drf-tracking app
* Added LoggingMixin to all endpoints _except_ AutoComplete endpoint as
these don’t play nice together. To implement these, we will need to
rework autocomplete into a mixin
* Added `generate_analytics_json_file` which takes a date range
(default of “today”) to dump json-formatted data from the tracking
table
* Added tests for the tracking and reporting
* Updated common views to handle exceptions and return nice responses
with status codes instead of diaf
> Implement DRF tracking+reporting

- usaspending_api/accounts/views.py
- usaspending_api/awards/views.py
- usaspending_api/common/mixins.py
- usaspending_api/common/views.py
- usaspending_api/financial_activities/views.py
- usaspending_api/references/views.py
- usaspending_api/settings.py
- usaspending_api/submissions/views.py
add file logging to events, exceptions, and console
> Extra logging stuff

- usaspending_api/settings.py
Always show debug toolbar if debug is on
> If debug is on, show debug toolbar

- usaspending_api/static_doc_files/css/main.css
- usaspending_api/templates/index.html
- usaspending_api/templates/rest_framework/api.html
This update adds needed padding for the header to display correctly and also locks the hat to the header at the top instead of letting it scroll.
> Style updates to docs

- usaspending_api/common/mixins.py
- usaspending_api/common/serializers.py
After testing these changes look good and improve performance, merging them into the main performance boosting branch
> Testing prefetch -> really-indistinct

- usaspending_api/common/api_request_utils.py
- usaspending_api/common/tests/test_filter_generator.py
This is a second pass at the fix for case insensitive strings. This fixes an issue where the fk traversal check would conflict with lookups.
Added tests for these cases.
> Fix iexact strings

- usaspending_api/awards/models.py
- usaspending_api/etl/helpers.py
- usaspending_api/etl/management/commands/load_usaspending_assistance.py
- usaspending_api/etl/management/commands/load_usaspending_contracts.py
- usaspending_api/settings.py
On the contract file I was benchmarking on (SBA 17 Contracts.csv), this sped the overall load up by 38%.
> Cache locations in memory during contracts load

- usaspending_api/accounts/tests/test_tas_autocomplete.py
- usaspending_api/accounts/urls.py
- usaspending_api/accounts/views.py
- usaspending_api/api_docs/markdown/data_dictionary.md
- usaspending_api/api_docs/markdown/using_the_api.md
- usaspending_api/awards/views.py
- usaspending_api/common/api_request_utils.py
- usaspending_api/common/mixins.py
- usaspending_api/common/views.py
- usaspending_api/references/tests/test_agency_autocomplete.py
- usaspending_api/references/views.py
* Add `AutocompleteView` which moves all of the autocomplete code into drf view friendly structures
* Add `/accounts/tas/autocomplete/` autocomplete
* Adds the ability to use filters on autocompletes (A nice bonus to moving to AutocompleteView!)
* Adds tests
* Updates docs
> Autocomplete tas

- usaspending_api/accounts/tests/test_accounts.py
- usaspending_api/accounts/urls.py
- usaspending_api/accounts/views.py
- usaspending_api/api_docs/markdown/data_dictionary.md
- usaspending_api/data/testing_data/endpoint_testing_data.json
* Added `accounts/tas/balances` for File A
(AppropriationAccountBalances)
* Added `accounts/tas/categories` for File B
(FinancialAccountsByProgramActivityObjectClass)
* Added tests
* Added documentation
> Adding new TAS aggregation endpoints

- requirements/requirements.txt
- usaspending_api/submissions/management/commands/rm_submission.py
- usaspending_api/submissions/tests/test_rm_submission_command.py
* Add `rm_submission` command for devops
* Add tests
> rm submission command

- usaspending_api/common/api_request_utils.py
- usaspending_api/common/tests/test_filter_generator.py
* String search was broken due to not knowing how to traverse reversed
relationships, this fixes that issue
* Added tests to make sure this doesn't break in the future
> [Bug] Fix reverse-fk string search

- usaspending_api/accounts/tests/test_tas_endpoints.py
- usaspending_api/accounts/urls_tas.py
- usaspending_api/accounts/views/tas.py
* Add `/tas/categories/quarters/total/`
* Add tests for said endpoint
> Tas quarterly (categories) totals

- usaspending_api/accounts/tests/test_tas_endpoints.py
- usaspending_api/accounts/urls_tas.py
- usaspending_api/accounts/views/tas.py
* Add `/tas/balances/quarters/total/`
* Add tests for said endpoint
> TAS balances quarters totals

- usaspending_api/etl/management/commands/load_submission.py
Turning off cached loading proved to be really simple.
Note that this is a PR *against the misc-submission branch*, not against dev.
> Disabling cached bulk loading for File C records

- data_reformatting.md
Adding Kristine's notes about changing the signs for display.
> Add data formatting note about changing the signs for display

- usaspending_api/common/models.py
- usaspending_api/routers/replicas.py
* RequestCatalog only reads from the source database
* RequestCatalog doesn't update it's access time every time
> RequestCatalog Deployment Changes

- usaspending_api/api_docs/markdown/api_tutorial.md
- usaspending_api/api_docs/markdown/data_dictionary.md
- usaspending_api/api_docs/markdown/endpoints.md
- usaspending_api/api_docs/markdown/landing_page.md
- usaspending_api/api_docs/markdown/request_recipes.md
- usaspending_api/api_docs/markdown/using_the_api.md
- usaspending_api/templates/index.html
- usaspending_api/templates/plate.html
- usaspending_api/templates/rest_framework/api.html
Bring recent hotfixes back down to dev (this branch fixes a merge conflict on the endpoints table in the API docs).
> Dev stable --> dev

- usaspending_api/accounts/migrations/0004_auto_20170512_2013.py
- usaspending_api/accounts/models.py
- usaspending_api/references/management/commands/loadtas.py
This should fix the TAS migration problem we're seeing in dev
> Fixing tas migration

- usaspending_api/references/tests/test_agency_v2.py
- usaspending_api/references/urls_v2.py
- usaspending_api/references/views_v2.py
> Agency endpoint

- usaspending_api/api_docs/markdown/endpoints.md
> Fixed targets of some v2 endpoint links in doc

- usaspending_api/accounts/models.py
- usaspending_api/references/reference_helpers.py
Reverts fedspendingtransparency/usaspending-api#422
> Revert "Backend Hotfix: Dev stable -> dev"

- usaspending_api/references/tests/test_naics_autocomplete_v2.py
- usaspending_api/references/urls_autocomplete.py
- usaspending_api/references/views_v2/autocomplete.py
https://federal-spending-transparency.atlassian.net/browse/DS-1340
Gist reviewed by ( @ejgullo ):
> NAICS endpoint and test

- usaspending_api/references/v2/views/toptier_agencies.py
Gist to be approved by frontend ( @ebdabbs ):
> DS-1429: Adding sort and order options for /v2/references/toptier_agencies endpoint

- usaspending_api/awards/tests/test_award_spending.py
- usaspending_api/awards/v2/views/award_spending.py
Updated code to filter for all categories if not entered by user.
@kevinli-work
> award_spending_recipient

- usaspending_api/references/tests/test_recipient_autocomplete_v2.py
- usaspending_api/references/v2/views/autocomplete.py
Inadvertently created and submitted a pull request on a branch that already exists.
Reverted back to TriGramSimilarity. Able to get complete results with few characters and multiple string entries. Excess brackets removed. Tests complete.
Added exact_match calculation to improve results. Limit filter applied to results. parent_recipient_unique_id, and recipient_unique_id included in both result fields for TriGramSimilarity search
@kevinli-work
> recipient_autocomplete_trigram

- usaspending_api/accounts/serializers.py
- usaspending_api/accounts/views/financial_spending.py
- usaspending_api/common/helpers.py
- usaspending_api/common/tests/test_helpers.py
- usaspending_api/references/models.py
- usaspending_api/references/tests/test_financial_spending.py
- usaspending_api/search/tests/test_spending_by_category.py
- usaspending_api/search/v2/urls_search.py
- usaspending_api/search/v2/views/search.py
When the major object class is 00, the v2/references/agency endpoint reports the major object class name as "Unknown Object Type", regardless of what's in the database.
See DS-1602: https://federal-spending-transparency.atlassian.net/browse/DS-1602
> Feature unknown object class ds 1602

- usaspending_api/etl/management/load_base.py
- usaspending_api/etl/subaward_etl.py
Reverts fedspendingtransparency/usaspending-api#538
> Revert "codeclimate"

- usaspending_api/accounts/tests/test_federal_account_object_class_v2.py
- usaspending_api/accounts/views/federal_accounts_v2.py
- Updates available object class endpoint to remove integer conversion of major and minor object  class codes. 
- Update automated test to adjust for changes.
Updated Gist: https://gist.github.com/shinson/9638d5a2c8fa40dd5949d0e29d3d6e9a
> Removing integer conversion from ids, updated object class unit test

- usaspending_api/awards/v2/filters/award.py
- usaspending_api/awards/v2/filters/transaction.py
Fixing orqueryset's for both transaction and award filters. Primarily fixes bug found for spending-by-award-count.
> Or queryset fix award/transaction filters

- usaspending_api/etl/management/commands/load_submission.py
> add --nosubawards to load_submission 

- usaspending_api/broker/management/commands/update_awarding_agencies.py
- usaspending_api/broker/tests/test_update_awarding_agencies.py
Script to add awarding agency and funding agency mapping to Transactions Normalized and Awards
-DS story: DS-1659
> Awarding agency cleanup script

- usaspending_api/awards/tests/test_award_spending.py
Updating dev stable to fix award spending tests
> Adding action date to award spending tests

- usaspending_api/search/v2/views/search.py
* Award count should be `loans` not `loanss`
> Hotfix award count loanss second try

- usaspending_api/awards/v2/views/award_spending.py
Adding `Insurance` Awards under Other tab in the Recipient Section of the Agency page
> Hotfix Agency Page Recipient Section

- usaspending_api/awards/tests/test_v2_filters_awards.py
- usaspending_api/awards/v2/filters/award.py
- usaspending_api/awards/v2/filters/transaction.py
- usaspending_api/search/v2/views/search.py
- Populates awards table for situations where period_of_performance dates aren't provided
- Populates awards that only use a URI as the identifier
> Hotfixes for Awards Table

- usaspending_api/search/v2/views/search.py
> Hotfix spending by award performance

- usaspending_api/search/v2/views/search.py
- Resolving performance Issues
> Spending by category: Agency and Funding Agency

- usaspending_api/accounts/views/federal_accounts_v2.py
- usaspending_api/awards/v2/views/awards.py
- usaspending_api/common/views.py
- usaspending_api/references/v1/views.py
- usaspending_api/references/v2/views/agency.py
- usaspending_api/references/v2/views/autocomplete.py
- usaspending_api/references/v2/views/toptier_agencies.py
- usaspending_api/search/v2/views/search.py
- usaspending_api/spending_explorer/v2/views/spending_explorer.py
> cache hotfix --> dev-stable

- usaspending_api/common/cache.py
> [DS-1784] Ignore auditrail for caching

- usaspending_api/bulk_download/v2/views.py
- usaspending_api/download/v2/download_column_historical_lookups.py
- Adding Exec Comp Legal Entity Officer columns to Subawards
- Adding additional IDV filtering for just contracts
- Fixing minor typo for column mappings
> Hotfix: Bulk Download Exec Comp IDV fixes

- usaspending_api/awards/v2/filters/award.py
- usaspending_api/awards/v2/filters/matview_transaction.py
- usaspending_api/search/v2/views/search.py
Resolving IDV query logic to get the correct result set and consequently help performance
> Hotfix: Resolve IDV contract query logic

- usaspending_api/awards/models_matviews.py
- usaspending_api/awards/v2/filters/award.py
- usaspending_api/awards/v2/filters/matview_transaction.py
- usaspending_api/awards/v2/filters/transaction.py
- Updating recipient filter to use the exact text sent instead of a list of `legal_entity` IDs
> Recipient Filter Update

- usaspending_api/awards/management/commands/fix_missing_agencies.py
- Using a matview with indexes at the beginning so we can clear out a lot of the joining
> Speeding up agency code SQL queries

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
Only getting active and deletion records to update with
> HOTFIX: Fix which fabs records we're getting from the broker

- usaspending_api/awards/migrations/0011_upper_index_awards.py
- usaspending_api/awards/migrations/0012_upper_index_fain_uri_awards.py
Fixing migrations so the indexes are actually created
> Hotfix migration fixes

- usaspending_api/awards/v2/filters/matview_award.py
- usaspending_api/awards/v2/filters/matview_transaction.py
- usaspending_api/broker/management/commands/fabs_nightly_loader.py
Adding changes that would have been overwritten by merging dev-stable into dev in order to resolve conflicts
> Fixing dev-stable conflicts into dev

- usaspending_api/awards/v2/filters/award.py
- usaspending_api/awards/v2/filters/matview_award.py
- usaspending_api/awards/v2/filters/matview_transaction.py
- usaspending_api/awards/v2/filters/transaction.py
- usaspending_api/search/v2/views/search.py
Reverts fedspendingtransparency/usaspending-api#794
> Revert "Converting Award ID filters from database ID to text filters"

- usaspending_api/awards/models_matviews.py
- usaspending_api/awards/v2/filters/matview_transaction.py
- usaspending_api/awards/v2/filters/view_selector.py
- Also contains a requested hotfix for improving award type filters by including IDV.
> Hotfix for syncing the matview columns with the django models

- usaspending_api/awards/models_matviews.py
- usaspending_api/awards/v2/filters/filter_helpers.py
- usaspending_api/awards/v2/filters/view_selector.py
- usaspending_api/database_scripts/matviews/universal_award_matview.sql
- usaspending_api/search/v2/views/search.py
- Added ability to use summaryTransactionMonthView when award amounts match enum limits
- Fixed misspelled model names
- Removed the old cols from models so they can be removed from matviews' create SQL next sprint
- Fixed index SQL syntax errors
> Step 2 of col rename process and fixed minor matview issues

- usaspending_api/bulk_download/v2/views.py
- Including 'all' functionality for list monthly downloads endpoint
- Including 'type' in list monthly downloads endpoint
> Hotfix: list monthly downloads endpoint api updates

- usaspending_api/bulk_download/filestreaming/csv_selection.py
- usaspending_api/bulk_download/management/commands/populate_monthly_files.py
- usaspending_api/bulk_download/v2/views.py
Fixes bug where if someone submits the same Bulk Download requested earlier that day, it will refer to that instead of processing a new one.
> Cached bulk downloads

- usaspending_api/awards/v2/filters/location_filter_geocode.py
Includes hotfix to search for congressional and county codes as floats
> Congressional Code Fix

- usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
- usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
- usaspending_api/database_scripts/matviews/summary_transaction_month_view.sql
- usaspending_api/database_scripts/matviews/summary_transaction_view.sql
Previous hotfix did not catch the typo everywhere in the files
> HOTFIX Fixed group by cols to include country_name

- usaspending_api/broker/management/commands/fix_file_b_c_mappings.py
-Adding additional field based on test cases: `ussgl488100_upward_adjust_pri_undeliv_order_oblig_unpaid_cpe`
-Added additional code to automate updating the website tables in case of additional columns need to be added
-Fix improper naming of file_b and file_c corresponding tables in website
DS-Story: https://federal-spending-transparency.atlassian.net/browse/DEV-84
> Hotfix DEV-84, adding additional column

- usaspending_api/etl/management/commands/update_file_c_file_d_awards_sql.py
Added copy of script to dev-stable as instructed
> adding script to dev-stable

- usaspending_api/bulk_download/v2/views.py
- Tested locally
- Refers to previous merged in [PR](https://github.com/fedspendingtransparency/usaspending-api/pull/913)
> Bugfix: List agencies bugfix typo

- usaspending_api/broker/management/commands/load_fsrs.py
Updating subaward loader's compilation of generated_unique_award_id to include missing underscores
> Hotfix: Updating subaward loader

- usaspending_api/bulk_download/v2/views.py
- usaspending_api/search/v2/elasticsearch_helper.py
-Improve query performance & add functionality for other columns in function. 
-Remove unused functions
-Clear scroll
> Hotfix kws babydownload

- usaspending_api/broker/management/commands/load_fsrs.py
- usaspending_api/broker/management/sql/load_constraints.sql
Fixing creation of subaward locations so that references can be established. Updated load_constraints to properly handle cascaded deletes in Django.
> Hotfix: Subaward Loader & Bulk SQL Constraints Creation

- usaspending_api/broker/management/commands/load_exec_comp.py
Adding new nightly exec comp loader which reloads ALL exec comp data (currently faster than legacy loader)
> Hotfix: New exec comp nightly loader

- usaspending_api/settings.py
Fix merge conflict on `TRANSACTIONS_INDEX_ROOT` in `settings.py`
> Hotfix: Correct merge conflict

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
- usaspending_api/broker/management/commands/fpds_nightly_loader.py
Updating loaders to set the award's piid, fain, uri appropriately when creating a new award
> Hotfix: Properly set Award ID

- .codeclimate.yml
- README.md
Changing threshold might reduce the number of issues reported. Setting python to version 3 may or may not improve the issue reports.
Also corrected the Postgres version in the README
> Added additional code climate config Radon params

- usaspending_api/database_scripts/etl/drop_view.sql
Useful for running at the end of the ES etl process
> Added new SQL file to drop the view

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
**High level description**:
Fixing fabs nightly deletions again
**Technical details**:
Uppercasing the identifier so it always matches what we're looking for
**Link to JIRA Ticket**:
N/A
**The following are ALL required for the PR to be merged**:
> Hotfix fabs nightly deletions master

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
**High level description**:
Fixing fabs nightly deletions again
**Technical details**:
Uppercasing the identifier so it always matches what we're looking for
**Link to JIRA Ticket**:
N/A
**The following are ALL required for the PR to be merged**:
> Hotfix fabs nightly deletions staging

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
- usaspending_api/broker/management/commands/fpds_nightly_loader.py
- usaspending_api/broker/management/commands/update_awards.py
Fixing timer importing
See Above
N/A
> Bugfix fix timer import

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
Fixing the nightly loader for real
Removing entries from an array while looping over it causes problems. We no longer do this.
N/A
> Bugfix fabs nightly loader

- usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
- usaspending_api/search/v2/elasticsearch_helper.py
This changes the es_query so the raw fields will be included in the query.
> Updating query to search for additional raw fields

- usaspending_api/api_docs/markdown/data_dictionary.md
- usaspending_api/api_docs/markdown/endpoints.md
- usaspending_api/api_docs/markdown/landing_page.md
- usaspending_api/api_docs/markdown/using_the_api.md
Remove the Request Recipes page from the landing page.
Remove all links to the page.
NA
- NA Matview impact assessment completed
- NA Frontend impact assessment completed
- NA Data validation completed
- NA API Performance evaluation completed and present:
```
Timing changes:
Before = X seconds
After = Y seconds
Data volume changes:
Before = X rows
After = Y rows
> remove request recipes

- usaspending_api/database_scripts/etl/transaction_delta_view.sql
- usaspending_api/etl/es_etl_helpers.py
Fixed parsing problem with deleted transaction CSV files on S3. Changed the generated_transaction ID string to always be uppercase
Swapped out one pandas dataframe function to another for ingesting CSV to dataframe. Added simple uppercase functions to SQL view and S3 CSV parser
<None>
> Minor Bugfix for Elasticsearch ETL script

- usaspending_api/api_docs/markdown/endpoints.md
One link was broken
The paragraph the link was in was more v1 focused, so the whole paragraph was removed
NA
- NA Matview impact assessment completed
- NA Frontend impact assessment completed
- NA Data validation completed
- NA API Performance evaluation completed and present:
```
Timing changes:
Before = X seconds
After = Y seconds
Data volume changes:
Before = X rows
After = Y rows
> Update docs links

- usaspending_api/download/filestreaming/csv_generation.py
Python typo to fix the award search
See high level description
Immediate Hotfix
- NA Matview impact assessment completed
- NA Frontend impact assessment completed
- NA [ ] Data validation completed
- NA [ ] API Performance evaluation completed and present
> Hotfix: Award Search Limit

- usaspending_api/download/filestreaming/csv_generation.py
> Promote Staging to Master

- usaspending_api/download/filestreaming/csv_generation.py
Speeding up the download process for small downloads which should take less than 10 minutes.
Setting the wait time to update the visibility count from 60 seconds to 5 seconds.
N/A
> Hotfix: Small Download Speedup 

- usaspending_api/broker/management/commands/load_fsrs.py
This reverts commit 7f0d13408627a658c6884bc23e08a049c1d74abf.
> Revert "Logs for testing"

- usaspending_api/awards/v2/filters/sub_award.py
Altering null checks to happen on field named in the relationship between models vs the raw field name in the database.
Altering is_null checks to happen on the relationship instead of the ID fields.
(N/A)
>  Hotfix: Fixing Django style null relationship checks

- usaspending_api/awards/v2/filters/sub_award.py
Reverting changes and resolving `is_null` to be `isnull`
Reverting changes and resolving `is_null` to be `isnull`
(N/A)
> Hotfix: Reverting changes and resolving `is_null` to be `isnull`

- usaspending_api/database_scripts/etl/transaction_delta_view.sql
- usaspending_api/search/v2/elasticsearch_helper.py
Updating Elasticsearch delta SQL to pull loan specific fields from the correct source in order help display correct data.
Updating which matview "original_loan_subsidy_cost" and "face_value_loan_guarantee" are pulled from for the ES delta SQL. Also fixed quoting style to match proper format for docstrings.
[DEV-627](https://federal-spending-transparency.atlassian.net/browse/DEV-627)
> Hotfix: Update ES Delta SQL

- usaspending_api/etl/es_transaction_template.json
Again, change you asked for @miahunsicker
> changing the template here

- usaspending_api/download/filestreaming/csv_generation.py
Compress all csv downloads.
Using ZipFile to use deflated compression instead of stored.
[DEV-636](https://federal-spending-transparency.atlassian.net/browse/DEV-636)
> Compress Download Zips

- usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award.md
- usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award_count.md
- usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_geography.md
- usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_transaction.md
- usaspending_api/api_docs/api_documentation/advanced_award_search/spending_over_time.md
- usaspending_api/api_docs/api_documentation/advanced_award_search/transaction_spending_summary.md
- usaspending_api/api_docs/api_documentation/download/advanced_search_award_download.md
- usaspending_api/api_docs/api_documentation/download/advanced_search_transaction_download.md
- usaspending_api/api_docs/api_documentation/download/download_count.md
- usaspending_api/api_docs/api_documentation/search_filters.md
Simply importing the Search Filters documentation to this repo.
- Moved the file to the repo
- Updated it's section on award IDs to keep it up to date
- Updated links to point to this file instead
(N/A)
> Moving Search Filters from Wiki to Repo

- usaspending_api/download/v2/download_column_historical_lookups.py
Adding total loan value to downloads
Adding `total_loan_value` to download mapping dictionaries.
N/A
- Verified with local downloads that `total_loan_value` is populated in CSV artifacts
> Adding total loan value to downloads

- usaspending_api/common/logging.py
Updating the timestamp to match Kibana dashboard.
switching data and month in date formatting
N/A
- Matview impact assessment completed (N/A)
- Data validation completed (N/A)
- API Performance evaluation completed and present (N/A)
> Switching day and month to match Kibana

- usaspending_api/awards/v2/filters/sub_award.py
Improving the subaward filters matching the spreadsheet provided with the JIRA ticket.
* Commenting out NAICS as that correspondence hasn't been established with Subawards (see comment on [DEV-670](https://federal-spending-transparency.atlassian.net/browse/DEV-670))
* Matching CFDA program appropriately
* Adding `subaward_number` to Keyword and Award ID filters
Main task: [DEV-670](https://federal-spending-transparency.atlassian.net/browse/DEV-670)
Backend: [DEV-671](https://federal-spending-transparency.atlassian.net/browse/DEV-671)
- Matview impact assessment completed (N/A)
- API Performance evaluation …
> Bugfix: Subaward Filters

- usaspending_api/etl/management/commands/update_total_funding_amount_sql.py
Updating logs to include elapsed time
Updating logs to include elapsed time. Included more appropriate naming for SQL variables.
N/A
> Updating logs to include elapsed time

- usaspending_api/awards/v2/lookups/lookups.py
Mappings should match the field names posted in [this JIRA ticket](https://federal-spending-transparency.atlassian.net/browse/DEV-692).
> Update Subaward mappings to match frontend mockups

- usaspending_api/etl/es_etl_helpers.py
- usaspending_api/etl/management/commands/es_rapidloader.py
Fixes a few superficial issues related to logging to improve accuracy and transparency of ElasticSearch indexing processes
-Adds a refresh=True flag to the client.delete_by_query call so that the shards refresh instantly allowing the logs to reflect what actually happened
- Fixes a help comment for one of the management command arguments
- Adds an exit status of 1 to the output of a guard dog failure so that Jenkins will catch it
[DEV-683] (https://federal-spending-transparency.atlassian.net/browse/DEV-683)
> ES adding refresh flag fixing comment fixing system exit

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
- usaspending_api/broker/management/commands/fpds_nightly_loader.py
Correctly identifying which awards to delete/update.
* Making deletes and adding awards atomic individually
* Correctly identifying which awards to delete/update: awards who will have *all* their transactions deleted will be deleted as well, otherwise the award will be updated.
N/A
- * Matview impact assessment completed
- * Frontend impact assessment completed  (N/A)
- * API Performance evaluation completed (N/A)
> Hotfix: Nightly Load Delete Updates

- usaspending_api/awards/v2/lookups/matview_lookups.py
Resolving concatenation of dictionaries to support proper updates to the lookup values.
Fixing matview lookup dictionaries to update to combine with defaults instead of overwriting.
(N/A)
- Original bug showed "Recipient Name" wasn't being populated in the response. New response has the name correctly.
>  Hotfix: Matview lookup fix

- requirements/requirements.txt
- usaspending_api/accounts/tests/test_federal_account_fy_snapshot_v2.py
Updating model mommy version
Updating model mommy version to the latest available
(N/A)
> Updating model mommy version

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
Add `agency_id` to the Contracts delta file and update mapping from `award_sub_agency_id` to `agency_id`.
_Same as above._
[DEV-911](https://federal-spending-transparency.atlassian.net/browse/DEV-911)
Related: [DEV-813](https://federal-spending-transparency.atlassian.net/browse/DEV-813)
> Hotfix: Update delta files script

- usaspending_api/bulk_download/config/supervisord.conf
[DEV-1016](https://federal-spending-transparency.atlassian.net/browse/DEV-1016)
> Adding line to supervisord log

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
- Switch the logic for the `correction_delete_ind` field.
- Do not include deletions from the morning the previous file was created.
> Hotfix: Update Award Data Delta files correction_delete_ind 

- usaspending_api/download/filestreaming/csv_generation.py
Requested by the Operations team for whenever downloads fail.
> Extra SQL Log for Download Exceptions

- usaspending_api/database_scripts/etl/transaction_delta_view.sql
- usaspending_api/database_scripts/matview_generator/summary_state_view.json
This will fix the Jenkins nightly pipeline error encountered during the last attempt to run the pipeline
> Applying Hotfix from Staging to Master 

- docker-compose.yml
Changed the version in docker-compose.yml to 10.3
> upgrade postgres version in compose

- usaspending_api/recipient/v2/views/states.py
Added missing cache decorator to State Profile Endpoints
None
(N/A)
> Dev Hotfix: Adding cache decorator to State Profile endpoints

- usaspending_api/download/filestreaming/csv_generation.py
Fixing settings variable reference
Fixing settings variable reference
(N/A)
> Fixing AWS region var reference

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
Fix issue in populate_monthly_files:
```missing 1 required positional argument: 'agency_id'```
> Hotfix populate_monthly_delta_files

- usaspending_api/database_scripts/matviews/functions_and_enums.sql
Do not merge until #1345 is merged.
> Reverting changes committed from conflict resolution on github

- requirements/requirements.txt
Switched repo for django-mock-queries, the fedspendingtransparency is the project's maintained version
None
(N/A)
> Use fedspendingtransparency django-mock-queries repo for module

- usaspending_api/recipient/tests/integration/test_recipient.py
- usaspending_api/recipient/v2/views/recipients.py
Accounting for situations where:
* The parent DUNS listed in transactions is not provided in SAM or transaction data
* A child DUNS listed in Recipient Profile affiliations is not found.
See high level description
(N/A)
-  Matview impact assessment completed
- API Performance evaluation completed
> Recipient Profile Dev Bugfixes

- usaspending_api/etl/management/commands/load_submission.py
One hotfix to `master` created a merge conflict with `stg` so I branched from `stg` and locally merged origin/master into this branch.
> Safe downmerge with conflicts from "master" -> staging

- usaspending_api/recipient/management/sql/restock_recipient_profile.sql
Previously, only recipients which had activity within the previous 12 months were listed and searchable in the Recipient landing page
Added two more "steps" in the SQL script which is intended to be run on a nightly basis
N/A
Overall, the SQL script takes approximately 17 minutes to complete and must be run if the materialized view have been updated
> Adding Recipients which do not have activity in previous 12 months to landing page 

- usaspending_api/broker/management/sql/restock_subawards.sql
Removed one unnecessary line and renamed filename to match similar sql scripts naming convention in dev
N/A
N/A
> Edit to recent hotfix into staging

- usaspending_api/conftest.py
- usaspending_api/search/tests/unit/test_spending_by_category.py
- usaspending_api/search/v2/views/spending_by_category.py
8. [x] Jira Ticket [DEV-1109](https://federal-spending-transparency.atlassian.net/browse/DEV-1109):
**Area for …
> Added NAICS description lookup to spending_by_category

- usaspending_api/broker/management/commands/fpds_nightly_loader.py
- usaspending_api/common/helpers/generic_helper.py
- usaspending_api/common/tests/test_helpers.py
8. [x] Jira Ticket [DEV-1616](https://federal-spending-transparency.atlassian.net/browse/DEV-1616):
**Area for …
> Hotfix/FPDS incremental ETL script

- .pyup.yml
- requirements/requirements.txt
Minor security vulnerability by having the older version of requests in the python environment
Upgraded `requests` to 2.20.0 based on a Github security scan. also tweaked the .pyup.io file to hopefully work since the current file seems to break pyup.io scanners
8. [x] Jira Ticket  (N/A)
```
Minor edits to library version and config file, no code changes to require more …
```
> Updated requests version and tweaked pyup file

- usaspending_api/etl/award_helpers.py
8. [x] Jira Ticket [DEV-1891](https://federal-spending-transparency.atlassian.net/browse/DEV-1891):
```
Changes to ETL helper function.
No API behavior changed
```
> [Bug Sprint] [DEV-1891] update award category to the latest transaction's type

- requirements/requirements.txt
Updating urllib3 to the latest version
None
```
No code changes, only a Python (dependency?) library being updated
```
> Updating urllib3 to newest version

- usaspending_api/api_docs/api_documentation/awards/idvs/amounts.md
- usaspending_api/awards/serializers_v2/serializers.py
- usaspending_api/awards/tests/test_awards_v2.py
- usaspending_api/awards/v2/urls_awards.py
- usaspending_api/awards/v2/views/awards.py
- usaspending_api/core/validator/tinyshield.py
Add new IDV counts and sums to a new API endpoint `/api/v2/awards/idvs/amounts/<award id>/`.
Created a new URL route, view, serializer, and tests.
* No materialized views were harmed in the making of this pull request
* I don't *THINK* there any data validation that needs to occur.
* No operations ticket needed
8. [X] Jira Ticket [DEV-1997](https://federal-spending-transparency.atlassian.net/browse/DEV-1997):
- No data was altered (read only)
> DEV-1934/DEV-1997: Add new IDV counts and sums to a new API endpoint

- usaspending_api/awards/serializers_v2/serializers.py
- usaspending_api/awards/tests/test_awards_idv_v2.py
Changed IDV results to include new ParentIDV award object as `parent_award1`
`parent_award_func` function was added to the IDV serializer
3. [x] Necessary PR reviewers: 
8. [x] Jira Ticket [DEV-1801](https://federal-spending-transparency.atlassian.net/browse/DEV-1801): (N/A)
```
Changes are required for front-end ASAP
Actions specified: 
- New object to the IDV response (ParentIDV)
- Update broken tests
```
> Updated IDV results for current dev implementation

- usaspending_api/database_scripts/populate_awards_idv_columns/populate_awards_idv_columns.py
Fix for backfill script in support of DEV-2000.
There was a bug in the original load query.
7. [X] Appropriate Operations ticket(s) created [OPS-494](https://federal-spending-transparency.atlassian.net/browse/OPS-494)
8. [X] Jira Ticket [DEV-2000](https://federal-spending-transparency.atlassian.net/browse/DEV-2000):
```
1. Tests are part of the code created in the parent ticket.
2. Does not affect the API directly.
3. Only backend is affected.
4. None …
```
> DEV-1916/DEV-2000/OPS-494: Backfill IDV Awards columns (fix)

- requirements/requirements.txt
Use the latest Django v1.11.x to stay abreast of security patches
https://docs.djangoproject.com/en/2.1/releases/1.11.18/
https://docs.djangoproject.com/en/2.1/releases/1.11.17/
https://docs.djangoproject.com/en/2.1/releases/1.11.16/
```
No code changes, this is strictly a dependency version change.
Deploy scripts will handle the new package version …
```
> Update Django minor version to stay up-to-date

- usaspending_api/broker/management/commands/fpds_nightly_loader.py
FK constraints needed to be addressed during the FPDS nightly pipeline script
For deleted awards, set `parent_award_id` to `null` when the value is a soon-to-be deleted award id and remove the row in `parent_award` when `award_id` is a soon-to-be deleted award id
```
Operations script hotfix PR
```
> Account for deleted awards in parent_award table

- usaspending_api/broker/management/commands/fpds_nightly_loader.py
- usaspending_api/database_scripts/populate_awards_idv_columns/populate_awards_idv_columns.py
Fix for pipeline break related to new `parent_award` table
> Sprint 74 Deploy Stg -> Master (fix)

- usaspending_api/api_contracts/contracts/award/idv/Funding.md
- usaspending_api/awards/tests/test_awards_idvs_amounts_v2.py
- usaspending_api/awards/tests/test_awards_idvs_funding_v2.py
- usaspending_api/awards/v2/urls_idv_awards.py
- usaspending_api/awards/v2/views/idvs/awards.py
- usaspending_api/awards/v2/views/idvs/funding.py
- usaspending_api/awards/v2/views/transactions.py
- usaspending_api/common/helpers/sql_helpers.py
- usaspending_api/common/tests/test_sql_helpers.py
- usaspending_api/core/validator/pagination.py
- usaspending_api/etl/broker_etl_helpers.py
Provide File C funding data for IDV award descendant contracts.
Endpoint `/api/v2/awards/idvs/funding/`.
7. [X] No Operations ticket(s) required
8. [X] Jira Ticket [DEV-1896](https://federal-spending-transparency.atlassian.net/browse/DEV-1896):
> DEV-1896/DEV-2144/DEV-2145: Add new IDV funding endpoint

- .github/CODEOWNERS
Initial CODEOWNERS had a few mistakes
N/A
```
Small github config file change
```
> Modifications to CODEOWNERS after first test 

- usaspending_api/api_docs/api_documentation/awards/idvs/awards.md
- usaspending_api/awards/tests/test_awards_idv_v2.py
- usaspending_api/awards/tests/test_awards_idvs_awards_v2.py
- usaspending_api/awards/tests/test_awards_v2.py
- usaspending_api/awards/v2/data_layer/orm.py
- usaspending_api/awards/v2/views/idvs/amounts.py
- usaspending_api/awards/v2/views/idvs/awards.py
- usaspending_api/awards/v2/views/idvs/funding.py
- usaspending_api/awards/v2/views/transactions.py
- usaspending_api/common/recipient_lookups.py
- usaspending_api/core/validator/award.py
- usaspending_api/core/validator/tests/unit/test_award.py
Fixes for TinyShield usage and /v2/awards/ response
> Downmerge `stg` -> `dev` with resolved merge conflicts

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
- usaspending_api/etl/management/commands/es_rapidloader.py
Fixing broken imports introduced in a previous PR
New CSV file line count function was moved and improved, changes were not applied everywhere.
```
Fixing broken Python imports, no additional behavior is desired
```
> fixing broken imports

- usaspending_api/awards/management/sql/restock_parent_award.sql
This was previously completed for Python files. Run on SQL for consistency
There are no differences for results
```
Trivial SQL change
```
> Replace `IDV\_%` with `IDV%` in searches

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
- usaspending_api/download/management/commands/populate_monthly_files.py
> Staging -> dev

- README.md
To reflect information obtained on Slack. I haven't confirmed that doing these steps actually created the views for me, so this may need further updates.
7. [ ] Appropriate Operations …
> Adding steps for materialized views

- README.md
Updated README.md to have more clear/better instructions on how to setup the API with a virtual python environment
NONE
```
```
> Doc/usa spending api updated README with better instructions

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
Fixes a regression introduced during DEV-1904 where incremental updates were becoming full refreshes due to a missed filter check.
1. [X] No unit tests for this code (although wouldn't it have been awesome if there were)
2. [X] API documentation unaffected
5. [X] Front end unaffected
7. [X] No Operations ticket required
8. [X] Jira Ticket [DEV-1904](https://federal-spending-transparency.atlassian.net/browse/DEV-1904):
> Hotfix for another regression added during DEV-1904

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
Contents from S3 were not being decoded.  Future upgrade for RetrieveFileFromUri.
> DEV-1904: Quick fix for new file reader to manually decode contents

- requirements/requirements.txt
Suggestion to upgrade urllib3 to 1.24.2
> Hotfix library version upgrade

- requirements/requirements.txt
- usaspending_api/broker/management/commands/fabs_nightly_loader.py
Downmerge hotfix changes to python package version in staging
> Staging -> Dev downmerge

- usaspending_api/awards/v2/filters/idv_filters.py
- usaspending_api/download/filestreaming/csv_generation.py
Oversight on my part.  There's still value in generating download files when there are no descendants.
As requested, only files with data will be included in the zip file.
1. [X] There are no unit tests for this particular change
2. [X] No API documentation needs updating
4. [X] No materialized views were affected
5. [X] Front end should be unaffected
7. [X] No Operations ticket(s) required
8. [X] Jira Ticket [DEV-2336](https://federal-spending-transparency.atlassian.net/browse/DEV-2336):
> DEV-2336: Generate files even if no descendants

- usaspending_api/common/helpers/text_helpers.py
- usaspending_api/common/tests/test_text_helpers.py
- usaspending_api/data/idv_download_readme.txt
- usaspending_api/download/download_utils.py
- usaspending_api/download/filestreaming/csv_generation.py
- usaspending_api/download/filestreaming/csv_source.py
- usaspending_api/download/filestreaming/file_description.py
- usaspending_api/download/filestreaming/include_file_description.py
- usaspending_api/download/filestreaming/zip_file.py
- usaspending_api/download/lookups.py
- usaspending_api/download/tests/unit/test_csv_generation.py
- usaspending_api/download/tests/unit/test_file_description.py
- usaspending_api/download/tests/unit/test_zip_file.py
- usaspending_api/download/v2/base_download_viewset.py
- usaspending_api/download/v2/download_column_historical_lookups.py
- usaspending_api/download/v2/request_validations.py
- usaspending_api/settings.py
Added a readme file to the download zip that describes the constituent files.  Also renamed zip and constituent files to contain the award id.
2. [x] No API documentation updates required
4. [x] No materialized views are affected by these changes
5. [x] Front end is unaffected by these changes
7. [x] No Operations ticket(s) required
8. [x] Jira Ticket [DEV-2336](https://federal-spending-transparency.atlassian.net/browse/DEV-2336):
> DEV-2336: Added readme and renamed files

- usaspending_api/data/idv_download_readme.txt
- usaspending_api/download/download_utils.py
- usaspending_api/download/lookups.py
Updated the readme text for IDV downloads and brought the file names more in line with the original requirements.
**IMPORTANT:** Will be rebased once staging to dev downmerge completes.
1. [X] No unit or integration tests affected
2. [X] No API documentation affected
4. [X] Materialized views unaffected
5. [X] Front end unaffected
7. [X] No Operations ticket(s) required
8. [X] Jira Ticket [DEV-2571](https://federal-spending-transparency.atlassian.net/browse/DEV-2571):
> DEV-2571: Update IDV download readme and file names (#2)

- usaspending_api/common/helpers/sql_helpers.py
> Mistake expecting a non-existant key in non-replica envs

- usaspending_api/common/helpers/sql_helpers.py
- Changes in this PR will allow the function to operate as desired in various environments
- Issues were encountered when used in ETL pipelines
- Changes were tested in a staging environment
> [Master Hotfix] Emendation of new function for Postgres DSN string

- usaspending_api/awards/v2/views/idvs/funding_accounts.py
Removed a grouping from the IDV accounts endpoint that was causing accounts to repeat and present incorrect totals.
1. [x] No test updates required
8. [x] Jira Ticket [DEV-1937](https://federal-spending-transparency.atlassian.net/browse/DEV-1937):
> HOTFIX: DEV-1937: Remove grouping from IDV accounts endpoint

- usaspending_api/etl/management/commands/es_rapidloader.py
reload command didn't reflect changes made to prefer dashes over underscores
> es_rapidloader comment sp

- usaspending_api/search/tests/unit/test_es_sanitize.py
- usaspending_api/search/v2/elasticsearch_helper.py
Create sanitizer method to escape or remove reserved elasticsearch characters
Uses regex to add escape character to set of reserved characters 
6. [N/A] Data validation completed
- [N/A] Link to this Pull-Request
No change to data/matviews etc. No change to frontend behavior
> Elasticsearch sanitizer

- usaspending_api/conftest_helpers.py
- usaspending_api/etl/es_etl_helpers.py
Minor fix to silent option in `create_aliases`.
> DEV-2616: Minor fix to silent option

- requirements/requirements.txt
- usaspending_api/common/pagination.py
1. [ N/A] Unit & integration tests updated
2. [N/A ] API documentation updated
4. [N/A ] Matview impact assessment completed
5. [N/A ] Frontend impact assessment completed
6. [N/A ] Data validation completed
7. [N/A ] Appropriate Operations ticket(s) created
8. [N/A ] Jira Ticket 
```
```
> updated djangorestframework version

- requirements/requirements.txt
- usaspending_api/common/pagination.py
- usaspending_api/references/v2/views/city.py
> Down merge Staging -> Dev hotfix

- usaspending_api/awards/tests/unit/test_location_filter_geocode.py
- usaspending_api/awards/v2/filters/location_filter_geocode.py
- usaspending_api/awards/v2/filters/matview_filters.py
- usaspending_api/awards/v2/filters/sub_award.py
- usaspending_api/search/tests/test_spending_by_geography_city.py
- usaspending_api/search/v2/views/spending_by_geography.py
Downmerge hotfix in staging to dev.
There were merge conflicts going directly from staging -> dev, so a branch was created to resolve the conflicts outside of Github.
> Downmerge hotfix from staging to dev

- usaspending_api/api_docs/markdown/endpoints.md
Quick fix to update endpoint list with IDV activity endpoint.
> DEV-2749: Updated endpoint list with IDV activity endpoint

- requirements/requirements.txt
Recommended update from 1.11.20 to 1.11.21. No impact to behavior is expected.
Routine patches and security updates
```
Minor version update.
No code or document changes
```
> Update Django version in requirements.txt

- usaspending_api/api_docs/markdown/endpoints.md
Documentation ended up going elsewhere. This is just adding the link to the endpoint list.
> added city autocomplete endpoint

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
Due to changes in how internal assistance keys are constructed, the columns for deleted transactions were misaligned in monthly delta files.  This hotfix re-aligns those columns.
1. [x] Sadly, there are no tests for this code
2. [x] Documentation is unaffected by this change
4. [x] Materialized views are unaffected by this change
5. [x] Frontend is unaffected by this change
8. [x] Jira Ticket [DEV-3051](https://federal-spending-transparency.atlassian.net/browse/DEV-3051):
> DEV-3051 HOTFIX: Fix delta file column alignment

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
We failed to downmerge a hotfix which went into staging and master. The conflicts were mostly (entirely?) due to black run in dev
> Resolve merge conflicts for Dev from hotfix

- usaspending_api/download/v2/request_validations.py
During testing it was discovered that an important piece of plumbing that linked the TAS filters to download code was overlooked.  This pull request rectifies that oversight.
1. [x] Unit tests affected
7. [x] No Operations tickets required
8. [x] Jira Ticket [DEV-2068](https://federal-spending-transparency.atlassian.net/browse/DEV-2068):
> DEV-2068 HOTFIX: Attach TAS search to downloads

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
> Fixing Travis-CI checks after Hotfix introduced issue

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
Simple fix to correct delete indicator column being added twice to delta files.
> [HOTFIX] Correct delete indicator column issue

- usaspending_api/download/filestreaming/csv_source.py
- usaspending_api/download/management/commands/populate_monthly_delta_files.py
Fixed delta downloads by de-duplicating the delete indicator column
> Another Hotfix from Master -> Staging

- usaspending_api/broker/management/commands/fpds_nightly_loader.py
- usaspending_api/database_scripts/job_archive/backfill_per_transaction_exec_comp.py
Adding tiny functionality to the operation script
> [DEV-3318] Update EC backfill script to also populate transaction_delta

- usaspending_api/data_load/fpds_loader.py
- usaspending_api/data_load/tests/test_derived_field_functions_fpds.py
- usaspending_api/data_load/tests/test_fpds_loader.py
> Add Keith's changes to FPDS loader

- usaspending_api/awards/v2/views/funding.py
- usaspending_api/references/constants.py
There is a discrepancy between the results returned here and the count returned by the `count/federal_account` endpoint. This resolves the discrepancy.
The reason why the counts being returned were different was due to the `group by` clause. For some awards, the fields being used by this endpoint are identical and therefore get coalesced into one result. 
8. [X] Jira Ticket [DEV-3489](https://federal-spending-transparency.atlassian.net/brows …
> [DEV-3489] fix count difference

- usaspending_api/common/tests/unit/test_fiscal_year_helpers.py
- usaspending_api/search/tests/unit/test_tas_search.py
Fixed a couple of tests that could not keep up with the times...
> Quick fix for fiscal year based tests

- usaspending_api/database_scripts/job_archive/recompute_all_awards.py
- Removed full from the vacuum statement so the table isn't prohibitively locked.
- Added "closing-time" cli arg to set the desired script end datetime
> [staging] removed full from vacuum and added "closing-time" to awards backfill

- usaspending_api/download/helpers/download_annotation_functions.py
- usaspending_api/download/tests/integration/test_download_status.py
- usaspending_api/download/v2/download_column_historical_lookups.py
Edited the CSV for Subaward downloads.
Removed column from download:
* `prime_award_fiscal_year`
Renamed column in download:
* `prime_award_action_date` -> `prime_award_base_action_date`
* `prime_award_action_date_fiscal_year` -> `prime_award_base_action_date_fiscal_year`. 
Along with these changes some test cases were updated/fixed.
5. [X] Frontend impact assessment completed (N/A)
8. [X] Jira Ticket [DEV-3601](https://federal-spending-transparency.atlassian.net/browse/DEV-3601 …
> [DEV-3601] Edit Sub-Award Download

- usaspending_api/api_docs/markdown/endpoints.md
- usaspending_api/awards/tests/test_awards_v2.py
- usaspending_api/awards/tests/unit/test_federal_account_count.py
- usaspending_api/awards/tests/unit/test_transaction_count.py
- usaspending_api/awards/v2/urls_awards.py
- usaspending_api/idvs/tests/data/idv_test_data.py
- usaspending_api/idvs/tests/test_awards_idvs_accounts_v2.py
- usaspending_api/idvs/tests/test_awards_idvs_activity_v2.py
- usaspending_api/idvs/tests/test_awards_idvs_amounts_v2.py
- usaspending_api/idvs/tests/test_awards_idvs_awards_v2.py
- usaspending_api/idvs/tests/test_awards_idvs_funding_rollup_v2.py
- usaspending_api/idvs/tests/test_awards_idvs_funding_v2.py
- usaspending_api/idvs/tests/test_federal_account_count.py
- usaspending_api/idvs/v2/urls_idvs.py
Fixes issue with the URL regex that prevented using generated_unique_award_id's that have special characters in URLs. The URLs will require the award ids to be encoded due to the special characters being introduced.
Split URLs into two - one accepts only numbers for internal ids, the other enforces the generated unique award id pattern of `(CONT/ASST)_(AWD/IDV/NON/AGG)_(anything)`
5. [x] Frontend impact assessment completed  …
> [WARMFIX] Fix URL regex

- usaspending_api/accounts/v2/filters/account_download.py
We were having a difficult time consistently retrieving agency names for account download files.  The logic is a little convoluted, but the bottom line is that because our agency table doesn't fully represent all CGACs and FRECs for agencies and because we don't have FREC mappings for ATAs in our TAS table, there were certain situations where we struggled to look up FREC agency names.
This fix ensures we will always get an agency name but at the cost of losing some FREC agency name resolution.  Said another way, for the few FREC agencies we maintain that are not toptier equivalent, the names presented by this fix will be of their toptier counterpart.  This is a compromise solution until such time as we have the data available to fully represent all FREC agencies (ATA or …
> DEV-2134: Fix agency names in downloads

- .travis.yml
Trying to leverage caching pip installs to speed up travis CI runs
https://docs.travis-ci.com/user/caching/#pip-cache
```
CI config change
```
> Update .travis.yml to enable pip caching

- usaspending_api/broker/management/commands/load_fpds_transactions.py
- usaspending_api/etl/transaction_loaders/fpds_loader.py
Added a concise log that informs users of awards that failed instead of just breaking the load, as well as stylistic changes for the convenience of whomever has to clean up this mess in a year.
I used a global. I wish I hadn't, but adding it to the function return values would have been a way bigger change in a ticket that just needs to finish.
8. [ ] Jira Ticket …
> [DEV-3634] Small changes to new FPDS loader

- usaspending_api/accounts/tests/test_federal_account_autocomplete.py
- usaspending_api/accounts/tests/test_tas_autocomplete.py
- usaspending_api/accounts/views/common.py
- usaspending_api/accounts/views/federal_account.py
- usaspending_api/accounts/views/tas.py
Some endpoints were missed in the original work. This is just to bring the warmfix down to DEV
> Mod -> staging downmerge for dev-3746

- usaspending_api/broker/management/commands/load_fpds_transactions.py
This log statement appears right below the one about deletes, which confused me as to what it was counting a total of. When the code you wrote confuses you the first time you run it for real, that's a bad sign.
> log update

- requirements/requirements-app.txt
Downgrading after testing locally and on ec2
> Downgrading Markdown version

- pyproject.toml
Black can run against several Python versions. Changing from targeting 3.5 to 3.7.
None
```
Config change for code formatter
```
> Updated black target Python version

- usaspending_api/etl/es_etl_helpers.py
- usaspending_api/etl/management/commands/es_rapidloader.py
This PR resolves merge conflicts which were created by #2155 and surfaced in #2156.
> Downmerge ES ETL DB connection warmfix to Dev

- usaspending_api/accounts/v2/filters/account_download.py
- usaspending_api/download/v2/download_column_historical_lookups.py
Convert reporting period to FYQ format (e.g. FY2019Q1) in award financial custom account download files.
8. [x] Jira Ticket [DEV-4006](https://federal-spending-transparency.atlassian.net/browse/DEV-4006):
> DEV-4006: Convert report period to FYQ

- usaspending_api/download/lookups.py
Shorted the filename for one type of file
N/A
8. [x] Jira Ticket [DEV-1566](https://federal-spending-transparency.atlassian.net/browse/DEV-1566):
```
Minor edit to desired code
```
> [DEV-1566] names were too long for Windows users

- usaspending_api/etl/tests/test_es_rapidloader.py
Minor tweaks to speed up `test_es_rapidloader` a bit.
There are sleeps sprinkled throughout the Elasticsearch code to help mitigate issues with the asynchronous nature of our rapidloader.  These are not entirely necessary for `test_es_rapidloader` so we monkey patched them to a much shorter duration to speed up tests.
4. [x] Matviews unaffected
7. [x] No Operations tickets required
8. [x] Jira Ticket [DEV-4096](https://federal-spending-transparency.atlassian.net/browse/DEV-4096):
> [DEV-4096] Speed up test_es_rapidloader a bit

- usaspending_api/etl/management/commands/submission_loader.py
Modified script to return non-zero exit code at the end of the loading all submissions is one of the submissions encountered an error
`submission_loader` is a wrapper management command which invokes `load_multiple_submissions`. `load_multiple_submissions` requires a FY and Q input, which works well but requires all FY+Q combinations to be passed into sequential runs to ensure all DABS are loaded. This wrapper will calculate the current FY+Q and call `load_multiple_submissions` from FY2017Q2 - current FY+Q …
> Update submission runner for pipeline

- usaspending_api/api_contracts/contracts/v2/download/count.md
- usaspending_api/download/v2/download_transaction_count.py
- usaspending_api/settings.py
Beefing up the `/api/v2/download/count/` response after an investigation ticket demonstrated the benefits of returning more information.
Everything is straightforward. See API contract for new response
```
No matviews were modified
No data to change
```
> Augmenting /api/v2/download/count/ Response

- usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
A field was wrongly marked as optional
5. [x] Frontend impact assessment completed(N/A)
6. [x] Data validation completed(N/A)
7. [x] Appropriate Operations ticket(s) created(N/A)
8. [x] Jira Ticket [DEV-4160](https://federal-spending-transparency.atlassian.net/browse/DEV-4160):
```
```
> dev-4160 updated contract

- usaspending_api/common/management/commands/matview_runner.py
- usaspending_api/database_scripts/matviews/drop_old_matviews.sql
Encountered odd error with `matview_runner` so I ensured files are opened and closed properly which will help future debugging if someone has local env issues.
N/A
```
Minor edits to a SQL file and how SQL files are opened
```
> Fixing bad matview name and cleaning up file reads

- usaspending_api/download/v2/download_column_historical_lookups.py
Column name remained the original header name, was not updated with the new desired name
N/A
8. [x] Jira Ticket [DEV-4098](https://federal-spending-transparency.atlassian.net/browse/DEV-4098):
```
Only minor edits to download header name
```
> [DEV-4098] Fix download header name

- usaspending_api/download/filestreaming/download_generation.py
- usaspending_api/download/filestreaming/download_source.py
- usaspending_api/download/helpers/csv_generation_helpers.py
- usaspending_api/download/tests/integration/test_download_awards.py
- usaspending_api/download/tests/integration/test_download_status.py
- usaspending_api/download/v2/base_download_viewset.py
If a particular file in a download .zip does not contain a specified column then that file is blank. Also, updated the column count since it was not accurately summing columns across all files similar to how the row count sums all rows. 
If a particular download does not have any columns in common with the requested columns then a blank file is created and placed in the .zip folder. …
> [DEV-3806] Download with no matching columns returns blank file

- usaspending_api/download/v2/list_monthly_downloads.py
Code has NOT been tested due to not having boto set up to run locally.  Putting the PR up in advance in case we don't think that that's a serious concern.
8. [ ] Jira Ticket [DEV-4104](https://federal-spending-transparency.atlassian.net/browse/DEV-4104):
```
```
> dev-4104 removed scaffolding code

- usaspending_api/search/tests/integration/spending_test_fixtures.py
- usaspending_api/search/tests/integration/test_elasticsearch_header.py
- usaspending_api/search/tests/integration/test_spending_by_awarding_agency.py
- usaspending_api/search/tests/integration/test_spending_by_awarding_subagency.py
Pulls out common test functionality to prevent lots of pain maintaining these tests down the line.
> DRYed tests

- usaspending_api/download/v2/download_list_agencies.py
The agency list on the Custom Account Download page was a wee bit off.  This rectifies that.
1. [x] Unit & integration tests unaffected
8. [x] Jira Ticket [DEV-3931](https://federal-spending-transparency.atlassian.net/browse/DEV-3931):
> [DEV-3931] Fix Custom Account Download agency list

- usaspending_api/etl/management/commands/load_submission.py
- usaspending_api/etl/management/helpers/load_submission.py
Our largest File C submission ever has managed to break the nightly pipeline.  This pull requests chunks the submission to reduce memory footprint.
1. [x] Unit tests unaffected
7. [x] Operations Ticket [OPS-1096](https://federal-spending-transparency.atlassian.net/browse/OPS-1096)
> [OPS-1096] Added chunking to submission loader

- usaspending_api/etl/es_etl_helpers.py
- usaspending_api/etl/rapidloader.py
- usaspending_api/transactions/agnostic_transaction_deletes.py
- usaspending_api/transactions/management/commands/delete_assistance_records.py
**Elasticsearch ETL for awards is broken**
Highly confident this has the fix, but unable to test locally due to odd error on missing index name......
Please review and test **before** merging!!!
**New Assistance transaction ETL didn't do very well without inactive FABS**
> [FIX] Fixing ETL issues

- usaspending_api/bulk_download/tests/test_download.py
- usaspending_api/download/v2/download_list_agencies.py
Fixed a minor typo that caused subtier agencies not to populate.
> [DEV-3932] WARMFIX Subtier agency response typo

- usaspending_api/broker/management/commands/fabs_nightly_loader.py
Simply making the call to pull FABS delete records case-insensitive when checking on the `correction_delete_indicatr`
N/A
6. Data validation completed
7. [x] Appropriate Operations ticket(s) created [DEV-4626](https://federal-spending-transparency.atlassian.net/browse/DEV-4626)
8. [x] Jira Ticket [DEV-4608](https://federal-spending-transparency.atlassian.net/browse/DEV-4608):
- Performance evaluation of affected (API | Script | Download)
- Before / After data comparison …
> DEV-4608: FABS delete records Case-Insensitive 

- requirements/requirements-app.txt
Updating psutil and pip to be willdcard versions
old psutil had a security warning
```
Dependency version upgrades
```
> Update dependency versions

- usaspending_api/common/helpers/date_helper.py
- usaspending_api/transactions/transaction_delete_journal_helpers.py
Normalizing datetime compares in ETL scripts to convert naive datetimes to timezone-aware and UTC
Leveraging existing functions and some `operator` functions
8. [x] Jira Ticket [DEV-1671](https://federal-spending-transparency.atlassian.net/browse/DEV-1671):
```
Bugfix for ETL script code
```
> [FIX/DEV-1671] Handling naive datetimes

- usaspending_api/broker/helpers/delete_fabs_transactions.py
- usaspending_api/broker/management/commands/fabs_nightly_loader.py
- usaspending_api/transactions/agnostic_transaction_deletes.py
- usaspending_api/transactions/management/commands/delete_assistance_records.py
Found another edge case during situations the loader is run with no delete records to process
N/A
8. [x] Jira Ticket [DEV-1671](https://federal-spending-transparency.atlassian.net/browse/DEV-1671):
```
Edit to ETL script code
```
> [FIX] another overlooked edgecase

- usaspending_api/common/cache_decorator.py
Should fix the merge conflict between staging and dev.
> Fix merge conflict 

- usaspending_api/api_contracts/contracts/v2/download/awards.md
- usaspending_api/api_contracts/contracts/v2/download/count.md
- usaspending_api/api_contracts/contracts/v2/download/transactions.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_award_count.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_subagency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_agency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_subagency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_geography.md
- usaspending_api/api_contracts/contracts/v2/search/spending_over_time.md
API Blueprint uses `array` not `list`. 
```
```
> Corrected API contracts

- usaspending_api/search/v2/views/spending_by_geography.py
Typo in business logic for congressional district per capita spending
N/A
8. [x] Jira Ticket [DEV-4768](https://federal-spending-transparency.atlassian.net/browse/DEV-4768):
```
Value was always null for per capita, addressing typo corrects behavior
```
> [DEV-4768] district per capita

- usaspending_api/download/management/commands/populate_monthly_files.py
Adding adjustments to monthly file generation script to match the bulk download parameters for award levels.
API request changed for the Custom Award Download page in a previous sprint
```
Edits to Operations script
```
> [FIX] Monthly file generation script outdated

- usaspending_api/common/recipient_lookups.py
- usaspending_api/download/management/commands/populate_monthly_files.py
downmerge for monthly file generation script
> Qat -> Dev

- usaspending_api/common/helpers/s3_helpers.py
- usaspending_api/transactions/transaction_delete_journal_helpers.py
Add extra logging to FPDS delete code in an effort to track down why deletes are not happening consistently.
> [DEV-4873] Add extra logging to FPDS deletes

- usaspending_api/transactions/transaction_delete_journal_helpers.py
Previously, the FPDS loader was obtaining the delete file date from the date contained in the delete file's name.  This was only a date which meant the datetime was treated as though the delete occurred at midnight.  The last run timestamp is a full timestamp which means it captures the time as well as the date.  Since the timestamp is usually a few minutes after midnight, this means files created on the same day as the last run were not being picked up.
That's confusing.  Perhaps a real life example will help:
```
2020-04-21 00:05:46  Last run datetime
2020-04-21 14:57:30  Actual file create date  (04-21-2020_delete_records_IDV_1587481048.csv)                                        
2020-04-21 00:00:00  The date the FPDS loader THINKS the delete file was created since …
```
> [DEV-4873] Fix S3 file datetime filtering for FPDS loader

- usaspending_api/api_docs/markdown/endpoints.md
The example DUNS hash provided for the recipient endpoint example returned 404, so I've updated with a value that exists in production.
```
```
> updated duns hash to value that exists in production

- config/uwsgi.ini
- usaspending_api/settings.py
- Reducing maximum uwsgi workers from 500 to 200
- Added Hard and Soft (total) memory limits of running workers
- Added some lifespan constraints of running workers
> [FIX] Reduce max number of uwsgi workers

- config/uwsgi.ini
Cleanup/Fixes as part of https://federal-spending-transparency.atlassian.net/browse/OPS-1256
> [FIX] added config line to support uwsgi memory limits

- usaspending_api/common/query_with_filters.py
Adds `parent_recipient_name` to the keyword search fields being searched on.
8. [X] Jira Ticket [DEV-4818](https://federal-spending-transparency.atlassian.net/browse/DEV-4818):
```
No change to matviews, no ops tickets needed
```
> [HOTFIX] Keyword search field update

- usaspending_api/common/query_with_filters.py
Fixes a bug in the keyword filter on the advanced search page where when escaping some reserved characters it prevented the search returning correctly.
For some reason, when escaping 
8. [ ] Jira Ticket [DEV-5252](https://federal-spending-transparency.atlassian.net/browse/DEV-5252):
```
```
> [DEV-5252] Fix sanitization

- usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/award/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/award/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/cfda/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/def_code/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/def_code/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/federal_account/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/federal_account/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/object_class/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/object_class/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/business_category/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/business_category/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/location/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/location/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/spending.md
Minor changes to the API Contracts previously created 
N/A
8. [x] Jira Ticket [DEV-5342](https://federal-spending-transparency.atlassian.net/browse/DEV-5342):
```
```
> [DEV-5342] Necessary API changes

- usaspending_api/api_contracts/contracts/v2/download/accounts.md
A client asked for clarification on a field.  The whole contract could use some love, but this pull request clarifies just the field in question.
> [UNTICKETED] Minor API contract clarification

- usaspending_api/idvs/v2/views/amounts.py
Error with turning array of ids into sql string.
8. [ ] Jira Ticket [DEV-5136](https://federal-spending-transparency.atlassian.net/browse/DEV-5136):
```
```
> [DEV-5136] Minor fix in SQL string

- usaspending_api/spending_explorer/v2/filters/type_filter.py
This corrects a Django grouping issue with the Spending Explorer.
> [DEV-5170] Warmfix Django grouping issue

- usaspending_api/spending_explorer/v2/filters/type_filter.py
/lesigh
Attempt 2 to fix this little Django quirk.  This attempt fixes a shortcoming in my previous warmfix.
> [DEV-5170] Warmfix Django grouping issue attempt 2

- usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
Adds `resource_link` to the result object in `disaster/cfda/loans` API contract.
8. [x] Jira Ticket [DEV-5509](https://federal-spending-transparency.atlassian.net/browse/DEV-5509):
```
API Contract changes only
```
> [DEV-5509] add resource link to CFDA loans API contract

- usaspending_api/etl/management/commands/load_submission.py
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain_and_uri.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_piid.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_uri.sql
- usaspending_api/submissions/management/commands/rm_submission.py
This PR updates an Award's **update_date** when it is linked during the C to D linkage process in the **load_submission** management command. 
Because this **update_date** has been updated, the award will be included in the nightly ElasticSearch update. 
8. [ ] Jira Ticket [DEV-5504](https://federal-spending-transparency.atlassian.net/browse/DEV-5504):
```
```
> [DEV-5504] Updates Awards update_date when attached to submission during load_submission

- usaspending_api/common/helpers/endpoint_documentation.py
- usaspending_api/common/matview_manager.py
- usaspending_api/common/renderers.py
- usaspending_api/conftest.py
- usaspending_api/disaster/management/commands/generate_covid19_download.py
- usaspending_api/download/filestreaming/download_generation.py
- usaspending_api/settings.py
While investigating issues with running the script in Jenkins, edits were made for testing. While these changes are not necessary for the script to run successfully, they do improve the script.
Renamed generic `BASE_DIR` to `REPO_DIR` for a little more clarity
7. [x] Appropriate Operations ticket(s) created (forthcoming)
8. [x] Jira Ticket [DEV-5302](https://federal-spending-transparency.atlassian.net/browse/DEV-5302):
``` …
```
> [DEV-5302] Followup edits

- usaspending_api/download/helpers/download_annotation_functions.py
Removes case statement for awards, as that was not actually required, and uses correct comparison field for transaction case statement.
8. [ ] Jira Ticket [DEV-5245](https://federal-spending-transparency.atlassian.net/browse/DEV-5245):
```
```
> [DEV-5245] Fixes for downloads

- usaspending_api/awards/v2/filters/idv_filters.py
- usaspending_api/download/lookups.py
- usaspending_api/idvs/v2/views/funding.py
In my rush to get #2615 merged, I missed a comment and failed to address a comment by @tony-sappe.  This baby pull request addresses those issues.  Sorry for the extra work.  Don't hate me.
> [DEV-5685] Fix missed comment and rename function

- usaspending_api/awards/v2/data_layer/orm.py
- usaspending_api/awards/v2/views/awards.py
Minor fix for DEF code detection for IDVs.  Non-IDV code should be largely unchanged.
7. [x] No Operations required
8. [x] Jira Ticket [DEV-5132](https://federal-spending-transparency.atlassian.net/browse/DEV-5132):
> [DEV-5132] Fix IDV DEF code detection

- usaspending_api/common/cache_decorator.py
A patch that should ~resolve~ temporarily rectify a caching issue with several of our endpoints.  We will eventually fix the endpoints, but this will get the site operational more quickly for testing.
> [UNTICKETED] Band-Aid (tm) for caching issue

- usaspending_api/api_docs/markdown/endpoints.md
- usaspending_api/common/data_classes.py
- usaspending_api/references/v2/views/submission_periods.py
HTML comments didn't hold for `endpoints.md`, so removing lines
Minor edits to address minor items surfaced during PR reviews but were not blockers for merge
N/A
```
Minor edits don't touch the database and barely impact UX
```
> Fix API Endpoints HTML and other minor edits

- usaspending_api/api_docs/markdown/endpoints.md
Missed removal of a non-existent endpoint
N/A
8. [x] Jira Ticket [DEV-5622](https://federal-spending-transparency.atlassian.net/browse/DEV-5622):
```
doc change
```
> [DEV-5622] API Doc Links: missed one

- usaspending_api/download/helpers/download_annotation_functions.py
Chipping away at DEV-5717/DEV-5739. Adding filter to every FileC/FinancialAccountByAward annotation which wasn't limited to closed DABS submission periods
Note, in a non-prod env (QAT) there was no difference in an award-level download file after introducing these changes from Advanced Search because all of the Financial Account data are contained by closed submission windows (some artificially for testing U/I). This mostly covers the edge case of API clients requesting data during submission periods. The download requests from the website will most likely be limited to closed periods anyway.
N/A
4. [x] …
> [DEV-5739] Limiting Financial Account Data Download data to closed DABS

- usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
Switching source columns for CSV Total Budgetary Resources
N/A
8. [x] Jira Ticket [DEV-5771](https://federal-spending-transparency.atlassian.net/browse/DEV-5771):
```
Minor change to download 
```
> [DEV-5771] update download SQL (QAT)

- usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
Switching source columns for CSV Total Budgetary Resources
N/A
8. [x] Jira Ticket [DEV-5771](https://federal-spending-transparency.atlassian.net/browse/DEV-5771):
```
Minor change to download 
```
> [DEV-5771] update download SQL (STG)

- usaspending_api/etl/management/commands/load_multiple_submissions.py
- usaspending_api/etl/management/commands/load_submission.py
- usaspending_api/submissions/dabs_loader_queue_helpers.py
Added some minor tweaks to submission loader to automatically handle failure retries and improve logging.
> [DEV-5696] Add failure reprocessing to submision loader (Q.A.T.)

- usaspending_api/etl/management/commands/load_multiple_submissions.py
- usaspending_api/etl/management/commands/load_submission.py
- usaspending_api/submissions/dabs_loader_queue_helpers.py
Added some minor tweaks to submission loader to automatically handle failure retries and improve logging.
> [DEV-5696] Add failure reprocessing to submision loader (STAGING)

- usaspending_api/submissions/helpers.py
A very minor bug was found in the new account download code that was causing some agencies to appear incorrectly in the download file.  See the ticket for more details.
1. [x] Tests unaffected
8. [x] Jira Ticket [DEV-5805](https://federal-spending-transparency.atlassian.net/browse/DEV-5805):
> [DEV-5805] Tweak to submission id query for account downloads

- usaspending_api/recipient/management/sql/restock_summary_award_recipient.sql
Original ETL deleted all rows then repopulated table in a SQL transaction block. The ETL script will now make incremental changes to the table (deletes, inserts, and updates)
Local testing demonstrated using Postgres' "upsert" functionality was slower than separate update and insert statements. Since the table have over 80M rows and the SQL script is small I decided to duplicate the code for better performance.
8. [x] Jira …
> [OPS-1470] Refactored summary_award_recipient ETL script to incrementally update table

- usaspending_api/references/tests/integration/test_city.py
- usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
- usaspending_api/search/v2/es_sanitization.py
Adds sanitization for `*` to both sanitization methods for elasticsearch
2. [ X] API documentation updated
8. [x] Jira Ticket [DEV-5252](https://federal-spending-transparency.atlassian.net/browse/DEV-5252):
```
```
> [DEV-5252] Elasticsearch sanitization fix

- usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
- usaspending_api/api_contracts/contracts/v2/download/awards.md
- usaspending_api/api_contracts/contracts/v2/download/transactions.md
- usaspending_api/download/v2/request_validations.py
- usaspending_api/download/v2/year_limited_downloads.py
Due to merge conflicts a new branch needed to merge master into QAT
> Master -> QAT

- .env
- usaspending_api/etl/elasticsearch_loader_helpers/es_etl_helpers.py
- usaspending_api/etl/elasticsearch_loader_helpers/rapidloader.py
- usaspending_api/etl/management/commands/elasticsearch_indexer.py
- usaspending_api/recipient/tests/integration/test_state.py
> [DEV-6181] Downmerging hotfix PR 2804 from master down to qat and resolving merge conflicts 

- usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
- usaspending_api/etl/elasticsearch_loader_helpers/controller.py
- usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
- usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
- usaspending_api/etl/management/commands/elasticsearch_indexer.py
- usaspending_api/recipient/tests/integration/test_state.py
> [DEV-6181] Downmerging hotfix PR 2804 from qat down to dev and resolving merge conflicts

- usaspending_api/download/filestreaming/download_generation.py
New conditional broke for COVID-19 download script
COVID-19 downloads don't have a "download job" record until successfully creating the file
8. [x] Jira Ticket [DEV-6153](https://federal-spending-transparency.atlassian.net/browse/DEV-6153):
```
Minor change to fix COVID-19 download script
```
> [DEV-6153] Overlooked code execution broke a conditional

- usaspending_api/references/v2/views/filter_hash.py
API Endpoint contained a link to the wrong API contract
Also made the endpoint a little more robust
8. [x] Jira Ticket [DEV-4976](https://federal-spending-transparency.atlassian.net/browse/DEV-4976):
```
Minor edits to API doc link and making the endpoint more robust
```
> [DEV-4976] fixed API doc link and made endpoint more robust

- usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
- usaspending_api/database_scripts/etl/transaction_delta_view.sql
- usaspending_api/etl/es_transaction_template.json
- usaspending_api/etl/management/commands/es_rapidloader.py
- usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
- usaspending_api/search/v2/elasticsearch_helper.py
Fixing columns being extracted from postgres and loaded into Elasticsearch
N/A
8. [x] Jira Ticket [DEV-6456](https://federal-spending-transparency.atlassian.net/browse/DEV-6456):
```
No behavior change to API responses or materialized views
```
> [DEV-6456] fixed columns in ES transactions ETL and renamed one in code

- usaspending_api/api_contracts/contracts/v2/reporting/agencies/publish_dates.md
JSON was intended to define an array of objects but had a syntax error:
> [api-contract-json-bug] fixes json in publish_dates.md

- usaspending_api/etl/management/sql/c_file_linkage/C_to_D_Linkage.md
- usaspending_api/etl/management/sql/c_file_linkage/check_assistance_file_c_linkages.sql
- usaspending_api/etl/management/sql/c_file_linkage/check_contract_file_c_linkages.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain_and_uri.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_piid.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_uri.sql
- usaspending_api/etl/management/sql/c_file_linkage/update_transaction_obligated_amount_nans.sql
Updates to documentation for File C to D Linkage
8. [x] Jira Ticket [DEV-6537](https://federal-spending-transparency.atlassian.net/browse/DEV-6537):
```
No code changes. Only changes to markdown 
```
> [DEV-6537] Updates to C_to_D_Linkage.md

- usaspending_api/agency/tests/integration/test_agency.py
- usaspending_api/agency/v2/views/agency_base.py
- usaspending_api/agency/v2/views/agency_overview.py
- usaspending_api/api_contracts/contracts/v2/agency/toptier_code.md
Add agency id to v2/agency/{toptier_code} response
Not technical, just adding it
4. [x] Matview impact assessment completed N/A
5. [x] Frontend impact assessment completed N/A
7. [x] Appropriate Operations ticket(s) created N/A
8. [x] Jira Ticket [DEV-6505](https://federal-spending-transparency.atlassian.net/browse/DEV-6505):
Simply adding another column that is already in table
> Dev 6505 add agency id to overview

- .env
- CONTRIBUTING.md
- README.md
- docker-compose.yaml
- usaspending_api/common/helpers/generic_helper.py
- usaspending_api/common/management/commands/matview_runner.py
- usaspending_api/common/matview_manager.py
- usaspending_api/database_scripts/matview_generator/shared_sql_generator.py
What started out as a minor upkeep of CONTRIBUTING.md turned into more substantial changes including README.md and fixing/improving the docker-compose services.
1. New Docker compose services:
- `usaspending-test` : easy way to run pytest
- `usaspending-ci` : one-liner to run (most) of the travis-ci checks
2. Fixed creating materialized views and running pytest in docker containers
3. Switched Docker containers' `bind` to `volume` for faster disk performance 
- These were unfortunately used for the data directories for `usaspending-db` and `usaspending-es`
4. Updated PostgreSQL image from 10.6 to 10.13
5. Added a few missing file cleanups to the matview scripts
2. [x] API …
> Improve Docker Compose Services and Update Dev Documentation

- usaspending_api/api_contracts/contracts/v2/reporting/agencies/overview.md
- usaspending_api/api_contracts/contracts/v2/reporting/agencies/publish_dates.md
`/api/v2/reporting/agencies/publish_dates` & `/api/v2/reporting/agencies/overview/` params update:
Renaming ?search to ?filter in query params
```
Very trivial contract update
```
> [DEV-6435] API Contract Update

- usaspending_api/disaster/tests/fixtures/disaster_account_data.py
- usaspending_api/disaster/tests/fixtures/federal_account_data.py
- usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
- usaspending_api/disaster/tests/integration/test_federal_account_total.py
- usaspending_api/disaster/v2/views/agency/spending.py
- usaspending_api/disaster/v2/views/federal_account/spending.py
Handle merge conflicts in downmerge of Master -> QAT.
> Downmerge Master -> QAT

- usaspending_api/disaster/management/commands/generate_covid19_download.py
- usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
* Updating the `All_TAS_AccountBalances` to include the latest GTAS data per fiscal year. 
N/A
6. [x] Data validation completed (ran the updated query on production and verified its values)
8. [x] Jira Ticket [DEV-6408](https://federal-spending-transparency.atlassian.net/browse/DEV-6408):
```
```
> DEV-6408: Covid Page Download Updates

- usaspending_api/api_contracts/contracts/v2/disaster/agency/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/award/amount.md
- usaspending_api/api_contracts/contracts/v2/disaster/award/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/cfda/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/def_code/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/federal_account/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/federal_account/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/federal_account/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/object_class/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/object_class/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/object_class/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/overview.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/count.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
- usaspending_api/api_contracts/contracts/v2/disaster/recipient/spending.md
- usaspending_api/api_contracts/contracts/v2/disaster/spending_by_geography.md
- usaspending_api/api_contracts/contracts/v2/download/disaster.md
- usaspending_api/api_contracts/contracts/v2/download/disaster/recipients.md
- usaspending_api/api_contracts/contracts/v2/references/def_codes.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
Adding DEFC U to API contracts
N/A
8. [x] Jira Ticket [DEV-6723](https://federal-spending-transparency.atlassian.net/browse/DEV-6723):
```
Only changes are to API contract docs
```
> [DEV-6723] Adding DEFC U to API contracts

- usaspending_api/disaster/tests/fixtures/disaster_account_data.py
- usaspending_api/disaster/v2/views/agency/spending.py
Updated TBR, obligation, and outlay calculations for total response
- See ticket for details
- Mock data for tests were modified so the same results are created by the new calculation
6. [x] Data validation completed (in SBX)
8. [ ] Jira Ticket [DEV-6912](https://federal-spending-transparency.atlassian.net/browse/DEV-6912):
```
No changes to API schema or materialized views
Some testing will be performed in Sandbox …
```
> [DEV-6912] update agency/spending for totals

- usaspending_api/disaster/tests/fixtures/federal_account_data.py
- usaspending_api/disaster/v2/views/federal_account/spending.py
Updated TBR, obligation, and outlay calculations for total response
- See ticket for details
- Mock data for tests were modified so the same results are created by the new calculation
6. [x] Data validation completed (in SBX)
8. [x] Jira Ticket [DEV-6911](https://federal-spending-transparency.atlassian.net/browse/DEV-6911):
```
No changes to API schema or materialized views
Some testing will be performed in Sandbox …
```
> [DEV-6911] Update federal_account/spending

- usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_b.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
This PR adds new fields and updates some calculations on Covid File A, B, and D CSV dowloads
This PR simply edits SQL files used to generate downloads.
8. [x] Jira Ticket [DEV-6921](https://federal-spending-transparency.atlassian.net/browse/DEV-6921):
```
```
> [DEV-6921] Updates Covid Downloads - File A, B, D

- usaspending_api/download/tests/integration/test_populate_monthly_files.py
Annoying pattern of the tests either clearing all downloads in `csv_downloads/` or failing due to directory extracted from zip file not able to be removed by the fragile delete logic. Also improved a test case which wasn't really testing anything of value
If I had more time I would have refactored `os` out and used `pathlib` from standard lib instead …
> Improve pytest file deletions to not clear entire directory

- usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
- usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
Attempt to make tests less fragile
- Removed assigning FKs by "value" and instead assigned by objects
- Switched to atomic DB transaction using decorator instead of context manager
```
Fixing tests
```
> Fixing another test

- usaspending_api/search/v2/views/spending_by_award.py
Fixes bug with sorting the COVID-19 Obligations and COVID-19 Outlays 
Since the DEFC values are now being stored as nested fields in elasticsearch, the sorting for the outlays and obligations had to switched to a nested type, as well as adding a filter so that the number being sorted on was accurate to what is being returned when there is a DEFC filter. (i.e. if we are filtering only on DEFC `L`, we are sorting only on the obligation/outlay for DEFC `L`)
7. [N/A] Appropriate Operations ticket(s) …
> [DEV-7388] fix covid sorting

- usaspending_api/recipient/management/sql/recipient_agency.sql
- usaspending_api/recipient/migrations/0007_recipientagency.py
- usaspending_api/recipient/models.py
Very minor PR fixing the migration 0007 from AutoField to BigAutoField
8. [x] Jira Ticket [DEV-7459](https://federal-spending-transparency.atlassian.net/browse/DEV-7359):
```
```
> [DEV-7359] Recipient stats

- usaspending_api/api_contracts/contracts/v2/agency/toptier_code/budgetary_resources.md
- usaspending_api/api_contracts/contracts/v2/agency/toptier_code/obligations_by_award_category.md
- usaspending_api/api_contracts/contracts/v2/agency/toptier_code/recipients.md
Adds clarifying descriptions to a few fields that we are using on the Agency Profile v2 frontend.
6. [N/A] Data validation completed
8. [x] Jira Ticket [DEV-7134](https://federal-spending-transparency.atlassian.net/browse/DEV-7134):
- [N/A] Performance evaluation of affected (API | Script | Download)
- [N/A] Before / After data comparison
> DEV-7134 API contract descriptions

- .gitignore
Updated the `.gitignore` to include the matview directories that are generated as part of the `matvier_runner`.
> Update gitignore to include matview folders

- usaspending_api/awards/v2/filters/sub_award.py
Make some additional performance changes for CFDA Subaward filter.
The pervious PR for this bug helped the count, but didn't really do much for the actual table of results. Some additional changes made in this PR around that filter make use of Exists. Overall the performance is better for both the count and table results endpoints, with both completely well under 1 min so that they are not timing out. Unfortunately, the performance isn't as good as it could be due to how Django handle the Exists in versions <3.0 (link to docs if curious: https://docs.djangoproject.com/en/3.0/ref/models/expressions/#filtering-on-a-subquery-or-exists-expressions). 
2. [x] API documentation …
> [DEV-7743] Some additional performance changes for Subaward CFDA

- usaspending_api/agency/v2/views/agency_base.py
- usaspending_api/reporting/tests/integration/test_agencies_overview.py
- usaspending_api/reporting/tests/integration/test_agency_code_overview.py
Updating the links of the Assurance Statements for the following changes:
* Bucket has no directory structure.
* Name has changed from Assurance_Statements.txt to Agency_Comments.txt
N/A
6. Data validation completed
8. [ ] Jira Ticket [DEV-7904](https://federal-spending-transparency.atlassian.net/browse/DEV-7904):
- Performance evaluation of affected (API | Script | Download)
- Before / After data comparison
```
```
> DEV-7904: Updating Agency Comments links

- usaspending_api/recipient/management/sql/restock_recipient_profile.sql
Reverts changes to `restock_recipient_profile.sql`
> [WARMFIX] Recipient Profile Fix

- usaspending_api/settings.py
Updating the download max to be 100k.
```
```
> Change download max up to 100k

- usaspending_api/common/query_with_filters.py
- usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
- usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
Incorrect field used when filtering in advanced search on UEI.
8. [x] Jira Ticket [DEV-8164](https://federal-spending-transparency.atlassian.net/browse/DEV-8164):
```
```
> [DEV-8164] Fixes UEI advanced search filter

- usaspending_api/common/recipient_lookups.py
Updated subaward recipient logic to not use DUNS for parent relationship.
```
```
> [DEV-8476] Remove DUNS from subaward parent recipient logic

- usaspending_api/download/v2/download_column_historical_lookups.py
> [DEV-7948] Fix UEI / DUNS sorting

- CONTRIBUTING.md
- README.md
Recently re-traced the developer bootstrap process to help improve the process for future devs
Updates:
* Updated stale branch names
* Added Elasticsearch index generation step
* Various updates
> [DEV-8469] Developer bootstrap documentation improvements

- usaspending_api/broker/management/commands/update_duns.py
- usaspending_api/broker/management/sql/restock_duns.sql
The Broker DUNS table is being renamed, this PR makes sure there are no interruptions to the pipeline due to this change.
Changing the name of the table/columns in the pipeline scripts
8. [ ] Jira Ticket [DEV-8409](https://federal-spending-transparency.atlassian.net/browse/DEV-8409):
- [N/A] Performance evaluation of affected (API | Script | Download)
9. [x] Merged after …
> DEV-8409: rename broker duns table

- usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
- usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
- usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
- usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
- usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
- usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
- usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
- usaspending_api/database_scripts/matviews/vw_award_search.sql
- usaspending_api/etl/migrations/0001_create_schemas.py
- usaspending_api/recipient/management/sql/restock_summary_award_recipient.sql
Creating new schemas and moving Award related tables.
Creating a migration inside of the `etl` app that has some dependencies on other apps to make sure we move the most recent state of the award tables.
8. [x] Jira Ticket [PIPE-192](https://federal-spending-transparency.atlassian.net/browse/PIPE-192):
```
```
> [PIPE-198/202] Move Awards related tables into different schemas

- usaspending_api/etl/management/commands/create_delta_table.py
- usaspending_api/settings_databricks.py
This PR updates the `settings_databricks.py` to match the changes made to `settings.py` by https://github.com/fedspendingtransparency/usaspending-api/pull/3440/files#diff-6f927744266f66a4e5bb69251ac908ade18155d8a14a62d6320b92ef94063906
> [PIPE-284] Updates settings_databricks.py to match Postgres upgrade version

- usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
Add changes to `award_description` field to the COVID page downloads.
8. [X] Jira Ticket [DEV-8905](https://federal-spending-transparency.atlassian.net/browse/DEV-8905):
```
```
> [DEV-8905] Update covid downloads

- usaspending_api/search/delta_models/award_search.py
Fixes issue where for contracts and IDVs, the `cfdas` field was being returned as an empty array rather than `NULL`.
Sets the `cfdas` field to `NULL` for all FDPS awards
```
```
> [WARMFIX] Fix NULL cfdasfield

- usaspending_api/config/envs/__init__.py
- usaspending_api/config/envs/production.py
Adds production config for databricks
6. N/A - Data validation completed
```
```
> Adds production config for databricks

- requirements/requirements-app.txt
> [PROD] Remove atomicwrites from requirements

- usaspending_api/search/delta_models/award_search.py
- usaspending_api/transactions/delta_models/transaction_search.py
Updating JSONB columns in Delta model postgres columns appropriately.
Technically, these aren't being used and more cover the situation if we had to rely on just the columns from this model and not the already existing base table.
6. Data validation completed
8. Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123):
- Link to this Pull-Request
- Performance evaluation of affected (API | Script | …
> Updating JSONB columns in Delta model postgres columns appropriately

- usaspending_api/broker/management/sql/restock_duns.sql
"Downmerge" to staging of hotfix into master (see: https://github.com/fedspendingtransparency/usaspending-api/pull/3572)
> [HOTFIX] [DEV-9073] Fetch unique broker recipients by UEI (staging-downmerge)

- .travis.yml
This PR fixes the failures we've been seeing in Travis CI.
- Removes unnecessary services in travis-ci.yml
- Manually installs and configures Postgres 13
```
```
> Travis CI and Postgresql Install Fix

- usaspending_api/search/v2/views/spending_over_time.py
SpendingOverTimeVisualizationViewSet with Subawards didn't include the `aggregated_amount` in the new values, so I refactored that code to be a bit more readable and included it back in.
N/A
8. [x] Jira Ticket [DEV-9216](https://federal-spending-transparency.atlassian.net/browse/DEV-9216):
```
```
> [DEV-9216] Subawards Spending Over Time Fix

- usaspending_api/etl/management/commands/create_delta_table.py
> Removes DROP TABLE from create_delta_table command

- usaspending_api/etl/earliest_latest_transaction.md
Adds a markdown file to describe the logic for calculating the earliest and latest Transaction for an Award
8. [x] Jira Ticket [DEV-9284](https://federal-spending-transparency.atlassian.net/browse/DEV-9284):
```
```
> [DEV-9284] Adds earliest_latest_transaction.md file

- usaspending_api/database_scripts/matview_generator/award_search.json
- usaspending_api/search/delta_models/award_search.py
Dropping the filtering of awards -> award_search as that will contain all the award data.
N/A
```
```
> Include All Awards in Award Search

- usaspending_api/etl/management/commands/swap_in_new_table.py
Simply updating the swap code to switch statements when dealing with views vs. matviews.
N/A
8. [ ] Jira Ticket [PIPE-465](https://federal-spending-transparency.atlassian.net/browse/PIPE-465):
```
```
> [PIPE-465] Update swap code for *materialized* views

- usaspending_api/etl/management/commands/update_delta_award_with_subaward_counts.py
- usaspending_api/etl/tests/integration/test_load_to_from_delta_subawards.py
- usaspending_api/recipient/delta_models/recipient_lookup.py
- usaspending_api/recipient/delta_models/recipient_profile.py
- usaspending_api/search/delta_models/award_search.py
- usaspending_api/search/delta_models/subaward_search.py
- usaspending_api/transactions/delta_models/summary_state_view.py
- usaspending_api/transactions/delta_models/transaction_search.py
Updating downstream delta table creation SQL to build off of the new int transaction and award tables
Find and replace
* `raw.awards` -> `int.awards`
* `raw.transaction_normalized` ->`int.transaction_normalized`
* `raw.transaction_fabs` ->`int.transaction_fabs`
* `raw.transaction_fpds` ->`int.transaction_fpds`
8. [ ] Jira Ticket [PIPE-339](https://federal-spending-transparency.atlassian.net/browse/PIPE-339), …
> [PIPE-339,PIPE-340,PIPE-342] Use int schema when building delta tables off transactions and awards

- usaspending_api/etl/management/commands/load_table_from_delta.py
Prevent any old/stale CSV files from past runs getting swept up in `load_table_from_delta` and causing duplicative data.
Unsure if this is the culprit for duplicative data, but will be tested shortly. This will ensure each new load from delta has a clean and empty "folder" in S3 in which to dump its CSV files before they are dumped there. 
- Yes, testing seemed to confirm this was a bug: _if a `load_table_from_delta` Spark job is aborted, and some of the .csv.gz part files were created, they will apparently be picked up by the next run_
- This code ensures to clean out any leftover/stale/residual files from previous runs so only the latest data is processed.
2. [ ] API …
> [PIPE-380] Ensure empty s3 folder for delta table CSV files

- usaspending_api/etl/management/commands/swap_in_new_table.py
Resolving a minor bug with the index validation. It wouldn't sort the indexes before comparing them.
N/A
```
```
> Sorting the indexes before comparing

- usaspending_api/download/helpers/download_annotation_functions.py
- usaspending_api/download/helpers/elasticsearch_download_functions.py
- usaspending_api/settings.py
Downmerge of #3748 to qat branch and env.
> [HOTFIX-qat] #3748 downmerge to qat

- usaspending_api/accounts/v2/filters/account_download.py
- usaspending_api/download/download_utils.py
- usaspending_api/download/filestreaming/download_generation.py
- usaspending_api/download/filestreaming/download_source.py
- usaspending_api/download/lookups.py
- usaspending_api/download/tests/unit/test_file_generation.py
Splits some Account Downloads up into files D1 and D2. This is limited to Award Financial downloads.
8. [x] Jira Ticket [DEV-9729](https://federal-spending-transparency.atlassian.net/browse/DEV-9729):
```
```
> [DEV-9729] Account Download Performance

- usaspending_api/agency/tests/integration/test_agency_tas_object_class.py
- usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
- usaspending_api/agency/v2/views/tas_object_class_list.py
- usaspending_api/agency/v2/views/tas_program_activity_list.py
Staging PR that cherry-picked the commit from https://github.com/fedspendingtransparency/usaspending-api/pull/3818
> [DEV-9887] Staging Version; Duplicate of PR: #3818

- usaspending_api/api_contracts/contracts/v2/download/transactions.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_subagency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/cfda.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/country.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/county.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/district.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/federal_account.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_agency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_subagency.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/naics.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/psc.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient_duns.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_category/state_territory.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_geography.md
- usaspending_api/api_contracts/contracts/v2/search/spending_over_time.md
Fixes some small markdown file formatting issues.
> Fixing markdown formatting

- usaspending_api/accounts/v2/filters/account_download.py
- usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
- usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
- usaspending_api/download/filestreaming/download_source.py
- usaspending_api/download/helpers/download_annotation_functions.py
- usaspending_api/download/v2/download_column_historical_lookups.py
Changes the formatting approach above by prepending the state abbreviation to the congressional district fields in the download
8. [x] Jira Ticket [DEV-9817](https://federal-spending-transparency.atlassian.net/browse/DEV-9817):
4. The nature of this work does not impact materialized views
5. The nature of this work does not require frontend impact assessments
7. The nature of this work does not require …
> [DEV-9817] Customizes CD Field in Downloads

- usaspending_api/common/helpers/generic_helper.py
- usaspending_api/download/tests/integration/test_download_count.py
- usaspending_api/download/v2/download_transaction_count.py
- usaspending_api/search/tests/integration/test_spending_by_award.py
- usaspending_api/search/v2/views/search_elasticsearch.py
- usaspending_api/search/v2/views/spending_by_award.py
The purpose of this PR is to fix the formatting of some message elements in our messages field of API responses. Some elements were being added to the messages fields as lists; resulting in the messages field storing a list of lists. Not all endpoints had this behavior. After this PR, every endpoint adds elements in a consistent format to the messages field (strings as elements of a single list).
During implementation of a fix, I discovered it wasn't only the time period message that had this nested list issue, but it was also any messages regarding un-used filters. This PR fixes that too. Going forward our API consistently returns messages as string elements in a messages list. Our API responses are still, if not more, aligned with the guarantees …
> [DEV-9977] Fixes Malformed Filter Messages in API Response

- requirements/requirements-server.txt
> update supervisor for testing

- usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
A test was written relative to the current date, that didn't account for a change in logic after the test data reached FY 2022 data (it was using current FY minus 2 years). So at the changeover to FY 2024, the test began to fail. 
Refactored to have TWO unit tests, one testing DABS submission data before the FY 2022 cutover, so only quarterly data is accumulated, and one testing DABS submission data after the FY 2022 cutover, so period data is also included. 
- [NA] Operations <OPTIONAL>
- [NA] Domain Expert <OPTIONAL>
5. [NA] Frontend impact …
> Fixing flakey FY logic in budgetary resources integration test

- usaspending_api/settings.py
See [Fixes bucket name in staging and prod lane](https://github.com/fedspendingtransparency/usaspending-api/pull/3933)
> [PIPE-504]; Fixes bucket name in staging and prod lane

- usaspending_api/common/query_with_filters.py
- usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
- usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
- usaspending_api/search/tests/integration/spending_by_category/test_spending_by_state_territory.py
- usaspending_api/search/tests/integration/test_spending_by_geography.py
> [DEV-10317] Update domestic place_of_performance ES query [hotfix][master] 

- usaspending_api/conftest.py
Updates a path in our test suite to reflect the new location of this file in Broker's code base.
See [DEV-1682](https://federal-spending-transparency.atlassian.net/browse/DEV-1682)
> [DEV-1682]; Fixing breaking change introduced by Broker

- usaspending_api/etl/submission_loader_helpers/file_c.py
PR #3961 has already been approved and merged. This follow up PR adds some additional logging.
> [DEV-10362] [WARMFIX] Logging - Skip C to D Linkage

- usaspending_api/etl/management/commands/load_multiple_submissions.py
- usaspending_api/etl/management/commands/load_submission.py
- usaspending_api/etl/submission_loader_helpers/file_c.py
- usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py
> [DEV-10362] [HOTFIX] Skip C to D Linkage Logic in Submission Loader

- .env.template
- Dockerfile.testing
- README.md
- docker-compose.yml
- usaspending_api/conftest.py
- usaspending_api/etl/tests/integration/test_load_to_from_delta.py
- usaspending_api/etl/tests/integration/test_spark_app.py
Updated the usaspeding-test container to run as described in the README without errors.
Updated the Dockerfile.testing to install missing packages and updated Broker-related tests to skip if there's no `DATA_BROKER_DATABASE_URL` environment variable.
2. [x] Jira Ticket [DEV-9596](https://federal-spending-transparency.atlassian.net/browse/DEV-9596):
> [DEV-9596] Update testing container

- usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md
- usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction_count.md
Removed "IDV" from the title of the API Contract, specifically the spending_by_transaction.md
Changes made to the spending_by_transaction.md. No further technical details.  
1. [x] Unit & integration tests updated N/A
2. [x] API documentation updated N/A
4. [x] Matview impact assessment completed N/A
5. [x] Frontend impact assessment completed N/A
6. [x] Data validation completed N/A
8. [x] Jira Ticket [DEV-8107](https://federal-spending-transparency.atlassian.net/browse/DEV-8107):
```
```
> Dev-8107 "Remove "IDV" from the title of the API Contract"

- usaspending_api/references/management/commands/population_data_loaders/loaders.py
- usaspending_api/references/tests/unit/test_population_data_loaders.py
Fixes a bug that was found in DEV-10132 implementation. The bug was caused by comparing latest population values that were of a different type. Consequently, every record was always being updated. This PR fixes that.
> DEV-10132; Fixes incompatiable type bug

- usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
Created a new API Contract for a new Location autocomplete endpoint for Award Search 2.0.
Created a new API Contract for a new Location autocomplete endpoint for Award Search 2.0.
1. [x] API documentation updated
2. [ ] Necessary PR reviewers:
3. [x] Frontend impact assessment completed
4. [x] Jira Ticket [DEV-10292](https://federal-spending-transparency.atlassian.net/browse/DEV-10292):
> [DEV-10292] Add location autocomplete API Contract

- usaspending_api/awards/management/commands/generate_unlinked_awards_download.py
- usaspending_api/download/v2/list_unlinked_awards_downloads.py
- usaspending_api/settings.py
For API code we cannot import pyspark, this PR fixes a case where it was being imported.
> [DEV-10588] Remove Pyspark Import

- requirements/requirements-server.txt
Constrain uWSGI version to resolve docker build errors
```
```
> Constrain uWSGI version 

- usaspending_api/awards/management/sql/spark/unlinked_accounts_file_c.py
- usaspending_api/awards/management/sql/spark/unlinked_assistance_file_d2.py
- usaspending_api/awards/management/sql/spark/unlinked_awards_summary_file.py
- usaspending_api/common/etl/spark.py
- usaspending_api/common/helpers/download_csv_strategies.py
Staging PR for the hotfix of DEV-10662
> [DEV-10662] Hotfix

- usaspending_api/references/management/commands/load_rosetta.py
1. [x] Unit & integration tests updated - N/A
2. [x] API documentation updated - N/A
5. [x] Jira Ticket [DEV-10690](https://federal-spending-transparency.atlassian.net/browse/DEV-10690):
```
```
> [DEV-10690] Load_Rosetta command should return an appropriate exit code in the case of failure

- usaspending_api/references/management/commands/load_offices.py
Fixes the join so that it returns unlinked offices
> [DEV-10624]: Reverts office changes from release

- usaspending_api/references/management/commands/load_offices.py
**Description**
Hotfix PR for https://federal-spending-transparency.atlassian.net/browse/DEV-10624 that addresses performance issues in the office loader.
> [DEV-10624]: Hotfix to Optimize and Correct Unlinked Offices

- usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
> [DEV-10453] Fix Spark dictionary error [warmfix][qat] 

- usaspending_api/etl/es_covid19_faba_template.json
> [DEV-10834] Increase the nested_object.limit value for the covid19-faba index [hotfix][master]

- usaspending_api/data/unlinked_awards_instructions_readme.txt
Hotfix that updates the instructions in the unlinked awards download package. Additionally, fixes file name bug.
> DEV-10876; Updates unlinked awards instructions doc

- usaspending_api/data/unlinked_awards_instructions_readme.txt
Down-merges the hotfix that was made for DEV-10876
> DEV-10876: Downmerge

- manage.py
- requirements/requirements-app.txt
- usaspending_api/accounts/v2/filters/__init__.py
- usaspending_api/common/helpers/fiscal_year_helpers.py
- usaspending_api/download/filestreaming/__init__.py
- usaspending_api/download/filestreaming/download_generation.py
- usaspending_api/download/management/commands/download_sqs_worker.py
Newer version of Django changed the way that aggregation is done and therefore requires code changes in regards to this. However, I am hoping that instead of doing the code changes now, they can be done when we switch to the latest version of Django which would be above version 5.*. Right now we upgraded the Django version from 3.2.* to version 4.1.13. 
No further technical details necessary.
5. [x] Jira Ticket [PIPE-527](https://federal-spending-transparency.atlassian.net/browse/PIPE-527):
```
```
> [Pipe-527] Fix for format_exception() failure in testing suite

- .env.template
- Dockerfile
- Dockerfile.spark
- Makefile
- docker-compose.yml
Aligning Python version with Databricks runtime version 14.3
https://docs.databricks.com/en/release-notes/runtime/14.3lts.html
> Changes Python version from 3.10.13 to 3.10.12

- usaspending_api/references/v2/views/cfda.py
Updates CFDA URL to grants.gov due to change on their side
8. [x] Jira Ticket [DEV-11015](https://federal-spending-transparency.atlassian.net/browse/DEV-11015):
- N/A - Performance evaluation of affected (API | Script | Download)
- N/A - Before / After data comparison
```
```
> [DEV-11015] CFDA url update

- usaspending_api/references/v2/views/cfda.py
- usaspending_api/settings.py
QAT version of https://github.com/fedspendingtransparency/usaspending-api/pull/4093
> [DEV-11015][QAT] CFDA url update

- requirements/requirements-app.txt
- usaspending_api/common/tests/unit/test_tracing.py
This PR was created to address all tests that were failing titled `Unit Tests` as a result of upgrading from python 3.8.16 to python 3.10.12
N/A
3. [x Necessary PR reviewers:
5. [x] Jira Ticket [PIPE-526](https://federal-spending-transparency.atlassian.net/browse/PIPE-526):
```
```
> [PIPE-526] Test Failures in Unit Tests Travis Job

- usaspending_api/database_scripts/etl/recipient_profile_delta_view.sql
- usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py
Add the schema to the table name in the `recipient_profile_delta_view.sql` file.
8. [x] Jira Ticket [DEV-11100](https://federal-spending-transparency.atlassian.net/browse/DEV-11100):
```
No unit tests need to be updated for this change.
The frontend is not impacted by this change.
```
> [DEV-11100] Add schema to recipient profile delta SQL

- usaspending_api/download/helpers/download_file_helpers.py
Incorrectly reading some settings in our download helpers. This PR fixes the problem
8. [x] Jira Ticket [DEV-11187](https://federal-spending-transparency.atlassian.net/browse/DEV-11187):
- N/A - Performance evaluation of affected (API | Script | Download)
- N/A - Before / After data comparison
```
```
> [DEV-11187] Fixes issue loading from CONFIG instead of settings

- usaspending_api/config/envs/production.py
- usaspending_api/config/envs/qat.py
- usaspending_api/config/envs/sandbox.py
- usaspending_api/config/envs/staging.py
Added a `DATABASE_DOWNLOAD_S3_BUCKET_NAME` variable to all environmental config files.
8. [x] Jira Ticket [DEV-11406](https://federal-spending-transparency.atlassian.net/browse/DEV-11406):
```
No tests were affected by this change.
No API documentation was affected by this change.
No matviews were affected by this change.
The frontend is not affected by this change.
No operations tickets are needed for this change.
```
> [DEV-11406] Add DATABASE_DOWNLOAD_S3_BUCKET_NAME config to all environments

- usaspending_api/transactions/delta_models/summary_state_view.py
Duplicate of https://github.com/fedspendingtransparency/usaspending-api/pull/4195 for qat
> [DEV-11422] Fixes total outlay calculation relating to bound by year [QAT]

- usaspending_api/download/helpers/elasticsearch_download_functions.py
This fixes a bug in the Elasticsearch download logic that was resulting in incorrect / duplicate data.
The root cause of the problem was introduced when Subaward downloads moved to Elasticsearch. The process for Elasticsearch downloads is:
1. Query ES and get a list of IDs that we should lookup in the DB for download
2. Insert those IDs into a lookup table that is joined on
3. Query the primary table for a download (e.g., `award_search`) by joining to the lookup table
The problem is that when Subawards were introduced into the ES download workflow they would also insert into the same lookup table and while it would capture the `lookup_id_type`, that field was not actually used in the download. That meant the two cases were occurring:
* An ID was …
> [DEV-11361] Update ES download query

- .codeclimate.yml
- usaspending_api/common/tests/integration/test_subawards_elasticsearch_query.py
- usaspending_api/conftest_helpers.py
Update the Elasticsearch test setup when using Subawards.
```
The frontend is not impacted by this change.
No operations tickets are needed for this change.
8. Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123):
No JIRA ticket for this fix.
```
> Update subaward ES test setup

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
Replace a deprecated pandas function.
8. [x] Jira Ticket [DEV-12096](https://federal-spending-transparency.atlassian.net/browse/DEV-12096):
```
There's not a great way to test the updated function as it requires mocking most of the functionality that is to be tested.
5. Frontend impact …
```
> Update monthly delta files command [hotfix][staging]

- usaspending_api/download/management/commands/populate_monthly_delta_files.py
> [DEV-12096] Fix populate monthly delta command [hotfix][QAT]

- usaspending_api/common/query_with_filters.py
- usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_basic_cases_subaward.py
- usaspending_api/search/tests/integration/test_spending_by_award.py
>  [DEV-12248] Update Award ID query for Subawards [hotfix][prod]

- usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
- usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
- usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
This fixes the check awards for deletes to escape spcial characters.
The code handles both postgres queries using psychopg2 and spark sql by passing in arguments.
8. [x] Jira Ticket [DEV-12261](https://federal-spending-transparency.atlassian.net/browse/DEV-12261):
```
```
> [DEV-12261] -  Fix check awards for deletes to escape special characters

- usaspending_api/search/delta_models/subaward_search.py
Additional values have the change to be NULL currently and we need to protect against those without removing the NOT NULL constraints that exist on the tables.
N/A
8. [x] Jira Ticket [DEV-12260](https://federal-spending-transparency.atlassian.net/browse/DEV-12260):
```
```
> Preventing null value for sub_action_date and subaward_amount

- .github/actions/init-python-environment/action.yaml
- .github/actions/init-test-envrionment/action.yaml
- .github/actions/run-pytest/action.yaml
- .github/workflows/build-broker-docker-image-for-test.yaml
- .github/workflows/cancel-running-workflow.yaml
- .github/workflows/code-climate-before-build.yaml
- .github/workflows/code-climate-report-coverage.yaml
- .github/workflows/code-style-checks.yaml
- .github/workflows/pull-request-checks.yaml
- .github/workflows/test-non-spark-integration.yaml
- .github/workflows/test-spark-integration-load-to-from-delta.yaml
- .github/workflows/test-spark-integration-load-transactions-fabs-fpds.yaml
- .github/workflows/test-spark-integration-load-transactions-lookup.yaml
- .github/workflows/test-spark-integration-other.yaml
- .github/workflows/test-unit.yaml
> Dev 11988/add GitHub actions

- usaspending_api/database_scripts/etl/location_delta_view.sql
- usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
Add a missing `location_type` field and a new test.
8. [x] Jira Ticket [DEV-123](https://federal-spending-transparency.atlassian.net/browse/DEV-123):
```
```
> [DEV-12144] Add missing location_type key for `United States` [hotfix][staging]

- usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
- usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
- usaspending_api/references/v2/views/location_autocomplete.py
> [DEV-12478] Update location autocomplete to limit by location_type [hotfix][master]

- usaspending_api/search/v2/views/spending_by_award.py
Consolidate 3 database queries, per result, into 1 database query, per request. Also cleaned up some type hints that were incorrectly showing that some methods return a `Response` object from the DRF package instead of the `Response` object from the elasticsearch_dsl package.
1 database query is now made and a lookup dictionary is created and used by every result instead of each result making 3 separate database queries.
8. [x] Jira Ticket [DEV-11342](https://federal-spending-transparency.atlassian.net/browse/DEV-11342):
```
No tests were added or updated since the existing tests should still function correctly, but with fewer database …
```
> [DEV-11342] Consolidate DB queries

- usaspending_api/awards/management/commands/generate_unlinked_awards_download.py
- usaspending_api/disaster/management/commands/generate_covid19_download.py
Fixing issues with covid 19 downloads and unlinked award downloads.
> [DEV-12574] - fix issues download jobs

- usaspending_api/common/spark/configs.py
Updating the S3 endpoint to correct an issue impacting starting a job with local Spark.
In cleaning up the config to work with non-local the S3 endpoint was updated to be just the host instead of the combined host and port for local dev environments. 
2. N/A API documentation updated (examples listed below)
2. API UI
3. Comments
3. [x] Data validation completed (examples listed below)
4. N/A Appropriate Operations ticket(s) created
5. [x] Jira Ticket(s)
1. …
> [DEV-12638] Update the S3 endpoint for starting local spark job

- usaspending_api/awards/delta_models/financial_accounts_by_awards.py
Adds program_activity_reporting_key to financial_accounts_by_awards delta model
2. N/A API documentation updated (examples listed below)
2. API UI
3. Comments
3. N/A Data validation completed (examples listed below)
4. N/A Appropriate Operations ticket(s) created
5. [X] Jira Ticket(s)
1. [DEV-13179](https://federal-spending-transparency.atlassian.net/browse/DEV-13179)
[DEV-13179]: https://federal-spending-transparency.atlassian.net/browse/DEV-13179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
> [DEV-13179] Add program_activity_reporting_key to financial_accounts_by_awards delta model

- usaspending_api/api_contracts/contracts/v2/federal_accounts/federal_account_totals/program_activities.md
fix typo in api contract for program_activities.md
2. [X] API documentation updated (examples listed below)
2. API UI
3. Comments
3. N/A Data validation completed (examples listed below)
4. N/A Appropriate Operations ticket(s) created
5. N/A Jira Ticket(s)
1. [DEV-13016](https://federal-spending-transparency.atlassian.net/browse/DEV-13016)
[DEV-13016]: https://federal-spending-transparency.atlassian.net/browse/DEV-13016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> [DEV-13016] Fix typo in api contract

- usaspending_api/download/delta_downloads/filters/account_filters.py
- usaspending_api/download/delta_models/account_balances_download.py
- usaspending_api/download/tests/integration/test_account_download_factories.py
- usaspending_api/download/tests/integration/test_account_download_filter.py
A few fields are missing from the File A download table that are needed by the filters.
Adds the missing fields to the File A download table in Delta as well as adding test cases to test that each doesn't result in a missing column error.
2. [x] API documentation updated (examples listed below)
2. API UI
3. Comments
3. [ ] Data validation completed (examples listed below)
5. [ ] Jira Ticket(s)
> Fix missing fields on File A donwload table and add tests

- usaspending_api/etl/management/commands/create_delta_table.py
Fixes a bug where creating a delta table from a dataframe will fail if the schema changed.
2. N/A API documentation updated (examples listed below)
2. API UI
3. Comments
3. [x] Data validation completed (examples listed below)
4. N/A Appropriate Operations ticket(s) created
5. [ ] Jira Ticket(s)
> Overwrite delta table's schema when recreating

- usaspending_api/api_contracts/contracts/v2/search/spending_over_time.md
- usaspending_api/search/tests/integration/test_spending_over_time.py
- usaspending_api/search/v2/views/spending_over_time.py
This PR updates the model type to "text" for the program activity code. (string is not a valid model type for the Tiny Shield validator.)
2. [ ] API documentation updated (examples listed below)
2. API UI
3. Comments
3. [ ] Data validation completed (examples listed below)
4. [ ] Appropriate Operations ticket(s) created
5. [ ] Jira Ticket(s)
1. [DEV-0](https://federal-spending-transparency.atlassian.net/browse/DEV-0)
> [DEV-13063] - Update spending_over_time.py to fix model type
